### ISSUE TITLE
kde stable fails to boot, entering a bash loop 

### ISSUE THREAD

**Issue by quesada** [geckolinux/geckolinux-project#10]
'calling CRDA to update regulatory domain' is printed multiple times, then it says ti cannot find a HDD or something similar, and after many attempts it reboots.

I tried this on two computers that both boot fine on mint KDE.

Thanks!

**Comment by geckolinux** [comment]
Hi there, sorry for the extremely slow response time. Did you ever find a workaround? What method did you use to create the USB? And what kind of graphics card are you running?

**Comment by geckolinux** [comment]
Hello, please try the newest GeckoLinux release with the Calamares installer.
