### ISSUE TITLE
Cinnamon Leap stops communications

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#101]
A few times now I've installed Cinnamon Leap on a wiped drive. The installation goes fine. Eventually I get the system the way I like it, with Audacious, Leafpad, and Otter Browser. I install my VPN, first installing openVPN and Dialog. Then Ethernet and Wireless are lost, preventing me from accessing the Internet. I can then swap drives -- it's running via USB 3.0 -- and run Linux Mint with no problem at all, so I cannot blame the laptop. Do you have any guesses as to what it could be?

**Comment by geckolinux** [comment]
Yes, if you updated the system you probably got hit by this upstream openSUSE bug:
https://bugzilla.opensuse.org/show_bug.cgi?id=1047004

To fix it, run `sudo rm /etc/resolv.conf` and reboot.

**Comment by pccobbler** [comment]
Thanks for the reply. Do I need to run that every update?

**Comment by geckolinux** [comment]
Possibly yes. Could you please confirm if that workaround did the trick for you?

**Comment by pccobbler** [comment]
Let me use it for a day or two (I wiped the drive and started over). It never dies immediately, only after I get everything running. I'll post soon.

**Comment by geckolinux** [comment]
If it's the bug I cited above, it only happens after running a system update with `sudo zypper up` or the equivalent updating all available packages via YaST Software.

**Comment by pccobbler** [comment]
I built a new Cinnamon Leap system. The loss of connectivity happened sooner than before. I executed the command you referenced and rebooted, and connectivity returned. And yes, this all happened soon after I used YaST to add some applications. Let me use it for a few more boots, but so far so good.

**Comment by geckolinux** [comment]
OK, so it's definitely the upstream openSUSE bug. I can't really do anything to fix it, but hopefully after the first time that happens it won't happen again on a given system.

**Comment by pccobbler** [comment]
The bug hits more than just after updates. I'm having to remove the file almost every boot. It's a simple fix, but it needs to be fixed. I'll post on openSUSE's forum regarding it.

**Comment by geckolinux** [comment]
Must be related to the VPN config. But yes, that would be a good question for the openSUSE forum. Sorry I can't be more helpful.

**Comment by pccobbler** [comment]
The openSUSE folks told me that "netconfig -f update" is a better solution, as it does not require a reboot.

**Comment by geckolinux** [comment]
Ah yes, well, technically deleting `/etc/resolv.conf` also doesn't technically require a reboot either, you can just restart the NetworkManager service afterwards.
