### ISSUE TITLE
HELP, PLEASE

### ISSUE THREAD

**Issue by tlcmd** [geckolinux/geckolinux-project#102]

**Comment by tlcmd** [comment]
I am trying repeatedly to install a Brother MFC 490cw printer onto my GeckoLinux Mate distro. My remaining on GeckoLinux necessitates my being able to install this machine's rpm files to make it operate.  Will you please help me and walk me through this install? Otherwise I'll be forced to try other rolling Linux distros which do not use rpm files. This model is not listed in the list of printer files in the package manager or under its name on my printer list in GeckoLinux/openSUSE. I really like the GeckoLinux distro and would like to keep it.
Thanks,
tlcmd

**Comment by Mazaduk** [comment]
> Brother MFC 490cw

Maybe try this?
https://support.brother.com/g/b/downloadend.aspx?c=us&lang=en&prod=mfc490cw_all&os=127&dlid=dlf006893_000&flang=4&type3=625

Extract the file. 
Go to the directory where the `linux-brprinter-installer-2.2.x-x` file is. 
Then in a terminal `chmod +x yourfile`.
Then `sudo ./yourfile` and follow the prompts.
