### ISSUE TITLE
Next Rolling

### ISSUE THREAD

**Issue by drdaffey** [geckolinux/geckolinux-project#104]
First of all thank you for your work.

My question is when are we to expect new Rolling ISOs being released.

**Comment by Xmetalfanx** [comment]
I appreciate all the hard work the team does and while I admit it's been awhile since I have given it a try ... I think there is an issue with the rolling release schedule of Gecko... in my experience in the past with Gecko the problem lies with using an older snapshot of what is Tumbleweed (Gecko Rolling) + thousands of updates ... after the release date for Gecko's ISO, everything is fine for awhile I admit

I'd ask if there is a way to maybe do snapshots for the rolling release more often... maybe not weekly like TW but quarterly perhaps? .. that may get rid of the issues.   and I do not THINK this is a Gecko Linux issue alone ... if you did the same thing with a (example ~>) 6 month old ISO of Tumbleweed you'd run into the same issues

**Comment by perjonasbengtsson** [comment]
I installed rolling kde some days ago, there was about 1680 package to update,and it went pretty quickly to my surprise, nothing to worry over, and after that i got to make 2-3 minor updates, after all it was a fast installation... so far it works without any problems. considering how quickly the installation from usb to all the updates went (for me at least), it is not in a hurry to update the rolling edition, it works according to me.

**Comment by Xmetalfanx** [comment]
have to be honest ... 1680 is not bad ... I know this is a small dev (not even sure it's a "team") team for Gecko .... but I wish a snapshot for Rolling could be made (maybe even automated for the Dev's sake) say every 3 months or so ... so at THE OLDEST (not counting "a new set of rolling ISOs is about to be re-released") ISO you could install Rolling/Tumbleweed from is only 3 months old MAX  ... 

anyway, even that (considering the nature of TW and rolling distros) that is no promise of not having 1000's of upgraded pacakges 

again I just want to thank the dev of Gecko for all the hard work they do... everyone seems focussed on Ubuntu spins, but to have a spin of OpenSuse with stuff predone (and for Fedora too ... as with the now dead Korora) is really nice to have available

**Comment by Xmetalfanx** [comment]
I am not sure what is involved with making Gecko on the backend but it would be nice to have some sort of script or something on the dev's end so it's minimal effort to make newer ISOs every so often

**Comment by geckolinux** [comment]
Hi @Xmetalfanx , thanks for saying thanks. I do use a script to generate the ISOs, but there are always changes and updates that require manual adaptation of the scripts and additional testing. That's where the extra time goes. But the updated ISOs will be released, hopefully before too long.

**Comment by wingdo** [comment]
I really liked Gecko, but when I installed the rolling release in a VM, after running all updates software manager showed me on a 5.x kernel, but neofetch and screenfetch reported the 4.16(?) kernel as the running kernel.  It seems to run, but this does concern me a bit so I am still on official Tumbleweed.

Looking forward to giving Gecko rolling a try once a new ISO is created.  I love the look of it.

**Comment by alexis0071** [comment]
hola buenas disculpen de casualidad hay una sesion en español? me arriesgue a instalar gecko me llamo la atencion vengo de opensuse Tumbleweed y al llegar lo primero es que no encuentro el español y por mas que lo intento por yast2 descarga pero nada que se instala y al poner zypper dup tenia un monto de paquetes nuevos por instalar y una enorme actualizacion la ultima instantanea fue hace mucho tiempo

**Comment by geckolinux** [comment]
@alexis0071 Ya echaste a correr el instalador de paquetes de idiomas? Aparece por defecto en el escritorio o en el menu de inicio como "Language Installer". Es necesario usarlo primero, YaST no es suficiente.

**Comment by alexis0071** [comment]
> @ alexis0071 ¿ Ya has ejecutado un instalador de paquetes de idiomas? Aparece por defecto en el escritorio o en el menú de inicio como "Instalador de idioma". Es necesario usarlo primero, YaST no es suficiente.


primero que nada saludar y felicitarlos por su trabajo cuando fui a instalar me apareció el paquete de idioma en el defecto después de instalarlo no apareció, aunque lo puse en español por yast2 y por preferencias del entorno kde, aun asi me aparecen varias aplicaciones como dolphin manager en ingles, pero la parte mas fuerte, es que después de la actualización de 1697 paquetes la computador de repente se me apaga

**Comment by alexis0071** [comment]
y en las actualizaciones que hizo medijo que instalo el kernel 5.2.1 y me muestra el 4.16.x sera esa la causa por el cual se apaga?

**Comment by geckolinux** [comment]
@alexis0071 Por favor crea un nuevo informe para cada problema:
https://github.com/geckolinux/geckolinux-project/issues/new

**Comment by geckolinux** [comment]
Hi everyone, I'd appreciate your help testing this new ROLLING ISO:
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_ROLLING_Cinnamon.x86_64-BETA-999.200725.0.iso/download
Please try it in virtual machines _and_ physical hardware, in both legacy and EFI modes. Thanks a lot!

**Comment by darknetmatrix** [comment]
download is running, gonna put it on physical hardware in EFI mode, to replace my tumbleweed installation with kde

**Comment by geckolinux** [comment]
@darknetmatrix Thanks! Appreciate it. Remember, it could still eat your kitten though...

**Comment by darknetmatrix** [comment]
installation went smoothly, made some changes to the look, hopefully we left for several years
https://imgur.com/a/GI46Loz

**Comment by geckolinux** [comment]
@darknetmatrix  Great, thank you!

**Comment by geckolinux** [comment]
https://github.com/geckolinux/geckolinux-project/releases/tag/999.200729
