### ISSUE TITLE
How do I install &/ use Alien

### ISSUE THREAD

**Issue by tlcmd** [geckolinux/geckolinux-project#105]
I need to convert a .deb file to an .rpm one ti install my JRivers Media Center.
How do I do this? I've tried to use the package manager to get Alien, but have several choices of files to download. 
Do I need to use the terminal command line?

Thanks,
tlcmd

**Comment by perjonasbengtsson** [comment]
Is this helpfull?! https://en.opensuse.org/User:Noee

**Comment by tlcmd** [comment]
pergonasbengts: thanks for the reply, but I think i will try downloading Alien to either Windows 10 or Linux Mint 19. I just finished my 3rd install of GeckoLinux Mate after I screwed the package manager up 2x previously.At leaset everything else is backed up on my external HDD and I've just begun to get well into GeckoLinux.
Thanks,
tlcmd
