### ISSUE TITLE
something to be corrected for opensuse 15.1

### ISSUE THREAD

**Issue by penguin67** [geckolinux/geckolinux-project#107]
opensuse 15.1 is out.

I installed geckolinux opensuse 15.0 (XFCE) and upgraded as desrcibed here :
`https://en.opensuse.org/SDB:System_upgrade`

Some things that still are not repaired or need to be repaired/changed with geckolinux (XFCE) edition as follow: (to developer)

**1**- preinstall leafpad instead of pluma (would be better)

**2**- still ''cannot open display'' appears when one tried to run something (leafpad in terminal).
Solution maybe can be : 

> export DISPLAY=:0.0

as described here: `https://www.linuxquestions.org/questions/linux-newbie-8/export-display%3D-0-0-a-682926/` or relative web portals

**3**- gksudo is missing but one can replace with pkexec (see here `https://askubuntu.com/questions/287845/how-to-configure-pkexec`)
as follow:
> open a terminal
> cd /usr/local/bin
> sudo gedit gksudo (create new file called "gksudo" write the following content: (alternatively one can open terminal cd /usr/local/bin, open su and open leafpad )
> pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY $@
> (don't forget the $@ at the end. This is for redirecting all parameters)
> save and quit
> make the file executable: chmod 755 gksudo
> Now you should have a fully functional gksudo command available on your system - permanently.

**4**-Pre-install **mlocate** `https://software.opensuse.org/package/mlocate` ( one can use updatedb and locate in terminal)

**5**- Install multimedia codecs for opensuse15.1 as described here `https://opensuse-guide.org/codecs.php` (XFCE) 
`https://opensuse-community.org` (KDE and GNOME) or as described here : `https://fosspost.org/tutorials/things-to-do-after-installing-opensuse`

**6**- Associate ymp (one click install with yast2 )
`https://en.opensuse.org/SDB:One_click_install`
`https://www.suse.com/documentation/opensuse121/book_opensuse_startup/data/sec_y2_sw_1click.html`
**7**- When one execute **su** in Terminal, the follow message is displayed
**non-network local connections being added to access control list** 
Why this message ? or it is normal ? Googling this message this gives some explanations :
`https://www.suse.com/c/running-graphical-programs-remotely-root/` and 
`https://en.opensuse.org/SDB:Administer_with_sudo
`
**8**- **sudo visudo** cannot open by nano as default.
One should use in terminal 

> sudo EDITOR=nano visudo 
to open /etc/sudoers by nano
(developer please add nano as default editor for visudo)
as descried here: `https://askubuntu.com/questions/539243/how-to-change-visudo-editor-from-nano-to-vim`

 _Additional_ (Additional custom actions can added to thunar)
`https://docs.xfce.org/xfce/thunar/custom-actions`
`https://www.linux.com/learn/extend-xfces-thunar-file-manager-custom-actions`

- _Additional_ (i3lock can used as screen locker with xautolock)
i3lock can start/configured in start programs in XFCE through settings > startup programs
`http://rabexc.org/posts/awesome-xautolock-battery`
some examples : (search in google i3lock lur screen)
`https://gist.github.com/csivanich/10914698 `
`https://www.reddit.com/r/unixporn/comments/7iddwn/i3lock_faster_and_better_lockscreen/`
`http://plankenau.com/blog/post/gaussianlock`
`https://github.com/meskarune/i3lock-fancy`
`https://michaelabrahamsen.com/posts/custom-lockscreen-i3lock/`

_Additional for people that want to use Opera browser and cannot play H.264 format files_
from this portal :
`https://www.slimjet.com/en/libffmpeg.php`
`https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases` and copy libffmpeg.so under this directory /usr/lib64/opera/lib_extra/libffmpeg.so
(or as deb package here vvld.in/lm64 > chromium-codecs-ffmpeg-extra XX.deb ) 
I am investigating for other issues and will relate them. 
If, gecko linux will offer a utility that that can produce an snapshoot iso file for distribution/re-mastering (like MX Linux or Sparky Linux ) will be great.

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
