### ISSUE TITLE
can't see wifi options

### ISSUE THREAD

**Issue by pijano42** [geckolinux/geckolinux-project#108]

**Comment by pijano42** [comment]
Hi. I just install geckolinux rolling xfce. I like it. It work fast in my 2gb ram pc. 
The point: after install, the network connection worked fine and i could see the internet available networks and i could connect to my wifi. But after the actualization, the connection still works, i have internet, but i could not see the internet available networks in the network icon at the panel. What can i do to solve it? 
Thanks for the help and sorry for my english

**Comment by Mazaduk** [comment]
I'm not sure how to fix this, but here are some other ideas:

- This weird thing might work for you: click the network icon, disconnect from your current wi-fi network, click away, then click the network icon again and perhaps you will see a list of more networks.

If that doesn't work:

- Try opening up YaST and going to "Network Settings" under "Settings."
- If you get a "Warning" prompt saying something about networking being handled by NetworkManger, close YaST. Instead, open up a terminal and type `nmcli dev wifi`. This will list available networks. Then you can click the network icon on the panel and click "Create New Wi-Fi Network..." Next, type in the network name you want from the aforementioned list and the passkey.

**Comment by pijano42** [comment]
Thank's Mazaduk. 

I could not try the solutions that you suggest me because the problem is that clicking in the network icon it nothing happens. The pop-up window with the list of wifi networks is what is does not work. I tried deleting the notification area and after adding another to the panel, but the problem remains. The other thing i did was pull-off the usb wireless adapter and then put it in again, but nothing. The icon is back, i have internet (the system connects to my network), but the pop-up window with the list of network it doesn't appears. Maybe is a xfce problem because when i disconnected the usb wireless, showed up a warning message near to the notification area but my impression is that was a opensuse message (having in count the fonts type and the color and the window form). I'll keep looking what to do and any help will be grateful.
Greetings and sorry for my english again!

**Comment by Mazaduk** [comment]
Hello again pijano42,

- Did you try to open the "Network Settings" in YaST? Maybe take another look.
- Did typing `nmcli dev wifi` in a terminal output anything?
- Try typing this in a terminal (or press Alt+F2 and type this): `nm-connection-editor`

Also, if you are Gecko rolling using XFCE, perhaps you may want to try out openSUSE Tumbleweed, which now has a new XFCE Live iso. After installation, you can even enable communities repositories from YaST and install propriety drivers and codecs if you need them.

**Comment by pijano42** [comment]
Thanks again Mazaduk. I've tried nmcli dev wifi and shows the available networks. It's not the problem. I have internet and the connection works fine. The only trouble is that i can't see the available wifi networks when i click in the network icon at the panel. I guess it's a xfce problem but don't know how to solve it. I'll look for help at the xfce forum and then try with tumbleweed. 
Greetings and thank you again

**Comment by Mazaduk** [comment]
Sure, no problem. Sorry I couldn't help too much. It could be an XFCE
problem, but according to Jim Dean on the #xfce freenode IRC channel, "nm
applet isn't part of Xfce so you should probably ask your distro."

Perhaps you can talk to some people over on the #suse or #opensuse-chat IRC
channels along with your forums.

**Comment by m4u9** [comment]
Please make sure you're using status notifier panel plugin. If you're using the legacy systray instead, it's a known issue introduced by a patch and the fixed package is on the way.

please refer to bug report here: https://bugzilla.opensuse.org/show_bug.cgi?id=1132659

Fix on the way to Factory: https://build.opensuse.org/request/show/708939

**Comment by pijano42** [comment]
Thank's guys. I solved it: the panel did not have the status notifier plugin. That was all. 
Greetings and thanks again.
