### ISSUE TITLE
Leap-15.0_non-OSS_updates seems out of date

### ISSUE THREAD

**Issue by perjonasbengtsson** [geckolinux/geckolinux-project#109]
Hi,
Using Geckolinux NEXT (version 15.0) and when updating i get this message: "Warning: Storage location Leap-15.0_non-OSS_updates seems out of date. Consider using a different mirror or server."
Is this something to worry about? do I need to do something?

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719

The *NEXT* spin will also be updated in the near future.
