### ISSUE TITLE
sK1 vector tool

### ISSUE THREAD

**Issue by dendenis82** [geckolinux/geckolinux-project#11]
Hi!
The issue is that vector tool doesn`t run in any cases: remote test mode, installed on local machine, live mode on local machine(both KDE&XFCE).

The point is that there is no alternative to import Corel Draw file on Linux platform(except coined web servises)

Thank you!

**Comment by geckolinux** [comment]
Hello, what vector graphics program did you try?

**Comment by dendenis82** [comment]
Hi
sorry, that program was silent installed in some wierd way by me during adopting to my needs Geckolinux. I thought it was in Geckolinux because i didn`t installed it. My apologies. It calls sK1.

So now i must correct unactive this ticket?
