### ISSUE TITLE
gecko won't install/boot

### ISSUE THREAD

**Issue by LaGrabow** [geckolinux/geckolinux-project#110]
Downloaded  GeckoLinux_ROLLING_LXQt.x86_64-999.180607.0.iso.
Checked the sha-1 checksum - it matched.

Followed directions to create bootable usb stick using [](https://etcher.io) program and informtion from [](https://github.com/geckolinux/geckolinux-project/wiki) to use the Calamares Installer to install to my OCZ Vertex 4 SSD. 

Installer went through without any errors until it told me to reboot.
Upon reboot I rec'd error msgs:
ACPI Bios error: (bug) failure looking up SB.PC10.SATO.SPT3_G
ACPI Error: Method Parse execution failed SB.PC10.SATO.SPT3_GT
PKCS # 7 signature not signed with a trusted key
kvm: disabled by BIOS
You are in emergency mode
After logging in type journalctl -xb
to view system logs type systemctl reboot
...systemctl default
type exit to boot into default mode
press Control+D to continue

typing any of the above only repeats the above msg.

Is there something else I need to do to install Gecko to an SSD?

**Comment by geckolinux** [comment]
On 2019-09-10 10:37 a.m., LaGrabow wrote:
> journalctl -xb

What does this show?

**Comment by LaGrabow** [comment]
I am not able to type anything. the only way to quit the terminal is to Control Alt Del which brings me back to the error msg on reboot.

**Comment by LaGrabow** [comment]
I am currently writing from the LIVE Gecko usb stick.

**Comment by geckolinux** [comment]
> press `Control+D` to continue

And what about this? (**Not** `Ctrl+Alt-Del`)

**Comment by LaGrabow** [comment]
When I press Control+D it just repeats the msg "press Control+D to continue"

**Comment by geckolinux** [comment]
Hmm, I'm honestly not sure. Have you successfully installed other Linux distros on that system?

**Comment by LaGrabow** [comment]
yes I have had both openSuse 15.1 and debian 10 as well as others on this SSD.  Also I have used gecko as a LIVE usb  on this system a few years now.  I am going to try installing the Gecko stable version to see what happens.

**Comment by geckolinux** [comment]
OK, thanks, and sorry for the trouble. Let me know how that works. Also make sure it's installing GRUB correctly, with a valid EFI partition and all that if you're not using a BIOS scheme.

**Comment by LaGrabow** [comment]
JFYI - I was mistakenly trying to mount an NTFS HDD at installation time.  Sorry for the bother.  Gecko Rolling LxQt is now installed.
p.s. thank you for replying so quickly.
I do like Gecko.

**Comment by geckolinux** [comment]
Great! I'm glad you figured it out.
