### ISSUE TITLE
Size Question?

### ISSUE THREAD

**Issue by FitzM** [geckolinux/geckolinux-project#112]
Not an issue, just a question. If the distro/spin is based on openSUSE why are the iso sizes so different? tumbleweed KDE is 4.2g for openSUSE but only 1.2g for the gecko linux version. What am I missing out on? Sorry if it's a simple question, I just couldn't find the answer in the interwebs.

**Comment by geckolinux** [comment]
Mainly because the the openSUSE ISO offers tons of packages that can be optionally selected during installation. GeckoLinux offers a much more targeted selection of software for each edition.

Also, GeckoLinux does not install recommended packages by default, which also helps to keep the size down.
