### ISSUE TITLE
How can I purge Numix ? 

### ISSUE THREAD

**Issue by FitzM** [geckolinux/geckolinux-project#114]
I'm curious how to get rid of the Numix theme completely.  ( It just isn't my cup of tea is all) . I know how to change the settings in KDE ( that's the DE I use). But how do I do it for other parts of the system ? Firefox will still show orange boxes when I click on something as well as a few other locations that I can't think of now.  Is there a .config file I should be editing or something? 

Thanks again for providing the distro, I enjoy it quite a bit

**Comment by geckolinux** [comment]
Hi there, glad you're enjoying the distro.

To change the Firefox theme and other GTK app themes, you'll need to install another GTK theme and change it via the KDE System Settings *Application Style > Gnome/GTK Application Style*.
