### ISSUE TITLE
lag & freezes last few weeks?

### ISSUE THREAD

**Issue by HacimLlih** [geckolinux/geckolinux-project#117]
I've loved GeckoLinux to point of production / daily driver dependence here; now that I've had something create lag over the last few weeks to point of disruption in daily productivity? Not savvy enough to drill out the culprit to this 5-45 second lag &/or system freezes I'm now seeing daily/hourly?
Any clues mucho appreciated.

**Comment by HacimLlih** [comment]
Example: frequently attempt to Ctrl+w to close a Firefox tab when lag makes one assume I missed key combo.. only to end up closing 2-3 tabs I'd unintended? It effects typing and most all production efforts.

**Comment by penguin67** [comment]
Man. I am afraid that problem comes from desktop you use and not from geckoLinux.  What kind of GeckoLinux use use ? Rolling or Stable? Which desktop ? Are you sure that it is enough space in your profile ? How much ram? SSD or HDD ? Sure about status of your HDD (if you use hdd). It is OK? (no bad sectors?). Are you sure that your machine has no any heating problem ? How about your Ram status ? And so on... 

By the way. I use Opera browser. try it . Or Slimjet .

Wish you luck.

**Comment by HacimLlih** [comment]
> Man. I am afraid that problem comes from desktop you use and not from geckoLinux. What kind of GeckoLinux use use ? Rolling or Stable? Which desktop ? Are you sure that it is enough space in your profile ? How much ram? SSD or HDD ? Sure about status of your HDD (if you use hdd). It is OK? (no bad sectors?). Are you sure that your machine has no any heating problem ? How about your Ram status ? And so on...
> By the way. I use Opera browser. try it . Or Slimjet .
> Wish you luck.

Thanks.. however one may note how last few weeks this issue has arisen after 2+/- YEARS of virtually zero lag etc? The only addition in that time span has been the growth of storage on my 2nd 128GB USB stick.. and some additional packages added etc..

For most of that time period.. my setup was great & dependable.. 

Re browsers.. I depend significantly on Chrome/Firefox's profiling systems; i.e. Firefox Multi-Account Containers extension & Chrome's People Management.. this lag is system wide & not specific to browsers/internet activity.

Thanks for feedback ideas hero..

**Comment by geckolinux** [comment]
Hi, is this with the Static (Leap based) or Rolling (Tumbleweed based) edition?

**Comment by HacimLlih** [comment]
Thx for response.. much less your brilliant creation of GeckoLinux! Huge Tumbleweed fan thus rolling hero.

**Comment by geckolinux** [comment]
Thanks, I'm glad you like it. It's most likely an upstream issue. What kind of graphics does your machine have?

**Comment by HacimLlih** [comment]
Intel HD Graphics 3000, Dell L atitude E6420
Re:
https://www.dell.com/support/home/us/en/04/product-support/servicetag/0-K0wxWlZTdG96a2FiOGFEanMxbGhsdz090/overview

**Comment by geckolinux** [comment]
As mentioned above, it could be hardware failure. But you could try removing the `xf86-video-intel` package and rebooting your system to see if it makes any difference.

**Comment by penguin67** [comment]
@HacimLlih 
I did not want do interrupt your flow. Man. To know the details of your machine open terminal, fire up **inxi -Fxz** and post output here. 

See : 
https://askubuntu.com/questions/1072427/what-can-inxi-be-used-for

or 
https://sites.google.com/site/usertipslinuxmint/inxi-terminal-command

**Comment by HacimLlih** [comment]
Niyiiice hero Gecko!!! ;]] Thanks (mea culpa for response 'lag'); had used inxi in past but didn't recall it due time span since.. as you kindly requested:

localhost:~ # inxi -Fxz
System:    Host: localhost.localdomain Kernel: 4.16.12-1-default x86_64 bits: 64 compiler: gcc v: 7.3.1 Console: tty 0 
           Distro: openSUSE Tumbleweed 20191109 
Machine:   Type: Laptop System: Dell product: Latitude E6420 v: 01 serial: <filter> 
           Mobo: Dell model: 0K0DNP v: A01 serial: <filter> BIOS: Dell v: A21 date: 11/14/2013 
Battery:   ID-1: BAT0 charge: 48.8 Wh condition: 44.4/48.8 Wh (91%) model: Samsung SDI DELL F0D4CA7 status: Full 
CPU:       Topology: Dual Core model: Intel Core i7-2620M bits: 64 type: MT MCP arch: Sandy Bridge rev: 7 L2 cache: 4096 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 21550 
           Speed: 1801 MHz min/max: 800/3400 MHz Core speeds (MHz): 1: 1999 2: 2192 3: 1997 4: 2077 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 
           Display: server: X.Org 1.20.5 driver: intel unloaded: fbdev,modesetting resolution: 1600x900~60Hz 
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 19.2.2 direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Sound Server: ALSA v: k4.16.12-1-default 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e v: 3.2.6-k port: 4080 bus ID: 00:19.0 
           IF: em1 state: down mac: <filter> 
           Device-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi v: kernel port: 4040 bus ID: 02:00.0 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 256.42 GiB used: 169.45 GiB (66.1%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 840 EVO 120GB size: 111.79 GiB 
           ID-2: /dev/sdb type: USB vendor: SanDisk model: Cruzer Glide size: 29.32 GiB 
           ID-3: /dev/sdc type: USB vendor: PNY model: USB 3.0 FD size: 115.31 GiB 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 bus ID: 00:1f.2 
Partition: ID-1: / size: 27.62 GiB used: 22.40 GiB (81.1%) fs: overlay source: ERR-102 
Sensors:   Missing: Required tool sensors not installed. Check --recommends 
Info:      Processes: 193 Uptime: 7h 47m Memory: 7.67 GiB used: 1.65 GiB (21.4%) Init: systemd runlevel: 5 Compilers: gcc: N/A 
           Shell: bash v: 5.0.11 inxi: 3.0.32 
localhost:~ # 
![inxi -Fxz output-via GeckoLinux github support req-Screenshot_20191204_052918](https://user-images.githubusercontent.com/31673973/70146588-5c9d4d00-1657-11ea-8d0b-239ae7ce4875.jpg)

**Comment by HacimLlih** [comment]
> As mentioned above, it could be hardware failure. But you could try removing the `xf86-video-intel` package and rebooting your system to see if it makes any difference.

Here now post following your suggestion:

localhost:~ # zypper rm xf86-video-intel

**_Perhaps wishful thinking..?_** but feels better. Any efficient tests or ?? ways to confirm lag gone in any obvious ways beside a day or three of productivity use good Sir Capitan?

Thx again hero..

**Comment by geckolinux** [comment]
> Any efficient tests or ?? ways to confirm lag gone in any obvious ways beside a day or three of productivity use good Sir Capitan?

No good way to confirm it, just use it as you normally would and please report back if it helps long-term.

**Comment by HacimLlih** [comment]
@geckolinux THX hero.. will give it a go on a heavy day today and see if discernible improvements follow!

**Comment by HacimLlih** [comment]
*Meant backup critical files only.. care less about Windows OS data itself..

**Comment by HacimLlih** [comment]
Ok heroes.. so is it ignorance on my part to hope that full local Calamares GeckoLinux/Tumbleweed rolling installation has any chance of eliminating my lag issues please? My thinking is it could run more efficiently relative to my E6420's 8GB ram etc?
On that front.. is there any creative ways to sync said locally installed Tumbleweed with the USB thumb-drive I've been running all this time so it is still portable as needed so I could run full install on my laptop, but still have fully synced version to run on remote machines via thumb-drive?
Thanks!

**Comment by HacimLlih** [comment]
Yellow?

**Comment by HacimLlih** [comment]
GeckoLinux getting virtually unusable now sadly.. worst occasions = 30-45 second lags including full on, gkrellm display & system freezes.. desperate hopes that full local installation could theoretically expand access to my 8GB RAM on board?

**Comment by geckolinux** [comment]
So you are running the live system via USB?

**Comment by HacimLlih** [comment]
yes.. via USB.. now trying to complete full install as full windows 7 replacement.. deleted all partitions on my 128gb SSD on my Dell.. here's the rub? now with single ext4 partition mounted as '/'.. Calamares Installer refuses to even see the drive at all? Above my pay grade as it were

**Comment by HacimLlih** [comment]
I'm starting to ponder if this whole lag issue is due the size/read-write speeds of my 128gb PNY USB stick I use for persistent data file storage along with my Sandisk Cruz Glide 32gb USB I run my GeckoLinux off of? My thinking was full local SSD hard drive installation may help w this? Thinking maybe more available RAM once no longer running off USB?

**Comment by geckolinux** [comment]
Please burn a fresh copy of GeckoLinux to a USB pendrive, and then try to install it again to your SSD. Please take screenshots along the way, so we can see what's happening.

**Comment by HacimLlih** [comment]
**Mea Culpa @geckolinux ;[[.. Jumped the gun and wiped my SSD 120GB hdd and went for it via USB booted Calamares Installer. Gotta say this install in now back to being an instant beast now! _NOW.. if I can find a practical way to sync daily use boots between my Dell laptop's hdd install.. and either my Sandisk 32GB --or-- PNY 128GB USB drives so I'm still fully ready to remotely access GeckoLinux virtually anywhere/any _PC.. I'll have it made?!** This of course still does not ID the USB boot lags at all.. but would keep me at least mobile ready if I had to boot my USB booted GeckoLinux at my Volunteer gig's offices to support their network etc.. I could get by with lag for 911 needs...
