### ISSUE TITLE
migrating from OpenSuse Tumbleweed to GeckoLinux?

### ISSUE THREAD

**Issue by PeterArt** [geckolinux/geckolinux-project#118]
Is is possible and or easy to move my install over to GeckoLinux - or is the only way to start from scratch and wipe the disk and install Gecko and re install my programs (Thunderbird, Accounting etc)?

I have been using OpenSuse for a few months and have run into some issues that prevent me from doing my normal work and it appears that Gecko would solve that.
Cheers
Peter

**Comment by geckolinux** [comment]
Hi there, basically it would require manually applying all the configuration changes [here](https://github.com/geckolinux/geckolinux-project), which would be a lot of work. I'd probably recommend a re-install.

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
