### ISSUE TITLE
Kmail Issue

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#119]
I just started using Gecko and so far I really like it! I am having one issue, however.

I am using the rolling KDE version of Gecko and am having an issue with Kmail. When I launch it I get the message, "The Akonadi personal information management service is not running. This application cannot be used without it."

Also, when I click "Start" nothing happens.

![akonadi-kmail-notworking](https://user-images.githubusercontent.com/58492880/70099329-c5e77680-15eb-11ea-9b92-766446129a91.jpg)

**Comment by geckolinux** [comment]
Hi there, could you please open the YaST Software manager, search for akonadi , and let us know which akonadi* packages you currently have installed? Thanks!

**Comment by ghost** [comment]
I searched akondai in YaST a little while ago and installed the packages that came up. It did fix that issue but then I was getting Kwallet issues. I ended up wiping it out and installing the Cinnamon version instead. I love it and I have had zero issues so far.

**Comment by geckolinux** [comment]
Glad that the Cinnamon version is working for you.
