### ISSUE TITLE
Unable to ping

### ISSUE THREAD

**Issue by vinyanalista** [geckolinux/geckolinux-project#12]
I tested GeckoLinux Plasma Stable using SUSE Studio's Testdrive. When I try to ping a host (e.g. Google Public DNS, 8.8.8.8)

```
linux@linux:~> ping 8.8.8.8
```

I get the following error message:

```
ping: error while loading shared libraries: libcap.so.2: cannot stat shared object: Permission denied
```

It happens even if I use `sudo` or invoke `ping` as root.

Linux Kamarada suffers from that same [issue](https://github.com/kamarada/kiwi-config-Kamarada/issues/1). Both are based on openSUSE Leap and built using KIWI/SUSE Studio. Maybe we can work around that issue together.

**Comment by geckolinux** [comment]
Hello, please re-open this issue if the problem still persists in future GeckoLinux _Static_ versions based on Leap 42.2. Thanks.
