### ISSUE TITLE
no network connection after installing Rolling Plasma

### ISSUE THREAD

**Issue by 303whodey** [geckolinux/geckolinux-project#120]
Hello,

I just ran the Rolling Plasma in live environment from a USB stick and noticed I had no network connection (Wifi or the wired ethernet I connected for this install). So....I went ahead and installed Gecko Linux without the network connection, and unfortunately, this did not change anything with respect to the lack of internet connection. When I use the command 'nmtui', it reads: 
NetworkManager is not running. 

When I use the command 'sudo systemctl restart NetworkManager', nothing happens (no output) .

This is my new build specs:
https://pcpartpicker.com/user/daverader1/saved/#view=9x7V7P

Thank you in advance for any advice or guidance that can be offered.

**Comment by 303whodey** [comment]
I did attempt a couple of the steps in the following link w/o success:
https://github.com/geckolinux/geckolinux-project/issues/33

**Comment by geckolinux** [comment]
`systemctl status NetworkManager`

**Comment by 303whodey** [comment]
![IMG_1397](https://user-images.githubusercontent.com/58500355/72223912-55f4d600-3531-11ea-8cfb-dbd2fe16ba77.jpg)

**Comment by 303whodey** [comment]
![IMG_1398](https://user-images.githubusercontent.com/58500355/72223947-b257f580-3531-11ea-9417-8ea71d7c35c8.jpg)

**Comment by geckolinux** [comment]
OK, so NetworkManager is running fine. So it's probably not finding your network devices. Are you sure that ethernet isn't working? What kind of hardware are you running?

**Comment by 303whodey** [comment]
The ethernet works fine on my other Windows computer. My linux build doesn’t show a network connection of any kind. This is my linux build:
https://pcpartpicker.com/user/daverader1/saved/#view=9x7V7P

Ryzen 9 3900x, gigabyte x570 aorus master mobo. I had Pop! OS running on the above build with a network connection (wifi and or ethernet) for 2 weeks, but the CPU was running hot at idle and the subwoofer had no sound.

**Comment by geckolinux** [comment]
The hardware might be too new. I'd say wait for the next refresh of the GeckoLinux ISOs with newer hardware support.

**Comment by 303whodey** [comment]
Thank you for the honest answer.

**Comment by Dremor** [comment]
Could you provide the result of the 'nmcli' command (with no option).

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
