### ISSUE TITLE
is the static version still based on opensuse 15.0?

### ISSUE THREAD

**Issue by EugeneJarecki** [geckolinux/geckolinux-project#121]
This is related to post #113 which hasn't been answered for four months: Is the static release still based on 15.0, which reached end of life on Nov 30 of last year? When will the fixed release be based off of 15.1? If it already is, why isn't there a news item on the website?

GeckoLinux is a cool distro, but it needs to signal to the community that it's a going concern. I'm a noncoder who signed up on GitHub just to make this point.

**Comment by geckolinux** [comment]
It does indeed need to be updated, and it will be eventually. But for now it's very easy to install the 15.0 version and then upgrade it to 15.1.

**Comment by EugeneJarecki** [comment]
Appreciate the quick response, but that's not a great answer. You're making the end user go through an extra step because you're not on the ball. I'm sorry to take this harsh tone because I know you don't get compensated for the heroic work you do. The world needs an alternative to the Ubuntu/Mint/Debian hegemony of the open source desktop, which is bland and strangling innovation. With Red Hat getting bought by IBM, we are in real danger of choosing between Microsoft, Apple and IBM in our computing. Mageia is running on fumes, Korora is dead; if this project stalls, I don't know where to turn. If contributing some cash would get things moving, please let us know. Thanks for all you do and here's hoping that an RPM-based distro can survive and thrive in 2020.

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719

**Comment by EugeneJarecki** [comment]
Gonna slap a few iso's on the ol' USB stick and give it a go. Just wish you had let everybody know you intended to skip over 15.1 and base the next static version on 15.2. (By the way, a perfectly reasonable approach given the calendar and openSuse's release schedule.) Thanks for all your hard work.

**Comment by geckolinux** [comment]
@EugeneJarecki  :+1: 

> Just wish you had let everybody know you intended to skip over 15.1 and base the next static version on 15.2

It wasn't really intended that way, that's just kind of how things worked out. ;-)
