### ISSUE TITLE
Possible to sync locally installed/bootable USB to go?

### ISSUE THREAD

**Issue by HacimLlih** [geckolinux/geckolinux-project#122]
Curious if there is a way to use on my laptop's local install AND sync to my 128GB PNY as bootable LIVE USB thumbdrive to use on remote sites/PCs?
Thanks!

**Comment by geckolinux** [comment]
Automatically no. Of course you could use rsync or something to manually sync the two systems.

**Comment by HacimLlih** [comment]
> Automatically no. Of course you could use rsync or something to manually sync the two systems.

I shall seek out some rsync hot-tos.. thanks hero.
