### ISSUE TITLE
ISO Refresh

### ISSUE THREAD

**Issue by belialzxz** [geckolinux/geckolinux-project#123]
Is there a planned ISO refresh. The current versions will not work with newer hardware.

**Comment by geckolinux** [comment]
Yep, it's coming, sorry for the delay.

**Comment by belialzxz** [comment]
Do you have an ETA? If out by a couple weeks or more, I may just re-install Tumbleweed, and work on tweaking it myself.

**Comment by geckolinux** [comment]
It might take more than a few weeks.

**Comment by Dremor** [comment]
Need help ? 
I'm the one who started packaging Calamares for OpenSUSE years ago, if you remember me.

**Comment by geckolinux** [comment]
Hi @Dremor , good to hear from you! Thanks a lot for the offer to help. At the moment I'm running into trouble with the dracut step on a test ISO I generated:

![Screenshot_20200123_104327](https://user-images.githubusercontent.com/2692138/72999626-9f64e100-3dcd-11ea-8258-12a8efa655c8.png)

`````````
2020-01-23 - 10:42:34 [6]: Starting job "hwclock" 
2020-01-23 - 10:42:34 [6]: Determining gettext path from ("/root", "/usr/bin", "/usr/share/locale") 
2020-01-23 - 10:42:34 [6]:  ..  Found "en_US" in "/usr/share/locale/en_US" 
2020-01-23 - 10:42:34 [6]: Job file "/usr/lib64/calamares/modules/hwclock/main.py" 
2020-01-23 - 10:42:34 [6]: Job description from pretty_name "hwclock" = "Setting hardware clock." 
2020-01-23 - 10:42:34 [6]: Running "chroot" ("/tmp/calamares-root-_pvzomgv", "hwclock", "--systohc", "--utc") 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress for Job[ 20 ]:  0 % completed 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress Overall:  74.0741 % (accumulated) +  0 % (this job) =  74.0741 % (total) 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress for Job[ 20 ]:  0 % completed 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress Overall:  74.0741 % (accumulated) +  0 % (this job) =  74.0741 % (total) 
2020-01-23 - 10:42:35 [6]: Finished. Exit code: 0 
2020-01-23 - 10:42:35 [6]: [PYTHON JOB]:  "Hwclock set using RTC method." 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress for Job[ 21 ]:  0 % completed 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress Overall:  77.7778 % (accumulated) +  0 % (this job) =  77.7778 % (total) 
2020-01-23 - 10:42:35 [6]: Starting job "dracut" 
2020-01-23 - 10:42:35 [6]: Determining gettext path from ("/root", "/usr/bin", "/usr/share/locale") 
2020-01-23 - 10:42:35 [6]:  ..  Found "en_US" in "/usr/share/locale/en_US" 
2020-01-23 - 10:42:35 [6]: Job file "/usr/lib64/calamares/modules/dracut/main.py" 
2020-01-23 - 10:42:35 [6]: Job description from pretty_name "dracut" = "Creating initramfs with dracut." 
2020-01-23 - 10:42:35 [6]: Running "chroot" ("/tmp/calamares-root-_pvzomgv", "dracut", "-f") 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress for Job[ 21 ]:  0 % completed 
2020-01-23 - 10:42:35 [8]: [JOBQUEUE]: Progress Overall:  77.7778 % (accumulated) +  0 % (this job) =  77.7778 % (total) 
2020-01-23 - 10:42:37 [6]: Finished. Exit code: 1 
2020-01-23 - 10:42:37 [6]: Target cmd: ("dracut", "-f") 
2020-01-23 - 10:42:37 [6]: Target output:
dracut: Executing: /usr/bin/dracut -f
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'mdraid' will not be installed, because command 'mdadm' could not be found!
dracut: dracut module 'multipath' will not be installed, because it's in the list to be omitted!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: 95nfs: Could not find any command of 'rpcbind portmap'!
dracut: dracut module 'kiwi-live' cannot be found or installed.
2020-01-23 - 10:42:37 [6]: Skipping non-emergency job "grubcfg" 
2020-01-23 - 10:42:37 [6]: Skipping non-emergency job "bootloader" 
2020-01-23 - 10:42:37 [6]: Skipping non-emergency job "packages" 
2020-01-23 - 10:42:37 [6]: Skipping non-emergency job "removeuser" 
2020-01-23 - 10:42:37 [6]: Skipping non-emergency job "umount" 
2020-01-23 - 10:42:37 [1]: ERROR: Installation failed: 
2020-01-23 - 10:42:37 [6]: - message: "Failed to run dracut on the target" 
2020-01-23 - 10:42:37 [6]: - details: "The exit code was 1" 
2020-01-23 - 10:42:38 [6]: Calamares will quit when the dialog closes. 
2020-01-23 - 10:42:38 [6]: FinishedPage::setUpRestart(), Quit button setup= "never" command= "systemctl -i reboot" 
``````

Here's the ISO if you want to play around:
https://drive.google.com/open?id=1-HWX-QJyIXuGKDdgPJdai8d7fmdNvV6l

Thanks again!

**Comment by geckolinux** [comment]
OK, I think I got it figured out, thanks to these posts:
- https://github.com/calamares/calamares/issues/1245
- https://github.com/OSInside/kiwi/issues/1228

Config  change:
````````
---
unpack:
    -   source: "/run/rootfsbase"
        sourcefs: "ext4"
        destination: "/"
        exclude: [ "02-livecd.conf" ]
`````````

**Comment by woodyx86** [comment]
I know it's easy to install the 15.0 version and then upgrade it to 15.1.
However it takes too much time due to slow network connection.
I installed the barebone static so as to minimize the downloading time for a fresh install on my laptop.
I have a few more to do the same installation

Any update on the ISO refresh?
Maybe you're thinking of skipping 15.1 and waiting for 15.2?

Gecko linux is the best for me.
Thanks

**Comment by woodyx86** [comment]
@geckolinux 

I'm happy to report that the XFCE-STATIC ISO worked well for me,
I re-installed it on my main laptop, and I'm writing this on the refreshed 15.1 of Geckolinux :-)
Many thanks,

> Here's the ISO if you want to play around:
> https://drive.google.com/open?id=1-HWX-QJyIXuGKDdgPJdai8d7fmdNvV6l

What I have to do is that I should edit the following file as you mentioned.

file: /etc/calamares/modules/unpackfs.conf
---

> unpack:
> 
>     -   source: "/run/rootfsbase"
>         sourcefs: "ext4"
>         destination: "/"
>         exclude: [ "02-livecd.conf" ]
![Screenshot_2020-03-23_22-44-38](https://user-images.githubusercontent.com/62431488/77323113-11b75a80-6d58-11ea-9511-cb59d84b6e7f.png)

**Comment by gsitgithub** [comment]
Hello @geckolinux thanks for doing great job, hope you are doing well.
I am programmer but new to linux and using opensuse-Microos with kde version, do you have any shell script for goodies you are doing with geckolinux, so I can execute it and apply the changes and install third party repositories and packages without installing any new iso.
If you have it, can you share it on your repo.
Sorry for my bad english.
Thanks in advance.

**Comment by geckolinux** [comment]
Hi there, I'm doing well, thanks for asking.
I don't have a shell script, but you can find the complete list of packages and changes in the .tar.gz files here:
https://github.com/geckolinux/geckolinux-project

**Comment by Xmetalfanx** [comment]
> Yep, it's coming, sorry for the delay.

no problem ... thank you for the work you are doing on the only (to my knowledge) OpenSuse spin ... i have scripts to setup  OpenSuse myself but a distro like Gecko makes it easier for others

**Comment by dr03m** [comment]
Any update on this? I think the drivers for AMD graphics are outdated, since I can't get a picture on the screen with my Vega 8 graphics. Trying to boot it into Failsafe mode takes me into a terminal and I'm unsure what to do there.

**Comment by 64br137** [comment]
Hi @geckolinux , hope you're doing fine!

No pressure, but do you've plans to put a new ISO anytime soon?

Have a nice day.

**Comment by geckolinux** [comment]
@64br137  Thanks for the interest, I'm finishing up an XFCE test ISO based on Leap 15.2, I'll release it as a beta soon.

**Comment by 64br137** [comment]
Great, that's good news!!!

There's a "Tumbleweed" idea in the future?

**Comment by geckolinux** [comment]
> There's a "Tumbleweed" idea in the future?

The ROLLING ISOs will also be refreshed, but they're not a priority since the current ISOs can still be installed and reliably updated to the current Tumbleweed release with a simple `sudo zypper dup`.

**Comment by Xmetalfanx** [comment]
when i think of an ISO refresh for this I wouldn't expect it to be a constant thing with each TW snapshot so to speak .. too much work in my view... I do admit i did do a Gecko Rolling install + thousands of packages and in the end the system worked ... the updates are the reason i am thinking of this ... the update size of what was to be downloaded was almost as big as the size of the ISO 

I'd like to see something like a refresh every ... say oh (guessing here) every 2 months or something ... just so there are not TONS of updates... updates yes from the constantly rolling TW ... but not like 900 packages or something from a say (haven't checked the ISO lately i admit) 2 year old Gecko Rolling ISO.

Again thank you for your work and I do admit the updates do work on Gecko Rolling the last time I checked... just tons and tons of updating...that is why a somewhat updated Rolling ISO would be handy

**Comment by geckolinux** [comment]
Hi everyone, thanks for your patience. Please give this a spin, and test it on EFI and traditional BIOS systems:
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_STATIC_XFCE.x86_64-152.200714.0.iso/download

**Comment by woodyx86** [comment]
@geckolinux 
I've installed the test iso you'd shared.

the very first issue was that the /etc/resolv.conf seemed not to be updated
there is no entry in /etc/resolv.conf;
I manually added one, now the network started working. I'm writing this now on Gecko 15.2 :-)

but I'm expecting same issue will be likely happen when I switch the network, i.e., home to office

BTW,
the YaST soft management is working as expected.

Best,
woody

Edit: Fixed a typo error : /etc/resolve.conf -> /etc/resolv.conf

**Comment by geckolinux** [comment]
On 17/07/2020 04:44, woodyx86 wrote:
> the very first issue was that the /etc/resolve.conf seemed not to be updated
> there is no entry in /etc/resolve.conf;

Thanks a lot for the report. I assume you mean /etc/resolv.conf ?

I'm not able to confirm any issues with networking, both in the live environment as well as after installation, when using the NetworkManager defaults from the panel GUI.

Do you have a more complex network setup or something non-standard for your DHCP server?

**Comment by woodyx86** [comment]
> Thanks a lot for the report. I assume you mean /etc/resolv.conf ?

Yes I mean /etc/resolv.conf (sorry for typo)

> Do you have a more complex network setup or something non-standard for your DHCP server?

No, just I've been using an local ISP, which had been experiencing no problem at all (Win 10, other linux like Clearlinux is working fine)

I need to dig more about it, but I had similar experience with your previous test iso (XFCE version you shared in this thread)
it ran without an issue(DHCP - regardless of wired or wireless) at home,
however tried to make it plugged-in in office, then the resolv.conf was not updated.
so every time I had to edit it manually.

A question,
should I come up with networkmanager and try to re-configure it whenever I need to switch over from one network setup to another?
it happens with my HW installation. I've not tried it in Live mode

**Comment by geckolinux** [comment]
I see. Could you also please test a live ISO of Leap 15.2 straight from openSUSE? I suspect you'll find the same behavior, but it would be interesting to know for sure.

**Comment by woodyx86** [comment]
A quick check according to your suggestion: before I go, I asked my friend, google :-)

https://www.reddit.com/r/openSUSE/comments/b91tjk/opensuse_resolvconf_not_updating/

some people had it already, 
the reddit page suggested "sudo netconfig update -f"

I have 2 installations of Gecko
one on Lenovo X250, the other on Lenovo X200
same issues!!
Interesting..

Update: a Gecko user
https://forums.opensuse.org/showthread.php/535973-etc-resolv-conf-needs-to-be-deleted-almost-every-boot

**Comment by geckolinux** [comment]
The only issue I am aware of relating to resolv.conf was an upstream openSUSE issue where it would not update after upgrading the system, leaving the system with no DNS addresses, but that's a different issue and it should have been fixed over a year ago.

**Comment by woodyx86** [comment]
got it.

In the mean time, I resorted to this guide on the wiki page link below
https://en.opensuse.org/SDB:Configure_DNS

> Method 1: Use NetworkManager applets

    In your panel or system tray, click the network icon.
    Click Configure network connection.
    Choose the connection.
    In IPv4 tab, type 1.1.1.1,1.0.0.1 in Additional DNS field.
    In IPv6 tab, type 2606:4700:4700::1111,2606:4700:4700::1001 in Additional DNS field.
    Save connection.
    As NetworkManager in OpenSUSE uses netconfig DNS settings, you need to edit /etc/NetworkManager/NetworkManager.conf and add following line:

    rc-manager=file

    Disconnect and reconnect.

--
If I have something to share, I'll be back then
Take care,
Thanks

**Comment by woodyx86** [comment]
I tried Opensuse 15.2 installation disc, it had no issue around network setup.

so I'd re-installed gekco xfce test.iso again,
this time I had the wifi network setup configured before I went to click 'install' icon,
it had no problem at all now. all is working as charming!

the /etc/resolv.conf in the previous installation was blank, but
this time :

cat /etc/resolv.conf

'# /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
'# autogenerated by netconfig!
...
'# See also the netconfig(8) manual page and other documentation.
'# Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
nameserver 192.168.0.1

I still have no idea why the issue happened, but
as WA, it need to practice making the wifi(DHCP) configured before one starts to install gecko. at least it works for me.

There is no other problem observed so far.
Thanks for the solid distro!

**Comment by geckolinux** [comment]
Interesting, thanks a lot for confirming that.

**Comment by geckolinux** [comment]
@woodyx86 Thanks again for catching that issue and reporting that /etc/resolv.conf should be symlinked to /var/run/netconfig/resolv.conf . I later ran into the same bug when testing the ISO on real hardware with WiFI. This bug has been rearing its head in different forms for several releases, but you helped me find the root cause. Now the above mentioned symlink will be provided out-of-the-box on GeckoLinux to prevent this from happening.

**Comment by woodyx86** [comment]
@geckolinux 

AWESOME!!
You're genius :-)

Happy Gecko-ing

**Comment by geckolinux** [comment]
Here's the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719

**Comment by geckolinux** [comment]
Hi everyone, I'd appreciate your help testing this new ROLLING ISO:
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_ROLLING_Cinnamon.x86_64-BETA-999.200725.0.iso/download
Please try it in virtual machines _and_ physical hardware, in both legacy and EFI modes. Thanks a lot!
