### ISSUE TITLE
no reviving from suspend rolling MATE install with Nvidia GTX 780 card MacPro?

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#125]
Geckos:
Had some similar issue in Gecko and in TW awhile back, 6 months to a year, and got a reply here suggesting going to proprietary Nvidia drivers, so I did that and . . . it was good.  Until recently . . . seemed like I started having problems in TW as the rolling aspect brings out packages faster than Nvidia drivers can handle . . . so in TW I did a fresh start and went to "default video drivers," i.e., not "nouveau" . . . and haven't had any issues with "reviving from suspend."

In comparison my Gecko MATE rolling install has been more or less "problem free" until again recently, and I believe I uninstalled the Nvidia drivers, but didn't do a fresh install . . . ran zypper a few days back, no problems, then this morning there were "292 packages" to upgrade, which I ran, and then continued to use the computer w/o rebooting.  I went into suspension zone for a few minutes, then clicking "go" and the display button stayed orange, had to use power button to shut down . . . went back into Gecko, everything working, then "suspended" again . . . and again, no revival??

I rebooted and went into TW and checked and "revival from suspend" is working, and no updates to run . . . ??  I'd like to avoid doing a fresh install of Gecko if possible, and seems like avoid Nvidia proprietary if possible, because they aren't keeping up with bleeding edge software like "rolling" . . . is there a way to see if I can clean what is likely "nouveau" driver out and match my TW set up using something, like default driver "drm"???? using Yast or command line, without running fresh install?? to bring back the "revival from suspend" feature that seems to be happening in Gecko now?  It's fade to black . . . and the machine fires up, but display stays black, very black in nature????

**Comment by geckolinux** [comment]
Yep, just remove the xf86-video-nouveau package and reboot. It will fall back to the Xmodesetting general driver, usually works pretty well.

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks for the reply, it's helpful to get the package name . . . as I was in a black screen I couldn't check anything out at the time . . . .  I'll get back into Gecko in a bit, maybe tomorrow . . . or later today and test your suggestion out . . . and I'll post back on it.  Since going to default in TW worked pretty well I'm assuming this will work here in Gecko w/o issue . . . the gents over on OS forum didn't have your option to "rm nouveau" . . . they had me run fresh install to get down to base driver. : - (

**Comment by esteelpaz** [comment]
@geckolinux 

Well, I used Yast to remove that package, which seemed to go quickly and I rebooted, then suspended the computer and left for a couple of hours.  When I got back I hit "go" and the machine fired, but the screen stayed black.  I ran "lsmod" and video is still showing "nouveau" and other places are showing "nvidia, nouveau" . . . so seems like the problem remains . . . no reviving from suspend after the latest upgrades???  I'll have to look at the sources in a bit, to see if anything makes sense . . . .

**Comment by esteelpaz** [comment]
Yep, well I tried it a couple of times, and Gecko is continuing to not reviving from suspend, or rather the video/display doesn't wake up.  Had this happen in a couple of my linux distros and the "solution" was to go to Nvidia, but, then recently Nvidia drivers weren't keeping up with the speed of the rolling upgrades, so going nouveau seemed to work . . . until yesterday . . . .  But now it seems like default isn't reviving either . . . .

PS:  Also there is in the dmesg one item line with "Failed" :failed to set up virtual console and another "Depend" failed for dracut ask for add'l cmdline parameters . . . errors.

**Comment by esteelpaz** [comment]
@geckolinux 

So, after that last post I was back over in TW and I had updated earlier in the day and then got another whole bunch of upgrades, so I ran them . . . all remains well there as far as "waking" goes.

So I thought, well I removed the package you suggested and rebooted, but I didn't then run an upgrade, booted back into Gecko and ran zypper and it showed "161 packages" including some with "pattern" and "kernel" in the name . . . after that I again rebooted and logged in, hit "suspend."  But, unfortunately, "wake up" is not happening.  I'm in Gecko now to type this post . . . so video/display works when logging into the system . . . it just isn't able to have the revival . . . .

**Comment by esteelpaz** [comment]
Problem remains in Gecko today after running a zypper upgrade that installed "119 packages" . . . I logged out and back in, hit suspend and computer did not revive.  I rebooted and selected Gecko and went to eat breakfast, when I came back the display had gone to "sleep" but the display power button remained "blue" for "go."  I moved the mouse and the display instantly revived.

I again clicked "suspend" . . . display power went to "orange" for "sleep" . . . clicking the keyboard, the machine powers up . . . but display remains "black" . . . i.e., no signal.  Same errors are in the dmesg as mentioned above.  The problem began not through any changes that I made, but after a regular system zypper upgrade.  I'll try a few more times at the zypper upgrade over the coming days, if that fixes the problem I'll post back, otherwise I'll start looking around for where to file a Gecko Bug report . . . system should be able to suspend and then revive normally . . . problem is not occurring now in TW . . . .

**Comment by esteelpaz** [comment]
Found out that this is the "bug report" site so I'm posting at the right place.  Since there hasn't been any follow-up response to the "non-reviving from suspend" issue, I checked into getting the iso for a "fresh" install of rolling MATE Gecko . . . tried two downloads to get a clean checksum, but numbers don't appear to match up.  

I cloned the file to usb and booted it up and ran "media check" . . . the same error that I get in my bare metal install, "PKCS#7 not signed with trusted key" showed up in this iso dated from "2018"???  Tried a few apps in the live system, seems to be OK.  

I'm still trying to avoid the full fresh install, as even updating the system from 2018 will entail a lot of data transferring . . . and other than the system taking several minutes to boot up, once there it runs well . . . it just won't revive from suspend.

**Comment by esteelpaz** [comment]
Again ran zypper and it pulled in "158 packages" including new kernel . . . rebooted and clicked "suspend" . . . and once again it failed to activate the display . . . .  Comments? <cue sound of crickets>

**Comment by esteelpaz** [comment]
Seems like the posts here are being "edited" for content, without offering comment.  Saga still continues . . .  I ran another "99 package" update this morning, then yesterday I add the "nouveau" driver back in . . . problem remained, so today I switched back to "nvidia" drivers and still the system failed to revive, so I wiped the partition with the Gecko / filesystem and I ran a fresh install from the 2018 circa download available on Sourceforge . . . keeping the /home folder as it was.  Have to say the install went very fast, and with the new/old system from 2018 the suspend function revived!!!!  So that was "succesful" . . . in the interest of science now the Firefox browser was "old" and wasn't working . . . I ran again zypper to "dup -l" and it pulled in 1666 packages, which it ran through, when it finished I shut the computer down.

A couple hours later I returned and booted to the top hit in Grub, Gecko rolling" . . . and it errored out saying "failed to load kernel" . . . tried a few times, tried "recovery" with same error.  So the install appeared to be "clean" but after upgrading to the latest packages now system fails to boot.  Since it appears that I am working to "fix" this on my own, I'll try to boot the install using SG2, if that fails to work I guess Gecko is busted down and broke up in the latest kernel???

**Comment by geckolinux** [comment]
On 2020-03-22 4:31 p.m., esteelpaz wrote:
> Seems like the posts here are being "edited" for content, without offering comment. 

Hmm? No editing or censoring has taken place.

**Comment by esteelpaz** [comment]
Thanks for a reply . .. I had "cue sound of crickets" with < in front of and after it, seems to not show up in the post?? after yesterday's post??  

Anyway, I just tried to get SG2 to boot the upgraded install of Gecko that was there and booted up into and the suspend revive function did work this morning before I ran the latest updates, etc.  I tried all the different options in SG2 to try to boot Gecko, but seemingly in the upgrade of 1666 packages it seemed to not install the kernel??  It says something like "initrd-4.16.12-1-default has failed to load" . . . each option I try won't bring it past a grub error window . . . so I can't get to a Gecko TTY to try to run upgrades . . . ??  Is there a way to "load the kernel" somehow?  Question is what is it that is breaking the install, after fresh install it works, but after massive package upgrade now "no kernel"?  Now I'm out of ideas . . . .

**Comment by esteelpaz** [comment]
@geckolinux 

I'm struggling to try to figure out if this is a "forum" for issues related to Geckolinux, or just a place to post updates about stuff?  Even if this is a "bug report" place only then it seems like there should be some processing of the report that would take place?  This problem showed up after running a routine zypper update/upgrade . . . I've tried several options to alleviate the problem, including a fresh install, which did solve the problem, but then the problem returned after bringing the system up to current packages, or rather, the problem worsened, as now it won't even boot the system--again after fresh install and zypper update/upgrade of the stock install.

To wit, no comment, or suggestions made, other than to say, "we aren't editing these posts" . . . or even to say, "Hey, I only check in here on Sunday for a minute, so otherwise, nothing will happen here." ???  I offer the comparison to my TW install, where I have revive from suspend and the system is still working, to suggest that somewhere in Gecko is a "bug" . . . how to narrow that down to a singular package or packages???  Gecko WAS one of my top choices for a great linux platform, but, now . . . it has a problem . . . .  I have two ubuntu, a Manjaro, and TW installs that are all essentially stock installs, all working fine . . . Gecko is the problem child at this moment . . . .

**Comment by esteelpaz** [comment]
Issue(s) seem to have been "solved" for now . . . chrooted into Gecko's yast from TW TTY, tried to do some adjustments there, but nothing could be changed, tried to launch "terminal," command not found, same for console, got an "xhost unable to open display """ error several times . . . seemed like nothing was "fixed" in doing that process.  But on reboot, a plain jane generic Grub 2.02 window opened, not the gorgeous OpenSUSE square w/in the square Grub . . . but, Gecko was the top hit listed, it selected itself, "unable to open display" showed again, but then "linux 5.5 xxxx" showed up and a few seconds later the GUI opened.  I logged into GUI Yast, clicked on some stuff, then launched GUI console, ran zypper . . . rebooted, logged in . . . clicked suspend . . . that worked, waited a minute, clicked the keyboard, and display power light turned blue and revival was initiated.  Must have been just "mounting" the partition that somehow worked to get Gecko to "find the kernel"?????  Done for now.
