### ISSUE TITLE
Gecko install seems to have deleted "/" data in an adjacent partition???

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#127]
As per my previous post where problems with Gecko brought the need for a fresh install process, but after that Gecko wouldn't boot due to "kernel not found" error.  That might have been discussed here, and I wound up chrooting into Gecko via the TW console in another partition, and Gecko was again functional.
A day or so later I tried to boot into my Manjaro install, but, the "/" data was wiped out, leaving only 447MB of data, non-mountable . . . only serious operation done was the Gecko install using Calamares installer . . . have seen some problems from that installer previously.  It's difficult to nail it down exactly as to how this happened, very rare to have large swathes of data removed other than in installations??  But seemingly in close temporal proximity to the recent installer . . . perhaps being confused about what it was supposed to do???

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
