### ISSUE TITLE
Gecko installs Geary but it won't open

### ISSUE THREAD

**Issue by DPinNM** [geckolinux/geckolinux-project#128]
I have Gecko Linux Rolling Plasma installed on an Acer Aspire One 722,

All has gone very well, actually (after that titanic 1700+ package update to an .iso from 2018)...and I'm getting used to YaST Software for adding packages. But one package completely stumps me: Geary.

It's available through YaST Sofware...and it and its dependencies all download and install without a hint of a problem. It appears in the menu under Internet...but, then, when I click on it, simultaneously a small Geary icon appears alongside the cursor and another one appears in the panel...and then they disappear. Geary never opens up. But, on the other hand, there's never any kind of error message or sign of a "broken" process.

Does anyone have any ideas as to what's going on here? I feel I'm so close to opening the app...but then there's horseshoes and hand grenades for the things where "close" counts.

**Comment by geckolinux** [comment]
Please try the latest Static release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
