### ISSUE TITLE
intel 64bit processor / 32 bits UEFI boot support

### ISSUE THREAD

**Issue by JYYYYJY** [geckolinux/geckolinux-project#129]
Dear Gecko team,
 
Considering the need of many new linux users to support the strange archictecture of the intelbaytrail hybrid tablet/compters (that have 32bits UEFI but 64 bit intel processor) Do you ever consider supporting these 64bits processor / 32bits uefi architecture?
A lot of people look for linux distributions for these intel bay trail netbooks online, that could be a lot of new users for Gecko since most struggle to find a distribution that works/boots for them (only Fedora, Debian and Mxlinux so far...)
Greeting!

**Comment by geckolinux** [comment]
Hi there,

I would also like to run GeckoLinux on a 32bit laptop I have, but unfortunately I am limited by the fact that openSUSE does not support 32bit for Leap. GeckoLinux doesn't produce any of its own packages, rather it is a spin of openSUSE that depends entirely on its infrastructure.

Thanks and best regards.

**Comment by JYYYYJY** [comment]
Hi!
Well what i am talking about is just the 32UEFI bootloader that can just be included in the iso for 64bit processor! Its for that architecture that has 64bit processor but 'inside' a 32bit uefi...

**Comment by geckolinux** [comment]
Oops, sorry I misread that. By any chance do you know what the openSUSE package is called for that 32bit UEFI? To be honest I don't understand very well how UEFI works, so I'm kind of in the dark. Thanks.

**Comment by JYYYYJY** [comment]
Hi!
Well i think that so far opensuse ships with only "64bit UEFI"! And therefore Opensuse is not bootable of these hybrid tablets... That is why it could be a new argument for GeckoLinux to add this boot option for 32bits UEFI 64processors...

**Comment by JYYYYJY** [comment]
Hi again!
Here is an exemple of solving this in another distribution:
https://forum.manjaro.org/t/manjaro-usb-with-ia32-efi-support/77180/6

**Comment by JYYYYJY** [comment]
Hello again!
Here is an article I found about someone managing to do exactly this!
For leap: https://nwrickert2.wordpress.com/2018/11/28/opensuse-leap-15-0-and-32-bit-efi/
For tumbleweed: https://nwrickert2.wordpress.com/2018/12/05/opensuse-tumbleweed-and-32-bit-efi/

**Comment by geckolinux** [comment]
Thanks for the tip. I've been reading his blog for years as well, he's a genius with UEFI and has helped identify some bugs with GeckoLinux's UEFI support in the past. I'll try to request him to take a look at the next GeckoLinux release to see if he can identify any bugs or ways to improve it, although we're limited to what openSUSE and Calamares can provide out of the box.

**Comment by Afsalmc** [comment]
Dear geckos , just adding a bootia32.efi file into your iso may solve the problem . I have a 32 bit UEFI device ,which i am not able to boot geckolinux . with Ubuntu and derivatives , copying all the files from installation iso along with bootia32.efi to a fat32 drive will do the job . But with gecko , from my experience only iso9660 drives (created by dd/Etcher/etc ..) can be booted properly and as iso9660 is a readonly filesystem , i cant copy my bootia32 efi file into it and iso failes to boot in 32 bit Uefi . I even tried to create my own Gecko iso (by following opensuse documentation of making a custom iso )with bootia32.efi but it failed to boot . only you Geckos can help solve the issue .

**Comment by geckolinux** [comment]
@Afsalmc  Thanks a lot for the suggestion. Are you saying that the 32bit UEFI doesn't even allow booting the GeckoLinux live USB?

**Comment by Afsalmc** [comment]
@geckolinux yes . i tried boooting your lxqt leap based iso today with bootia32.efi and i cant pass the "leap" booting screen .

**Comment by Afsalmc** [comment]
The reason for i can't boot gecko even with bootia32.efi is clear from your statement " Dont use Rufus" . in order to add bootia32.efi to my usb stick , i must have write permission to the device . when Etcher or dd or rufus with dd is used , i dont have rights to write bootia32.efi .

**Comment by geckolinux** [comment]
@Afsalmc Do you mean the very first screen with the four selectable options? Or did you see a "Leap" bootsplash screen with a spinner?

**Comment by Afsalmc** [comment]
i mean the Leap bootsplash or the green progress bar when used with failsafe .

**Comment by Afsalmc** [comment]
![photo_2020-08-16_20-15-47](https://user-images.githubusercontent.com/48438931/90337037-63110080-dffd-11ea-8d39-f38cac0b317d.jpg)
![photo_2020-08-16_20-15-59](https://user-images.githubusercontent.com/48438931/90337040-65735a80-dffd-11ea-9be3-6de1aa78f090.jpg)
![photo_2020-08-16_20-16-02](https://user-images.githubusercontent.com/48438931/90337042-66a48780-dffd-11ea-958e-254ff2754447.jpg)
![photo_2020-08-16_20-16-05](https://user-images.githubusercontent.com/48438931/90337043-67d5b480-dffd-11ea-8ffc-fd236bfd597c.jpg)

**Comment by Afsalmc** [comment]
These are the error screens i got .

**Comment by Afsalmc** [comment]
when using Etcher , i cant add bootia32 so no boot screen .

**Comment by geckolinux** [comment]
@Afsalmc  OK, I think I understood. Sorry I'm definitely not an expert on UEFI. But I do have an idea for an additional package I could add to the GeckoLinux ISO that might work. Hopefully later today I'll have time to generate an ISO, if you'd like to try that then?

**Comment by Afsalmc** [comment]
@geckolinux im not sure if i can test your iso today itself due to the fact that i have a limited data pack and online classes . will try maximum to test your iso within a couple of days .

**Comment by geckolinux** [comment]
@Afsalmc OK, no problem. We'll be in touch over the next couple of days then.

**Comment by Afsalmc** [comment]
great 😀😀

**Comment by Afsalmc** [comment]
hopefully today i can test your iso , looking forward and best wishes for your awesome work .

**Comment by geckolinux** [comment]
@Afsalmc Unfortunately it looks like it won't be a viable option. I just built the ISO with `grub2-i386-efi` package, but it fails to boot on normal x86-64 EFI hardware.

Could you please try one of these ISOs and let us know if it boots for you?
https://download.opensuse.org/distribution/leap/15.2/live/

**Comment by Afsalmc** [comment]
@geckolinux i tried Gnome live iso and resulted in getting the same error screen . so this is actually an opensuse problem and not one that affects gecko exclusively .

**Comment by geckolinux** [comment]
@Afsalmc  Thanks a lot for confirming that. I'd recommend filing a report with openSUSE:
http://bugzilla.opensuse.org

**Comment by Afsalmc** [comment]
ok , will do it . thanks man and keep up with your good work . your project made me into opensuse . Gecko has a more welcoming philosophy .

**Comment by geckolinux** [comment]
Another idea for @Afsalmc : Does your EFI system support legacy BIOS mode?

**Comment by Afsalmc** [comment]
unfortunately No . somebody on reddit told me that tumbleweed supports my kind of systems . is gecko rolling uptodate to have a try ?

**Comment by Afsalmc** [comment]
@geckolinux **This kernel also adds support for EFI “mixed mode” booting. This allows 64-bit x86 kernels to be booted from 32-bit firmware running on 64-bit capable CPUs.** [source](https://www.omgubuntu.co.uk/2020/06/linux-5-7-kernel-features)
isn't it so promising ?

**Comment by geckolinux** [comment]
Very interesting. No guarantees, but it sounds like it would be worth giving GeckoLinux ROLLING a try, the ISO is only a few weeks old.

**Comment by Afsalmc** [comment]
tried it , this time disc is not recognized .

**Comment by geckolinux** [comment]
Hi there, which disk is not recognized? What does it do or what errors does it throw?

**Comment by Afsalmc** [comment]
![photo_2020-08-18_11-23-45](https://user-images.githubusercontent.com/48438931/90475724-ab3b3a80-e145-11ea-8170-d28a810191a7.jpg)

**Comment by Afsalmc** [comment]
may be emmc storage is not getting recognized . idk exactly.

**Comment by Afsalmc** [comment]
@geckolinux successfully booted gecko tumbleweed from Ubuntu grub command line by selecting grub.cfg manually from there . Live Usb was made using Etcher . Thanks man , I'm trying your distro now .so happyy

**Comment by geckolinux** [comment]
@Afsalmc Thanks for your persistence, I'm glad it worked. That being said, I have no idea why it's throwing those errors, it still feels like something went wrong while creating the live USB.

**Comment by yusssufff** [comment]
Hi!
I am wondering if you plan to add the 32bits boot file in an future iso? That would be great really! So far i am not sure this issue is actually 'solved'...

**Comment by geckolinux** [comment]
@yusssufff  Unfortunately GeckoLinux can only support what openSUSE supports, so this issue wasn't marked as "Solved" but rather as "Closed" because it probably won't be possible to fix.

**Comment by yusssufff** [comment]
thanks for the answer! but is it so complicated to add a bootia32 file to your iso?

**Comment by geckolinux** [comment]
> but is it so complicated to add a bootia32 file to your iso?

I honestly don't know what's needed or how to make it work. I have little experience with UEFI, I prefer the simplicity of a legacy BIOS setup on my systems.

**Comment by yusssufff** [comment]
Hi!
At the end this issue was actually solved?
