### ISSUE TITLE
keymap problem

### ISSUE THREAD

**Issue by bardor** [geckolinux/geckolinux-project#13]
The finnish keymap selection is using the wrong keyset it should be using the same keyset as swedish but as it is now it uses the US/UK keyset and thats wrong.

**Comment by geckolinux** [comment]
Hi, is this with a live or installed GeckoLinux system? If it's an installed system, please verify that it is actually using the Finnish/Swedish layout, since there appears to be a bug that does not preserve the layout you selected during installation.

**Comment by bardor** [comment]
ok will do

**Comment by bardor** [comment]
yea i confirmed thatlayout you choose after first boot after install will set the right keymap but the bug is in the installtion that even if you choose your keymap it will still set the actual keymap as us/uk keymap even if value is in my case finnish

**Comment by geckolinux** [comment]
Ok, thanks for confirming. Unfortunately it's not something I can fix. Please file an openSUSE bug report against the `live-installer` package.
