### ISSUE TITLE
Thumbnails not generating in Nautilus

### ISSUE THREAD

**Issue by tansowny-tech** [geckolinux/geckolinux-project#130]
I installed and fully updated Gecko Rolling with Gnome and am having an issue with thumbnails not showing up for picture files on any kind. When I open pictures with gThumb, the thumbnails are generated but not until I open the pictures with gThumb.

I have tried deleting the thumbnail cache and ensured Nautilus was set up to show previews.

Any ideas?

**Comment by tansowny-tech** [comment]
I couldn't get it to work so I ended up just installing Tumbleweed where it is working fine.

**Comment by geckolinux** [comment]
Sorry, I was just going to respond. I had something similar happen to me, you just need to install `gdk-pixbuf-thumbnailer` and optionally `gdk-pixbuf-loader-rsvg`.

**Comment by geckolinux** [comment]
Fixed in the latest release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
