### ISSUE TITLE
Is font rendering in gecko still better than recent openSUSE releases?

### ISSUE THREAD

**Issue by datMaffin** [geckolinux/geckolinux-project#131]
I am pretty sure that current openSUSE releases have greatly improved their text rendering: subpixel antialiasing of text is now enabled by default.
(I believe the responsible patent expired)

I am therefore wondering if geckolinux should/can still claim to provide improved font rendering.

Font rendering is mentioned in various places:
* https://github.com/geckolinux/geckolinux.github.io/blob/6893c0a428afb5a4d4ed5c0d5259b50e75c12a6a/index.html#L69
* https://github.com/geckolinux/geckolinux.github.io/blob/6893c0a428afb5a4d4ed5c0d5259b50e75c12a6a/index.html#L84
* README of geckolinux-project: https://github.com/geckolinux/geckolinux-project/blob/geckolinux-release/README.md

***Unrelated:***
Really like the idea of geckolinux; tried it in the days of openSUSE 42 (main reason was the font rendering). Great to see updated images!

**Comment by geckolinux** [comment]
That's a fair point, thanks for mentioning this. It would be good to do some side-by-side comparisons. I would add that there is more to font rendering than just the actual rendering minutia; the application theme and the specific font that is chosen also makes a huge difference in contrast and readability, and GeckoLinux is still very different from openSUSE in that respect.

**Comment by simonsaysthis** [comment]
Hello. Great discussion. To be honest, I still find gecko font rendering superior to Leap, especially when using Ubuntu fonts.

**Comment by geckolinux** [comment]
@simonsaysthis The Ubuntu fonts are seriously good. They can definitely go a long way to making any distro much more readable and enjoyable to look at all day.

**Comment by woodyx86** [comment]
Well,
I'm spending a lot of time reading codes, so I'm very keen to some fonts for programming due to their readability
I used to use Hack fonts, but I found one, I meant the better, or the most

 https://www.ibm.com/plex/

Unfortunately there is no package in the Leap repo,
but if the geckolinux takes care of the all time coder or programmer as such,
I think it worth having a look.

**Comment by geckolinux** [comment]
@woodyx86 Oh that's a good one. Thanks for reminding me about Plex. I always love a good monospaced font. It's available in the Tumbleweed repos as `texlive-plex-fonts`, and there's a semi-official Leap repo [here](https://build.opensuse.org/package/show/Publishing%3ATeXLive/texlive-specs-s).

**Comment by datMaffin** [comment]
Fonts are highly subjective... So with a grain of salt 😉 !

Soo your talking about Monospaced fonts 😁 :

I feel like I need to defend Ubuntu Mono here: It is one of the best monospaced fonts (as soon as you get used to the `m`). Turns out I **really** enjoy the Ubuntu Mono `m`, which is why I forked another top (but unknown) font, Mononoki, and changed it to be more similar to Ubuntu Mono. 
The only (really minor) issues I have with Ubuntu Mono are:
* The italic letters are too far back (some terminals (like xterm) cut them off)
* It exudes the "Ubuntu" brand (not that much, but at least a little)
* Italic `i` and `l` (I personally think they could be better like Consolas, Mononoki demonstrate).

About IBM Plex Mono: Yeah it definitely is not bad. Personally i do not really like the shape of `i` and `l`; i prefer the way of Ubuntu Mono/Hack. There are a few other letters of which I am not a big fan; like the `t`. I also like my Monospaced fonts to have the minimal amount of serifs (see IBM Plex `r`, `f`). I really like how different the italics of IBM Plex Mono look (kinda like Operator Mono), but I am more used to the Consolas style of italics.
However the reason why I (personally) would not choose IBM Plex Mono as the default is: It does not look as "sharp" as other fonts in low-DPI settings. 

=> Ubuntu Mono is the best choice for the general case.

Other great Monospaced fonts (may not have heard of some of them):
* Source Code Pro - takes alot of width
* Iosevka - highly condensed width
* Iosevka Wide - Pretty good, but is more boring than Ubuntu Mono etc.
* Fantasque Mono - Great unless you want things to be aligned and perfect
* Inconsolata - Great but has no Italic
* Inconsolata LGC - Great but italics are not as polished as regular (and line height is really high in most programms)
* Cascadia Code - It recently got *all the weights* added but no italics (yet(?))
* Bitstream Vera Mono/DeJaVu Mono/Menlo - Boring and has no italics
* Hack - Improves a lot on DeJaVu but still pretty boring (I believe it is the default in openSuse)
* Mononoki - Might not be as polished/exhaustive as other fonts; development is really slow.
* Jetbrains Mono - Letters are really similar to each other (can be seen as good or bad)

And then there are monospaced fonts/variations with Coding-Ligatures (but I do not use them). If chosen as default they can be really confusing.

Now about sans serif fonts 😜:
I was thinking about IBM Plex Sans: I really like it; I use it as the default sans serif font in all my browsers. It also seems to be used everywhere; in youtube videos, reddit etc. I like it because it has more "character" than Open Sans (and the italic are  more distinct (in a good way)).
To me Ubuntu Sans seems (even more so than the mono variant) to exude the "Ubuntu" brand (Geeko uses it for window titles). As far as I know openSuse uses OpenSans as default, which is a great neutral choice. IBM Plex Sans could be a great (more brand neutral) but more characterful alternative. However, I am not entirely convinced that it would objectively improve the readability when compared to Ubuntu Sans.

**Comment by geckolinux** [comment]
So, what do you think? Am I just biased? (Make sure to view all the images at 100%)

![Screenshot at 2020-07-31 15-42-46](https://user-images.githubusercontent.com/2692138/89077670-4eb7dd00-d348-11ea-8ae5-636144e400df.png)

![Screenshot at 2020-07-31 15-52-21](https://user-images.githubusercontent.com/2692138/89077688-56778180-d348-11ea-82d6-e5eb9ff65af2.png)

![Screenshot at 2020-07-31 16-00-55](https://user-images.githubusercontent.com/2692138/89077701-5ecfbc80-d348-11ea-80b1-c28b7a55b1aa.png)

![Screenshot at 2020-07-31 16-06-48](https://user-images.githubusercontent.com/2692138/89077718-6c854200-d348-11ea-9ca6-ad30cacc36fa.png)

**Comment by datMaffin** [comment]
In the first image: Text without subpixel-antialiasing can be found in two places:
The application titles and the FF url bar:
<img width="1593" alt="Screenshot 2020-08-01 at 10 19 22" src="https://user-images.githubusercontent.com/29998721/89097851-fd106080-d3e2-11ea-8a7b-cbc231c734d2.png">
<img width="1393" alt="Screenshot 2020-08-01 at 10 23 22" src="https://user-images.githubusercontent.com/29998721/89097854-013c7e00-d3e3-11ea-9bb1-ce9c93a4406c.png">
Though everywhere else subpixel-antialiasing was used.

I was unable to find greyscale-antialiased text in the other 3 images.

I don't have a monitor to view the image correctly in 100%/pixel perfect. (Somebody else would need to critique "the whole" picture.)

**Comment by geckolinux** [comment]
Sharp eyes @datMaffin !

Here's another nice (unsolicited) testimony from a real-world user:
https://www.reddit.com/r/linux/comments/i1t6lz/what_magic_has_geckolinux_made_to_font_rendering/

**Comment by geckolinux** [comment]
Here's another XFCE comparison, because I realized that the Numix theme changes the colors in unfocused windows.

![Screenshot at 2020-08-01 13-28-15](https://user-images.githubusercontent.com/2692138/89108147-c3981f00-d3fb-11ea-8fc2-46655dab6adf.png)

![Screenshot at 2020-08-01 13-31-55](https://user-images.githubusercontent.com/2692138/89108151-c72ba600-d3fb-11ea-9aad-927fa094cec8.png)
