### ISSUE TITLE
Cinnamon does not support metacity-theme-1.xml format

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#132]
As of version 3.8.x, Cinnamon no longer supports metacity-theme-1.xml format (TraditionalOk from mate-themes is one of these). You have no control over what Cinnamon supports, but you do have control over which Windows Borders and Controls are included in Gecko Cinnamon Themes. I suggest you eliminate the ones from mate-themes which no longer work and add some that do.

**Comment by geckolinux** [comment]
Thanks for the suggestion, the only theme that is explicitly included in GeckoLinux (and recommended for optimum font readability) is Numix. All the others themes come as dependencies of some other necessary packages and can not be eliminated. If you want you can trace which other package is forcing them to be installed, and file an openSUSE bug to eliminate those dependencies.
