### ISSUE TITLE
How to turn off changes saving on LiveUSB

### ISSUE THREAD

**Issue by Ygarr** [geckolinux/geckolinux-project#134]
How to, what parameter or tuning need to LiveUSB stops saving changes while using OS in portable way

**Comment by geckolinux** [comment]
Hi, at the boot screen hit the `E` key on the first option:

![Screenshot at 2020-07-30 08-15-06](https://user-images.githubusercontent.com/2692138/88928513-89355300-d23e-11ea-8f4d-1055c8f17126.png)


Then delete these highlighted options and boot with `F10` or `Ctrl+X` : 

![Screenshot at 2020-07-30 08-15-57](https://user-images.githubusercontent.com/2692138/88928457-7589ec80-d23e-11ea-969f-66a5363409fc.png)
