### ISSUE TITLE
Rolling Plasma ISO only working with one monitor

### ISSUE THREAD

**Issue by SungHwan-J** [geckolinux/geckolinux-project#135]
When I tried to use second monitor with HDMI on my laptop(intel i5-6600, hd 530) during installation with plasma, primary screen was stop and only second monitor responded to input, and then i disconnected second monitor, primary screen normally responded.

**Comment by geckolinux** [comment]
Hi, did you adjust the monitor configuration settings in Plasma? It should pop up a monitor configuration helper when you plug in a new monitor. Or you can enable/disable screens and configure how they work together in the Plasma configuration settings.

**Comment by SungHwan-J** [comment]
There are no-popup when I connect second monitor and I can't open monitor settings because it only show wall paper(there are no panel and widget) and responds to right button click and right click menu(I can open dolphin and configure desktop with this menu) with second monitor. And most applications are not working.(I tried to run application through krunner on right click menu, but it's not working.). But system normally working with single monitor.

**Comment by geckolinux** [comment]
Please verify the MD5sum of the ISO you downloaded and make sure it is `fc75046c57d4714139b746524e3f8ab1`, and then run the media check tool when booting the live distribution, you probably have a bad download.

**Comment by SungHwan-J** [comment]
[https://imgur.com/iWJ8tit](https://imgur.com/iWJ8tit)
checksum was not matched. I tried to re-download image but It failed to verify again.
but every file return 95c3da22a95a30d65b9d239ba82f5c80 checksum not fc75046c57d4714139b746524e3f8ab1.
but sourceforge info said checksum of that file is  95c3da22a95a30d65b9d239ba82f5c80.
I think you confused MD5 or uploaded wrong file.

**Comment by geckolinux** [comment]
> I think you confused MD5

Sorry, I did confuse the MD5, `95c3da22a95a30d65b9d239ba82f5c80` is the correct checksum:

![Screenshot at 2020-07-31 09-20-09](https://user-images.githubusercontent.com/2692138/89044114-219b0880-d30f-11ea-89a5-9922a41f1af8.png)

So please re-create your live USB, and then run the mediacheck on the live USB boot screen.

**Comment by SungHwan-J** [comment]
It passed mediacheck, but show same problem.
I also tested LXQT rolling ISO file, but it's normally working.
I think it's a KDE plasma bug.

**Comment by geckolinux** [comment]
I can not reproduce this problem. If many of the applications and panels and widgets are not working, then there is most likely something corrupted in your installation. I would recommend trying a different USB pendrive.
