### ISSUE TITLE
Big .iso release?

### ISSUE THREAD

**Issue by rubyFeedback** [geckolinux/geckolinux-project#136]
Hey geckolinux devs,

I recently hd-installed geckolinux, works fine. I'd like to switch 
between DEs though e. g. KDE5 and GNOME3 in particular.

Right now we can download only either variant e. g. GNOME3
or KDE5.

I am not sure how much work it is; the individual .iso files
work as it is, so perhaps it is just copying the content, and
then bundling it into a single .iso file.

My general idea is to be a bit like slackware, where you can
download a big .iso file and then select "install full" and choose
which variant you want to use at "runtime".

I am aware that I can install the DE lateron with a working
internet connection, but there are two reasons why I still
filed this report:

(1) One is for convenience. A full hd-install is very convenient
for me, my hdds typically have about 3 terabyte these days,
so even a full DVD has only about 4.7 gig, and extracte I 
dunno, 13 gig? That's still tiny.

(2) More importantly than (1), the computer geckolinux
is running on currently is without internet access. I can
change this, but it takes a bit of time, so I'd love to 
set it all up properly before connecting to the internet
(this requires moving it, or using a USB stick for WIFI/WLAN
connection but this is all a bit cumbersome as it is due
to how small-ish my flat actually is).

Anyway thank you for reading - if a big .iso release is too
hard to maintain feel free to skip this; or perhaps do it
only at xmas release or something. :)

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestion, but it wouldn't really work well for several reasons. The Calamares installer that GeckoLinux uses doesn't select packages for installation from the ISO, but rather it simply dumps the entire live image onto the target disk. And then there's the problem where Gnome works best with the GDM login manager whereas Plasma works best with SDDM, and it results in a cluttered hodgepog to have both environments installed concurrently. Sorry! I hope that at least one of the GeckoLinux options is viable for you though. Cheers.
