### ISSUE TITLE
Clock language

### ISSUE THREAD

**Issue by andrewbocho** [geckolinux/geckolinux-project#137]
When I installed geckorolling, I set the language to English, but because I have to put my location, which is Mexico, the clock is in Spanish.  How can I change this back to English.  Thank you.

**Comment by geckolinux** [comment]
Hi there,

Please edit the `/etc/locale.conf` file as root, you'll see something like this:

`````
LANG=en_US.UTF-8
LC_NUMERIC=es_MX.utf8
LC_TIME=es_MX.utf8
LC_MONETARY=es_MX.utf8
LC_PAPER=es_MX.utf8
LC_NAME=es_MX.utf8
LC_ADDRESS=es_MX.utf8
LC_TELEPHONE=es_MX.utf8
LC_MEASUREMENT=es_MX.utf8
LC_IDENTIFICATION=es_MX.utf8
`````

Change all the `es_MX.utf8` entries, or at least the `LC_TIME` variable to `en_US.UTF-8`.

BTW, you can avoid this from happening on installation by changing the locale values in the Calamares installer to `en_US.utf8` 

![Screenshot at 2020-08-02 07-30-03](https://user-images.githubusercontent.com/2692138/89123361-613f2d00-d494-11ea-9008-a8150a2232c5.png)
