### ISSUE TITLE
GeckoLinux Nvidia settings not opening

### ISSUE THREAD

**Issue by donuts12** [geckolinux/geckolinux-project#138]
I just downloaded all my nvidia drivers through yast and activated my prime to intel and it's not opening the app just see the bottom tab pop up and disappear. I've done all the same steps on opensuse and it works fine. 

I'm using rolling release version of kde.

**Comment by geckolinux** [comment]
A screenshot would be helpful.

Also, try temporarily setting the Plasma compositor settings to the most basic Xrender with tearing control set to "never". Or, log out of Plasma and change the desktop to Openbox or IceWM and try to run the Nvidia settings from there.

**Comment by geckolinux** [comment]
Probably related to #139 but not 100% certain.

**Comment by geckolinux** [comment]
https://github.com/geckolinux/geckolinux-project/issues/140
