### ISSUE TITLE
Grub error: symbol `grub_calloc' not found.

### ISSUE THREAD

**Issue by yxinolija** [geckolinux/geckolinux-project#141]
Hi, I recently stumbled upon this problem while updating with sudo zypper dup and restarting the computer.

Using Gecko Linux ROLLING KDE Plasma..

error: symbol `grub_calloc' not found.
Entering rescue mode...
grub rescue> 

I'm unable to boot on my desktop but i can from laptop.

What should i do?

Thanks.

**Comment by geckolinux** [comment]
Hi, is the affected system using SecureBoot and/or EFI?

**Comment by geckolinux** [comment]
Looks like it's probably related to the mess that developed around the "Boothole" GRUB+UEFI bug. Almost all the information I can find about your error message is very recent. Unfortunately it looks like openSUSE wasn't spared from this either, although you appear to be the first to report it. This is the most helpful thread I can find:
https://askubuntu.com/questions/1263125/how-to-fix-a-grub-boot-error-symbol-grub-calloc-not-found

I'd recommend [filing an openSUSE bug report](https://bugzilla.opensuse.org/enter_bug.cgi?product=openSUSE%20Tumbleweed), as it's definitely upstream. Since GeckoLinux uses 100% openSUSE + Packman packages, openSUSE can support this sort of problem, as an installed GeckoLinux system is essentially openSUSE.

Please let us know what comes of this. Thanks for reporting.

**Comment by yxinolija** [comment]
It's UEFI/GRUB2 for EFI, and secure boot is off inside BIOS.

Thanks for your help, I'll let you know.

**Comment by yxinolija** [comment]
[Bugzilla Link](https://bugzilla.opensuse.org/show_bug.cgi?id=1175036)

**Comment by geckolinux** [comment]
Thanks @yxinolija .
Meanwhile you could try repairing it with a GeckoLinux live USB as described in the above Askubuntu thread.

**Comment by geckolinux** [comment]
Another couple of questions for @yxinolija : 

Was this a fresh install of GeckoLinux that you updated for the first time? Or had you performed successful `zypper dup` upgrades before on this system?

Are there any other OSes installed on this same machine?

**Comment by yxinolija** [comment]
Desktop: I dual boot with Win10, i used standard openSUSE Tumbleweed until i ran into gecko.
So i guess it was like, format, install gecko and then update via zypper dup, when i stumbled upon that error, i reformatted again two times, reinstalled two times, still the same.

**Comment by yxinolija** [comment]
> Thanks @yxinolija .
> Meanwhile you could try repairing it with a GeckoLinux live USB as described in the above Askubuntu thread.

I will and report the results here in a few hours. Thank you.

**Comment by geckolinux** [comment]
> So i guess it was like, format, install gecko and then update via zypper dup, when i stumbled upon that error

And after installing GeckoLinux on that machine for the first time did you have any successful `zypper dup` ? What I'm trying to get at is that the most recent release of GeckoLinux ROLLING was on 2020-07-29, but very shortly after that this whole Boothole thing blew up. But there should have been a brief window _after_ the GeckoLinux release and _before_  the updated GRUB packages. So I just want to make sure that before the buggy GRUB packages were introduced that you could do a successful `zypper dup` on that setup.

Here's what you could do: [Tumbleweed-CLI](https://github.com/boombatower/tumbleweed-cli) uses [historical snapshots](http://download.opensuse.org/history/) of the Tumbleweed repos. Try installing it and setting it to upgrade to the `20200802` snapshot. If that snapshot updates and reboots successfully try upping it one by one until you figure out which snapshot introduced the bug.

Thanks for your time to help troubleshoot.

**Comment by yxinolija** [comment]
Nope, only on laptop for some reason which is updated to latest snapshot, but not desktop. 

Basically, install and use Tumbleweed-CLI inside Gecko that hasnt been zypper-dupped, right?

**Comment by geckolinux** [comment]
On 09/08/2020 09:56, yxinolija wrote:> Basically, install and use Tumbleweed-CLI inside Gecko that hasnt been zypper-dupped, right?

Right, what Tumbleweed-CLI will do is change the repos from the normal openSUSE Tumbleweed latest to the snapshot date that you choose. Then it will run the `zypper dup` for you, or if you interrupt the process then you can run it yourself.

**Comment by yxinolija** [comment]
When using "tumbleweed switch --install 20200802", should i ignore the line that says it will be updated to 20200807?

**Comment by yxinolija** [comment]
Nevermind, its an issue as listed in [here](https://github.com/boombatower/tumbleweed-cli/issues/15), will turn off the official tumbleweed repos if that helps.

**Comment by yxinolija** [comment]
I cant seem to install the 20200802 snapshot even with repos turned off, I'm unable to test the snapshots with tumbleweed-cli even when target is 20200802, it still does a distribution upgrade to the latest 20200807 or just downgrades installed packages.

**Comment by geckolinux** [comment]
Please post the contents of your `/etc/os-release` and your `/etc/zypp/repos.d/Tumbleweed_OSS.repo` file

Then post the output of:
`tumbleweed status`

Then try:
`tumbleweed switch 20200802`

**Comment by yxinolija** [comment]
![Screenshot_20200809_220443](https://user-images.githubusercontent.com/57045983/89738871-42d0c700-da7c-11ea-86fd-395e24eda5c7.png)


btw its a freshly reinstalled system again, since i kinda tried to ignore the zypper dup line saying its updated to latest 20200807, apologies

**Comment by geckolinux** [comment]
OK that all looks good, notice the `target: 20200802`. So now just do a `sudo zypper dup` and it should get you to the `20200802` snapshot.

**Comment by yxinolija** [comment]
even tho its switched to 20200802, it still wants to update to the latest 20200807 via here:
![Screenshot_20200809_202721](https://user-images.githubusercontent.com/57045983/89739183-db684680-da7e-11ea-8bd1-bdd5e82c2d44.png)

**Comment by geckolinux** [comment]
OK, I see the problem, I think you forgot to initialize the Tumbleweed-CLI configuration:
`tumbleweed init`

Then again:
`tumbleweed switch 20200802`

**Comment by yxinolija** [comment]
Returns this:

![Screenshot_20200809_203150](https://user-images.githubusercontent.com/57045983/89739238-6cd7b880-da7f-11ea-8150-8a81630e8b19.png)

**Comment by geckolinux** [comment]
That's fine, it's just saying that's what the target is set to. Your `/etc/zypp/repos.d/Tumbleweed_OSS.repo` should be different now, and `zypper dup` should now offer to take you to `20200802`.

**Comment by yxinolija** [comment]
Unfortunately it still returns 20200807
![Screenshot_20200809_203451](https://user-images.githubusercontent.com/57045983/89739291-d2c44000-da7f-11ea-8bf0-2e523ae748c9.png)

**Comment by geckolinux** [comment]
For some reason it's not modifying your repository files. I think you need to `su root` first. Then try:

`tumbleweed uninit`
`tumbleweed init`

**Comment by yxinolija** [comment]
without luck, still the same:
![Screenshot_20200809_203832](https://user-images.githubusercontent.com/57045983/89739382-6990fc80-da80-11ea-98f8-bef07d18ff60.png)

**Comment by geckolinux** [comment]
Please post a screenshot of Yast Repositories.

**Comment by yxinolija** [comment]
Here:
![image](https://user-images.githubusercontent.com/57045983/89739410-c8ef0c80-da80-11ea-8fa7-59081182ce45.png)

**Comment by geckolinux** [comment]
For whatever reason it's not modifying the repositories. You can just manually change the **Tumbleweed_OSS** repo URL to this:
`http://download.opensuse.org/history/20200802/tumbleweed/repo/oss/`

Then `zypper dup`

**Comment by yxinolija** [comment]
Success, will report when the grub error still shows up on 20200802

**Comment by geckolinux** [comment]
OK, thanks a lot for your time, and really sorry for the hassle.

**Comment by yxinolija** [comment]
Its alright.

Btw, it returns the same after zypper dup to 20200802, grub_calloc not found

**Comment by geckolinux** [comment]
Ah, that's interesting. So they introduced the bug very shortly after the most recent GeckoLinux release. If I generate a current GeckoLinux ROLLING Plasma ISO from the latest packages would you mind installing it and seeing if that successfully updates to future Tumbleweed releases?

**Comment by yxinolija** [comment]
Sure, ill try

**Comment by geckolinux** [comment]
OK, give me an hour or so and I'll have a download link for you. Thanks!

**Comment by yxinolija** [comment]
No problem, thanks.

**Comment by yxinolija** [comment]
Will it make a difference if ill just clone my windows somewhere and use my whole SSD for Gecko without dualboot? Just to repeat the steps from before if dualboot is the problem

**Comment by geckolinux** [comment]
I don't fully understand what happened with this Boothole mess, but it had something to do with Microsoft being the certificate authority that confirms that the GRUB bootloader is legitimate. So when they found a serious GRUB vulnerability, Microsoft blacklisted that version, and then they discovered problems caused by the fixes to GRUB and rolled them back, leaving GRUB in some kind of a limbo state where the old version can't be used and it can't boot to update to the new one. Something like that. 

So it's pretty easy to generate a new GeckoLinux ISO, I'd be interested in knowing if that continues to work from here on out. 

Meanwhile could you please try to completely remove the GRUB bootloader from your UEFI settings?

**Comment by yxinolija** [comment]
Sounds like a big mess after that vulnerability discovery. I can remove it but via reformatting the boot partition where GRUB is installed thru LiveCD, if thats ok with you.

**Comment by geckolinux** [comment]
Ah yes, true, reformatting the EFI partition should work. Probably backup that partition somewhere first to keep around the Windows bootloader, just in case. Then you could just use the Advanced partitioning option in Calamares once I get you the new ISO.

**Comment by yxinolija** [comment]
Alright, standing by.

**Comment by yxinolija** [comment]
Should i use rufus or etcher for writing the image?

**Comment by geckolinux** [comment]
> Should i use rufus or etcher for writing the image?

Probably etcher, but both should work. Here you go:
https://sourceforge.net/projects/geckolinux/files/testing/
The `GeckoLinux_ROLLING_Plasma.x86_64-999.200808.0.iso` will be available for download in a few minutes as soon as it gets picked up by the mirrors.

**Comment by yxinolija** [comment]
Thank you, update coming soon.

**Comment by yxinolija** [comment]
Even though the Calamares installer randomly exited on me close to the end, i successfully booted inside, running zypper dup now.

rebooting..

and successful boot, everything working now.

I salute you and thank you for solving this.

**Comment by geckolinux** [comment]
Thanks for your persistence. The real test will be in a day or two the next time there is a new Tumbleweed release, especially if it contains updated GRUB packages. Please report back how that goes.

**Comment by yxinolija** [comment]
True, no prob. Will do when the problem comes back. Thanks again.

**Comment by yxinolija** [comment]
Leaving a link to reddit post about the same thing but on Leap:[Reddit](https://www.reddit.com/r/openSUSE/comments/i6pici/looks_like_the_busted_uefi_grub2_packages_have/)

**Comment by geckolinux** [comment]
> Leaving a link to reddit post about the same thing but on Leap:[Reddit](https://www.reddit.com/r/openSUSE/comments/i6pici/looks_like_the_busted_uefi_grub2_packages_have/)

I saw that too... So this is absolutely an upstream issue, i.e. nothing I can do to prevent it from hitting GeckoLinux users. If @yxinolija confirms that his freshly installed system from the GeckoLinux 20200808 ISO survives a few zypper dups, then I'll probably refresh the entire GeckoLinux lineup so that at least fresh installs don't get hit by this bug. Existing users should probably not update their systems until we have some sort of official resolution from openSUSE and it is confirmed to have hit the update repositories.

**Comment by yxinolija** [comment]
Just a little update when i started my laptop:

I listed my boot options, one is grub, second one is geckolinux-secureboot. The grub choice returns the grub_alloc obviously, but the secureboot boots up normally even though secure boot inside LT BIOS is disabled. 
Just a little heads up.

**Comment by geckolinux** [comment]
Interesting. I honestly don't understand the intricacies of how UEFI works, I'm very old-school in that sense.

**Comment by yxinolija** [comment]
Update: 

Zypper-dup successful from 20200807 to 20200810 while using the updated GeckoLinux_ROLLING_Plasma.x86_64-999.200808.0.iso on my laptop.

More info coming soon on the desktop computer.

**Comment by geckolinux** [comment]
Looks like this has been resolved upstream. Additionally, the next releases of GeckoLinux will have an improved Calamares configuration to make UEFI installations and subsequent updates to those systems more reliable.

**Comment by geckolinux** [comment]
In all spins of the current set of updates the GRUB identity has been changed to `geckolinux` for more predictable naming after GRUB updates.
