### ISSUE TITLE
Source forge links for Cuba is blocked

### ISSUE THREAD

**Issue by jkarpio** [geckolinux/geckolinux-project#144]
I think is not fair the developers from Cuba can't download ISOs because USA law against our country.

**403 Error – Forbidden**

Your request is being denied as it appears to be coming from a location banned by our Terms of Use.
Report Not Being From a Blocked Country

If you are not from one of the countries banned from accessing this site, please submit us a Support Request including your IP address (152.207.231.183) and country of origin.

**Comment by geckolinux** [comment]
Concuerdo totalmente, pero lamentablemente no tengo control sobre las políticas de Sourceforge, ya que es un servicio de terceros. Por favor intente con un torrent:
https://linuxtracker.org/index.php?page=torrents&search=geckolinux&category=0&active=1

**Comment by jkarpio** [comment]
ok, lo intentaré, pero por favor considere cambiar a otro proveedor de servicios que le brinde más libertad. Muchas gracias por su tiempo.
