### ISSUE TITLE
NVIDIA driver --> Xorg won't start

### ISSUE THREAD

**Issue by DoomExplorer** [geckolinux/geckolinux-project#145]
Hi, I was thinking of doing a testing spree of various Linux distro and decided to try Gecko for my first installation. But I am having quite a bit of problem with it. I have 2 issues:

1. Unable to boot into the Live session, using Rufus initially and then imageUSB.exe. Using Rufus, I initially wrote the ISO onto my USB and it just would not load into the Desktop. It got stuck in the following:
![IMG_20200816_143615](https://user-images.githubusercontent.com/69746435/90328971-5f688400-dfd3-11ea-9bde-fa5ef6174b40.jpg)

I hit Ctrl-D but to no avail. Hitting enter just brings me into Command Line. 
I subsequently used Rufus but the DD Image option instead and somehow got it to work. However, the first 2 lines of "ACPI region does not cover ...." still pops up during the start up, but I managed to boot into the GUI.

2. After booting into Gecko Live Session and installing in onto my PC, I installed the nVidia driver and then rebooted. This time, I am not able to go into the Desktop anymore. It just leave me at the CLI of sorts as attached below.  I am not sure if it is due to the nVidia or other factors where the installation was not done correctly as that was the first time I rebooted after the installation. 
![IMG_20200816_151108](https://user-images.githubusercontent.com/69746435/90329004-80c97000-dfd3-11ea-9d7e-0387b1028f42.jpg)

I used to install Manjaro and openSUSE a few months ago, but did not encounter installation problems. Really liked the polished feel of Gecko, a shame I can't use it.

**Comment by Afsalmc** [comment]
same issue here , but i can't even boot gecko into live . how did you managed to boot into GUI ?

**Comment by geckolinux** [comment]
@DoomExplorer  Sorry for the trouble. Rufus is not reliable for creating USB drives with GeckoLinux. Please try with Etcher or Rosa Image Writer:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-create-a-bootable-geckolinux-usb-key
You can see on your first screenshot that it can't find the filesystem, so something went very wrong while creating the USB key. Also, please check the md5sum of your ISO, you might have a bad download.

Regarding the NVIDIA drivers, there are no guarantees with NVIDIA and openSUSE. But you probably need to fully update the system first before trying to install the NVIDIA drivers. Also, for additional NVIDIA help please post your hardware details and exactly which versions of GeckoLinux you tried and how you tried to install NVIDIA in this issue: https://github.com/geckolinux/geckolinux-project/issues/140

@Afsalmc  Please create a new issue with the details of which ISO you downloaded, how you created the USB key, and what errors you're seeing. Thanks.

**Comment by DoomExplorer** [comment]
> same issue here , but i can't even boot gecko into live . how did you managed to boot into GUI ?

You need to select **DD Image** instead of ISO image when writing the ISO to the USB stick. Rufus has a pop-up option that lets you select it:

![Screenshot_20200816_214556](https://user-images.githubusercontent.com/69746435/90335796-f05a5200-e009-11ea-8546-40adf5f12dd0.png)

After that, I managed to get it up and running. In fact, I am replying to you via Gecko Linux here. But there's a bigger problem which I will address in my post below.

**Comment by geckolinux** [comment]
### Again, please do ***NOT*** use ***Rufus*** to create the GeckoLinux live USB.

These are the officially recommended programs in Linux and Windows for creating a live USB:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-create-a-bootable-geckolinux-usb-key
I can't offer support if you don't use those methods. (`dd` from the Linux command line can also be used by experienced users, but please be careful to not wipe the wrong partition and disk.)

**Comment by DoomExplorer** [comment]
> ### Again, please do _**NOT**_ use _**Rufus**_ to create the GeckoLinux live USB.
> 
> These are the officially recommended programs in Linux and Windows for creating a live USB:
> https://github.com/geckolinux/geckolinux-project/wiki#how-to-create-a-bootable-geckolinux-usb-key
> I can't offer support if you don't use those methods. (`dd` from the Linux command line can also be used by experienced users, but please be careful to not wipe the wrong partition and disk.)

Thanks for replying. I actually checked the SHA1 and it matches before I attempt to install it. I actually tried the OSForensics Image Writer (3rd in your list) and it still resulting in me not able to boot into Live Session at all. That's why I responded to @Afsalmc in such a manner as Rufus was the only one that was able to get it up and running. I will do one more re-installation with Etcher if you require but as of now, Gecko is running.

This is actually my 4th installation of Gecko and I am currently running it to respond to here. I have managed to narrow down the issue and it seems to be one of the packages from this list. Right after installation, I run the Yast Online Update, and installed everything on the list and restarted. All went well and good.

Then I opened YaST, clicked on Software Management and update the following list:

![YaST Software Management](https://user-images.githubusercontent.com/69746435/90336020-a4101180-e00b-11ea-91bf-c46b56406f0c.png)

Right after that, I restarted and the issue as per the 2nd screenshot in my first post happened:

![Cannot boot](https://user-images.githubusercontent.com/69746435/90329004-80c97000-dfd3-11ea-9d7e-0387b1028f42.jpg)

It may / may not have been the nVidia drivers. Does this help?

To add: I actually ran Leap 15.1 and hunted down my own nVidia driver about 2 months back and managed to install it without any issues. It took a bit of effort for a Linux newb like me, but it did not give me issues, so I don't think it is nVidia unless things has changed in the past 1-2 month.

**Comment by geckolinux** [comment]
>  I actually tried the OSForensics Image Writer (3rd in your list) and it still resulting in me not able to boot into Live Session at all.

OK, thanks, I just removed that one from the recommended list.

The problem with it failing to load a graphical session after installing those updates is definitely due to the NVIDIA driver. Unfortunately even with official openSUSE installs there are no guarantees with the NVIDIA hardware, I've read recent reports of it failing for openSUSE users too in Leap and Tumbleweed. If the default open source drivers work well enough for you I'd recommended just sticking with those. Otherwise, you can ask for help in https://github.com/geckolinux/geckolinux-project/issues/140 where there are users that have experience with NVIDIA hardware.

**Comment by DoomExplorer** [comment]
> > I actually tried the OSForensics Image Writer (3rd in your list) and it still resulting in me not able to boot into Live Session at all.
> 
> OK, thanks, I just removed that one from the recommended list.
> 
> The problem with it failing to load a graphical session after installing those updates is definitely due to the NVIDIA driver. Unfortunately even with official openSUSE installs there are no guarantees with the NVIDIA hardware, I've read recent reports of it failing for openSUSE users too in Leap and Tumbleweed. If the default open source drivers work well enough for you I'd recommended just sticking with those. Otherwise, you can ask for help in #140 where there are users that have experience with NVIDIA hardware.

Uhhh, ok. Just for the record, I tried the KDE Leap 15.2 version of Gecko.

So what can I do? Will me trying to install openSuse Leap 15.2 with the nVidia drivers help? That was my original intent actually, but I took a detour with Gecko Linux here since it looks much prettier from the screenshots. I have prepared space for 5 different distros to be tested on my desktop actually. :D 

My current rig is as follow:

Dell XPS 8910
- Intel i7 6700
- nVidia GTX 960
- 16GB RAM
- 256GB SSD (which I have partitioned it up nicely with 35GB for each distros to be tested)

I need some hand holding here as am really new to Linux.

**Comment by geckolinux** [comment]
@DoomExplorer  Thanks for the details. I'd say just re-install it GeckoLinux, but don't try to install the NVIDIA drivers. I'm not sure if you're aware of this, but Linux includes basic drivers out-of-the-box for NVIDIA hardware, which work fine for everyday work and watching videos. Then NVIDIA (the company) also offers their own drivers for Linux in a separate repository, but since they aren't built into the kernel they can sometimes be unreliable. That's what you see in the "NVIDIA" repository in GeckoLinux, but they're optional and not recommended in your case. Usually only gamers need them.

**Comment by DoomExplorer** [comment]
> 
> 
> @DoomExplorer Thanks for the details. I'd say just re-install it GeckoLinux, but don't try to install the NVIDIA drivers. I'm not sure if you're aware of this, but Linux includes basic drivers out-of-the-box for NVIDIA hardware, which work fine for everyday work and watching videos. Then NVIDIA (the company) also offers their own drivers for Linux in a separate repository, but since they aren't built into the kernel they can sometimes be unreliable. That's what you see in the "NVIDIA" repository in GeckoLinux, but they're optional and not recommended in your case. Usually only gamers need them.

I have not install the nVidia driver yet in my 4th installation of Gecko. I was hoping to switch to Linux for good in the future as am quite tired dealing with work loss from auto restart of Windows 10. That's why I am quite interested in the nVidia drivers as I do play some games. 

I will try openSUSE Leap 15.2 and report back here on the results. Thanks.

**Comment by geckolinux** [comment]
Ok, thanks a lot, please let us know.

**Comment by DoomExplorer** [comment]
Ok, I just did and it broke my openSUSE installation as well. I installed KDE version of openSUSE Leap 15.2 and every thing went well initially. I rebooted once and it loaded well. I proceeded to add the nVidia repository via YaST and it gave me a list of items to install as below.

![Screenshot_20200817_094550](https://user-images.githubusercontent.com/69746435/90340559-a1bdaf80-e02b-11ea-9bf6-59c1357bf5a5.png)

Right after that, I restarted and it has the same screen as what I posted for Gecko Linux. Damn... now I gotta reinstall my openSUSE. Or may be I will leave it be for now and run Gecko in the interim.

**Comment by geckolinux** [comment]
Yeah, I read something about that on the openSUSE Reddit. Thanks a lot for confirming that. You might be aware of this already, but nVidia is not known for being friendly and reliable with Linux. I'd recommend just using GeckoLinux with the pre-installed open source drivers and see if the performance is acceptable, you might not even notice a big difference. From the very little experience I have with nVidia, the main difference with the nVidia drivers is better thermal performance on laptops, but if you're using a desktop that shouldn't matter as much.
