### ISSUE TITLE
xhost terminal error

### ISSUE THREAD

**Issue by hari-aum** [geckolinux/geckolinux-project#146]
there is one minor issue when starting a terminal and going from user to root. a message above the root prompt states, when using "sudo -i" : xhost: unable to open display ""  and, when using "su" : non-network local connections being added to access control list.
terminal commands work fine. however, in other distros i have installed i do not see either of these messages. i've searched the internet and tried various solutions to no avail. any suggestions appreciated. is this anything to be concerned about?
thank you s.b. for your time & energies with geckolinux, much appreciated.

**Comment by geckolinux** [comment]
Hi there, thanks for mentioning this. It's not an error per se, it's an access control message due to a configuration that used to be necessary to make applications start as root in the live session, especially for the Calamares installer. It might not be necessary anymore, so I'll look into eliminating that for the next releases.

**Comment by geckolinux** [comment]
Ah, forgot to mention, you can disable that message by deleting your `~/.bashrc` file or removing from it the line:
`xhost local:root`

**Comment by hari-aum** [comment]
@geckolinux: thank you for your quick reply and suggestion.  the line to remove from ~/.bashrc was not there, however, i thought it might be in the root .bashrc file.  it was.  probably since the message occurred going from home user to root user.  i just commented it out and voila - gone.  it is something probably very minor, but, it was annoying.  thank you.

**Comment by geckolinux** [comment]
Fixed in all spins of the latest set of updates.

**Comment by hari-aum** [comment]
thank you for this notification and update
am downloading new iso now for backup as i do updates from terminal
 at least once per week.
i did fix the xhost error msg from a previous suggestion that had
worked fine.
still using geckolinux (static) as my main driver
thank you for work and energy with geckolinux
cheers - happy holidays too :-)
     On Friday, December 11, 2020, 05:43:56 PM GMT+1, GeckoLinux <notifications@github.com> wrote:  
 
 


Fixed in all spins of the latest set of updates.
