### ISSUE TITLE
xf86-video-intel package causes occasional complete freezes of KDE plasma 

### ISSUE THREAD

**Issue by Afsalmc** [geckolinux/geckolinux-project#147]
in Gecko Rolling plasma , with default xf86-video-intel package desktop freezes completely  with a working audio playback and mouse pointer . Removing this package enables modesettings intel graphics driver from kernel which eliminates this issue completely .

**Comment by geckolinux** [comment]
You could also try changing the Plasma compositor rendering method and/or disable screen tearing controls.
With that being said, I've also had considerable trouble with the `xf86-video-intel` driver with Plasma and am considering removing it.

**Comment by Afsalmc** [comment]
well that is a good news . 
out of curiosity , what is the need of xf86-video-intel in gecko iso if modesettings is working fine ?

**Comment by geckolinux** [comment]
On 21/08/2020 08:08, Randa Rason wrote:> out of curiosity , what is the need of xf86-video-intel in gecko iso if modesettings is working fine ?

The Intel driver does provide better performance, but for the Plasma edition it's just not worth it due to the instability.

**Comment by Afsalmc** [comment]
yesterday with modesettings driver vaapi harware accelaration suddenly stopped working . Vlc gave this error with intel-media-driver installed
![image](https://user-images.githubusercontent.com/48438931/90904175-903e2400-e3ec-11ea-9cda-1507d41e0cdf.png)
solved the issue by installing intel-vaapi-driver and editing /etc/profile.d/intel-media.sh to look like :  
```
# add libva driver path/name exporting for intel media solution
export LIBVA_DRIVERS_PATH=/usr/local/lib/dri
export LIBVA_DRIVER_NAME=i965
```
and copying /usr/lib64/dri/i965_drv_video.so to /usr/local/lib/dri .

**Comment by geckolinux** [comment]
Thanks, I think we can install `intel-vaapi-driver` out of the box, but I'm not sure if the other tweaks can be included by default without unintended side effects on different hardware configurations.

**Comment by Afsalmc** [comment]
Good to know . I will report issues with intel HD (Baytrail) while using intel-vaapi-driver( (i965)  for hardware acceleration.

**Comment by Afsalmc** [comment]
Seems fine , no graphics glitches or rendering issues with intel HD (Baytrail) graphics . No noticeable performance decay is found due to the transition from intel driver to modesettigs for day to day usage .

**Comment by geckolinux** [comment]
All Plasma spins in the latest set of updates now use Xmodesetting on Intel hardware.
