### ISSUE TITLE
The process for the gdrive protocol died unexpectedly.

### ISSUE THREAD

**Issue by Afsalmc** [geckolinux/geckolinux-project#148]
with plasma rolling , kio-gdrive throws an error `The process for the gdrive protocol died unexpectedly.` additional packages installed :` kio-gdrive  kaccounts-integration  kaccounts-providers    `

**Comment by geckolinux** [comment]
> additional packages installed :`kio-gdrive kaccounts-integration kaccounts-providers `

Thanks a lot, so that fixes it?

**Comment by Afsalmc** [comment]
@geckolinux nope . this is not a fix for it , what i meant is with Ubuntu and my previous distros , installing kio-gdrive enabled google drive access in dolphin . But with Gecko plasma i'm getting the same error even after installing `kaccounts-integration kaccounts-providers` . i have no idea about kio-gdrive dependencies btw , i just tried to get gdrive in dolphin by simply installing kio-gdrive and then noticed that Online Accounts settings for plasma is not coming by default with Gecko and then installed packages `kaccounts-integration kaccounts-providers` .

**Comment by geckolinux** [comment]
It would be interesting if you could try a live CD of Kubuntu or KDE Neon with your same account, because it looks like it might be an upstream issue:
https://www.reddit.com/r/kde/comments/id78t4/kiogdrive_error_when_accessing_google_drive_folder/

**Comment by Afsalmc** [comment]
unfortunately i don't have access to a live CD but can confirm that kio-gdrive was working fine with Kubuntu-20.04 before 3 days (and now i have replaced it with Gecko) . 
Thanks !

**Comment by geckolinux** [comment]
The problem with cloud services is that they can change something on their backend without notice, and 3rd party access methods will break. I suspect that this is probably the case here too. If you later have time and available data to test a live USB of KDE Neon or Kubuntu that would be helpful to know if we need to do additional debugging.

**Comment by Afsalmc** [comment]
sure ,will try then. Thanks man for your awesome work .

**Comment by Afsalmc** [comment]
https://www.mail-archive.com/kde-bugs-dist@kde.org/msg472298.html .

**Comment by Afsalmc** [comment]
this issue is solved now .
