### ISSUE TITLE
Dolphin Previews of Microsoft Word and Excel

### ISSUE THREAD

**Issue by freecicero** [geckolinux/geckolinux-project#149]
Hello - I am brand new to Gecko / Opensuse because i am testing it out for use in my office.  One of my major desires in using KDE is to use the Information panel in Dolphin to be able to scroll down a list of Microsoft word doc, dox, and excel xls and xlsx files and see a big preview of the file on the right.  This has been a feature available on Microsoft Windows File manager, and many third party windows file managers, for many years, and I really need to duplicate it in Linux if I am to have any chance of success at conversion.

So today I downloaded the latest KDE iso from the website and installed.  It is my understanding from googling that it is necessary to install Calligra to get these file type previews to work, so I have done that and checked off all the preview types in the Dolphin / Configure / Previews file types list, but what is showing up instead of previews is just a big white box.  

I have tried everything I can think of to make this work and am wondering if you have any tips or can just confirm that it is working for you.

**Comment by geckolinux** [comment]
Hi there, are you sure the bit white box isn't just a mostly blank white LibreOffice document?

>  latest KDE iso from the website

Could you also please specify which one, as there are 3 Plasma variants.

**Comment by geckolinux** [comment]
GeckoLinux NEXT Plasma:

![Screenshot at 2020-08-21 14-12-24](https://user-images.githubusercontent.com/2692138/90926338-8bf81380-e3b8-11ea-9dac-e7445db50f46.png)

**Comment by geckolinux** [comment]
GeckoLinux NEXT Plasma:

![Screenshot at 2020-08-21 14-20-38](https://user-images.githubusercontent.com/2692138/90926915-ad0d3400-e3b9-11ea-8646-89d45f83fb75.png)

**Comment by freecicero** [comment]
Thank you for your time and response!  Here is what I am seeing:


![Screenshot_20200821_152647](https://user-images.githubusercontent.com/21122734/90927459-24939100-e3c3-11ea-8689-e2c104a01b91.png)



And here is a copy of the actual document:  
[testspreadsheet.zip](https://github.com/geckolinux/geckolinux-project/files/5110873/testspreadsheet.zip)



As to the version I downloaded, the filename was GeckoLinux_ROLLING_Plasma.x86_64-999.200729.0

**Comment by freecicero** [comment]
In case it might help, here is a screenshot of my dolphin config panel:

![configpanel](https://user-images.githubusercontent.com/21122734/90928082-388bc280-e3c4-11ea-8449-a74df6692695.png)

**Comment by geckolinux** [comment]
Thanks for the screenshots, sorry I didn't notice that this was for MS Office formats.
Did you also try installing the `calligra-extras-dolphin` and `calligra-extras-converter` packages?

**Comment by freecicero** [comment]
Boy that sounded like such a good suggestion!  I checked and I did NOT have those loaded.  Unfortunately after I loaded and rebooted, exactly the same behavior.  

I tested further and I notice that if I save a spreadsheet in Libreoffice in ODS format, I can see a - sort of - preview for that, but it doesn't look much like a spreadsheet, more like an outline.

But when I create a spreadsheet in Calligra, and save it in ods format  I get the same blank result:

![ksnip_20200821-204017](https://user-images.githubusercontent.com/21122734/90944735-a51bb700-e3ee-11ea-8d40-d8b626cfd312.png)

**Comment by freecicero** [comment]
Let me say thank you very much for your attention so far.  I have tried and tried to get previews of Microsoft office documents to work in many distros, and I rarely find much success.  Seems like I recently had some success in Kubuntu and even Manjaro, but I gave those up for other reasons.  I would really like to settle in on a "businesslike" distro and I am impressed with how professional the opensuse community seems -- this preview problem in dolphin is just getting to be a pet peeve to me. So close to matching "windows" functionality, but just not quite there in my experience.  I am hoping we're on the verge of succeeding though.

**Comment by geckolinux** [comment]
Sorry we don't have a better solution.

There are no issues with `.ods` or `.odt` or any of the ODF formats, thumbnails for those work out of the box.

However it looks like there is currently no accepted good standard solution for thumbnails of MS Office documents. Maybe this will help:

- https://forums.linuxmint.com/viewtopic.php?p=1804934
- https://askubuntu.com/questions/870633/how-to-get-nautilus-to-show-file-previews-thumbnails-for-office-files
- https://github.com/NicolasBernaerts/ubuntu-scripts/tree/master/thumbnailer/msoffice
