### ISSUE TITLE
Doesn't Boot from UEFI

### ISSUE THREAD

**Issue by abdullahsabbir** [geckolinux/geckolinux-project#15]
Doesn't Gecko support GPT+UEFI? It's not booting. Rebooting every time when trying to boot it up.

**Comment by geckolinux** [comment]
Hello, what isn't booting? The live USB or the installed system?

**Comment by abdullahsabbir** [comment]
The Live USB. I made the Live USB using Rufus. (And of course I selected GPT with UEFI)

**Comment by geckolinux** [comment]
Hello, please use something besides Rufus, which usually or always fails 
to work with openSUSE. Please try this:

http://www.pendrivelinux.com/universal-usb-installer-easy-as-1-2-3/
or
http://www.osforensics.com/tools/write-usb-images.html
or
http://www.linuxliveusb.com/en/download
or
http://www.microsoftstore.com/store/msus/html/pbPage.Help_Win7_usbdvd_dwnTool/

Or better yet, if you have access to a Linux system, please use the 
SuseStudio Imagewriter tool.

**Comment by abdullahsabbir** [comment]
Thank You very much. ImageUSB Worked (others didn't).

**Comment by geckolinux** [comment]
Great, thanks for confirming. I'll put ImageUSB as the recommended tool 
in the wiki.
