### ISSUE TITLE
thermald as a default package

### ISSUE THREAD

**Issue by Afsalmc** [geckolinux/geckolinux-project#150]
why not include thermald in the default package list ? it makes a big difference tho :)

**Comment by geckolinux** [comment]
Thanks, big difference in what sense? Does it work with TLP, which is also preinstalled?

**Comment by Afsalmc** [comment]
I'm not that much aware about the scope of TLP here . Thermald helps very much to decrease over heating issue in my device . It's effect is pretty much noticeable in a fanless SOC like mine .

**Comment by Afsalmc** [comment]
Thermald causes complete freezes in Baytrail . Removing this packages seems to completely eliminate the issue . Don't know about other generations of intel cpus . A quick google search can list similar issues on other generations of intel but they are relatively old  and it seems that a patch is already applied to the kernel addressing the issue even though baytrail is still affected by this bug .

**Comment by geckolinux** [comment]
Thanks a lot for the information. I'm testing it on my daily driver with an older Ivy Bridge chip, and I don't notice any issues, but I also don't notice any reduction in CPU temps. So I'm thinking this probably shouldn't be included by default.

**Comment by Afsalmc** [comment]
May be you are right . Thanks !

**Comment by geckolinux** [comment]
Alrighty, thanks for the suggestion at any rate.
