### ISSUE TITLE
Replacing grub2 with systemd-boot

### ISSUE THREAD

**Issue by newinnov** [geckolinux/geckolinux-project#153]
Hi,

Would it be possible to replace grub2 with systemd-boot ?  
In other os like fedora and ubuntu , it can be done and there are guides available for that. But I could not find any material for Gecko/Suse.

Finally, Thanks for creating such a large number of DE isos, your work will surely increase Suse adoption.

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestion. What are the advantages of systemd-boot? We would also have to make sure that it works with the YaST Boot configuration tool, which is unlikely.

**Comment by newinnov** [comment]
Hi,

First visual advantage being faster boot time:
https://www.phoronix.com/scan.php?page=article&item=11-linux-boot&num=1

Second, Systemd-boot config files are way more clean and easier to manage relatively to grub.

Thirdly, newer distros are using Systemd-boot eg- PopOs, solus, arch variants …

Take PopOs for example, While Ubuntu( parent distro of popos) use grub2 only. Popos setup has both grub2 and systemd-boot, on blank disk it installs systemd-boot but if it detacts grub2 is already installed; it creates grub entry only ( To avoid replacing grub2 ). Also, solus has similar approach.

Personal reason- My already installed os use systemd-boot and personally I prefer systemd-boot over grub2.

But, if YaST being the limit reason then may be we have to wait until Suse does it officially. As I do not have enough exposure of Suse, just an average linux user.

**Comment by geckolinux** [comment]
Thanks for the reply. Does systemd-boot work with legacy BIOS mode, or just with EFI?

**Comment by newinnov** [comment]
Hi, 
It works only in EFI mode, no bios support. Thanks
And Yast will not work with it, Yast options are for grub2

**Comment by geckolinux** [comment]
Thanks for confirming. In that case it will not be implemented.
