### ISSUE TITLE
[Pantheon] Changing the default shell crashes the desktop.

### ISSUE THREAD

**Issue by kquote03** [geckolinux/geckolinux-project#154]
Pretty much self explanatory.
When changing the default shell to fish or zsh (for example) using chsh, the desktop crashes after a few minutes and you're sent back to lightdm.
Not sure if a pantheon bug or a gecko linux bug.
Thank you.

**Comment by geckolinux** [comment]
@awissu Any idea what's going on here?

**Comment by awissu** [comment]
I have no idea.
![Screenshot_20200914_195250](https://user-images.githubusercontent.com/8833364/93114944-ec325a80-f6c3-11ea-8f21-07ed01344d13.png)

**Comment by geckolinux** [comment]
@kenan1099 I'm pretty sure that the crash was unrelated to the shell change. Please confirm.

**Comment by kquote03** [comment]
I'm sorry for the amature-ish description and the late reply.
I didn't try zsh, I only tested with fish as it is my primary shell (which has given me problems before when running some bash scripts)

Steps to reproduce:
1. Install fish
2. Change the shell for both the main and root users
> sudo chsh user
/usr/bin/fish
>sudo chsh
/usr/bin/fish
3. Reboot

Symptoms:
When logging in as user or root, the wallpaper loads and notifications appear but wingpanel and the dock don't show and after around 5 minutes the user is sent back to the log in screen.

Reverting back to bash fixes the problem.

Output of journalctl (doesn't seem to include anything significant)
[journal.txt.zip](https://github.com/geckolinux/geckolinux-project/files/5252073/journal.txt.zip)

Thank you for making this amazing project!

**Comment by awissu** [comment]
You need to set a global variable:
```
sudo chsh user
/usr/bin/fish
sudo chsh
/usr/bin/fish
fish
set -x XDG_CURRENT_DESKTOP Pantheon
```

**Comment by awissu** [comment]
Fixed: https://build.opensuse.org/request/show/839667

**Comment by geckolinux** [comment]
Thanks very much @awissu !
