### ISSUE TITLE
How GeckoLinux is made?

### ISSUE THREAD

**Issue by prp-e** [geckolinux/geckolinux-project#155]
I was searching for openSUSE based distributions on Distro Watch and I found GeckoLinux. Haven't tested the operating system personally yet, but I got curious about the build process. 
If there's any documentation about making a custom openSUSE/GeckoLinux based operating system, I'd be happy to have it. 
Regards.

**Comment by geckolinux** [comment]
Hi there, I saw in a Reddit post that somebody already answered your question. But just in case, GeckoLinux is built with Kiwi, and here are the specific descriptions used:
https://github.com/geckolinux/geckolinux-project
Let me know if you need any more information.
