### ISSUE TITLE
Cannot Install Xampp

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#157]
Hi,
I am getting the below error when I tried to install the Xampp from bitnami ( **xampp-linux-x64-7.4.9-0-installer.run**
 ) 

```
Please wait while Setup installs XAMPP on your computer.

 Installing
 0% ______________ 50% ______________ 100%
 ########################################Warning: Problem running post-install step. Installation may not complete 
correctly
 Error running chown -R root:daemon "/opt/lampp/apache2/htdocs": chown: invalid 
group: ‘root:daemon’
```
I am not sure whats this invalid group. 

thanks for any help

**Comment by geckolinux** [comment]
Hi, that looks like a bug in the installer script.

**Comment by ghost** [comment]
Hello, 
yes, it was an issue with installer, I tried with a different one - seems worked
