### ISSUE TITLE
Do not apply theme for qt base softwares

### ISSUE THREAD

**Issue by mrostd** [geckolinux/geckolinux-project#158]
Hello
I am using Rolling Gecko Linux (GNOME desktop).
My themes do not apply to qt based softwares and they look ugly.
![Screenshot from 2020-09-13 08-15-07](https://user-images.githubusercontent.com/53259265/93009694-4b478080-f599-11ea-8e20-7d452e970975.png)

They are only compatible with the Numix theme:
![Screenshot from 2020-09-13 08-20-00](https://user-images.githubusercontent.com/53259265/93009778-21428e00-f59a-11ea-8509-db6c9cc7e4ee.png)
I did not have such a problem in openSUSE.

**Comment by geckolinux** [comment]
Hi, which GTK theme do you want to use?

**Comment by mrostd** [comment]
> Hi, which GTK theme do you want to use?

I use Adwaita (default).

**Comment by geckolinux** [comment]
Hi, you just need to install the missing Adwaita theme packages:

![Screenshot at 2020-09-13 18-57-39](https://user-images.githubusercontent.com/2692138/93031851-8d051500-f5f3-11ea-84ab-48bb57faea58.png)


![Screenshot at 2020-09-13 18-59-08](https://user-images.githubusercontent.com/2692138/93031856-99896d80-f5f3-11ea-99be-4d8aa240b5ef.png)
