### ISSUE TITLE
[Pantheon] Save as dialog no longer has 'ok/accept' button after updating.

### ISSUE THREAD

**Issue by kquote03** [geckolinux/geckolinux-project#159]
Steps to reproduce:
1. Distro update (zypper dup)
2. Try to save file from any application

I have used firefox for this example by trying to save an image, this has also occurred in other applications when trying to save files.
I do not know how to capture logs for this exact issue.
![Screenshot from 2020-09-20 20-37-40](https://user-images.githubusercontent.com/37013292/93716497-3cf0fa00-fb81-11ea-9ce2-218a770bf293.png)
![Screenshot from 2020-09-20 20-38-03](https://user-images.githubusercontent.com/37013292/93716500-3ebabd80-fb81-11ea-98f2-589f8f80a837.png)

**Comment by kquote03** [comment]
![Screenshot from 2020-09-20 20-48-10](https://user-images.githubusercontent.com/37013292/93716788-a32a4c80-fb82-11ea-843e-2e6f5cd652dd.png)
Same program (pantheon code)
The VNC session of eOS 5.1 has a 'save' button at the bottom of the dialogue while the gecko linux one doesnt

**Comment by kquote03** [comment]
Switching to the Pantheon-branch_tumbleweed repo and updating packages has not fixed the problem

**Comment by geckolinux** [comment]
@awissu Any tips here?

**Comment by awissu** [comment]
> Switching to the Pantheon-branch_tumbleweed repo and updating packages has not fixed the problem

`sudo zypper dup --recommends -r https://download.opensuse.org/repositories/X11:/Pantheon:/Branch/openSUSE_Tumbleweed`

Please show your settings:

`gsettings get org.opensuse.pantheon.wrap.gnome.settings-daemon.plugins.xsettings overrides`

See: https://bugzilla.opensuse.org/show_bug.cgi?id=1175628

**Comment by geckolinux** [comment]
@kenan1099  Did awissu's suggestion help?

**Comment by orianflaust** [comment]
I still have this annoying issue on both Gecko Pantheon installations!

**Comment by orianflaust** [comment]
![Bildschirmfoto von 2021-03-21 17-39-24](https://user-images.githubusercontent.com/59671213/111913000-717c3a80-8a6c-11eb-820b-85a51fb67bae.png)
![Bildschirmfoto von 2021-03-21 17-39-29](https://user-images.githubusercontent.com/59671213/111913001-72ad6780-8a6c-11eb-8cfb-21c0318c082c.png)

**Comment by geckolinux** [comment]
@orianflaust  Two possible workarounds:

- Sometimes installing and unremoving an unrelated GTK app can run a scriptlet that fixes it. Try installing and removing something like `gedit`.
- Use dconf-editor to edit `org.opensuse.pantheon.wrap.gnome.settings-daemon.plugins.xsettings overrides` and paste in the following:
     - `{'Gtk/DialogsUseHeader': <0>, 'Gtk/EnablePrimaryPaste': <0>, 'Gtk/ShellShowsAppMenu': <0>, 'Gtk/DecorationLayout': <'close:menu,maximize'>}`
     - (This will move the buttons to the bottom of the file chooser dialog like in normal GTK apps)

**Comment by orianflaust** [comment]
Second workaround worked! Thanks!

**Comment by geckolinux** [comment]
@orianflaust Thanks for confirming.
@awissu Any more ideas to fix the root problem?
