### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#16]
Did you try these steps for remove live user?
http://suse-studio-users.1598176.n2.nabble.com/How-to-get-rid-of-the-live-user-after-live-install-td7356725.html

Another good pratice is lock root user

And the step to remove builtin from splash screen

http://superuser.com/questions/380654/how-to-remove-built-with-susestudio-suse-studio

**Comment by geckolinux** [comment]
Hi there, 

I don't mind the overlay credit to SuseStudio, but those do like very useful instructions to remove the live user. I'll check into it and update this issue.

Thanks a lot!

**Comment by ghost** [comment]
Hi,

Lock root user is a security approach.

Another thing is fonts on libreoffice menu, on KDE static at least, is very overlapped.

**Comment by geckolinux** [comment]
> Lock root user is a security approach.

Sorry? I'm not sure what you're referring to here.

> Another thing is fonts on libreoffice menu, on KDE static at least, is very overlapped.

This will depend on your screen resolution and DPI and system font settings. There are also LibreOffice interface scaling settings you can play with.

**Comment by ghost** [comment]
If you create an user with sudo rights there's no reason to set password for root.
For how know that installed system is geckolinux it's very easy to know that root password is "linux", and a unsuspecting user incorrectly set up the ssh server and open security breaches.

I will test libreoffice

**Comment by geckolinux** [comment]
> If you create an user with sudo rights there's no reason to set password
> for root.
> Basically, openSUSE is designed to expect a working root user account, 
> some things like YaST don't work correctly without it. So GeckoLinux 
> also follows in this convention.
> 
> For how know that installed system is geckolinux it's very easy to know
> that root password is "linux", and a unsuspecting user incorrectly set
> up the ssh server and open security breaches.
> If this happens, I would place the blame on the user that is playing 
> with SSH without knowing what he is doing. ;-)
> But for the sake of a "clean" installation I agree that it would be good 
> to remove the "linux" user, and I'll try to implement that in future 
> revisions.

**Comment by ghost** [comment]
I think just force user to chance root password is a good pratice. Even you don't imagine a deliberated ssh access, the local access is compromissed with a know password.

**Comment by ghost** [comment]
Maybe add to script after install

passwd -l root 

Is an solution. I 'm using opensuse for last 3 years (my first try was on 2001) and the 'root' user was nevers used since I use 'sudo', so the 'root' password was never used.

**Comment by geckolinux** [comment]
Hello, please try the newest GeckoLinux release with the Calamares installer.

**Comment by ghost** [comment]
Everything seems fine now. Any chances of the original theme for gnome installed by default and gnome Classic SLE? Or the steps to do that.

**Comment by geckolinux** [comment]
Hi there, 

What "original theme for gnome" are you referring to?

As for the Classic SLE session, I'm looking into it now. I can't seem to find that session available for Leap 42.2.

**Comment by ghost** [comment]
The theme that comes with default installation. The classic SLE is an type of session coming from SUSE Enterprise, features now on opensuse

**Comment by geckolinux** [comment]
Hi again,

I believe that the standard openSUSE Gnome installation just uses the 
Adwaita theme for GTK, whereas GeckoLinux uses Numix across the board. 
The Gnome Shell theme in GeckoLinux however, is the same as what 
openSUSE uses.

I am familiar with the classic SLE, but it doesn't seem to be available 
for openSUSE, unless you can point me to the package?

Thanks.

**Comment by ghost** [comment]
In this image is possible to find https://doc.opensuse.org/documentation/leap/gnomeuser/html/book.gnomeuser/images/sled_login_sessiontype.png

SLE Classic (default)

    The default desktop of SUSE Linux Enterprise, designed to appeal to users of older versions of SUSE Linux Enterprise and users of Microsoft* Windows*. This desktop is a GNOME 3 configuration and uses a single panel that is placed at the bottom of the screen. 

I think his name is sle-gnome-basic pattern

http://lists.suse.com/pipermail/sles-beta/Week-of-Mon-20151102/001931.html

**Comment by ghost** [comment]
patterns-openSUSE-gnome_basis and gnome_basis are installed on a vanilla opensuse gnome, on gecko gnome is not installed.

**Comment by geckolinux** [comment]
Please install the `gnome-shell-classic` package to enable the SLE Classic session.

**Comment by ghost** [comment]
zypper in gtk2-metatheme-adwaita gtk2-theming-engine-adwaita gtk3-metatheme-adwaita metatheme-adwaita-common gnome-shell-classic

It's Works
