### ISSUE TITLE
GeckoLinux Static Budgie

### ISSUE THREAD

**Issue by gmbr3** [geckolinux/geckolinux-project#160]
The budgie packages are being released to Leap 15.2 , should allow GeckoLinux Static Budgie soon.

**Comment by gmbr3** [comment]
BUDGIE DESKTOP
DONE - https://build.opensuse.org/package/show/openSUSE:Leap:15.2:Update/budgie-desktop

BUDGIE SCREENSAVER
IN PROGRESS - 
https://build.opensuse.org/request/show/836373

**Comment by geckolinux** [comment]
Great! So Leap allows new packages to be introduced after the release?

**Comment by gmbr3** [comment]
Yeah, has to go through testing and review again after Factory (Tumbleweed) but yes.

**Comment by gmbr3** [comment]
Main packages done , are you using any budgie applets?

**Comment by geckolinux** [comment]
These are all of the `budgie*` packages explicitly included in the the current released ISO:

```
    <package name="budgie-desktop"/>
    <package name="budgie-screensaver"/>
    <package name="budgie-haste-applet"/>
    <package name="budgie-screenshot-applet"/>
    <package name="budgie-calendar-applet"/>
```

But when I was testing your dev repo to fix that notification tray bug I noticed there were a lot of other really cool applets that I would probably also include by default.

**Comment by gmbr3** [comment]
Yeah, those in my dev can't be used properly yet, still missing some stuff. Not all of them in that list are in Leap 15.2 yet.

**Comment by gmbr3** [comment]
The applets are now in the hands of the maintenance team, I'll tell you when ready.

**Comment by gmbr3** [comment]
@geckolinux All done! Go ahead and try it.

**Comment by geckolinux** [comment]
> @geckolinux All done! Go ahead and try it.

Awesome, thank you! I hope to find time fairly soon to update the ISOs.

**Comment by geckolinux** [comment]
Updated ISO was just released as GeckoLinux _STATIC_ Budgie. Thanks again to @gmbr3 for the hard work!
