### ISSUE TITLE
problem installing chromium

### ISSUE THREAD

**Issue by benn13** [geckolinux/geckolinux-project#161]
Hi, just installed gecko plasma static and performed an update.
now i want to install chromium, zypper gives me this error:
`Additional rpm output:
xhost:  unable to open display ""                                                                                                                                      
/sbin/ldconfig: /usr/lib64/chromium/libGLESv2.so.TOC is not an ELF file - it has the wrong magic bytes at the start.                                                   

/sbin/ldconfig: /usr/lib64/chromium/libEGL.so.TOC is not an ELF file - it has the wrong magic bytes at the start`

whats the issue? thanks.

**Comment by geckolinux** [comment]
Hi there, I assume this is either an upstream bug, or else there might be some kind of filesystem corruption on your system. Please post the full output of `sudo zypper in chromium` .

**Comment by benn13** [comment]
it is installed and running and this is a full output:



`The following 2 NEW packages are going to be installed:
  chromium libharfbuzz-subset0

2 new packages to install.
Overall download size: 78.4 MiB. Already cached: 0 B. After the operation, additional 264.7 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libharfbuzz-subset0-2.6.4-lp152.1.5.x86_64           (1/2), 211.3 KiB (474.4 KiB unpacked)
Retrieving: libharfbuzz-subset0-2.6.4-lp152.1.5.x86_64.rpm ..............................[done (133.6 KiB/s)]
Retrieving package chromium-85.0.4183.121-lp152.2.33.1.x86_64           (2/2),  78.2 MiB (264.3 MiB unpacked)
Retrieving: chromium-85.0.4183.121-lp152.2.33.1.x86_64.rpm ........................................................................................[done (105.7 KiB/s)]

Checking for file conflicts: ....................................................................................................................................[done]
(1/2) Installing: libharfbuzz-subset0-2.6.4-lp152.1.5.x86_64 ....................................................................................................[done]
(2/2) Installing: chromium-85.0.4183.121-lp152.2.33.1.x86_64 ....................................................................................................[done]
Additional rpm output:
xhost:  unable to open display ""
/sbin/ldconfig: /usr/lib64/chromium/libGLESv2.so.TOC is not an ELF file - it has the wrong magic bytes at the start.

/sbin/ldconfig: /usr/lib64/chromium/libEGL.so.TOC is not an ELF file - it has the wrong magic bytes at the start.

`


What is the error mean? it is installed though and it is working.

**Comment by geckolinux** [comment]
Not sure about the error, but glad that it's working. Please feel free to report this bug to the openSUSE Bugzilla, as GeckoLinux does not create or maintain any packages.
