### ISSUE TITLE
dup -l  seems to have disappeared the log in window??

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#163]
Running Gecko TW and did a zypper dup -l this morning gave me some "package conflicts" that had four options, I was in a hurry, so I picked number one, included was a new kernel, 5.9 . . . ran the zypper and shut down.

When I came home a few hours later I rebooted the computer and Gecko is top hit in grub, went to a black screen with a vertical cursor in the middle of the screen . . . tried a few things, wound up using "advanced options to fall back to 5.8 kernel and GUI desktop and login was working.

Ran Yast Software Management, showed a couple of packages "sof-firmware" and "ucode-intel" to upgrade, so I accepted and rebooted into 5.9 and all seemed well . . . .  A little while later I ran zypper again to see if anything has been "fixed" . . . "12 packages" were available, so I ran that through . . . rebooted into the black screen . . . this time a figured out that the cursor was showing me that the login bar was waiting for my password, so I typed the password and the user desktop opened.  So it appears that something with "plymouth" has been messed with so that Gecko is booting into a black screen???

**Comment by geckolinux** [comment]
Hi there, which desktop edition do you have installed?
Please try running:
sudo zypper dup

**Comment by esteelpaz** [comment]
@geckolinux 

This MATE rolling.  Do you mean "sudo zypper dup" . . . rather than the "sudo zypper dup -l" that I ran two times????

**Comment by esteelpaz** [comment]
@geckolinux 

I ran zypper dup -l in my desktop machine in mainstream TW and got a similar question and options as I did on my laptop in Gecko, laptop is essentially a new machine . . . but it does seem like it's related to MATE??  I don't think the options are exactly what they were . . . I think in another day or so I'll be rotating into Gecko TW in this desktop machine, so likely the same problem will show there . . . .

`Problem: mate-menu-20.04.1-2.1.noarch requires python3-xdg, but this requirement cannot be provided
  deleted providers: python3-pyxdg-0.26-6.2.noarch
not installable providers: python3-xdg-4.0.1-1.1.noarch[download.opensuse.org-oss]
 Solution 1: Following actions will be done:
  deinstallation of mate-menu-20.04.1-2.1.noarch
  deinstallation of mate-panel-branding-openSUSE-42.1-4.44.noarch
  deinstallation of mate-menu-lang-20.04.1-2.1.noarch
 Solution 2: deinstallation of python3-pyxdg-0.26-6.2.noarch
 Solution 3: keep obsolete python3-pyxdg-0.26-6.2.noarch
 Solution 4: break mate-menu-20.04.1-2.1.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/4/c/d/?] (c): `

This was just to give you a hint on the issue, I'll post back when I run it in Gecko . . . unless it's the same data, on the same desktop, etc.

**Comment by esteelpaz** [comment]
Problem reported on "mate-menu" page on git-hub.
[https://github.com/mate-desktop/mate-menus/issues/87](url)

**Comment by esteelpaz** [comment]
Problem reported on "mate-menu" page on git-hub.
[https://github.com/mate-desktop/mate-menus/issues/87](url)

**Comment by esteelpaz** [comment]
Just reporting here that in mainstream TW on the desktop machine I ran the zypper dup -l and:

> Alrighty, well, this time I selected #3 option, "keep the obsolete python3-xxx package," and that then showed the package is now "locked" . . . and the rest of the 265 packages passed through processing . . . and reboot . . . took a couple minutes maybe, but the log in window appears and we are back into an operational MATE gui . . . albeit with "an obsolete python3 package" . . . locked in . . . . 


Since the decision on another option was made in the laptop, so far just running zypper dup hasn't provided any new chances on the decision . . . .  Might check in there again, see if any "broken packages" are showing up somewhere in Yast???  Still wouldn't mind knowing how to "-f install" via zypper in the console, etc.

**Comment by geckolinux** [comment]
Thanks for letting us know. So it sounds like an upstream issue, hopefully they'll get it fixed soon. I'll close this bug, but feel free to update us on how it turns out.

**Comment by esteelpaz** [comment]
Received this reply to my upstream MATE bug report on mate-menu:
"This is a packaging issu with your distro, not an upstream issue. You need to file issues with OpenSUSE TW & Gecko TW instead, as only they can fix this. Looks like they have python updates out of synch with their build of mate-menus and need to rebuild that package from the same source"

**Comment by esteelpaz** [comment]
@geckolinux 

Problem continues, unaddressed, in my Gecko rolling install . . . splash loads OK then goes to black screen with vert cursor, have to type password in the black, then GUI opens OK.  As posted MATE claims it isn't their problem, so looks like it's OpenSUSE issue, but only manifesting now in the Gecko install.

**Comment by geckolinux** [comment]
Hi, please confirm which `lightdm` packages you have installed. Also please post the output of `/etc/lightdm/lightdm-gtk-greeter.conf` and `/etc/lightdm/lightdm.conf` .

**Comment by esteelpaz** [comment]
Thanks for getting back to the thread.  When I search Yast with "lightdm"  it marks the following packages as installed, looks like a few other options are listed, but not installed:

```
liblightdm-gobject-1-0 - LightDM GObject-based Client Library  1.30.0-4.1
--
lightdm - Lightweight, Cross-desktop Display Manager   1.30.0-4.1
--
lightdm-gtk-greeter - Simple display manager (GTK+ greeter)  2.0.6-1.8
--
lightdm-gtk-greeter-branding-openSUSE - openSUSE branding of lightdm-gtk-greeter 2.0-3.2
--
lightdm-gtk-greeter-lang - Translations for package lightdm-gtk-greeter  2.0.6-1.8
--
lightdm-lang - Translations for package lightdm  1.30.0-4.1
--

sudo cat /etc/lightdm/lightdm-gtk-greeter.conf
[greeter]
background = /usr/share/wallpapers/Zwopper-Green-Dew-CC-BY-SA-30-2560x1600.png
theme-name = Numix
indicators = ~host;~spacer;~session;~language;~clock;~power
icon-theme-name = Faenza
font-name = Ubuntu 11
xft-antialias = true
xft-hintstyle = hintslight
xft-rgba = rgb

01@gazelle:~> sudo cat /etc/lightdm/lightdm.conf
[Seat:*]
#autologin-user=username
autologin-user-timeout=0

```

**Comment by esteelpaz** [comment]
sorry about the bold type, copied/pasted out of Yast.  : - )))

**Comment by esteelpaz** [comment]
So, it gets "weirder" . . .  more weird . . . .  When finished playing with Gecko earlier I logged out of the GUI . . . it went to the blackness, but when I moused over to upper right corner I know there is a "suspend" or "quit" listing in the drop down menu, so I blindly clicked on the corner, then dropped the mouse slightly and clicked . . . and the unit "suspended."

When I revived from suspend, the GUI log in window was there!!! . . . typing the password though is just blank, but it logs into the GUI.  I repeated the log out approach two times and it was repeatable.

Thinking that just by posting my lightdm data on this thread the problem was solved . . . I restarted, selected Gecko from grub , got the splash, and then back into the blackness for the log in . . . .

**Comment by geckolinux** [comment]
What kind of graphics hardware do you have?

**Comment by esteelpaz** [comment]
On Sat, Nov 21, 2020 at 4:45 AM GeckoLinux <notifications@github.com> wrote:

> What kind of graphics hardware do you have?
>
This is a new linux computer with Nvidia card . . . the slightly "older"
and therefore, cheaper card option from a two month old computer.  If you
needed the precise card I'll be booting it later today . . . .  Pretty sure
Gecko is using nouveau as the driver.

**Comment by esteelpaz** [comment]
Just checked the card . . .  it's 4 GB GDDR5 GTX 1650 w/ 896 CUDA Cores . . . .  I have Gecko, Pop!, and Manjaro installs on this computer, no similar problems in the other two installs, only Gecko, sorry to say.

**Comment by geckolinux** [comment]
Could you please try uninstalling `xf86-video-nouveau` and `xf86-video-nv` and then rebooting? This should make it use the default Xmodesetting driver.

**Comment by esteelpaz** [comment]
OK, zyppered them both out . . . rebooted . . . black log in.  I shut it down and cold booted . . . still the blackness, O, the blackness, with the vert cursor . . . entering password in blackness, and back into the GUI . . . .  So, it didn't seem to be related to nouveau??

As mentioned, in my other OpenSUSE installs in my desktop, so one TW and a Gecko TW, and in this Gecko install, there was an error question in the zypper dup -l on the mate menu & python3-xdg  packages . . . I had four choices, this laptop was the first time I saw that and I think I went with "#1 upgrade mate -menu" . . .????  It didn't come back again, but then neither did the GUI log in window.  

I "learned" from this computer that the problem wasn't solved by that choice, and posted my threads here and on main TW forum and over there somebody told me "keep obsolete python3" . . . so I made that choice on the desktop, in both your system and my main TW install, and the problem was fixed over there, i.e. had the problem in this laptop and the desktop, but made the #3 choice and got the log in back, but in the laptop, made another choice and problem remains.

**Comment by esteelpaz** [comment]
@geckolinux 

Had the **genius** idea to try to add another DE to see if that would get around the problem of the "mate-menu" & "python3" package dependency problem . . . so I added LXQT via Yast pattern . . . then I logged out . . . into the blackness.  I tried my "click suspend" blindly and it suspended.  Then on revival the GUI log in window appears, but clicking on the MATE icon doesn't show any other DE options??  And also the power applet didn't work either . . . so I logged back into the MATE session, found "Yast-alternatives" and saw that "default-xsessions.desktop" was set for "auto" on mate.desktop . . . so I clicked "edit" on that item and it showed an "lxqt.desktop" line, so I clicked on that and "set choice" . . . so it set it for "manual" rather than "auto" . . . .

But, trying multiple times, logging out, rebooting . . . all goes back to black log in screen, so I can't try anything else . . . log in is for MATE . . . via the dark pathway . . . so much for the genius idea.  Also not sure why power button on revival isn't working, would that relate to removing nouveau????

**Comment by esteelpaz** [comment]
OK, that didn't go well . . . I actually managed to measure where on the toolbar the MATE applet would be and then clicked there, and dropped down a tad to "select" what should have been "lxqt" . . . then I went over to right side and clicked blindly for "suspend" as I did before.

On revival there was another applet, assuming that was the lxqt applet . . . but this time the password wasn't accepted.  So I rebooted and back into Gecko, typed password and cursor changed from vert to actual mouse cursor, but desktop is black, so now we aren't able to log into GUI in any recognizable ways, so for some reason apparently "lxqt" desktop isn't fully featured or able to work with default X driver???  The mouse cursor is able to "mouse" around over the black background . . . didn't try to right-click on it as in openbox . . . ???

I was able to get to a tty and log in . . . but I don't how to switch DEs in the console or how to do something to get out of the black . . .

**Comment by geckolinux** [comment]
The desktop environment doesn't have anything to do with the login manager. I would suggest installing a different login manager like GDM and uninstalling LightDM to see if that fixes the problem. Definitely back up your system from with the GUI first before trying it.

**Comment by esteelpaz** [comment]
Well, OK, wasn't hearing back here so I thought I would "try something, try anything" . . . but, essentially there is no GUI at this point, apparently Yast's version of LXQT pattern didn't "hook up" and now all there is is more blackness than there was before, it's like all of the time . . . no GUI . . . like there was in MATE after the log in blind.  So is it as simple as "sudo zypper install gdm && sudo zypper remove lightdm"???  It all has to happen in the TTY at this point . . . .

**Comment by esteelpaz** [comment]
So, I don't know if this helps, but back over in my Gecko install on my desktop I ran a zypper and got this:

`Loading repository data...
Reading installed packages...
Warning: You are about to do a distribution upgrade with all enabled repositories. Make sure these repositories are compatible before you continue. See 'man zypper' for more information about this command.
Computing distribution upgrade...
2 Problems:
Problem: nothing provides libhogweed.so.5()(64bit) needed by librtmp1-2.4.20151223.fa8646d-1.53.x86_64
Problem: mate-menu-20.04.1-2.1.noarch requires python3-xdg, but this requirement cannot be provided

Problem: nothing provides libhogweed.so.5()(64bit) needed by librtmp1-2.4.20151223.fa8646d-1.53.x86_64
 Solution 1: Following actions will be done:
  install gstreamer-plugins-bad-orig-addon-1.18.1-4.2.i586 despite the inferior architecture
  install libopenh264-6-2.1.1-1.6.i586 despite the inferior architecture
 Solution 2: deinstallation of gstreamer-plugins-bad-orig-addon-1.18.0-4.2.x86_64
 Solution 3: keep obsolete librtmp1-2.4.20151223.fa8646d-1.52.x86_64
 Solution 4: break librtmp1-2.4.20151223.fa8646d-1.53.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or skip, retry or cancel [1/2/3/4/s/r/c/d/?] (c)`

In this install I was able to previously "keep obsolete python3" package I believe it is now "locked"??  Not sure, might be locked in main channel TW install . . . ??  But, anyway, that was today's zypper decision . . . .

**Comment by esteelpaz** [comment]
@geckolinux 

Previously I posted some other errors I had in my Gecko install on desktop, but that turned out to be unrelated, so I deleted it here. 

So, back in the offending Gecko install on the laptop, booted it up, logged into the blackness, dropped into a TTY, ran zypper dup -l and rebooted, and back into the black.  So I hit f1 again and then decided to quit the shell via f7 and I saw a flash of a GUI??  So I repeated the process, into TTY, then exit the TTY and there is the LXQT DE . . . !!??  So, now the problem is if I want to get back to the MATE DE/pattern it would have to be done in the black, without knowing where LXQT shows that, in the blackness it's hard to know.

Also don't know if going back to Yast-alternatives and setting "desktop" back to auto login for MATE would "fix" that problem??

But, at least I am able to get to a GUI now in LXQT . . .

**Comment by esteelpaz** [comment]
@geckolinux 

Well, that all was kind of a mess considering the problem showed in routine zypper -dup . . . I checked defalt configs, and there was an option already there for xdm, but selecting that option didn't change the problem, sort of made it worse.

But, seems like adding gdm has returned the GUI log in, and added GNOME DE, so now I have MATE, openbox, LXQT, and GNOME options that can be selected and logged into . . . .  So I guess lightdm was messed up, although over in the main TW forum a gent was suggesting that maybe "sddm" was the problem and he thought going to lightdm would solve my issue, but I was in lightdm, now I'm in gdm.  I'll monitor a few rounds of zypper dup -l before I feel that the problem is "fixed."
