### ISSUE TITLE
Enabling f2fs system support

### ISSUE THREAD

**Issue by Ygarr** [geckolinux/geckolinux-project#164]
There is no f2fs.ko in system how to enable f2fs support preferably without kernel rebuild?

**Comment by geckolinux** [comment]
Hi, this is a question of what openSUSE chooses to offer. GeckoLinux does not build or maintain any packages of its own. For what it's worth, this is the discussion about why openSUSE doesn't enable f2fs:

https://www.reddit.com/r/openSUSE/comments/enlu5b/speaking_of_lack_of_f2fs_support_by_tumbleweed/
