### ISSUE TITLE
/etc/fstab wrong config

### ISSUE THREAD

**Issue by rasatdev** [geckolinux/geckolinux-project#17]
I installed rolling Gnome and Barebones by using the iso images. Both CDs worked fine and installed in HDD. But the boot goes into a loop without booting the machine because the fstab configure is not correct. From another partition (Linux Mint) I edited fstab by tagging (#) geckolinux's lines and added new lines. This solved the issue. See below:

#UUID=744b5a19-8fc1-4af9-8f66-37f87e4e4a8b /                    ext4       acl,user_xattr        1   1
#UUID=8fed5297-feea-4858-8921-6bb31b28a858   swap                 swap       defaults              0 0
/dev/sda11	/		ext4	  errors=remount-ro   0		1
/dev/sda6 	none	swap	sw              0       0

Another annoying boot error, asking for vbox. I deleted vbox and vbox-service files in /etc/rc.d/

**Comment by geckolinux** [comment]
Hello, thanks for your report. Which version (Static or Rolling) did you 
use to install, and what ISO version did you use?

**Comment by rasatdev** [comment]
GeckoLinux_ROLLING_BareBones.x86_64-999.161031.0.iso
and
GeckoLinux_ROLLING_Gnome.x86_64-999.161031.0.iso

**Comment by geckolinux** [comment]
Thanks for the information. The installer that is used in those Rolling 
editions has reached the end of its life, and some bugs and 
incompatibilities are starting to pop up. I will soon be releasing a new 
set of Rolling releases with the new Calamares installer, which should 
be more reliable. Would you be so kind as to test it again when it comes 
available?

**Comment by rasatdev** [comment]
I am happy to test. Actually I expected to see Calamares instead of YaST2. It will be nice to see the difference. Post in this thread when its ready, so that I receive the email note.

**Comment by geckolinux** [comment]
Hello, please try the newest GeckoLinux release with the Calamares installer.

**Comment by rasatdev** [comment]
GeckoLinux_BareBones.x86_64-422.161213.0.iso
CD didn't boot. Failed to mount root file system..... reboot in 120s

In case if the problem is from my side, here is md2sum: 3c0191b2ecb6e5ad2f162b4a7600c3f2

**Comment by geckolinux** [comment]
Hi there, looks like you have a bad download. The correct md5sum for `GeckoLinux_BareBones.x86_64-422.161213.0.iso` is `beedabb49b0a61934966530fcab0a54e`

**Comment by rasatdev** [comment]
Thx, it was a bad download, 4MB were missing.

I installed GeckoLinux_ROLLING_Mate.x86_64-999.161218.0.iso (at the same have a look at MATE). The Calamares installer did a good work. Better and safer control with the installation than YaST2. Another thing what I didn't like with YaST2 (in expert mode, maybe also in other moods)) it pre-setup the "/" and "/home" partitions. If not careful, you may accidentally install in those partitions.

Keep up with your good work.

**Comment by geckolinux** [comment]
Excellent! Glad to hear it worked.
