### ISSUE TITLE
the possibility to add orca screen reader to the mate live image?

### ISSUE THREAD

**Issue by mhussaincov93** [geckolinux/geckolinux-project#170]
hi there,
would it be possible to add the orca screen reader to the mate live iso?
was thinking of giveing geckolinux a spin :+1: thanks for reading,
Majid Hussain

**Comment by geckolinux** [comment]
Hi there, I'm not too familiar with Orca, but it would also have to be activated by default to be truly useful for visually impaired users, correct? I think users would probably be better served by a dedicated distro that specializes in accessibility, but if it doesn't require a lot of additional configuration I could probably generate a Mate ISO with accessibility features pre-installed.

**Comment by mhussaincov93** [comment]
hi,
the orca package, speech dispatcher, pulseaudio, espeak-ng/espeak would need to be installed,
then the speech dispatcher service would need to be enabled.
I would assume that pulseaudio is preinstalled?
I hope this makes sence,
Majid Hussain

**Comment by mhussaincov93** [comment]
hi again,
I was hopeing that  it could be added to the mate roleing image?
Majid
