### ISSUE TITLE
Group numbers  needs a rethink

### ISSUE THREAD

**Issue by lsatenstein** [geckolinux/geckolinux-project#171]
I was always lead to believe that group numbers and user numbers began at 1000 and for each new user number/groupnumber was augmented by 1.

I installed Gecko Linux today, and found my user id at 1000, my group id at 1004 and with a mish-mash of numbers that did not make sense.
What is my point?
When I share files across systems, I expect, from practice with Debian, Arch, Ubuntu, Fedora, Suse that Gecko would respect their rules.
For example, Fedora/ClearLinux use group 25 for wheel/sudo.   I edited my group / password files to put the numbering in line with my experience with other distros.

1000--nnnn  User with matching group
0 for root
25-999 for user,flatpack, etc.  
For the next update, please follow the practice of other distros.

Thank you

And by the way, there was no issues with the installation and update of the most recent past release.

**Comment by geckolinux** [comment]
Correct, the uid should start at 1000, and that's what GeckoLinux does.

I don't know where the gid comes from, but on my system I see that the `network` group is gid 1000, `storage` --> 1001, `wheel` --> 1002, and then the next available is my user group at `1003`.
