### ISSUE TITLE
"Copying the live image to disk failed"

### ISSUE THREAD

**Issue by commonquail** [geckolinux/geckolinux-project#18]
I've tried installing the rolling Plasma and LXQt editions on a VMware Workstation 12.5.2 Player-virtual machine. I've verified the ISO checksums. The live images seem to behave fine but installation always fails with a less than helpful "Copying the live image to disk failed" no matter how I configure it, including leaving everything as default. [The only relevant search result I can find](https://lists.opensuse.org/opensuse-bugs/2009-11/msg03875.html) is ancient and proposes a solution that has already been applied.

I have no idea if this is a GeckoLinux, openSUSE, or VMware problem (I don't have a physical machine to try it on), nor what more to do to troubleshoot it. Nothing in `/var/log/` or `journalctl` jumped at me but I also don't know what to look for or where.

The bootloader's help indicates I can install without starting the live image but I don't see a way to work around the four presented options. The help also doesn't mention the live image at all and a few superficial Google searches indicate that the (official openSUSE) live image is now the recommended installation method, so I don't have much faith in the help's accuracy.

Any suggestions for things I can try?

**Comment by geckolinux** [comment]
Hi Mikkel,

Sorry for the difficulty. Could you please confirm which version 
(Rolling or Static) you tried, and which version of the ISO you used to 
install from? Also which filesystem are you trying to install to?

If it is the 161031 release of a Rolling edition, an incompatibility has 
appeared that makes it impossible to install to BtrFS. The new Calamares 
installer in the next release of the Rolling edition will fix that.

Thanks, and best regards.

**Comment by commonquail** [comment]
- GeckoLinux_**ROLLING**\_Plasma.x86_64-999.**161031**.0
- GeckoLinux_**ROLLING**\_LXQt.x86_64-999.**161031**.0

> 161031 [...] impossible to install to BtrFS

That's probably it. I used this as an opportunity to try BtrFS so that's about the only thing I hadn't experimented with. I just succeeded installing LXQt with Ext4 `/root` and `/home`. :)

**Comment by geckolinux** [comment]
Thanks for confirming. So that was the issue. I hope to have the next release of the Rolling editions out soon with the new installer. I'll post a note here when it's ready.

**Comment by geckolinux** [comment]
Hello, please try the newest GeckoLinux release with the Calamares installer.

**Comment by commonquail** [comment]
That works. Thanks!

(That is, the default now seems to be Ext4; I created a custom partition table with BtrFS and that worked)

**Comment by geckolinux** [comment]
Excellent! Glad to hear it.
