### ISSUE TITLE
[Pantheon] logout problem

### ISSUE THREAD

**Issue by tosziro** [geckolinux/geckolinux-project#189]
When I logout I get only wallpaper and mouse and it hangs for around one minute. After this time it normally show login screen. But why it takes so long time? Could you please help me? It happens in Rolling Gecko and openSUSE Tumbleweed with installed X11:Pantheon:Branch repo.

**Comment by geckolinux** [comment]
@awissu Any ideas?

**Comment by sorinfatu** [comment]
It doesn't look like this is an issue with Gecko / openSUSE.
I can reproduce the exact same issue on arch and I very much doubt it can be solved until elementary 6 does come out.
Here is a reference from the arch forums about the [issue](https://bbs.archlinux.org/viewtopic.php?pid=1929474#p1929474)

Considering the current incarnation of pantheon is at this point 2 years old and built on a base that is almost 3 years old (more if you count that the packages in the ubuntu lts base were outdated before it released) I doubt these issues can be fixed or even if they are worth fixing.

**Comment by geckolinux** [comment]
@sorinfatu Thanks for confirming that. You might want to try changing the Pantheon repository to this:
https://download.opensuse.org/repositories/X11:/Pantheon/openSUSE_Tumbleweed/
And then use YaST to switch installed packages to the versions in that repo. It looks like his has Pantheon 5.x in that repo.

**Comment by sorinfatu** [comment]
Thanks for the suggestion but this actually results in a very broken installation as most of the packages there are downgrades and switching to them kills pantheon entirely. So wouldn't recommend it :)
