### ISSUE TITLE
"iFuse" needs "liblistxxx" . . . but, can't find it, zypper provides choices??

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#190]
@geckolinux 

Had this query come up in both my editions of Gecko . . . but not in my mainstream TW install.  I ran a google on it and it came up empty.  I installed the "classic menu" so that I could navi toYast Software Management and I searched variations on iFuse and liblist and it found "no results" . . . .

So, rather than like last time where I made the wrong choice . . . I thought I would post the question here and get your advice on whether to choose #1, 2, or 3, or . . . nothing??  

`Problem: ifuse-1.1.3-3.18.x86_64 requires libplist.so.3()(64bit), but this requirement cannot be provided
  deleted providers: libplist3-2.1.0-1.4.x86_64
 Solution 1: Following actions will be done:
  keep obsolete libplist3-2.1.0-1.4.x86_64
  keep obsolete libusbmuxd6-2.0.1-1.3.x86_64
 Solution 2: deinstallation of ifuse-1.1.3-3.18.x86_64
 Solution 3: break ifuse-1.1.3-3.18.x86_64 by ignoring some of its dependencies
`

**Comment by geckolinux** [comment]
Yep, it's an upstream bug, hopefully they'll get it fixed relatively soon:
http://bugzilla.opensuse.org/show_bug.cgi?id=1181620

**Comment by esteelpaz** [comment]
@geckolinux 

OK, got it on "upstream" . . . but what choice of options would you recommend until such time that it is repaired and the repair filters down??  #1??

**Comment by geckolinux** [comment]
The easiest would be solution #2, and then remember to re-install it later once this gets fixed.

**Comment by esteelpaz** [comment]
OK, thanks for the hint . . . "memory" is the problem these days . . . .  And, oddly, "iFuse" didn't show in search of Yast Software Management???  
I guess I'll add myself to the bug report, might give a head's up on the fix??
