### ISSUE TITLE
Exceeded maximum number of CRDA calls

### ISSUE THREAD

**Issue by SeekingSight** [geckolinux/geckolinux-project#2]
When booting I get an error referring to CDBA. I have no clue what it means. I tried googling the issue and got no where. It's present in both Legacy and UEFI. Any help with fixing this issue is appreciated.

Exceeded maximum number of CDBA calls is what I get or something to that nature. I am not sure how I would get a log of it or anything without full access to TTY. 

My (relevant) hardware:
i5 3230M
BCM4313

It's a Latitude E5530 if that makes a difference.

**Comment by geckolinux** [comment]
Thanks for reporting this. 

Are you sure it's not "CRDA", as in this bug report?
http://askubuntu.com/questions/622993/unable-to-boot-after-installing-new-kernel

I'm assuming boot completely fails for you? Or does it make it to the login manager?

Which GeckoLinux version did you try? Could you please try the [BareBones edition](https://susestudio.com/a/OO38wm/geckolinux-barebones), which doesn't have UEFI support?

**Comment by SeekingSight** [comment]
Sorry. Yeah, it's CRDA. It completely fails. This was on the Cinnamon edition. I will try the barebones edition

**Comment by geckolinux** [comment]
Any luck with the BareBones edition? If not we can try a few other troubleshooting techniques.

**Comment by SeekingSight** [comment]
No luck. I think it has something to do with the kernel-firmware package not being in the ISO (unless of course it is). I can't bypass it.

**Comment by geckolinux** [comment]
The kernel-firmware package is included in the ISO. I don't think the CRDA thing necessarily has anything to do with it, it was probably just the last thing that it did before the boot process got stuck.

Did you check the MD5sum of the ISO? And could you try using a different USB stick? I've had better luck with Suse ImageWriter than with `dd`.

**Comment by SeekingSight** [comment]
It seems to be an issue with DD. It works fine when written with ImageWriter. Thanks!

 Secure boot would be an eventual great addition if that's possible,

**Comment by geckolinux** [comment]
Cool, glad it worked.

Re: secure boot: All GeckoLinux editions except for BareBones are supposed to have secure boot support included. I say "supposed to" because I don't have any way to test this functionality. I didn't include it in the BareBones edition because you can't get a list of changed files in the SuseStudio testdrive with UEFI images.
