### ISSUE TITLE
Installer: gparted not starting

### ISSUE THREAD

**Issue by ylluminate** [geckolinux/geckolinux-project#204]
Attempting install of `GeckoLinux_ROLLING-OBS_Pantheon.x86_64-999.210221.0.iso`.

After some attempts at trying to resolve the partitioning situation (it was previously partitioned by OpenSUSE TumbleWeed current release with the GPT EFI/EPS volume + an LVM for the remainder of the drive and the GeckoLinux calamares did not recognize it and wanted to do a manual partition, which I also was having trouble with and decided to run GPartEd), I discovered that `gparted` will neither start from the GUI nor from Terminal. When attempting to launch via Terminal I get:
```
linux@localhost:~> gparted
No protocol specified
No protocol specified
Unable to init server: Could not connect: Connection refused

(gpartedbin9764): Gtk-WARNING **: 14:39:02.850: cannot open display: :0
```

**Comment by ylluminate** [comment]
By the way: Since this is based on OpenSUSE, why not use the more robust installer that they use? It certainly is far more well developed than Calamares...

**Comment by geckolinux** [comment]
Hi there, you need to run gparted as root. What version of GeckoLinux are you using?

The openSUSE installer doesn't work for installing live systems for a compressed image.

**Comment by ylluminate** [comment]
Hi, I was using the installer at the time I executed this and I did run it as `sudo gparted` as well with the same result... As noted in the first message, this is the installer I was running: `GeckoLinux_ROLLING-OBS_Pantheon.x86_64-999.210221.0.iso`

**Comment by geckolinux** [comment]
`sudo` does not work for launching graphical applications in openSUSE. Please either do `su root` first, or use the graphical menu launcher.
