### ISSUE TITLE
[Pantheon] how to enable legacy system tray without PPA functionality?

### ISSUE THREAD

**Issue by ylluminate** [geckolinux/geckolinux-project#205]
It appears from this issue:
https://elementaryos.stackexchange.com/a/17453

That we need to be able to use PPAs from time to time.  Is there a way around this with GeckoLinux-Pantheon? I'm not seeing an equivalent package to facilitate this.

If not, perhaps we should ask ourselves: what options exist to get PPAs working on OpenSUSE? Is there a way we can facilitate these since they are disturbingly common with `elementary OS`?

**Comment by geckolinux** [comment]
openSUSE has no PPAs. The equivalent that you are looking for are called OBS repositories:
https://software.opensuse.org/search

**Comment by ylluminate** [comment]
Oh very interesting, thanks for pointing this out. After seeing your reply and recalling the installer I used was:
```
GeckoLinux_ROLLING-OBS_Pantheon.x86_64-999.210221.0.iso
```

I thought perhaps the OBS repo may be on (installed) by default, but I don't see that in YaST2 package manager Repositories tab. A search in YaST2 package manager doesn't yield any results.  

It seems as though you have to do a search for `wingpanel-indicator-ayatana` and then find the package, in this case:
https://software.opensuse.org/package/wingpanel-indicator-ayatana

And then look for "openSUSE Tumbleweed" and expand both "Show experimental packages" and "Show community packages" to see if you can discern which is newer and then click the button `1 Click Install` for the appropriate one (in this case it appears to be the "experimental" package. Then open with "YaST 1-Click Install.  

Does this sound right? The package appeared to install and work, thanks!

---------------------------
**Sidenote, not important, but might help someone searching about blindly for keywords:**
Just a gotcha for anyone else poking about, be careful not to have another package manager open in the background as this will happen and get ugly looking quickly:

I assume that this was the case to follow, and accepted the new repositories being added, but as I proceeded with that course I hit the following error while attempting to install:
```
An error occurred while initializing the software repository.
Details:
https-download.opensuse.org-fdb4843e: [https-download.opensuse.org-fdb4843e|https://download.opensuse.org/repositories/GNOME:/Backports:/Factory/openSUSE_Factory/] Valid metadata not found at specified URL
History:
 - Unknown error reading from 'https://download.opensuse.org/repositories/GNOME:/Backports:/Factory/openSUSE_Factory/'
 - System management is locked by the application with pid 3253 (/usr/bin/ruby.ruby2.7).
Close this application before trying again.

Try again?
```

This was due to having YaST2 package manager open while looking for packages.
