### ISSUE TITLE
TumbleWeed: Pantheon + Plasma?

### ISSUE THREAD

**Issue by ylluminate** [geckolinux/geckolinux-project#206]
Very much liking the ideology behind your distribution in taking OpenSUSE and improving it in much needed ways. After having installed the Pantheon version of GeckoLinux, is there a way to install a meta package to also have the KDE Plasma version running as well such that I can log out and select between the two via a desktop manager?

**Comment by geckolinux** [comment]
Hi there, I'm glad you like GeckoLinux.

You definitely can install additional desktop environments. In openSUSE speak the metapackage you refer to is known as a "pattern", you can search for them in the YaST Software manager or there in the "View" menu you can show all the patterns by category.

With that being said, I'm not sure if I would recommend it. Sometimes having different desktop environments installed can cause some weird things to happen. Feel free to give it a try, but just be prepared to re-install the system if it makes a mess.
