### ISSUE TITLE
Close macOS-like experience for Apple Magic Trackpad 2: Translating Ubuntu instructions to GeckoLinux/OpenSUSE

### ISSUE THREAD

**Issue by ylluminate** [geckolinux/geckolinux-project#207]
Would you mind please explaining the GeckoLinux way of following the instructions in this (I believe Ubuntu-based) writeup for the Apple Magic Trackpad 2 setup?: https://howchoo.com/linux/the-perfect-almost-touchpad-settings-on-linux-2

The dependencies and lib paths seem to be slightly different and I've run into `configure` errors thus far in getting them to line up for GeckoLinux.

**Comment by geckolinux** [comment]
I'm not too familiar with multitouch options for Linux,, but judging from the fact that that particular project hasn't been updated in almost 3 years and isn't packaged for openSUSE I'm pretty sure it's no longer the recommended method.

What appears to be work best at the moment is `touchegg` with `touchegg-gui`, both available in the openSUSE repositories.

**Comment by ylluminate** [comment]
Thank you very much for pointing that out. I'm investigating using it, but unfortunately it seems that no up-to-date packages are available for OpenSUSE (eg, https://software.opensuse.org/search?utf8=%E2%9C%93&baseproject=openSUSE%3AFactory&q=touchegg). I'm really surprised there's such lower levels of support for OpenSUSE when it seems better engineered than other distro options.

**Comment by geckolinux** [comment]
Hmm true. You could try the RPM that the Touchegg project offers on Github. Or, you could try requesting the Touchegg maintainer for openSUSE to update the package:
https://build.opensuse.org/package/show/openSUSE%3AFactory/touchegg

**Comment by ylluminate** [comment]
From what he said it seems he prefers to have the app updated by whoever made the (very old) packages that exist...

**Comment by geckolinux** [comment]
Right, the developer of the program is usually different from the packager. If you look in the changelog in the link that I sent you you'll see who created the openSUSE packages and you can directly request an update there.

**Comment by ylluminate** [comment]
Yeah, the age of the comments were discouraging since he did do as they requested... 😣

**Comment by Arcitec** [comment]
Uhm https://software.opensuse.org/package/touchegg?search_term=touchegg has 2.0.9.

The latest release is 2.0.9: https://github.com/JoseExposito/touchegg/releases

But of course, only openSUSE Tumbleweed has 2.0.9. That is exactly as it's intended to be. Leap updates slower.

**Comment by geckolinux** [comment]
@Bananaman Looks like they just recently updated it for Tumbleweed. Before that it hadn't been updated for years.

**Comment by Arcitec** [comment]
@geckolinux Woof, yep I see what you mean, it wasn't maintained for 3 years:

https://build.opensuse.org/package/revisions/openSUSE:Factory/touchegg

Oh well this can happen with unpopular projects. But if I notice any outdated touchegg I'll let the package maintainer know. And so should anyone else who uses this package and sees any issue. :)

**Comment by Arcitec** [comment]
Ahhh nice, the mystery has been solved. It wasn't openSUSE's fault. @geckolinux 

touchegg 1.1.1 was released in 2015:
https://github.com/JoseExposito/touchegg/releases?after=2.0.0

Then there were ZERO releases until 2.0.0 on September 27th, 2020.

On the SAME DAY as the developer released touchegg 2.0.0 on Github, he also left a message on the openSUSE package tellign them how to build it and include it:
https://build.opensuse.org/package/show/openSUSE:Factory/touchegg

They replied that there was a bug in touchegg that prevented building:
https://github.com/JoseExposito/touchegg/issues/337

Finally it took some time for openSUSE's package maintainer to react to the news that touchegg has been fixed. It was most likely thanks to @ylluminate leaving a comment on the package page, which the maintainer saw and then updated it.

It's all fixed now. :)
