### ISSUE TITLE
About version of static edition with budgie

### ISSUE THREAD

**Issue by lixinyancici** [geckolinux/geckolinux-project#21]
Hi, The project is great, I want to use it as my main operating system. I like the concise of budgie, so i want to select it, but i found that the version of static edition is all 42.2 but budgie, can it upgrade to 42.2 normally when it be installed by myself?

**Comment by geckolinux** [comment]
Hi there, yes, it can update normally for now. Just change the 
repository URLs that end in "42.1" to "42.2" and run:
sudo zypper dup

**Comment by lixinyancici** [comment]
Thanks!
