### ISSUE TITLE
Poll: What should the default filesystem be for GeckoLinux?

### ISSUE THREAD

**Issue by geckolinux** [geckolinux/geckolinux-project#210]
GeckoLinux and the Calamares installers supports all the major modern filesystems for Linux in the custom partitioning mode. But when using the "Erase disk", "Install alongside", or "Replace a partition" easy installation options, it currently uses EXT4 by default. Which filesystem would most GeckoLinux users prefer by default? Please note that the option of Btrfs would be a basic configuration with `@` and `@home` subvolumes and no GRUB snapshot integration.

[![](https://api.gh-polls.com/poll/01F3N9WMATTG2HY4RP6PW566MZ/EXT4)](https://api.gh-polls.com/poll/01F3N9WMATTG2HY4RP6PW566MZ/EXT4/vote)
[![](https://api.gh-polls.com/poll/01F3N9WMATTG2HY4RP6PW566MZ/Btrfs)](https://api.gh-polls.com/poll/01F3N9WMATTG2HY4RP6PW566MZ/Btrfs/vote)
[![](https://api.gh-polls.com/poll/01F3N9WMATTG2HY4RP6PW566MZ/Something%20else%20(please%20specify%20in%20the%20comments))](https://api.gh-polls.com/poll/01F3N9WMATTG2HY4RP6PW566MZ/Something%20else%20(please%20specify%20in%20the%20comments)/vote)

**Comment by MarkDraconian** [comment]
BTRFS is nice, it would be awesome to have that by default with Gecko

**Comment by DavidMP89** [comment]
I vote for BTRFS.

**Comment by djongepier** [comment]
Love to see btrfs as default too! Voted.

**Comment by ShareVepari** [comment]
BTRFS with requires subvolumes

**Comment by maparaschivei** [comment]
Btrfs with transparent compression (à la [Fedora 34](https://fedoramagazine.org/fedora-workstation-34-feature-focus-btrfs-transparent-compression/))  would be nice.

**Comment by geckolinux** [comment]
Btrfs with Zstd compression is now the default for the latest GeckoLinux _ROLLING_ release:
https://github.com/geckolinux/geckolinux-project/releases/tag/210519.999

What about the next _STATIC_ release? Please vote here! https://github.com/geckolinux/geckolinux-project/issues/226
