### ISSUE TITLE
[Xfce] [Rolling] Failed to edit user profile

### ISSUE THREAD

**Issue by maparaschivei** [geckolinux/geckolinux-project#211]
## Expected Behavior
Clicking the user profile icon via the Whisker menu should open the user profile configuration utility (mugshot). <sup>3</sup>

## Actual Behavior
Clicking the user profile icon fails with an error: <sup>1</sup>

> Failed to edit profile.
> Failed to execute child process "mugshot" (No such file or directory) <sup>2</sup>

## Steps to Reproduce the Problem

  1. Open the application (Whisker) menu
  1. Click on the user profile icon

## Possible Solution
Install the missing user profile configuration utility package "mugshot"

`sudo zypper install mugshot`

## Specifications
Edition: GeckoLinux Rolling XFCE
Release: GeckoLinux_ROLLING_XFCE.x86_64-999.210221.0.iso

## Screenshots
<sup>1</sup>
![Screenshot_94](https://user-images.githubusercontent.com/5330898/115580644-49fbd600-a295-11eb-8e72-de6dbe75b8e9.png)

<sup>2</sup>
![Screenshot_93](https://user-images.githubusercontent.com/5330898/115580480-1c169180-a295-11eb-9a8c-be88a2d41298.png)

<sup>3</sup>
![Screenshot_96](https://user-images.githubusercontent.com/5330898/115584876-233f9e80-a299-11eb-83d2-fa9f1498de62.png)

**Comment by geckolinux** [comment]
Sorry for the slow reply! But thank you for mentioning this useful improvement, Mugshot (and MenuLibre too) will be included in the upcoming release.
