### ISSUE TITLE
Absent "auto partition alongside" option fom usb version to dual boot Win10p.

### ISSUE THREAD

**Issue by 2wing** [geckolinux/geckolinux-project#212]
Sent here by "GeckoLinux" from forum on Linux.org
Posted this question ...

> Have previously used dual boot Win7 into OpenSuse with success.
Recent hardware "issues" mean I am starting again ...
Laptop Intel i5 with win10pro as efi gpt without secure boot, W10p on nvme primary drive, no second fixed drive just a microSD in slot.
Windows shutdown not hibernated.
Used Rufus as "DD" type to create usb stick for Gecko Static. (failed to boot with "iso" type).
Gecko boots (F12) as expected into working environment and functions seemingly as expected.
So went for Calamares installer and all was fine until volumes stage.
No option to auto partition was available as per this Calamares page ..
Auto partition
(I spent a considerable time on a previous dual boot Leap 15.2 install to a second drive and got manual partitions wrong first go ... so not going there again).
Happy to mess under instruction but not prepared to drop Windows into the fire through my lack of understanding.

And have 40% free on C: drive.  (GeckoLinux advised perhaps insufficient space or extended partition)
Macrium sees 4x partitions on 256GB (1x FAT & 3x NTFS)

GeckoLinux suggested asking at Calamares but their notes suggest posting here first.
Dell Latitude 5500, i5 vPro 8th gen, nvme 256GB ssd, 16GB ram ... no mods other than delay Windows build updates, currently to date with 1909 build.
Gecko from usb 'sees' the extra microSD card plugged in but no view of the Windows bits (familiar with that view from earlier OpenSuse installations).

Also noted elsewhere some mentions of nvme ssds causing issues ?
Paul

**Comment by geckolinux** [comment]
Hi there, if you could open Gparted and post a screenshot that would help. If it's a standard OEM Windows installation it probably has an extended partition that can't be changed.

**Comment by 2wing** [comment]
Thank you geckolinux
369 MB on rural copper so will be a while until I can get Gparted running ... will be back with results.

**Comment by 2wing** [comment]
While waiting ....
Windows disc management has "Shrink Volume available and a test "look" states it can give up 80GB ... is that any help?

**Comment by geckolinux** [comment]
> Thank you geckolinux
> 369 MB on rural copper so will be a while until I can get Gparted running ... will be back with results.

It's pre-installed in GeckoLinux.

**Comment by 2wing** [comment]
Thank you "geckolinux".
Gparted from within Gecko booted from usb only shows the external microSD card, as exFat.  No other devices/volumes in the main window (refreshed).
So now the only way is to have Gecko on an external second drive then ?

**Comment by geckolinux** [comment]
Ah, so that's the problem. It's probably a similar issue (or the same) to this:
https://askubuntu.com/a/696646

**Comment by 2wing** [comment]
Ouch !  Thank you "geckolinux".
I was thinking of doing an "in place" upgrade to Windows so will check with "TenForums" and see what they advise.
Thank you for your help.
Really like the Gecko (so much easier than the full Leap (even though it says that is what it is)
Over and out.
Paul
