### ISSUE TITLE
Running Yast Bootloader finds error??

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#216]
I ran into an issue with my TW & Leap 15.3 distros where running a zypper dup -l seemed to wipe grub connections so that two different computers booted to white screen instead of into grub.  So far the problem didn't seem to happen via Gecko, so that is great, but none-the-less I have to use SuperGrub2 to boot into one of my 5 or 6 choices of linux distro, by way of using a "vmlinuz" choice, seems like maybe something with "shim" has caused this problem, but so far the forums there haven't been overly helpful toward figuring out what the problem is and how to fix it.

This morning I was trying to boot into something and it wound up being Gecko, so while I was there I thought I'd run a Yast Bootloader "probe foreign os" . . . to see if that would do something, and it errored out--which it didn't previously in TW . . . so perhaps this data might give a clue as to how to fix or restore Grub functionality to be able to get into my installs w/o needing SG2 disk to figure out which system is which???   I tried to add my problems into a bugzilla and freedesktop bug report, but freedesktop said my problem didn't match the other peoples, had other stuff to do.  Any thoughts would be appreciated.

`Execution of command "[["/usr/sbin/grub2-mkconfig", "-o", "/boot/grub2/grub.cfg"]]" failed.
Exit code: 1
Error output: Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.12.0-2-default
Found initrd image: /boot/initrd-5.12.0-2-default
Found linux image: /boot/vmlinuz-5.11.15-1-default
Found initrd image: /boot/initrd-5.11.15-1-default
Found Manjaro Linux (21.0.3) on /dev/sdb7
Found openSUSE Tumbleweed on /dev/sdb9
Found Mac OS X on /dev/sdc2
Found Linux Mint 20.1 Ulyssa (20.1) on /dev/sdc5
Found Debian GNU/Linux bullseye/sid on /dev/sdc6
Found Ubuntu 21.04 (21.04) on /dev/sdc7
cannot open `/boot/grub2/grub.cfg.new': No such file or directoryUsage: /usr/bin/grub2-script-check [OPTION...] [PATH]
Try '/usr/bin/grub2-script-check --help' or '/usr/bin/grub2-script-check
--usage' for more information.
Syntax errors are detected in generated GRUB config file.
Ensure that there are no errors in /etc/default/grub
and /etc/grub.d/* files or please file a bug report with
/boot/grub2/grub.cfg.new file attached.`

**Comment by geckolinux** [comment]
Hi there, possibly try deleting `/etc/default/grub`, remove any legacy `grub*` packages, and then force re-install: `grub2 grub2-branding-openSUSE grub2-i386-pc grub2-snapper-plugin grub2-x86_64-efi` . Then try running the YaST Bootloader tool again.

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks for the hints . . . after I posted this thread I tried running the "grub2-mkconfig" command in Gecko's terminal, and it went through w/o error, but unfortunately did not solve the issue.  

As far as your suggestions, would I be looking in the GUI file system to remove "/etc/default/grub"  or legacy "grub*" packages, or are there commands that will trash those items, and then same question on the "force re-install"??  Is it something like "zypper install re-install grub2"???

I'm hoping for a simple solution to getting the grub menu back online . . . would this be it??

**Comment by geckolinux** [comment]
On 09/05/2021 15:06, esteelpaz wrote:
> I'm hoping for a simple solution to getting the grub menu back online . . . would this be it?Yes, that's the idea.

You can just manually delete the one file:
sudo rm /etc/default/grub
Then, use YaST Software to make the GRUB package changes.

**Comment by esteelpaz** [comment]
@geckolinux 

OK, thanks again for the hints.  Since TW is the "problem child" on this one I played in TW and I opened the directory in the GUI and then ran your "rm" command and the "grub" file went away, then I used Yast to "update" those grub2 packages, which were showing as installed . . . the "grub" file came back into the /etc directory, but on reboot, back into the whiteness, no grub menu shows up, nothing shows up.  Have to use SG2 disk to select the system and have to pick a "vmlinuz" listing.

Also in the meanwhile there were 246 packages to upgrade in zypper in TW, including a "shim-15.4" package (which may or may not be a source of the problem) . . . and that also didn't fix anything.

I've tried chrooting into both TW and the Gecko partitions and run the os-prober op, but so far that hasn't gotten grub menu back online.  Not sure if I should have used "upgrade unconditionally" . . . but the packages installed in TW were "the latest available"????

**Comment by geckolinux** [comment]
Could you please try the YaST Bootloader option to disable "Graphical console" ?

![Screenshot_2021-05-09_20-07-02](https://user-images.githubusercontent.com/2692138/117593772-28f30c00-b102-11eb-97b3-f1ceed392e2e.png)

**Comment by esteelpaz** [comment]
@geckolinux 

In looking at that suggestion, it is now already "unchecked" . . . which I didn't mess with it before looking at it.  Is that something that if I want "graphical grub menu" I would want that box to be checked "on"???

What would I expect if I toggle it off/on?

**Comment by geckolinux** [comment]
When it's enabled it should offer a pretty stylized GRUB menu with openSUSE colors. When it's disabled it should show a black and white GRUB menu similar to the one that Ubuntu uses.

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks again for the reply . . . OK, well, so it's not a major change, right now there is no grub menu at all . . . but I do like the OpenSUSE version of it as my preferred "handler" . . . .

One of the bugs that I thought was "similar" to mine but relating to Dell laptops seems to be testing a version of the 5.12 kernel as the "fix" . . . so far today no updates have trickled down into zypper . . . .  I'll try to check the box and see if that brings grub back in living color.  : - ))

**Comment by geckolinux** [comment]
The 5.12 kernel is indeed in Tumbleweed now. But that doesn't make sense as being the culprit or the solution, because the GRUB screen appears before the kernel even gets loaded.

I'd recommend that you try to shrink one of your partitions a bit and try to re-install GeckoLinux to that, mainly so that it does a fresh installation of GRUB, which should also pick up your other working openSUSE and GeckoLinux installations.

**Comment by esteelpaz** [comment]
@geckolinux 

Ah, OK on the kernel thing, possibly that related to something in the current kernel that is "breaking" something??  Anyway, it is what it is, to quote a famous personage . . . .  I did try checking that "graphical" box and on reboot, we were back into the "blank/white" screen.

Thanks for the recommendation on the fresh install of Gecko, that traditionally has been my technique to fix grub problems, most often when an upgrade on the OSX side has broken the grub connections--so that may indeed be where I will wind up going to get out of this mess.  : - 0

**Comment by geckolinux** [comment]
Interesting, I noticed your OSX partition from your previous post. Are you running on Mac hardware or a Hackintosh install?

**Comment by esteelpaz** [comment]
@geckolinux 

I try to be "interesting" whenever possible.  But, in this case not so much; running OSX on a Mac as "God" intended.  This issue affected two Macs, one desktop running TW and a few other choices, and the other an older laptop running two OSX partitions and a Leap 15.3.  

Seemingly Gecko has evaded this problem, as I have a Gecko on the offended '12 Mac Pro AND on a Sys76 laptop, and grub has gone unscathed on the Sys76 laptop . . . so Gecko has been very "golden" as of late, whereas TW has been breaking up every other zypper dup . . . for one thing or another.  : - (

**Comment by esteelpaz** [comment]
@geckolinux 

I'm trying to get an iso of Gecko rolling Plasma checksum'd . . . but running "sha1sum GeckoLinux_ROLLING_Plasma.x86_64-999.210221.0.iso"  and/or "md5sum GeckoLinux_ROLLING_Plasma.x86_64-999.210221.0.iso" . . . the numbers aren't matching what you are showing on Sourceforge??? . . . does that matter???  Or, am I running wrong commands??  I'm "in" Downloads, etc.

**Comment by esteelpaz** [comment]
@geckolinux 

So I deleted my previous post because I went ahead and installed the fresh Gecko Plasma, and as we suspected the grub menu is restored!!!!  A lot easier doing it that way than figuring out the UUID numbers and re-entering them one at a time.  : - (

But, one of my OpenSUSE "/" seems to be using 40GB of space, compared to the others at 11GB,  Something like this happened over in my Sys76 laptop where two systems got installed??  Anyway, for now this thread is "solved" . . . .  Thanks for the help on it, very kind of you.

**Comment by geckolinux** [comment]
Glad you figured it out! Cheers.

**Comment by esteelpaz** [comment]
@geckolinux 

Well, I spoke elatedly too soon . . . the base install of Plasma rolling went in fine and restored the grub menu function.   That put a 5.10 kernel in place, I rebooted scrolled around in Grub, then decided, "Ah, I should run a zypper to bring it up to date."  That showed 1576 packages to install, including a 5.12 kernel; so I dropped into a TTY and ran then through.  Quite a while later it finished and I rebooted . . . back into a blank white screen???  No grub, again . . . naturally . . . .

So, something isn't fitting in with my machine, I'm back in OSX to type this out.  Maybe later I'll try to wipe that install and just run it thru as the base and never ever upgrade it???  : - 0

**Comment by geckolinux** [comment]
I'd recommend filing an openSUSE Tumbleweed bug report. But it's not related to the kernel. It's definitely a GRUB issue, which loads before the kernel does.

**Comment by esteelpaz** [comment]
@geckolinux 

OK, good idea . . . I tried to piggyback onto a couple of similar sounding bugs, but they said, "Go play elsewhere."  Is this the "bugzilla" site that you are talking about??

**Comment by geckolinux** [comment]
At this link here please:
https://bugzilla.opensuse.org/enter_bug.cgi?product=openSUSE%20Tumbleweed

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks kindly for the link, it's often difficult navigating into the proper slot of the bug report realm . . . .  Bug report, filed.

[https://bugzilla.opensuse.org/show_bug.cgi?id=1185929](url)

**Comment by esteelpaz** [comment]
@geckolinux 

So I ran another fresh install of Gecko rolling and "voila" . . . grub is back.

I selected Gecko MATE install which I saw over the last few days that "sd8" "/" is showing "39.58 GB" as being used in a 48.83GB partition???  Other "/" for TW are using 11GB and I think Manjaro is using 15GB . . . any thoughts on why Gecko rolling seems to be using so much space . . . GParted shows "81% used"???

**Comment by geckolinux** [comment]
Well, a fresh installation of GeckoLinux is less than 6GB roughly. After that the space would depend on how the system is used and what additional packages are installed.

**Comment by esteelpaz** [comment]
@geckolinux 

Yes, I see that the new un-updated install is roughly 6 GB . . . I keep the "/home" in a separate partition so I'm not including that stuff.  Seems like a big jump up to about 40GB . . . for the most part my installs are mostly "stock" because I have a choice of now 6 or so, so I'm rotating through them . . . .

I saw on my Sys76 laptop that my Gecko MATE install on that computer is "26 GB" . . . which is still large but not 40 GB??

On another note, issues with "grub" have been plaguing ubuntu for at least a year, such that I don't upgrade anything they put out for grub, there is a bug report that has been going for quite awhile.  Some of the guys have "figured it out" and have fixed it, my /etc/grub/default???  file didn't match what they were talking about, but one guy said that "grub 2.04" is the problem and to either downgrade to 2.02 or upgrade to 2.06 to "get around this "grub menu not appearing" problem . . . .  I don't know if that relates over in Gecko/OpenSUSE, which as I had said, had been "immune" from the problem that ubuntu seems to think is cool, it only boots one system--theirs.  So for most folks that's OK, but if you have more than two systems then, no . . . .

**Comment by esteelpaz** [comment]
@geckolinux 

This problem **may** be resolved via the dev Michael C that worked on the bug report via updating the kernel to 5.12.4+ and then running this command he posted to the bug report:

> Thank you for the updated information. Would you please try booting without shim in the way ?

The procedure is simple, Run the command in your MBP Leap 15.3 install

  grub2-install
  efibootmgr -v

Please attach the 'efibootmgr -v' output here for reference. Also you have to disable secure boot for the testing, if your system supports that.

>
