### ISSUE TITLE
Gecko want to install bootloader on usb flash not correct partition!

### ISSUE THREAD

**Issue by mlibre** [geckolinux/geckolinux-project#22]
I am in installer right now. (nice font config btw!)
I set `/boot/efi` and `/`.
image:

![a](https://cloud.githubusercontent.com/assets/8473036/21748735/ce3491c0-d5a1-11e6-988a-81e21ebb9ed2.png)

but in the end, installer want to install `bootloader` on my flash! 
image:

![b](https://cloud.githubusercontent.com/assets/8473036/21748743/1858cc62-d5a2-11e6-884e-590c171b5ac0.png)

`lsblk`:
sdb      8:16   1   7.5G  0 disk 
├─sdb2   8:18   1     1G  0 part /livecd
└─sdb1   8:17   1     4M  0 part 
loop0    7:0    0 901.5M  1 loop /read-only
sda      8:0    0 465.8G  0 disk 
├─sda4   8:4    0  98.1G  0 part 
├─sda2   8:2    0   100M  0 part 
├─sda7   8:7    0  49.8G  0 part /tmp/calamares-root-ez1uf9to
├─sda5   8:5    0  92.8G  0 part 
├─sda3   8:3    0    16M  0 part 
├─sda1   8:1    0   450M  0 part 
├─sda8   8:8    0 220.7G  0 part 
└─sda6   8:6    0   3.9G  0 part

`uname -a`:
Linux dhcppc3 4.9.0-2-default #1 SMP PREEMPT Fri Dec 16 19:51:27 UTC 2016 (6fbc0c0) x86_64 x86_64 x86_64 GNU/Linux

`test -d /sys/firmware/efi/ && echo UEFI || echo BIOS`:
UEFI

Gecko-rolling release, created by `dd`.

**Comment by geckolinux** [comment]
Hi there, thanks for reporting this. [EDITED, see next reply.]

**Comment by geckolinux** [comment]
Oops, sorry I didn't notice that you were already using the manual partitioning mode. So that definitely looks like a bug. Thanks for reporting it to the Calamares team as well.

Reference: https://calamares.io/bugs/browse/CAL-441

**Comment by geckolinux** [comment]
This should be fixed in Calamares 3.0, included in the latest GeckoLinux 170124 editions released today.
