### ISSUE TITLE
Gecko Linux NEXT Plasma - errors after language update

### ISSUE THREAD

**Issue by madelgijs** [geckolinux/geckolinux-project#222]
I just gave Gecklinux NEXT Plasma a try. Install wen fine, but after installing additional languages (I need German), the system settings App keeps crashing when I try to launch it and after a reboot the login screen is a total mess. I'm not sure what I  did wrong, but any help would be appreciated.
### 
![PXL_20210516_124148637](https://user-images.githubusercontent.com/21339118/118397778-3f8aed00-b645-11eb-9150-69f3dc699c9d.jpg)

**Comment by geckolinux** [comment]
Hi there, sorry for the trouble. Please reinstall it, and [update the system](https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux) first before running the language install script.

It looks like I'll have to add a full system update to the language installer script.

**Comment by geckolinux** [comment]
Workaround in place for the latest release:
https://github.com/geckolinux/geckolinux-project/releases/tag/210519.999

**Comment by madelgijs** [comment]
Thanks!
