### ISSUE TITLE
Installation doesn't work - error on partitioning

### ISSUE THREAD

**Issue by Revertron** [geckolinux/geckolinux-project#225]
Trying to install GeckoLinux rolling with Plasma on VirtualBox.
Have chosen automatic partitioning with SWAP. Can't proceed, see screenshot.
![VirtualBox_GeckoLinux_19_05_2021_10_11_10](https://user-images.githubusercontent.com/105154/118780782-afd77f80-b88c-11eb-9941-5396c00863c0.png)

**Comment by geckolinux** [comment]
Hello, please post a screenshot of the exact options you are choosing in the partitioning step.

**Comment by Revertron** [comment]
There is a choice with SWAP or without it. I only selected "with SWAP".

**Comment by geckolinux** [comment]
OK thanks for reporting the bug, I'll see if I can find a fix and make a new release.

**Comment by Revertron** [comment]
Thanks!

**Comment by geckolinux** [comment]
Thanks again for reporting this, the issue should be fixed in the latest release:
https://github.com/geckolinux/geckolinux-project/releases/tag/210519.999
