### ISSUE TITLE
Startup Script errors out and stops the run on Leap 42.2 (XFCE)

### ISSUE THREAD

**Issue by knathan54** [geckolinux/geckolinux-project#23]
I cloned your GeckoLinux XFCE for Leap 42.2 on Saturday (2017-01-07) and got an error of file not found. I saw what your startup script was doing here:
`# Remove repos that are only for the live system or wrongly named

rm /etc/ypp/repos.d/sb73542_openSUSE_Leap_42.1.repo

rm /etc/zypp/repos.d/42.2_Non-OSS.repo

rm /etc/zypp/repos.d/42.2_Non_OSS_Update.repo

rm /etc/zypp/repos.d/kek.repo

rm /etc/zypp/repos.d/leap_42.2_updates.repo

rm /etc/zypp/repos.d/sb56637-calamares-openSUSE_Leap_422.repo

rm /etc/zypp/repos.d/v_d5wsfe5cuj.repo
`

and saw that the first file didn't exist. So, I wrote a short function to check for directory and file and only then do the delete. Here is my fix:

`repoDir="/etc/zypp/repos.d"

repoDelete() {
    if [ -d $repoDir ]; then 
      if [ -e $repoDir/$1 ]; then
        rm $repoDir/$1
      fi
    fi
}

repoDelete sb73542_openSUSE_Leap_42.1.repo
repoDelete 42.2_Non-OSS.repo
repoDelete 42.2_Non_OSS_Update.repo
repoDelete kek.repo
repoDelete leap_42.2_updates.repo
repoDelete sb56637-calamares-openSUSE_Leap_422.repo
repoDelete v_d5wsfe5cuj.repo

`

**Comment by geckolinux** [comment]
Hi, thanks a lot for the useful contribution. Hopefully I can include it 
for the next set of GeckoLinux Static updates.

Cheers.
