### ISSUE TITLE
Gecko Plasma zypper hits dependency question???

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#241]
@geckolinux 

Howdy again, I was playing with my new install of Gecko Plasma and it's pretty zippy, so it's a "keeper" . . . tried to run a zypper dup -l and I hit this dependency issue right up top . . . .  What is best course of action?  I used to just go with the new, but in this case I don't know which that is and I've hit so many issues in SUSE lately I don't have any chops left for guessing.  : - )

`Problem: nothing provides kernel-uname-r = 5.12.4-1-default needed by broadcom-wl-kmp-default-6.30.223.271_k5.12.4_1-14.65.i586
 Solution 1: deinstallation of broadcom-wl-kmp-default-6.30.223.271_k5.10.16_1-14.25.x86_64
 Solution 2: keep obsolete broadcom-wl-kmp-default-6.30.223.271_k5.10.16_1-14.25.x86_64
 Solution 3: break broadcom-wl-kmp-default-6.30.223.271_k5.12.4_1-14.65.i586 by ignoring some of its dependencies`

**Comment by geckolinux** [comment]
Hi there, that's a common temporary issue when Tumbleweed updates its kernel version and Packman needs a bit of time to catch up with its `broadcom-wl` packages. If you don't have Broadcom WiFI you can safely delete it those Broadcom packages (although I remember that you have some Mac hardware, which probably does indeed need it).

**Comment by esteelpaz** [comment]
@geckolinux 

In this case, yes, this is running on my '12 cMP . . . but I am using ethernet to connect I wouldn't need wifi.

So, what's "best" "easiest" . . . wait a few days before running zypper and see if it goes through w/o asking me difficult questions?  There is no particular rush, I think it's been a couple of weeks since I did the install trying to get grub function operational, figuring there will be "packages waiting" . . . but, they could wait a bit??

**Comment by geckolinux** [comment]
Yep, just a wait a few more hours, they'll update it pretty soon.

**Comment by esteelpaz** [comment]
Cool.  I can wait a few hours . . . .  : - 0
