### ISSUE TITLE
[Pantheon] Session breaks after change Wallpaper 2x on Tumbleweed

### ISSUE THREAD

**Issue by AdsonCicilioti** [geckolinux/geckolinux-project#244]
I've tested on Live System before install and after on system installed.

On Leap all Works Fine! But on Tumbleweed after change wallpaper two time the session breaks, and return on login screen.
When change wallpaper by first turn, the window manager (Gala) restart and Wingpanel do not adjust the text color based on color of wallpaper,

**Comment by geckolinux** [comment]
Sorry for the difficulty. It looks like the packager of the Pantheon desktop for openSUSE has not been updating it, so I'll have to pause the Pantheon edition of GeckoLinux until that changes.
