### ISSUE TITLE
Here Are Miscellaneous Tweaks to Gecko That I Think Might Improve the Distro

### ISSUE THREAD

**Issue by ElliotLurie** [geckolinux/geckolinux-project#250]
Hi again. The 153 release is really good (though I opted to reinstall because of some extra repos I had enabled in 152) and found a few paper cuts in this release that I think could be easily fixed. I am coming from the XFCE edition, so how much these affect the other spins is something I am not aware of.

* While appearances are equally surface-level and up to one's opinion, the default look and feel of the distribution is a bit inconsistent. Numix is an okay theme, but it really clashes with the lime-green wallpaper. Obviously, any user can change these themes, but first impressions are first impressions. I would check out OpenSUSE's upstream "Greybird-Geeko" theme as a start, though I might be biased as it is my favorite. As for what to do for the QT desktops, I have no idea in that regard.
* There is no branding in Calamares for the distribution. While I wouldn't call this particularly off-putting on its own, the fact that there is just a blank screen while the install is happening certainly does not help in this case. This is relatively simple to fix as you could add a simple message saying that the system is being installed or something.
* The Gnome Keyring PAM module is disabled by default in Lightdm even though it is installed. This is a relatively quick fix with modifications to `/etc/pam.d/xdm` (or at least that's where I put them) following the [wiki](https://en.opensuse.org/GNOME_Keyring). But, as I mentioned before, I don't exactly know which file would be the best to edit for this.
* Upstream OpenSUSE has a really handy update notifier widget called `package-update-indicator`. All you have to do is also install the package along with `gnome-packagekit-extras` and `packagekit-backend-zypp` as well as enabling the indicator to autostart and you no longer need to manually check for updates with YaST.

Again, the distribution is really good as it is, but these would certainly take away a few pain points. Thanks for reading this!

**Comment by geckolinux** [comment]
Hi there, thanks a lot for the constructive suggestions!


> I would check out OpenSUSE's upstream "Greybird-Geeko" theme as a start, though I might be biased as it is my favorite.

That one definitely won't be used by default, as its font color contrast with the other UI colors is terrible. A major goal of GeckoLinux is highly legible fonts, so function takes precedence over form in the choice of UI themes, especially with GTK where the font colors are also defined in the theme. The only other GTK theme that I've found in the main openSUSE repos with good font contrast and otherwise attractive colors is Yaru. I'm really not concerned about matching with the default wallpaper, as that's the first thing that almost all users change, and generally windows are covering the wallpaper anyway.

> There is no branding in Calamares for the distribution. While I wouldn't call this particularly off-putting on its own, the fact that there is just a blank screen while the install is happening certainly does not help in this case. This is relatively simple to fix as you could add a simple message saying that the system is being installed or something.

Fair point. If somebody wants to contribute one I'd be happy to include it.

> The Gnome Keyring PAM module is disabled by default in Lightdm even though it is installed. This is a relatively quick fix with modifications to /etc/pam.d/xdm (or at least that's where I put them) following the wiki. But, as I mentioned before, I don't exactly know which file would be the best to edit for this.

Could you please explain what the advantage of enabling it would be? I'm not too familiar with it.

> Upstream OpenSUSE has a really handy update notifier widget called package-update-indicator. All you have to do is also install the package along with gnome-packagekit-extras and packagekit-backend-zypp as well as enabling the indicator to autostart and you no longer need to manually check for updates with YaST.

Unfortunately that widget uses the PackageKit framework, which I don't want to be installed on GeckoLinux as it creates major bloat and also causes an array of problems by interfering with the underlying Zypper package manager. They're major long-standing issues that have existed for years, and so it looks like PackageKit unfortunately will never be improved.

Thanks again for the suggestions!

**Comment by ElliotLurie** [comment]
> That one definitely won't be used by default, as its font color contrast with the other UI colors is terrible.

Okay, I never really noticed that with the dark variant but I see your point with the light one. There are the mint themes, but they seem to be broken at the moment. I'll report that upstream, but I wouldn't know if that would get fixed. While I get that having it match the wallpaper is not particularly important aside from a first impression, I would argue that the muted red of Numix and bright green of the wallpaper can kind of cause a bit of eyestrain in its current state.

> Fair point. If somebody wants to contribute one I'd be happy to include it.

I'm not the best with graphic design, but I'll check it out myself.

> Could you please explain what the advantage of enabling it would be? I'm not too familiar with it.

`gnome-keyring` is the Gnome password manager that OpenSUSE (and Gecko, consequently) uses. In the way it is configured right now, the login "keyring" isn't unlocked automatically, so whenever you need to access a password (say, for network manager) you need to type your login password. So, by enabling the PAM module, the experience is seamless.
> Unfortunately that widget uses the PackageKit framework...

It's funny, I just ran into an issue with it just after posting this. Never uninstalled something faster in my life.

Thanks for the quick reply!

**Comment by geckolinux** [comment]
> `gnome-keyring` is the Gnome password manager that OpenSUSE (and Gecko, consequently) uses. In the way it is configured right now, the login "keyring" isn't unlocked automatically, so whenever you need to access a password (say, for network manager) you need to type your login password. So, by enabling the PAM module, the experience is seamless.

Hmm OK, interesting. So what I've always done is simply use a blank password for Gnome Keyring the first time I enter a NetworkManager WiFI password, and it doesn't appear any more.  But that isn't a trick that most users know about, it would definitely be preferable for the keyring password prompt to never appear. If you could share your `/etc/pam.d/` modifications that would be a big help.

Thanks again!

**Comment by ElliotLurie** [comment]
Here's `/etc/pam.d/xdm` attached. Also, I would seriously suggest that you use a password protected keyring for your passwords as I am pretty sure they're currently in plain text on your machine!
[xdm.txt](https://github.com/geckolinux/geckolinux-project/files/6679480/xdm.txt)

**Comment by tuxayo** [comment]
@TrueTechie

> I would seriously suggest that you use a password protected keyring for your passwords as I am pretty sure they're currently in plain text on your machine!

So with your suggestion it would use the login password to encrypt the keyring, right? 

I'm confused by «so whenever you need to access a password (say, for network manager) you need to type your login password» which would mean it already uses it but the unlocking is not cached in RAM.

**Comment by geckolinux** [comment]
Implemented the `/etc/pam.d/xdm` tweak in upcoming _STATIC_ and _ROLLING_ releases, thanks @TrueTechie !
