### ISSUE TITLE
Reason for removing pantheon?

### ISSUE THREAD

**Issue by SilverMarcs** [geckolinux/geckolinux-project#257]
Pantheon was a wonderful edition to have. what went wrong?

**Comment by geckolinux** [comment]
The Pantheon repository wasn't updated initially when Leap 15.3 was released, and there were some bug reports with the Tumbleweed builds, with no updates from the openSUSE packager. If the situation improves I'll resume the Pantheon ISOs. Meanwhile you can use the previous ones and update them.
