### ISSUE TITLE
Rolling Budgie (and maybe others): PDF (and other documents) viewer is not installed

### ISSUE THREAD

**Issue by Squeezer-CZ** [geckolinux/geckolinux-project#26]
Evince is installed, but is missing its modules for reading documents (so it is in fact very useless).
For that, one has to manually install modules (plugins) via yast, for example, for reading PDFs, one has to install:
evince-plugin-pdfdocument

I think it would be good idea to integrate these plugins (at least PDF, XPS and PSD) to default installation image.

**Comment by geckolinux** [comment]
Thanks for reporting this bug. It will be fixed in an update that will hopefully be released today.
