### ISSUE TITLE
Gecko MATE upgrade reports "1.6 GB Disk Space" remaining in 48.83 GB partition?

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#265]
@geckolinux:

As reported previously, today running a zypper dup -l in my Gecko MATE partition I got a couple of errors reporting "1.6 GB disk space remaining" . . . I clicked examine disk usage and it showed "/" at "100%" and "var/cache" and "var/cache/zypp" at "99.8%" . . .  of what should be a very roomy 48.83 GB of space???

Also as reported previously my recently installed Gecko Plasma "/" is using 11.54 GB of space.  Since I have possibly 10 linux systems of various ilk spread across three machines I'm not customizing the installs, most of them are box stock and maintained via apt or zypper.

Can I remove the "var/cache" or "var/cache/zypp" folders to reduce the space being used down to more normal??  Asking again why Gecko MATE seems to be using inordinate amounts of space when compared to all of the other installs??

Screenshot of Disk Use Analyzer attached:

![DisjUseAnalyzer](https://user-images.githubusercontent.com/4001331/125313142-cd9fee80-e2e9-11eb-8fc0-3e76c9761f58.png)

**Comment by geckolinux** [comment]
Hi there, could you please first try `sudo zypper clean --all` ?

Then if that doesn't help, please post a screenshot of your disk layout in Gparted as well as your `/etc/fstab` .

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks for the reply, I ran your suggest command and it says, "All repositories have been cleaned up."  So this data should still be valid.

```
sudo cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>             <mount point>  <type>  <options>  <dump>  <pass>
UUID=67E3-17ED                            /boot/efi      vfat    defaults,noatime 0 2
UUID=2779207b-54a2-4b94-a7df-75edd1de9831 /              ext4    defaults,noatime 0 1
UUID=64c5dba2-bacd-4459-9904-6bda0fbe24e7 /home          ext4    defaults,noatime 0 2
UUID=dac6d73c-5e42-47ce-af39-ba762532645d swap           swap    defaults,noatime 0 2
UUID=f9ae531f-ec45-4a13-a75d-d3fd4cd80fe0 swap           swap    defaults,noatime 0 2
```

![GPartedGeckoMATE](https://user-images.githubusercontent.com/4001331/125321222-51a9a480-e2f1-11eb-8599-21ca9f8ba515.png)

**Comment by geckolinux** [comment]
> Thanks for the reply, I ran your suggest command and it says, "All repositories have been cleaned up." 

OK, so with that you should have another 40.9GB of free space now.

**Comment by esteelpaz** [comment]
@geckolinux 

In fact, yes, now down to 6.58 GB of used space in "/"??? . . . .  It happened so fast, I hit return, and instantly it claimed it was "clean," . . . so I figured that "nothing had changed" . . . as there wasn't a single second of what might have been the sound of **40 GB** of space being moved or cleaned????

So, very basic command, which there is "apt autoclean" in the ubuntu world . . . but why is it that zypper let this "virtual space" build up over the recent months, could file error reports on it, but then wouldn't "clean itself"??  Whereas even in other OpenSUSE installs there isn't this over-storage thing happening??

I believe that my Gecko MATE install in my linux machine also has this space build up in "/" . . . guess I'll have to "clean --all" over there as well . . . : - 0

Glad it was a simple fix . . . thanks again.

**Comment by geckolinux** [comment]
I don't think that Debian/Ubuntu caches downloaded packages, so the `apt autoclean` thing is actually for removing unneeded dependencies.

If you don't want packages to accumulate you can open the YaST Repositories tool and disable "Keep downloaded packages" for each repo.

**Comment by esteelpaz** [comment]
OK, thanks for the tip on Yast . . . items unchecked.
