### ISSUE TITLE
Snapper in Gecko

### ISSUE THREAD

**Issue by Afsalmc** [geckolinux/geckolinux-project#268]
How can i setup everything snapper including Grub2 integration with snapper like in openSUSE with Gecko linux ?

Following opensuse Docs made rollback entries available in Yast . But still it's not shown in Grub . Any help

**Comment by geckolinux** [comment]
Hi there, unfortunately it doesn't appear to be possible to make GRUB integration work without the YaST Installer (which in turn isn't compatible with offline installation of compressed images, so not an option for GeckoLinux).

**Comment by geckolinux** [comment]
@Afsalmc 
If you'd like to test it here's an ISO with Btrfs snapshots and GRUB integration, thanks to some major improvements in Calamares and a bit of hacking:
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_ROLLING_XFCE.x86_64-999.211212.0.iso/download
I'd appreciate tests on real hardware and VMs, with and/or without other installed operating systems, on legacy BIOS or EFI systems, and also with the other non-Btrfs filesystems to make sure the installed system is bootable. Thanks in advance!

**Comment by geckolinux** [comment]
Implemented in upcoming _ROLLING_ and _STATIC_ editions.
