### ISSUE TITLE
Leap not booting into GUI, just goes to command line

### ISSUE THREAD

**Issue by markadewet** [geckolinux/geckolinux-project#270]
Hi all,
I am a novice at Linux and I have just downloaded GeckoLinux_STATIC_Plasma.x86_64-153.210608.0 from here and created a USB boot disk using Etcher (running as Administrator) on Windows 7, as suggested. 
The USB boots fine as far as I can tell, however, neither the normal boot option nor the failsafe option bring up a GUI. It just drops to a command prompt. Is there something I am doing wrong or something wrong with the way the image was written to the USB Stick? Any assistance would be most appreciated.

**Comment by geckolinux** [comment]
Hi there, could you please verify the md5sum of the download?

**Comment by markadewet** [comment]
> Hi there, could you please verify the md5sum of the download?

I did, both SHA1 and MD5 are correct as per the website: https://sourceforge.net/projects/geckolinux/files/Static/153.210608/

**Comment by geckolinux** [comment]
Please give one of the Rolling editions a try, in case it's an issue with newer hardware compatibility.  Also try a different USB drive. Also please post your hardware specs and a picture of the screen when it fails to boot.
