### ISSUE TITLE
Pantheon is not on the download page again?

### ISSUE THREAD

**Issue by memesforlife1** [geckolinux/geckolinux-project#274]
The Pantheon Main Repo ([https://download.opensuse.org/repositories/X11:/Pantheon/openSUSE_Tumbleweed/](url) for tumbleweed has updated yesterday (11/8/21) and the Pantheon Branch Repo [https://download.opensuse.org/repositories/X11:/Pantheon:/Branch/openSUSE_Leap_15.3/](url) that avoids being dependent on gnome has updated for Leap 15.3 on 8/8/21.
So Please Put the pantheon ISO back on the website.

**Comment by geckolinux** [comment]
The packages are constantly rebuilt automatically in OBS when some other dependency package changes. However, the source packages have not received any attention for a long time:

![Screenshot_2021-08-11_23-50-27](https://user-images.githubusercontent.com/2692138/129139925-fb7d6569-55a8-4983-80be-05fb3f9a93ba.png)

![Screenshot_2021-08-11_23-50-44](https://user-images.githubusercontent.com/2692138/129139939-6e073528-d9be-4ef9-a311-81f37033833a.png)

**Comment by ylluminate** [comment]
Has the Pantheon edition been restored to activity again? Seems like the ISO updates are being built again. Very exciting if so!

**Comment by geckolinux** [comment]
Hi there, yes, the Pantheon version was reactivated since the past two releases.
