### ISSUE TITLE
bzip2 and other compression protocols support

### ISSUE THREAD

**Issue by geckolinux** [geckolinux/geckolinux-project#280]
Confirm and add across the board.

**Comment by geckolinux** [comment]
Implemented in upcoming _ROLLING_ and _STATIC_ editions.

**Comment by tuxayo** [comment]
comming from https://github.com/geckolinux/geckolinux-project/releases/tag/220105.999

So now filesystem level compression is enabled on / for new installs?

**Comment by geckolinux** [comment]
@tuxayo Yep, it has been for the last several releases.
