### ISSUE TITLE
Calamares crash on trying to setup LVM storage for install on Rolling Gnome

### ISSUE THREAD

**Issue by Polisson** [geckolinux/geckolinux-project#291]
Environment: Virtual Machine by VM Workstation Player 16
disk controller as NVMe (but SCSI or SATA acts same)
disk size 20GiB
100% reproducible

Every time when trying to setup target media as LVM device, the installer closes immediately:
after click on _New Volume Group_ the _Create Volume Group_ dialog appears. Adding proper values in it and click OK, the Calamares installer dies.

In Gecko Rolling with Gnome there are three tools for partitioning: Gnome Disk, GParted and Yast Partitioner.
The last one is capable to almost finish setup of partitions, but as it acts like submodule for Yast Installer, finishing setup breaks actual live environment (because of remounting partitions).

**Comment by geckolinux** [comment]
Thanks for reporting. Unfortunately it looks like Calamares basically has no support for LVM:

- https://github.com/calamares/calamares/issues/1132
- https://github.com/calamares/calamares/issues/1410#issuecomment-650637974
