### ISSUE TITLE
Wrong keyboard layout when grub have to open a LUKS partition (encrypted /boot)

### ISSUE THREAD

**Issue by tuxayo** [geckolinux/geckolinux-project#296]
Hi :)

- have an encrypted install with a non default keyboard layout (french azerty, german qwertz, dworak, esperanto, bépo, etc)
  - I selected to replace an existing partition with grub and to encrypt it. In case there are multiple possibilities that the installed can do
- boot
- layout is qwerty for the passphrase prompt

iso: GeckoLinux_ROLLING_XFCE.x86_64-999.210526.0

lead for a solution: https://cryptsetup-team.pages.debian.net/cryptsetup/encrypted-boot.html#using-a-custom-keyboard-layout

**Comment by geckolinux** [comment]
Thanks for this bug report. This is a very interesting issue. Unfortunately it looks like it would need to be handled by the Calamares installer, and they don't support non-English keyboard layouts yet for GRUB:

https://github.com/calamares/calamares/issues/1772#issuecomment-913197328
