### ISSUE TITLE
Language change doesn't work

### ISSUE THREAD

**Issue by tuxayo** [geckolinux/geckolinux-project#297]
- install
- double click the desktop launcher about languages
- full upgrade and addition package installation seems to be ok
- open yast languages
- switch to another language
- reboot
- XFCE, Firefox, sudo GUI prompt, yast software are still in english
- yast languages is in the right language! (fr in my case)

iso: GeckoLinux_ROLLING_XFCE.x86_64-999.210526.0

**Comment by geckolinux** [comment]
Hi there, looks like you forgot the step of changing the language in LightDM. Please confirm after following these instructions:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-install-non-english-languages
Thanks for reporting!

**Comment by tuxayo** [comment]
That might be it, thanks!
