### ISSUE TITLE
Discover and Gnome software can't manage packages

### ISSUE THREAD

**Issue by tuxayo** [geckolinux/geckolinux-project#298]
- install Discover including packagekit backend
- install gnome software
- open both
- they can't list installed apps
- nor search in the repos

I have a Tumbleweed install where I can do that. (even if I think there are some bugs, I wanted to retry)

iso: GeckoLinux_ROLLING_XFCE.x86_64-999.210526.0

I'm experimenting with Gecko in the hope to use it at install parties and having and having people use an application manager instead of a package manager would help a lot. To not have libs, bindings, backends, translations, debug symbols and other technical stuff coming up before the package of interest when wanting install lets says vlc or steam.

edit: packagelit zypper backend is installed

**Comment by geckolinux** [comment]
Hi there, unfortunately Discover and Gnome Software use the PackageKit framework, which is a terrible mess of bugs and unmaintained software, so they are not recommended for GeckoLinux.

- https://github.com/geckolinux/geckolinux-project/issues/250#issuecomment-860093714
- https://www.reddit.com/r/openSUSE/comments/n3v2ie/this_is_why_i_dont_use_packagekit_gnome_software/
