### ISSUE TITLE
dual boot: post install update causes the other Linux not to be listed anymore in grub

### ISSUE THREAD

**Issue by tuxayo** [geckolinux/geckolinux-project#299]
- install in a partition next to an non-encrypted existing linux install (encrypt Gecko in case that's a factor)
- first boot after install, I see also my other Linux in grub
- update the whole system (with the language change desktop launcher is case that's a factor)
- reboot
- only Gecko is in grub

iso: GeckoLinux_ROLLING_XFCE.x86_64-999.210526.0

**Comment by tuxayo** [comment]
The "Probe foreign OS" option in YaST->System->Boot Loader->Boot Loader Option is disabled. 

Maybe having GRUB_DISABLE_OS_PROBER=false in /etc/default/grub on install would fix it?

**Comment by geckolinux** [comment]
Thank you for this report, you're right that the latest version of GRUB changed its behavior and no longer probes for other OS versions by default.

> Maybe having `GRUB_DISABLE_OS_PROBER=false` in `/etc/default/grub` on install would fix it?

Yes exactly, this will be included in the upcoming updates to GeckoLinux.

**Comment by ghost** [comment]
I'm wondering if this is a problem with OpenSUSE as well or a GeckoLinux issue only?

**Comment by geckolinux** [comment]
It's an intentional change and feature regression in upstream GRUB due to (in my opinion) paranoid and unrealistic security concerns.

https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html
> `GRUB_DISABLE_OS_PROBER`
> 
> It is disabled by default since automatic and silent execution of `os-prober`, and creating boot entries based on that data, is a potential attack vector. Set this option to `false` to enable this feature in the `grub-mkconfig` command

https://wiki.archlinux.org/title/GRUB#Detecting_other_operating_systems

> If you get the following output: Warning: os-prober will not be executed to detect other bootable partitions then edit /etc/default/grub and add/uncomment:
> 
> `GRUB_DISABLE_OS_PROBER=false`

**Comment by geckolinux** [comment]
Fix implemented in upcoming _ROLLING_ and _STATIC_ releases.
