### ISSUE TITLE
Is there KDE desktop available?

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [geckolinux/geckolinux-project#3]
I can see many desktops: Cinnamon, XFCE, Gnome, ....

But what about the popular KDE desktop?

**Comment by geckolinux** [comment]
I'm working on it right now. :)

**Comment by DavidPerezIngeniero** [comment]
Thanks.  KDE used to be the default desktop in OpenSuse!.

**Comment by geckolinux** [comment]
https://susestudio.com/a/OO38wm/geckolinux-plasma5

**Comment by DavidPerezIngeniero** [comment]
In the description shown in the provided link I can read:

```
The latest stable release of the Cinnamon desktop environment with a pleasant default configuration
```

I think it should say:

```
The latest stable release of the KDE Plasma 5 desktop environment with a pleasant default configuration
```

**Comment by tkelman** [comment]
I'm trying this out on SuseStudio Test Drive (which is really cool! more distros should be doing what suse does with studio and obs), and noticed an Openbox option on the login screen. That option doesn't seem to be working, is that expected?

**Comment by tkelman** [comment]
I might just be dumb or missing something obvious in how openbox works, it's just a gray screen but if I right click then I do get a launcher that comes up. It looked so featureless I didn't think it had finished logging in. Apologies for the noise!

**Comment by geckolinux** [comment]
:) Yes, openbox is VERY minimal. It's just there as an emergency option in case something breaks in the main desktop environment.

Please let me know if you have any other thoughts or questions.
