### ISSUE TITLE
[Suggestion] Update notifications or other ways to keep a system up to date for beginners

### ISSUE THREAD

**Issue by tuxayo** [geckolinux/geckolinux-project#300]
I'm experimenting with Gecko in order to use it at install parties. And I'm searching for a way for users to be prompted when there are upgrades and in a few clicks launch it.

https://github.com/geckolinux/geckolinux-project/issues/250#issuecomment-860093714
> Upstream OpenSUSE has a really handy update notifier widget called package-update-indicator. All you have to do is also install the package along with gnome-packagekit-extras and packagekit-backend-zypp as well as enabling the indicator to autostart and you no longer need to manually check for updates with YaST.

> Unfortunately that widget uses the PackageKit framework, which I don't want to be installed on GeckoLinux as it creates major bloat and also causes an array of problems by interfering with the underlying Zypper package manager. They're major long-standing issues that have existed for years, and so it looks like PackageKit unfortunately will never be improved.

This is issue is for
1. the problem with package-update-indicator , see what upstream ticket could if eventually solved could make it a solution again
2. see if there would be alternatives without package-update-indicator
3. explore other solutions (not to be enabled by GeckoLinux) like automatic online updates that user/people installing could set up

edit:

4. on shutdown automatic update. That's how Debian unattended update work. Online download of the update from the security repo. And installation on shutdown (a systemd unit triggers this)

**Comment by tuxayo** [comment]
About auto updates (3.) , updating without rebooting could causes many issues.
On my EndeavourOS (Arch based) install 
- when I'm updating Firefox without restarting, at some point, any new tab prompts me to restart Firefox due to the update. Which can be in a very inconvenient moment if in the middle of a task and having forms not submitted yet, searches in horrible (so almost all) news or shopping sites in private browsing to limit the damage or a long running download or upload, etc. In the past it just crashed, so that's an improvement :D
- I don't know if it's light-locker or the GPU driver but after "the right" updates if I suspend the system, on resume I get a black screen and must go to a TTY to reboot the system, thus risking to loose work.

So that kind of stuff might happen in Gecko.

- On my Tumbleweed install last time after a lot of updates (IIRC!), my mouse wasn't detected anymore until reboot when unplugging it and replugging it. I suppose it's due to kernel update and the directory of kernel modules of the running kernel having been deleted. So USB plugged drives wouldn't have worked also. For the record, Arch has a [package](https://archlinux.org/packages/community/any/kernel-modules-hook/) to keep the old modules, otherwise even minor updates break plug and play. I *think* Ubuntu doesn't suffer from this but I don't know how they do it. (no major kernel update helps)

There isn't much hope in the the direction of online auto updates.

**Comment by geckolinux** [comment]
Hi there, GeckoLinux only offers packages that are officially maintained for openSUSE, since I am not a software developer and creating new software is far out of the scope of this project.

> the problem with package-update-indicator , see what upstream ticket could if eventually solved could make it a solution again

This will never be included in GeckoLinux due to its dependence on the terrible PackageKit framework.

These are the current recommendations for updating GeckoLinux:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux

Both `zypper` and YaST prompt the user to reboot the system when required after updating.


> see if there would be alternatives without package-update-indicator

Of course if any other maintained software that is packaged for openSUSE that does not use PackageKit is available I'd be happy to consider it for inclusion.
