### ISSUE TITLE
Misleading info on wiki about rufus

### ISSUE THREAD

**Issue by Squeezer-CZ** [geckolinux/geckolinux-project#31]
In wiki:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux

There is note:
Important note: The "Rufus" tool for Windows is known to NOT work with GeckoLinux images.

It works. Choose DD method. Text could be:

Important note: The "Rufus" tool for Windows is known to NOT work with GeckoLinux images via "ISO-method". Choose "DD-method" instead.

(btw, I am using DD method of rufus for geckolinux (and others) myself)

**Comment by geckolinux** [comment]
Thanks for letting me know. The wiki has been updated to:

> **The "Rufus" tool for Windows is NOT recommended due to many reports of failure.**
