### ISSUE TITLE
Fix for calendar thing

### ISSUE THREAD

**Issue by Squeezer-CZ** [geckolinux/geckolinux-project#32]
I cannot reopen closed issues, so:
Fix for bug #29 https://github.com/geckolinux/geckolinux-project/issues/29 can be achieved by installing gnome-calendar (and its dependencies!). So it is not bug in Budgie but missing component in Geckolinux/Budgie.

You can fix  this by adding gnome-calendar (and its dependencies) to live image and to programs installed by default.

(anyway, thanks for your work)

**Comment by geckolinux** [comment]
Hi again, thanks for letting me know about the solution, I wasn't aware of that. The addition of `gnome-calendar` would add 13 additional packages and 44.8 MB of disk space, so I think I'll leave it out.
