### ISSUE TITLE
Can you please add Mirror/Torrent files for the Geckolinux as Sourceforge is quite slow.

### ISSUE THREAD

**Issue by rokfrog** [geckolinux/geckolinux-project#320]
I was trying to download GeckoLinux_NEXT_Pantheon, but it's so slow. And I couldn't find a single torrent option for any of the variants. Kindly please add torrents for each of the types so that it be easy to download as Sourceforge is quite slow.

The one I found here is not seeded https://linuxtracker.org/index.php?page=torrent-details&id=eeb0ae22462183d96595fa259b7166569caf59be

**Comment by geckolinux** [comment]
Hi there, I don't really do torrents and I'm not too familiar with the process of creating and seeding them. I'm sure that Linuxtracker will post them soon. Also I would recommend a multi-threading download manager for Sourceforge downloads, for example `aria2c -x10 https://xxxxxxxxx`

**Comment by rokfrog** [comment]
> Hi there, I don't really do torrents and I'm not too familiar with the process of creating and seeding them. I'm sure that Linuxtracker will post them soon. Also I would recommend a multi-threading download manager for Sourceforge downloads, for example `aria2c -x10 https://xxxxxxxxx`

Thank you @geckolinux . I wish Gecko is put up in https://fosstorrents.com/ as well. It would be useful. Thank you.  And also, please share any article related to dual booting alongside Debian/Ubuntu. I couldn't find any other than just directing for using VM. It would be great if there is a video on how to dual boot Gecko alongside Ubuntu or Deb OS which helps for people to use this parallel.

**Comment by geckolinux** [comment]
Hi @rokfrog , thanks for your patience. Regarding dual booting with any other Linux distro, it's extremely simple with Calamares. If there's another Linux distribution taking up the entire disk it will give you an "Install alongside" option to shrink that partition and install GeckoLinux next to it. Or if there are multiple partitions there will be a "Replace" option that lets you install directly to that partition just by clicking on it.

**Comment by rokfrog** [comment]
@geckolinux Will try it again. I have tried Rocky Linux as well as FreeBSD and it sort of messed up my boot-loader. 
Drive Gparted image: [https://ibb.co/7VjzrJ1](url) 
I got an empty drive sda3 which I kept trying to install any RedHat version distro or BSD variant , either Rocky or OpenSuse or FreeBSD or GhostBSD, but than I saw Gecko which got Pantheon which is quite amazing with OpenSuse base so I wanted to download and install. For Rocky somehow it didn't work. May be I missed out few steps in hurry and even Rock has calamares which shows bootloader, so is why I was checking any info online which has steps to follow through(just in case). Will try again and update. Thank for this now.

**Comment by rokfrog** [comment]
@geckolinux I'm dual booting from #geckolinux . Calamares did work! :-) Thank you again.

**Comment by geckolinux** [comment]
Great! Thanks for confirming that @rokfrog .

**Comment by geckolinux** [comment]
https://linuxtracker.org/index.php?page=torrents&category=2214
Looks like they're starting to release some torrents of the latest release. Feel free contact them to request others if they don't put up the entire array of ISOs.
