### ISSUE TITLE
How to install this rtl8188fu wifi package on #GeckoLinux / #OpenSuse

### ISSUE THREAD

**Issue by rokfrog** [geckolinux/geckolinux-project#323]
I have this driver which Geckolinux didn't pick up.
Kindly help me to install this :https://github.com/kelebek333/rtl8188fu
I have found this https://software.opensuse.org/package/rtl8188fu but it doesn't show any support for Opensuse tumbleweed or Gecko or RPM based systems. This is the most commonly used driver for RTL 8188FTV. Kindly help.

Hardware info: 
https://ibb.co/H20Z265
https://ibb.co/ScY0mks

**Comment by geckolinux** [comment]
Hi there, unfortunately Realtek WiFI support is awfully hard to include. I'd probably recommend that you try to contact the packager of that OBS package that you found to ask him to enable building his package for openSUSE Tumbleweed and Leap.

**Comment by rokfrog** [comment]
@geckolinux I have reached to #opensuse on IRC and requested them to help. One person said will build it and share it in here . Hopefully they do.

**Comment by geckolinux** [comment]
@rokfrog Good idea, I hope it all it works out.

**Comment by geckolinux** [comment]
@rokfrog Would you be able to test with the latest GeckoLinux _Rolling_ ISO? I wonder if your card will be supported with the 5.16 kernel.

**Comment by rokfrog** [comment]
@geckolinux No. Didn't work somehow
