### ISSUE TITLE
Rolling Plasma doesn't recognize wifi card

### ISSUE THREAD

**Issue by Pival81** [geckolinux/geckolinux-project#33]
Hi, I've downloaded today the latest iso file for the Plasma Rolling (GeckoLinux_ROLLING_Plasma.x86_64-999.170124.0.iso) and also checked the md5 sum, but it won't recognize my wifi card (a realtek), which worked fine until my latest installation, which broke this morning.
I haven't installed it yet, only tried in live.

**Comment by geckolinux** [comment]
Hi there, on what OS and version did your WiFI previously work? Which installation broke this morning?

**Comment by Pival81** [comment]
@geckolinux it was working with Rolling Plasma 5  (GeckoLinux_ROLLING_Plasma.x86_64-999.161218.0.iso)
Also, I had put some Manjaro ISOs this morning, and everything was good.

**Comment by geckolinux** [comment]
Could you please boot the version of GeckoLinux that is failing, open a 
terminal, and run:

dmesg > ~/Desktop/dmesg.txt

Then please copy that file here.

**Comment by geckolinux** [comment]
Could you please boot the version of GeckoLinux that is failing, open a 
terminal, and run:

`dmesg > ~/Desktop/dmesg.txt`

Then please copy that file here.

**Comment by Pival81** [comment]
Ok: so here's the file:
[dmesg.txt](https://github.com/geckolinux/geckolinux-project/files/740321/dmesg.txt)
And as you can see, there are no networks available, but my router is only 3-4 meters away from my computer.
I also checked the status of the .service files for NetworkManager and wpa_supplicant and it didn't seem like there was something wrong with it, but I forgot to copy the outputs.
EDIT: sorry, seems like my wifi card is an atheros, not a realtek.
EDIT2: no, not even an atheros, `hwinfo` says it's a dlink:
`linux@localhost:~> sudo hwinfo --wlan --short`
`network:    `                                                    
  `wlp4s1               D-Link AirPlus DWL-G520 Wireless PCI Adapter (rev. B)`
`linux@localhost:~> `

**Comment by geckolinux** [comment]
Thanks for the additional information.

I believe that some D-Link devices like yours use the Atheros driver `ath5k`:
https://wiki.debian.org/ath5k

It looks like the kernel module is being successfully loaded for your WiFI, according to lines 772-773 in your dmesg:

```
[    3.073737] ath5k: phy0: Atheros AR2414 chip found (MAC: 0x79, PHY: 0x45)
[    3.074357] ath5k 0000:04:01.0 wlp4s1: renamed from wlan0
```

What exactly do you see in the Plasma NetworkManager thingy in the panel? Did you make sure that none of the digital or physical switches are turned off for your WiFI?

If you could play around a bit more with the 999.170124.0 version that you have, meanwhile I'm generating a new ISO from the latest state of Tumbleweed, if you'd like to download and test it later on today?

**Comment by Pival81** [comment]
I had made a screenshot of the applet, but forgot to add it before:
![screenshot_20170130_120525](https://cloud.githubusercontent.com/assets/15673222/22479627/c5c908d6-e7ee-11e6-8c94-9f50ca3ced35.png)
Unfortunately I don't have the time to test more, I have to study now.
And I'm sure that the wifi card is fine, I'm using it now on Windows 10.

**Comment by geckolinux** [comment]
Thanks for the screenshot. I don't doubt that your WiFI card is physically working, but I wonder if one of the physical or virtual switches is turning it off. 

The screenshot also shows that the WiFI card is being recognized, just for some reason it's not seeing any networks. Did you try clicking the "Settings" icon there to the right in your screenshot to see if it finds any networks there? Did you try booting GeckoLinux again to see if it happens to work this time?

At any rate, when it's done building I'll drop you a link to a newer ISO to test, if/when you have time.

Thanks.

**Comment by Pival81** [comment]
Everything you said, I tried.
I was also downloading an iso of Krypton to see if the problem is still present, but it got stuck at 69%, and I'm redownloading it again.
I don't know if there are any "virtual switches" turned off, can you guide me on this?

**Comment by geckolinux** [comment]
> I don't know if there are any "virtual switches" turned off, can you guide me on this?

Sure, try `rfkill list`

And here's an updated GeckoLinux *Rolling* Plasma ISO, based on Tumbleweed 20170129:
https://susestudio.com/download/f3c709242026a0067ff8707266af2088/GeckoLinux_ROLLING_Plasma.x86_64-999.170131.0.iso

**Comment by Pival81** [comment]
Downloaded and tried the latest iso, still nothing.
I also tried ```rfkill``` (```sudo rfkill list all```):
```
0: phy0: Wireless LAN
Soft blocked: no
Hard blocked: no
```

**Comment by geckolinux** [comment]
OK, thanks for confirming. Could you please open the terminal and run:

`nmtui` 

And try to activate a new WiFI connection via that. Thanks!

**Comment by Pival81** [comment]
Sorry, didn't have time to make a screen...
![img_20170131_233405](https://cloud.githubusercontent.com/assets/15673222/22487468/cabdce8e-e80d-11e6-83c5-208916c532b9.jpg)
Of course I also tried to create it instead of just activating, and it didnt work either.

**Comment by Pival81** [comment]
Ans this is the output of ```ip -a```:
![img_20170131_234438](https://cloud.githubusercontent.com/assets/15673222/22487843/5318d1ba-e80f-11e6-8aed-99bab8ff1e89.jpg)

**Comment by geckolinux** [comment]
Could you please boot the newest ISO and the older ISO that was working correctly and give me the following output?

`sudo lsmod > ~/Desktop/lsmod.txt`

Also the `dmesg` output from the working ISO would also be helpful.

Thanks for helping to troubleshoot this.

**Comment by Pival81** [comment]
I can give you only the dmesg and lsmod of the newest iso, since i would have to reflash the iso on the flash drive, and it's a quarter to 00:00 here in italy... 
Give a 5 min and I'll  edit  this post.

**Comment by geckolinux** [comment]
Sure, whatever you can do would be helpful.

**Comment by Pival81** [comment]
Here they are:
[dmesg.txt](https://github.com/geckolinux/geckolinux-project/files/743413/dmesg.txt)
[lsmod.txt](https://github.com/geckolinux/geckolinux-project/files/743414/lsmod.txt)

**Comment by geckolinux** [comment]
So the correct driver is getting loaded, and the WiFI device is being created. From what I can see, it could be a NetworkManager problem:
https://bbs.archlinux.org/viewtopic.php?id=210868

NetworkManager was upgraded from the version that worked for you to the version that no longer works for you. Could you please try manually downgrading NetworkManager by installing these two RPMs?

- ftp://ftp.icm.edu.pl/vol/rzm5/linux-opensuse/repositories/openSUSE:/Factory:/Staging:/I:/DVD/standard/x86_64/NetworkManager-1.4.2-2.5.x86_64.rpm\

You'll have to let in install it and break the dependencies for NetworkManager.

**Comment by geckolinux** [comment]
So the correct driver is getting loaded, and the WiFI device is being created. From what I can see, it could be a NetworkManager problem:
https://bbs.archlinux.org/viewtopic.php?id=210868

NetworkManager was upgraded from the version that worked for you to the version that no longer works for you. Could you please try manually downgrading NetworkManager by installing this RPM?

[ftp://ftp.icm.edu.pl/vol/rzm5/linux-opensuse/repositories/openSUSE:/Factory:/Staging:/I:/DVD/standard/x86_64/NetworkManager-1.4.2-2.5.x86_64.rpm](ftp://ftp.icm.edu.pl/vol/rzm5/linux-opensuse/repositories/openSUSE:/Factory:/Staging:/I:/DVD/standard/x86_64/NetworkManager-1.4.2-2.5.x86_64.rpm)

You'll have to install it and allow it to break the dependencies for NetworkManager.

**Comment by Pival81** [comment]
I just tried that, it didn't work
I even tried making that Krypton flash drive, but it just opens the grub.
So now I'm at a point where I can't boot to linux, since opensuse is the only distro I like now.
And here's the log from systemctl:
![img_20170201_154636](https://cloud.githubusercontent.com/assets/15673222/22511392/d81f499e-e895-11e6-8906-9dda83eece9d.jpg)

**Comment by geckolinux** [comment]
Could you please try installing GeckoLinux to see if your WiFI works correctly after installation?

**Comment by geckolinux** [comment]
Also could you please try the YaST Network Settings module? In the "Overview" tab what devices are displayed?

**Comment by Pival81** [comment]
Of course, putting the iso on the usb drive now.

**Comment by geckolinux** [comment]
Thanks for your helpful troubleshooting.

**Comment by Pival81** [comment]
Ok, so this appears right after i enter the Network Settings module in yast:
![img_20170201_171731](https://cloud.githubusercontent.com/assets/15673222/22515374/8c2c1d84-e8a2-11e6-87fc-dc2fff8c413d.jpg)
And these are the devices displayed:
![img_20170201_171756](https://cloud.githubusercontent.com/assets/15673222/22515414/adf01f88-e8a2-11e6-9aa1-10851567ef89.jpg)
Sorry for the photos, but making screenshots and uploading them is really a pain with this problem.

**Comment by geckolinux** [comment]
OK good. So it's definitely a NetworkManager problem.

Now in the "Global Options" tab change "Network Setup Method" to "Wicked Service". Hit OK. The YaST Tool will run a progress bar and then close. Then re-open it. Now on the wireless device hit the Edit button, set the Address type to Dynamic DHCP, Next, Operating Mode "Managed", and manually type in your WiFI network name (scan doesn't work for me), and set the authentication mode to WPA-PSK, and type in your WiFI network password as the encryption key. Then hit next and it should connect.

**Comment by Pival81** [comment]
No, still nothing.
But I think that it hasn't done anything, because after that the network manager applet was still there.
Now I'm trying to  have a temporary connection via tethering, but my cables don't seem to want to work.

**Comment by geckolinux** [comment]
Hmm, OK. Could you please try to install it to the hard disk to see if the WiFI works after installation?

**Comment by Pival81** [comment]
Ok, doing it now, i think that in a couple of minutes it'll be done.

**Comment by Pival81** [comment]
Max 10 mins

**Comment by geckolinux** [comment]
Good, please let me know how it works.

**Comment by Pival81** [comment]
Done, rebooting now

**Comment by Pival81** [comment]
No, still not working.

**Comment by geckolinux** [comment]
Could you please post this:

`sudo journalctl -u NetworkManager > ~/Desktop/journalctl.txt`

**Comment by Pival81** [comment]
here it is:
[journalctl.txt](https://github.com/geckolinux/geckolinux-project/files/745589/journalctl.txt)
Note that before creating this log i disabled (and stopped) networkmanager and enabled (and started) wicked manually, then i followed your previous instructions:

> "Now on the wireless device hit the Edit button, set the Address type to Dynamic DHCP, Next, Operating Mode "Managed", and manually type in your WiFI network name (scan doesn't work for me), and set the authentication mode to WPA-PSK, and type in your WiFI network password as the encryption key. "

But it still didn't work, so i reanebled networkmanager, rebooted, and made the log attached.

**Comment by geckolinux** [comment]
Hello again, please try editing the `/etc/NetworkManager/NetworkManager.conf` and adding the following:

```
[device]
wifi.scan-rand-mac-address=no
```

Then reboot the computer.

**Comment by geckolinux** [comment]
Also, what happens if you run:
`systemctl restart NetworkManager`

**Comment by geckolinux** [comment]
Also, what happens if you run:
`sudo systemctl restart NetworkManager`

**Comment by Pival81** [comment]
Just tried both, and nothing.
Ten minutes ago I kind of got it running  messing around with wicked, but it was displaying only one network, using the networkmanager plasma applet. Don't know how it happened.
Unfortunately I have to give up on GeckoLinux, because I need a working linux system as soon as possible now, sorry.
I hope i will be able to return to Gecko when this will be resolved.

**Comment by geckolinux** [comment]
I don't think it's a GeckoLinux specific issue. It would be good to post a bug report to the openSUSE [bugtracker](https://bugzilla.opensuse.org/index.cgi)

Also, could you please try a non-rolling version of GeckoLinux, based on Leap 42.2?
http://geckolinux.github.io/#download-static

Or, you could download the old version of GeckoLinux that was working for you:
https://sourceforge.net/projects/geckolinux/files/Rolling/999.161218/

**Comment by geckolinux** [comment]
Also, one last thing to check. I found these two bits of information, which appear to describe your problem:

- https://bbs.archlinux.org/viewtopic.php?pid=1298584#p1298584
- https://wiki.archlinux.org/index.php/NetworkManager#Unable_to_connect_to_visible_European_wireless_networks

Could you please try installing these two packages, in this order:

1. http://download.opensuse.org/repositories/openSUSE:/Factory/standard/noarch/wireless-regdb-2016.06.10-1.1.noarch.rpm
1. http://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/crda-3.18-2.4.x86_64.rpm

**Comment by geckolinux** [comment]
Also, one last thing to check. I found these two bits of information, which appear to describe your problem:

- https://bbs.archlinux.org/viewtopic.php?pid=1298584#p1298584
- https://wiki.archlinux.org/index.php/NetworkManager#Unable_to_connect_to_visible_European_wireless_networks

Could you please try installing these two packages, in this order:

1. http://download.opensuse.org/repositories/openSUSE:/Factory/standard/noarch/wireless-regdb-2016.06.10-1.1.noarch.rpm
1. http://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/crda-3.18-2.4.x86_64.rpm

Then reboot the computer.

**Comment by Pival81** [comment]
That worked!! Thank you so much!!!
I think you should include those two packages in your builds.

**Comment by geckolinux** [comment]
Ah, it was the regulatory domain thing that fixed it?

**Comment by geckolinux** [comment]
Ah, it was the regulatory domain thing that fixed it? Did you have to configure the `/etc/conf.d/wireless-regdom` settings at all?

**Comment by Pival81** [comment]
No, i didn't even have that file on my system.
Just installing those packages fixed everything.

**Comment by geckolinux** [comment]
Fantastic, thanks a lot for your persistence. And thanks for helping me identify this missing package, which I never would have found on my own.

In the next couple of days I will release updated ISOs with CRDA support.
