### ISSUE TITLE
Optimise usage on slow usb pen drives

### ISSUE THREAD

**Issue by Ygarr** [geckolinux/geckolinux-project#330]
Is there some options(e.g. for GRUB) to use OS more in RAM, copy to RAM, with less usage disk access writing?
Or even option  to sync manually to write changes to disk?

**Comment by geckolinux** [comment]
Hi there,

you can completely disable the USB persistence partition with this GRUB option:
`kiwi_hybridpersistent=no`

I also found this for creating a RAM disk, please report back whether it works for you:
`rd.kiwi.ramdisk ramdisk_size=2048000`

**Comment by Ygarr** [comment]
Seems no effect.(with the exception of disabling persistent, it works definitely )
Also tried in sysctl.conf
vm.swappiness = 0
vm.dirty_background_ratio = 20
vm.dirty_expire_centisecs = 0
vm.dirty_ratio = 80
vm.dirty_writeback_centisecs = 6000.
 At least nothing became worse

**Comment by geckolinux** [comment]
Hmm, at least disabling the persistence partition should definitely work. Please try removing `rd.live.overlay.persistent` from the default GRUB options.

**Comment by Ygarr** [comment]
I'm also confident that disabling persistent will help as well. But this is an extreme case, if you understand
