### ISSUE TITLE
Switchboard closes (crash?) when accessing universal access

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#332]
Is it because I have removed screen limits plugin and its backend through yast? 
Running Tumbleweed. Have not updated the system.

**Comment by geckolinux** [comment]
Not sure, please try running it from a terminal and post the output here. Also please test the same operation from a live USB to see if it behaves the same on a fresh system.

**Comment by ghost** [comment]
How may I run it from the terminal?

**Comment by geckolinux** [comment]
First I'd appreciate it if you could try it with the live USB system again to eliminate the possibility that it was from some modification you made.

**Comment by geckolinux** [comment]
Looks like it needs the `switchboard-plug-a11y` package, please install that if needed. I'll include it in the next GeckoLinux release. Thanks for reporting!

**Comment by ghost** [comment]
switchboard-plug-a11y is already installed. I will try it from a live usb tomorrow since this has nothing to do with the problem

**Comment by geckolinux** [comment]
Sorry, I meant to put `wingpanel-indicator-a11y` , please install that package to resolve the problem.

**Comment by geckolinux** [comment]
Reopening so I remember to include the missing package in the next ISO refresh.
