### ISSUE TITLE
[Firmware Bug]: TSC_DEADLINE disabled due to Errata; please update microcode to version: 0x52 (or later)

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#333]
Pantheon Tumbleweed
Core i3 Haswell
Which package do i have to upgrade to fix it?

**Comment by geckolinux** [comment]
Hi there, are you experiencing any missing functionality or lack of hardware support?

**Comment by ghost** [comment]
Wow that was such a quick reply. Open source/hobbyist devs are so devoted!
I'm not sure. Even hardware acceleration seems to be working. However the maximize and multitasking animations are a tad slow n jittery.

**Comment by ghost** [comment]
I have just noticed that some other animations are a bit slow too. Might be a spec limitation. I tried my best to make do with 4G ram with low swappiness, less startup scripts and services etc. Otherwise performance is perfect.

**Comment by geckolinux** [comment]
Please try updating the system with `sudo zypper dup`, that will install any missing firmware packages for your hardware.

**Comment by ghost** [comment]
I tried it but unfortunately the error still persists.

**Comment by geckolinux** [comment]
It's probably just an inconsequential kernel warning, they're very common.
