### ISSUE TITLE
Unable to turn off dyslexia friendly text Pantheon Rolling

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#334]
Installed infinality. Rebooted. Turned it on. Turned off however the change would not take place
![Screenshot from 2022-01-16 22 59 35](https://user-images.githubusercontent.com/95931540/149673347-98438ab4-834c-446c-b19d-0654b1592abe.png)
?

**Comment by geckolinux** [comment]
Hi there, Infinality is not supported or recommended anymore for openSUSE or GeckoLinux.
With that said, after disabling the dyslexia font please go into the Tweak utility and change the fonts there to whatever you want.

**Comment by ghost** [comment]
Can you recommend me an alternative that is supported? It really makes the fonts look smooth and more legible to read.

**Comment by geckolinux** [comment]
The GeckoLinux defaults are optimized for legibility out-of-the-box.
