### ISSUE TITLE
Language installer does not work

### ISSUE THREAD

**Issue by filip2cz** [geckolinux/geckolinux-project#335]
I can't install Czech language via language installer. I also set it up in the cinnamon settings, but it don't work.

I tried this: https://github.com/geckolinux/geckolinux-project/wiki#how-to-install-non-english-languages , but still nothing.

**Comment by filip2cz** [comment]
It already works, I had to enable UTF-8 in yats language settings.

**Comment by geckolinux** [comment]
Hello, did you follow these instructions?
https://github.com/geckolinux/geckolinux-project/wiki#how-to-install-non-english-languages

**Comment by filip2cz** [comment]
> Hello, did you follow these instructions?
> https://github.com/geckolinux/geckolinux-project/wiki#how-to-install-non-english-languages

I wrote that yes and later I also wrote what the problem was and how to solve it ...
