### ISSUE TITLE
Quirky bug with Pantheon's Alt-tab switcher

### ISSUE THREAD

**Issue by edo0** [geckolinux/geckolinux-project#336]
First of all, thank you very much for the work you are doing with GeckoLinux, and if you believe this should be addressed by another dev in another repo, please let me know and I'll do so.

On my newly (this morning) installed GeckoLinux Rolling-OBS Pantheon, I have noticed a bug, thereby the Alt-tab switcher misses the accent color to highlight the currently selected tab.

![image](https://user-images.githubusercontent.com/16632292/149812976-9c830023-af86-4cd9-9c90-94438edd8c7d.png)

Interestingly, going to the Settings > Desktop > Appearance, and switching the Style, the indicator will come back, and persist after you click again on the original Style.

![image](https://user-images.githubusercontent.com/16632292/149813372-94041544-60fa-4f08-ad7e-cbce14c956b2.png)

This unfortunately gets lost once you reboot, and you need to use the same trick to get back the shaded indicator.
Thank you in advance reading so far, and I hope the solution may be more trivial than what it looks like to a novice as myself!

**Comment by geckolinux** [comment]
Hi there, thanks a lot for the informative bug report. It looks like the fix would be non-trivial as you suspected.
@awissu is the guy behind the Pantheon packages for openSUSE. It might be helpful if you could confirm if this bug exists in Elementary (I doubt it, but it's worth checking).

**Comment by geckolinux** [comment]
I also wonder if it makes any difference if you make sure that the accent color and the actual GTK theme are set to the same color:
![Screenshot from 2022-01-18 10-24-01](https://user-images.githubusercontent.com/2692138/149966341-1347232c-6b58-4758-aa83-642d352ede05.png)
![Screenshot from 2022-01-18 10-24-28](https://user-images.githubusercontent.com/2692138/149966353-3c7b6aa4-cc6b-4a8b-bfd8-a7c68aa8f8c9.png)

**Comment by edo0** [comment]
Hi!
I have checked, and as expected on elementary this issue does not present itself.

Accent colour and theme were consistent as well - except for plank which has only the orange stylesheet theme, dark and light respectively, for eOS theming (though unrelated to the issue, I believe)

**Comment by geckolinux** [comment]
Please consider contacting @awissu (also [awissu](https://build.opensuse.org/users/awissu) on OBS), as GeckoLinux does not create or maintain any packages, so this sort of bug is outside the scope of the project. Thanks.
