### ISSUE TITLE
Wingpanel crashes and closes when clicking volume indicator.

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#337]
It does not happen just when the system is freshly booted. It reopens when accessing the application menu from hotkey or hot corner but the problem still persists. I have confirmed that this happens from the system monitor. I have also uninstalled many of the stock elementary apps like audience and added status icons

**Comment by ghost** [comment]
Fixed. Turns out I needed to install elementary-videos.

**Comment by geckolinux** [comment]
Hi there, `elementary-videos` is installed by default in GeckoLinux Pantheon editions.
