### ISSUE TITLE
Plank theme not respecting accent color

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#338]
I have tried reinstalling all stock elementary os plank themes, however the plank seems to only use elementary os cocoa for its accent color. I tried manually switching themes in plank's configuration menu but the only thing that changes is the background color

**Comment by geckolinux** [comment]
Possibly related:
https://github.com/geckolinux/geckolinux-project/issues/336#issuecomment-1015521562

Also please play around with the theming preferences in Plank (Ctrl+RightClick > Preferences) and let me know if anything works for you. Thanks!

**Comment by edo0** [comment]
![image](https://user-images.githubusercontent.com/16632292/149973652-99176e7b-aa92-43e6-b3c6-80faf7fd44a7.png)

As I was mentioning in the other bug, I also have only one choice of theme for Plank, though the only things changing are for the (orange) Light vs (orange) Dark theme, as no splash of colour is involved. So at the end of the day it seems to only look funky in the naming

![image](https://user-images.githubusercontent.com/16632292/149974138-d6213df2-1b81-4026-84fb-3c1b966f869f.png)
 
![image](https://user-images.githubusercontent.com/16632292/149974284-0378a1b3-04b7-4a54-91c9-f027551c9682.png)

**Comment by geckolinux** [comment]
@edo0 Thanks for the reply. It looks like you're using Adwaita for your main GTK theme?

**Comment by ghost** [comment]
@geckolinux As I have stated I have already done that. The only thing that changes is the background color

**Comment by edo0** [comment]
> @edo0 Thanks for the reply. It looks like you're using Adwaita for your main GTK theme?

@geckolinux  I use elementary's default theme, with blueberry accent

![image](https://user-images.githubusercontent.com/16632292/149976317-0a489b86-84cf-4078-9945-ccf5c217118e.png)
![image](https://user-images.githubusercontent.com/16632292/149976509-6e9e8f78-847c-4d18-ab57-b8bd41dad32d.png)

**Comment by ghost** [comment]
@geckolinux As I have stated I have already configured plank from its settings. The accent color still remains the same.

**Comment by geckolinux** [comment]
Please consider contacting @awissu (also [awissu](https://build.opensuse.org/users/awissu) on OBS), as GeckoLinux does not create or maintain any packages, so this sort of bug is outside the scope of the project. Thanks.
