### ISSUE TITLE
Elementary Appcenter not working

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#339]
It only fetches updates as Operating System Updates. I have tried multiple versions of the package but to no avail. It just displays categories.
![Screenshot from 2022-01-19 14 31 40](https://user-images.githubusercontent.com/95931540/150103041-51d2a94c-bc1e-42be-b276-c4523e926596.png)
![Screenshot from 2022-01-19 14 31 34](https://user-images.githubusercontent.com/95931540/150103055-0a2a3c7f-8f2d-466f-9834-fcb95065e124.png)
![Screenshot from 2022-01-19 14 31 29](https://user-images.githubusercontent.com/95931540/150103066-00976037-8f99-48c0-8c27-355a891f58f2.png)

**Comment by geckolinux** [comment]
The Elementary app center is not supported in openSUSE or GeckoLinux.

**Comment by ghost** [comment]
Is it still possible to get it to work?

**Comment by geckolinux** [comment]
You can try, but I highly doubt that it has the connectors that would be needed to interface with the Elementary app center servers. There's no need for it either in the case of openSUSE, which already has the YaST Software manager, and in the repositories incuded with GeckoLinux Pantheon some of the apps from the Elementary app center are available too.
