### ISSUE TITLE
KDE Rolling, QEMU VM - Mouse is rendered in top left corner always (nouveau)

### ISSUE THREAD

**Issue by polarathene** [geckolinux/geckolinux-project#34]
**UPDATE:** Appears to be an upstream issue, closing.

---

Wanted to try GeckoLinux out with my paravirtualized VM, I'm running the VM within QEMU/KVM with my NVIDIA 1070 GPU attached. It boots and loads nouveau as the driver, I was displayed a login screen and used `linux` as the password(any reason this isn't autologged in like other live media?). 

The mouse from the login manager and after was shown in the top left corner of the display. I moved it down to the bottom right to interact with the task bar, the rendering of the cursor remained at the top left but I noticed mouse over effects and clicked to bring up the app launcher. Tried to switch TTY and back as I've seen this fix a similar issue on my laptop, no luck.

Tried to avoid nouveau and use `nomodeset`/`nouveau.modeset=0` as a boot parameter, this leads to a blank screen.. There seems to be some messages about virtualbox modules, so I'm guessing perhaps some VM detection was done and loaded those assuming virtualbox was the hypervisor. I added a config to my VM to avoid hypervisor detection. This didn't seem to help avoid that, it only seemed to lead to booting into a blackscreen when not using `nomodeset` as well instead of getting to the login manager. Regardless of approach switching to another TTY starts to log the following over and over:

```
audit: type=1400 audit(1486610740.515:60): apparmor="DENIED" operation="open" info="Failed name lookup -disconnected path" error=-13 profile="syslog-ng" name="usr/share/syslog-ng/include/scl" pid=6587 comm="syslog-ng" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
vboxguest: PCI device not found, probably running on physical hardware.
```

They're both repeated twice in a row I've just omitted the extra repetition. The virtualbox service appears to have loaded that time.

There is also prior to this `[Failed] Failed to start LSB: VirtualBox Linux Additions kernel modules.` and a similar error for failing to start the VBox additions service.

---

I'm going to assume that GeckoLinux was working otherwise fine beyond the cursor issue which may be due to nouveau, if I could boot into non-free drivers like with Manjaro this might work like expected. Manjaro also has trouble unlike other distros with this VM. With Manjaro unless I use the non-free drivers with my UEFI VM it will refuse to boot properly. On BIOS VM it fails to use any of the graphic virtual drivers(Cirrus, VGA, Virtio) with VNC, it will boot with `xdriver` set to `vesa` however. `vesa` is only available as fallback for BIOS not UEFI, this requires EFIFB I think instead.

I'm going to try this setup with openSUSE and see if it's the same problematic experience in which case hopefully upstream can fix it :)

**Comment by polarathene** [comment]
Tested with live Tumbleweed image(Krypton) and same problem. How do I let the right people know about this so it can be fixed? The non live image installer that comes with Leap seemed to work fine with the mouse working, haven't installed to see how it reacts when booting into the system afterwards however.

**Comment by geckolinux** [comment]
Thanks for differentiating between GeckoLinux and upstream issues, that's a big help.

I'm no expert on this, but I agree with Reddit /u/Vogtinator that it would be best to uninstall all the `xf86-video-*` packages and revert to the built-in Xorg modesetting driver.
