### ISSUE TITLE
Unable to install dependency for elementary apps

### ISSUE THREAD

**Issue by amethylghostling** [geckolinux/geckolinux-project#340]
![p](https://user-images.githubusercontent.com/95931540/150171205-0d9e24f6-3be1-4c87-a002-718db59f2b87.png)
This error appears for many other elementary apps and it I ignore the dependency the apps dont work

**Comment by ghost** [comment]
The error is
nothing provides 'libgranite.so.5()(64bit)' needed by the to be installed tomato-2.0.2-1.47.x86_64
 Solution 1: do not install tomato-2.0.2-1.47.x86_64
 Solution 2: break tomato-2.0.2-1.47.x86_64 by ignoring some of its dependencies

**Comment by geckolinux** [comment]
Hi, is this with GeckoLinux _Rolling_ or _Static_?

**Comment by ghost** [comment]
Rolling

**Comment by geckolinux** [comment]
GeckoLinux doesn't create its own packages, rather the Pantheon environment comes from these two openSUSE sources:

- https://build.opensuse.org/project/show/X11:Pantheon:Branch
- https://build.opensuse.org/project/show/X11:Pantheon:Apps

There you can see that there are about 2 dozen apps for Pantheon that currently aren't compiling for Tumbleweed. If you're sure that there isn't a better mainstream option and you really need a specific Pantheon/Elementary app then you can contact the packager that maintains the package (check the `.changes` file in OBS to see who last updated it) and request him to update the packages. Most likely the packager will be @awissu (also [awissu](https://build.opensuse.org/users/awissu) on OBS).
