### ISSUE TITLE
Pantheon DE - New windows will not open in the foreground 

### ISSUE THREAD

**Issue by edo0** [geckolinux/geckolinux-project#342]
Step to reproduce:
- Boot system
- Everything works perfectly, windows are opened in the foreground and focused
- After a while, starting an app or opening a new window will lead to it being opened in the background and not focused

Please refer to the video below.

https://user-images.githubusercontent.com/16632292/150230040-3b89d8e3-cc4b-44bb-b06c-6f4a1d2edcee.mp4

In the past days I have tried to find a rationale, but failed to find any.
I have been mostly using terminal app, file manager, and PDF viewer when the behaviour appears, so nothing special that I can think of.
I would be grateful if you had any advice on how this could be best troubleshot. Thanks in advance!

**Comment by geckolinux** [comment]
Hi there, thanks for the report. So once it starts misbehaving does it do it constantly from then on? Any relationship to specific applications?

**Comment by ghost** [comment]
When opened over a maximized window apps like System Settings, Appeditor, gnome disks, clapper(video player), pantheon-mail, firefox dev open in background even if maximized. After using show desktop most of them work normally for a while. Windows that do not support maximize are pre focused like normal. As far as I can see it has no relation with certain applications though. They all take turns to misbehave.

**Comment by geckolinux** [comment]
Ok, thanks to both of you for confirming. Please confirm if the bug also exists in Elementary and file a bug report with the appropriate upstream project.

**Comment by edo0** [comment]
@geckolinux I can confirm that windows keep on misbehaving, and I am not completely sure of what triggers the behaviour (maximizing / full-screening an app, or just staying logged in for a while).

However, I cannot revert the behaviour by using the “Show Desktop” applet on the dock, @amethylghostling could you please explain to me how your temporary fix works and is performed? Thank you in advance!

**Comment by ghost** [comment]
I just toggle show desktop and any new windows that I open are already focused for me.
