### ISSUE TITLE
EDGE TILING NOT WORKING ON ANY TYPE OF WINDOW AT ALL !!!! Pantheon Rolling

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#343]
![Screenshot from 2022-01-21 01-10-13](https://user-images.githubusercontent.com/95931540/150414372-97432494-387c-4805-9eec-504a7a633473.png)
Even though it is turned on. No window would snap at resize at an edge.

**Comment by geckolinux** [comment]
![Screenshot from 2022-01-20 17-30-51](https://user-images.githubusercontent.com/2692138/150432629-4c95cc2c-9799-4a92-9046-7708fcd9360b.png)

Works fine for me. Maybe you're trying to snap a window that doesn't support resizing?

**Comment by ghost** [comment]
![Screenshot from 2022-01-21 15-42-43](https://user-images.githubusercontent.com/95931540/150515295-faaf777b-c79d-40f2-89aa-5ce8439ddfb4.png)
![Screenshot from 2022-01-21 15-46-05](https://user-images.githubusercontent.com/95931540/150515309-4542f85e-e63d-4327-a96b-8957dbec339b.png)
![Screenshot from 2022-01-21 15-46-17](https://user-images.githubusercontent.com/95931540/150515317-6c300a98-b896-427e-87fc-fc9b9d26bdbe.png)
![Screenshot from 2022-01-21 15-46-41](https://user-images.githubusercontent.com/95931540/150515331-d4c9e6f5-4e65-45d8-b259-cc51416c7c3c.png)
![Screenshot from 2022-01-21 15-46-44](https://user-images.githubusercontent.com/95931540/150515334-f77fcf8e-4078-4b88-b90e-cafc6423a3a0.png)
![Screenshot from 2022-01-21 15-46-49](https://user-images.githubusercontent.com/95931540/150515342-31318d97-fc17-41e9-8229-07a4793cbd86.png)
![Screenshot from 2022-01-21 15-46-56](https://user-images.githubusercontent.com/95931540/150515347-937f6b85-d8a6-4336-9e9d-da5f7a64c396.png)
![Screenshot from 2022-01-21 15-46-59](https://user-images.githubusercontent.com/95931540/150515349-0fdcd914-7db6-4ab1-9bac-9dde69ef59bb.png)

**Comment by geckolinux** [comment]
Hi there, are you using this on real hardware or a virtual machine? It's possible that some virtual managers might not work with that feature. Also try creating a new user account and test edge tiling/snapping with the default GeckoLinux settings.

**Comment by ghost** [comment]
Real Hardware

**Comment by geckolinux** [comment]
OK, please try this:

> Also try creating a new user account and test edge tiling/snapping with the default GeckoLinux settings.

**Comment by geckolinux** [comment]
And also please try this:
`gsettings set org.opensuse.pantheon.wrap.gnome.mutter edge-tiling true`

**Comment by ghost** [comment]
It does in the new user even though it follows default settings.

**Comment by geckolinux** [comment]
Sorry I didn't get that, say it again?

**Comment by ghost** [comment]
> And also please try this: `gsettings set org.opensuse.pantheon.wrap.gnome.mutter edge-tiling true`

no luck

**Comment by ghost** [comment]
> Sorry I didn't get that, say it again?

Edge tiling and snapping do not work even in the new user account even though it uses gecko linux's defaults

**Comment by geckolinux** [comment]
Ok thanks for confirming that. So that would seem to indicate that some package that you either added or removed from the system is breaking that functionality. Please test with the [latest ISO](https://sourceforge.net/projects/geckolinux/files/Rolling/999.220115/GeckoLinux_ROLLING-OBS_Pantheon.x86_64-999.220115.0.iso/download) to confirm that.

**Comment by ghost** [comment]
Dear Sir, I have a very slow and limited mobile broadband connection. I know that it is not be justifiable but  would you please be kind enough to perhaps just point to which package I may have to install to fix this ? Thank you Sir in advance but if you could do me this favour.

**Comment by geckolinux** [comment]
Hi there, I honestly don't know which one it is, my apologies. So in that case why not test with the original ISO that you downloaded?

**Comment by ghost** [comment]
It seems to work perfectly in the original live ISO environment.

**Comment by geckolinux** [comment]
Thanks for confirming that. So it's definitely an issue with a package having been added or removed. I would recommend that you start by using YaST Software in the original live ISO and search for packages that contain `elementary` or `pantheon`. Make note of which ones are installed and not installed. Then try to make your installed system the same.

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/95931540/150548839-1842646a-2fba-40f7-ac1e-d4de479730b0.mp4

It works with the keyboard but not the mouse.

**Comment by geckolinux** [comment]
Thanks for confirming that. So it's definitely an issue with a package having been added or removed. I would recommend that you start by using YaST Software in the original live ISO and search for packages that contain `elementary` or `pantheon` in the name. Make note of which ones are installed and not installed. Then try to make your installed system the same.

**Comment by geckolinux** [comment]
If it's easier for you the original package list can also be found here:
https://sourceforge.net/projects/geckolinux/files/Rolling/999.220115/GeckoLinux_ROLLING-OBS_Pantheon.x86_64-999.220115.0.packages/download

**Comment by ghost** [comment]
How do I select the fastest opensuse mirror? My package installations fail due to timeout as my mirror is unusable and slow.

**Comment by geckolinux** [comment]
Please confirm that the openSUSE repository URLs are for `mirrorcache.opensuse.org` and not `download.opensuse.org`.

**Comment by ghost** [comment]
All are. How can I select the fastest mirror for me in Pakistan.

**Comment by geckolinux** [comment]
The `mirrorcache.opensuse.org` manager will automatically select the best one. Otherwise you can manually change the URLs to one of these:
https://mirrors.opensuse.org/

**Comment by ghost** [comment]
Should I change all the mirrors to mirrorcache.opensuse.org

**Comment by geckolinux** [comment]
> Should I change all the mirrors to mirrorcache.opensuse.org

Only the openSUSE repositories, as in the default GeckoLinux configuration. Or you can try changing them to `download.opensuse.org` (just that part, the rest of the URL needs to stay the same), but in my experience it is extremely unreliable. The mirrorcache manager can be slower but is more reliable and less likely to have timeout errors.

**Comment by ghost** [comment]
Its working, Thank you so very much. I have never felt that I have achieved something so badly in a long time. Much love.

**Comment by geckolinux** [comment]
Interesting, thanks for your effort. Could you share what fixed it?
