### ISSUE TITLE
HOW DO I SET A NON STANDARD WINDOW BUTTON LAYOUT

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#346]
![Screenshot from 2022-01-21 22-07-34](https://user-images.githubusercontent.com/95931540/150569713-45d62825-a74b-4eae-acd9-4c28b9827d51.png)
I m sorry for taking so much of your time for my own faults. If its acceptable to you, can you kindly tell me how I can replace the close button with minimize and maximize button with minimize without altering their locations? I have tried to add these layouts for mutter and gala. However I could not get anything to change at all, let alone get my custom layout. For troubleshooting I uninstalled pantheon tweaks.

**Comment by geckolinux** [comment]
I would definitely recommend that you re-install Pantheon Tweaks and play around with these settings:

![Screenshot from 2022-01-21 13-06-40](https://user-images.githubusercontent.com/2692138/150579932-748eb582-11b8-4a45-9df2-fcdf876f6fc4.png)

**Comment by ghost** [comment]
I have it installed. It does not have this layout. 
I want there to be a minimize button at extreme left and maximize button at extreme right with no close button

**Comment by geckolinux** [comment]
With these dconf changes you can achieve that for some type of windows, but not all will obey:

![Screenshot from 2022-01-21 14-03-22](https://user-images.githubusercontent.com/2692138/150585195-00ae25ad-0ffd-4ea7-adff-6fa78a62cdcf.png)
