### ISSUE TITLE
Notejot blank window

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#347]
![Screenshot from 2022-01-21 22-52-13](https://user-images.githubusercontent.com/95931540/150577051-a3606e08-1b14-4648-b0c9-d6ff531f4008.png)
This is its window

**Comment by geckolinux** [comment]
Please consider contacting @awissu (also [awissu](https://build.opensuse.org/users/awissu) on OBS), as GeckoLinux does not create or maintain any packages, so this sort of bug is outside the scope of the project. Thanks.
