### ISSUE TITLE
Nemo Open as Root

### ISSUE THREAD

**Issue by PCTLC157** [geckolinux/geckolinux-project#350]
While using Gecko Linux in Virtualbox live environment only and two other real hardware installs I noticed that Nemo (Open As Root) took a lot longer than normal to open, I'm very familiar with the Nemo File Manager and found that this was unusual behaviour. 
VirtualBox was on a Intel NUC Skull Canyon i7-6770HQ 32GB Memory VBox was using 8GB Memory, Real Hardware, Toshiba P50T -A i7-4700MQ GeForce GT745M 8GB Memory & i5-3330 Radeon HD 7750 4GB Memory.

**Comment by ghost** [comment]
I have the same problem in Gecko Rolling.
Pkexec nemo opens fast though even though I have a dual core HDD system

https://user-images.githubusercontent.com/95931540/173342732-4ccbe91e-3f13-451b-986c-7abf69cc8874.mp4

**Comment by geckolinux** [comment]
Unfortunately I can't reproduce this problem on my system. Please try debugging it as follows:

`nemo --debug` and navigate to `/usr/share/pixmaps` and then "Open as root".

**Comment by geckolinux** [comment]
Thanks, and can you tell at which line does it hang?

**Comment by ghost** [comment]
> Thanks, and can you tell at which line does it hang?

>>(nemo:8082): Gtk-WARNING **: 15:43:16.109: Theme parsing error: gtk.css:9228:21: Not using units is deprecated. Assuming 'px'.
ERROR SET META:15 Setting attribute metadata::nemo-icon-view-auto-layout not supported

**Comment by geckolinux** [comment]
Please try again in the latest GeckoLinux release. Thanks!
