### ISSUE TITLE
Problem in latest Rolling MATE distro

### ISSUE THREAD

**Issue by StudioArena** [geckolinux/geckolinux-project#353]
I recently installed GeckoLinux_ROLLING_Mate.x86_64-999.220115.0.iso  Now I am unable to load Base Development package in YAST (patterns-devel-base-devel_base).  Gives all kinds of errors .. zlib missing, etc. etc.  This was working fine in previous Rolling MATE.  Without Base Development package, it is impossible to do any programming in C++, Ada, etc.  Has anyone else had this problem?  Is there any fix other than totally reinstalling?

**Comment by geckolinux** [comment]
Hi, did you update your installation first with `zypper dup`?

**Comment by StudioArena** [comment]
Yes, I did that right after I installed (about a week ago), and twice since then.  Does not help.

**Comment by geckolinux** [comment]
Could you please post the exact errors?

**Comment by StudioArena** [comment]
#### YaST2 conflicts list - generated 2022-02-07 10:11:08 ####

the to be installed patterns-devel-base-devel_basis-20170319-9.8.x86_64 requires 'zlib-devel', but this requirement cannot be provided
not installable providers: zlib-devel-1.2.11-18.19.i586[Tumbleweed_OSS]
                   zlib-devel-1.2.11-18.19.x86_64[Tumbleweed_OSS]
    [ ] break patterns-devel-base-devel_basis-20170319-9.8.x86_64 by ignoring some of its dependencies

    [ ] do not install patterns-devel-base-devel_basis-20170319-9.8.x86_64

    [ ] deinstallation of libz-ng-compat1-2.0.5-1.3.x86_64


#### YaST2 conflicts list END ###

Then I tried to install z-lib-devel and got similar errors.  I hate to have to reinstall Rolling MATE because I did a lot of work afterward, like adding Vivaldi browser, setting up firewall, setting up my printer/scanner, etc.  All this will be washed away if I have to go back and reinstall.

**Comment by geckolinux** [comment]
Yep, re-installing is usually not the solution, because you'll have the same situation after re-installing and updating from the same package sources with the same dependencies. In this case, it looks like you simply need to take the 2nd option it offers you for: `deinstallation of libz-ng-compat1-2.0.5-1.3.x86_64`.
