### ISSUE TITLE
keyboard is not working properly in tty

### ISSUE THREAD

**Issue by filip2cz** [geckolinux/geckolinux-project#359]
I have czech keyboard and I can't write special characters like & (on czech keyboard it is right-alt + c) or @ (right-alt + v) on tty.
I can't write any character which is alt + every letter or number, alt + special character button (like - . , ' | ...) works.

**Comment by geckolinux** [comment]
Hi there, we would need more information about what version of GeckoLinux you are using.

**Comment by filip2cz** [comment]
> Hi there, we would need more information about what version of GeckoLinux you are using.

I have latest Rolling with Cinnamon

**Comment by geckolinux** [comment]
Hi there, please use the YaST Keyboard module to set the correct keyboard layout, you might have to reboot after that. Also if needed you can set the keyboard layout for your user account and/or add additional keyboard layouts in the Cinnamon Settings **Keyboard** module under the **Layouts** tab.

**Comment by filip2cz** [comment]
> Hi there, please use the YaST Keyboard module to set the correct keyboard layout, you might have to reboot after that. Also if needed you can set the keyboard layout for your user account and/or add additional keyboard layouts in the Cinnamon Settings **Keyboard** module under the **Layouts** tab.

I tried, nothing changed.

**Comment by geckolinux** [comment]
Please post screenshots of your `YaST Keyboard` and Cinnamon Settings `Keyboard` configuration.

**Comment by filip2cz** [comment]
> Please post screenshots of your `YaST Keyboard` and Cinnamon Settings `Keyboard` configuration.

In YaST keyboard I confirmed Czech again and it works now. Thanks for your help

**Comment by geckolinux** [comment]
Glad you figured it out, thanks for confirming.
