### ISSUE TITLE
Calamares & encrypted LVM

### ISSUE THREAD

**Issue by temporarium** [geckolinux/geckolinux-project#36]
I'm finding (is it just me?) that the Calamares installer has issues with LUKS encrypted LVM partitioning. It simply crashes out of the installation process. No such issues with the OpenSUSE installer.

**Comment by geckolinux** [comment]
It does appear to have problems in some cases, I'm not sure if it's 
happening for everyone though. I opened a bug report for a similar issue 
here:
https://calamares.io/bugs/browse/CAL-454
If you could post at least your /root/.cache/Calamares/Calamares.log 
file it would be helpful. Thanks!

**Comment by temporarium** [comment]
I just tried again, with same result. Log attached:
[Calamares.log.txt](https://github.com/geckolinux/geckolinux-project/files/788363/Calamares.log.txt)

Any chance we could have the original openSUSE installer instead of Calamares? IMHO, it's more robust/stable...

**Comment by temporarium** [comment]
Any chance we could have the original openSUSE installer instead of Calamares? IMHO, it's more robust/stable...

**Comment by geckolinux** [comment]
Hello, the openSUSE installer is also available as "Live Installer" in YaST.

**Comment by temporarium** [comment]
I'm using GeckoLinux_XFCE.x86_64-422.161228.0.iso and I don't have it. Only Online Update. Was it just added to the more recent 422 images?

**Comment by geckolinux** [comment]
That's correct, it was added from this release onwards:
https://groups.google.com/forum/#!topic/geckolinux-updates/4pWN5ZV7qZM

**Comment by geckolinux** [comment]
There are supposed to be some fixes in the underlying library that Calamares uses, and it specifically mentions LVM. Mind giving the current version of GeckoLinux another try? Thanks.

**Comment by temporarium** [comment]
OK. I did. I dowloaded the GeckoLinux_ROLLING_XFCE.x86_64-999.170302.0.iso and tried installing an encrypted LVM via Calamares. Same error.

Frankly, I'm wondering why have Calamares as the default installer, when the Live Installer works great and seems more comprehensive and complete (even checks the strength of the passwords)...

I like GeckoLinux, but IMHO Calamares almost steered me away at first attempt...

**Comment by geckolinux** [comment]
Thanks for testing. I'll forward your report to the Calamares developers.

> Frankly, I'm wondering why have Calamares as the default installer, when the Live Installer works great and seems more comprehensive and complete (even checks the strength of the passwords)...

The `yast2-live-installer` has been completely jettisoned by openSUSE, and the developers don't want to touch it. Eventually it will stop working completely as upstream openSUSE continues to evolve. So Calamares is the way forward.

**Comment by geckolinux** [comment]
BTW this time did you try creating a new LVM or use an existing one?

**Comment by temporarium** [comment]
That's disappointing about the Live Installer. I hope Calamares "catches" up.

As to your question, I always start fresh (VM). Maybe I'm doing something not quite right??? But, it works smoothly in the Live Installer...

**Comment by geckolinux** [comment]
>  I hope Calamares "catches" up.

I think it will, it's progressing fast.

Thanks for the bug reports, and I'll let you know if the developers specifically address this bug again, if you don't mind testing a future release for me?

**Comment by temporarium** [comment]
I just found this: https://github.com/calamares/calamares/wiki/LUKS-Deployment

Are all the necessary dependencies included in the live images for GeckoLinux?

**Comment by geckolinux** [comment]
Yep, all the dependencies are pre-installed. I did notice a Calamares 
setting that appears to be incorrect for openSUSE, but I believe the 
problem would upon (trying to) boot the installed system, not during the 
installation stage. At any rate, could you please detail exactly what 
steps you are performing up until Calamares crashes/errors out on you? 
That will help me experiment a bit on my own in a VM. Thanks.

**Comment by temporarium** [comment]
I'm attaching a few snapshots. What I'm trying to achieve is an extended partition that's LUKS-encrypted and that holds the partitions you can see. The only way I can get encryption to work under Calamares is with one monolithic partition being set up by the installer on the whole disk, or by providing a password for each separate partition, which would mean entering the password numerous times on boot.

![sshot-1](https://cloud.githubusercontent.com/assets/4754345/23593504/e0930136-01dd-11e7-8f7a-a812baedb861.jpg)
![sshot-2](https://cloud.githubusercontent.com/assets/4754345/23593508/e0a338f8-01dd-11e7-847f-4d47cabe1d62.jpg)
![sshot-3](https://cloud.githubusercontent.com/assets/4754345/23593505/e09685cc-01dd-11e7-823f-dc2e59c071ee.jpg)
![sshot-4](https://cloud.githubusercontent.com/assets/4754345/23593507/e09ec822-01dd-11e7-94ed-fb832906c2f3.jpg)
![sshot-5](https://cloud.githubusercontent.com/assets/4754345/23593506/e09aebbc-01dd-11e7-8d3d-9f70d41f9691.jpg)

**Comment by temporarium** [comment]
Any news/developments?
I just saw this: https://sparkylinux.org/forum/index.php?topic=3843.0
