### ISSUE TITLE
Deepin desktop version?

### ISSUE THREAD

**Issue by RafaelLinux** [geckolinux/geckolinux-project#362]
Hi

I would like to have an opensuse gecko distro with Deepin, cause I use it Deepin distro but prefer openSUSE base ... I can't find nothing about it in this project .... what about this version?

**Comment by geckolinux** [comment]
Hi there, it's a possibility. The last time I tried Deepin for openSUSE it didn't work with LightDM, only with GDM, but that pulled in all of the Gnome desktop too. I'll give it another try sometime fairly soon.

**Comment by RafaelLinux** [comment]
Ok, I'll watch for news from time to time!!!

**Comment by GEPLinux** [comment]
https://software.opensuse.org/package/deepin-desktop

![image](https://user-images.githubusercontent.com/96615531/157046626-53404396-9248-499a-afef-d2da026bd8c1.png)

deepin-desktop.ymp works not so bad even brighntness modifcation for external display...

Except .... No Icons and not possible to change wallpaper 


Tested on Tumbleweed Gnome Edition

**Comment by RafaelLinux** [comment]
Yes, I saw that, but I would like a LIVE version, that's why I ask to GeckoLinux  :(

**Comment by Neocamelus** [comment]
> The last time I tried Deepin for openSUSE it didn't work with LightDM, only with GDM, but that pulled in all of the Gnome desktop too. I'll give it another try sometime fairly soon.

They have their own display manager and greeter, according to the Arch documentation: [Deepin Starting](https://wiki.archlinux.org/title/Deepin_Desktop_Environment#Starting)

Cf: [dde-session-ui](https://github.com/felixonmars/dde-session-ui/blob/master/README.md)

**Comment by geckolinux** [comment]
Hi there,

> They have their own display manager and greeter, according to the Arch documentation: [Deepin Starting](https://wiki.archlinux.org/title/Deepin_Desktop_Environment#Starting)

Hmm, not really, they use LightDM:
> Change the greeter for DDE's "lightdm-deepin-greeter"

It's just a visual theme change. There are also several other different "greeter" packages for LightDM, but the core functionality of them all is still handled by LightDM.

> Cf: [dde-session-ui](https://github.com/felixonmars/dde-session-ui/blob/master/README.md)

This is just a package for some core functionality within DDE.

**Comment by Mar0xy** [comment]
This would be interesting to see happen as I think deepin is a nice DE but there are still two things marked as broken in dbus and polkit features on the wiki(deepin-lock and managing users/network in control center) so I don't think this would happen anytime soon or will it?

**Comment by geckolinux** [comment]
Hi @Mar0xy , it seems to work fairly well with GDM, but that brings in the whole Gnome Shell session along with it. But for those who really want it you could either start with GeckoLinux Gnome or GeckoLinux BareBones and install Deepin.

I'll close this suggestion for now, but if there are any new developments feel free to post them here and I'll do the same.

Thanks to everyone!

**Comment by Mar0xy** [comment]
> it seems to work fairly well with GDM

Yes, I have seen that but I might try SDDM considering it is also listed as one that works besides GDM but thanks for hinting at GDM anyways :sweat_smile:

**Comment by geckolinux** [comment]
@Mar0xy Yes, SDDM might work too, but that in turn brings in the full set of dependencies for Plasma...

**Comment by Mar0xy** [comment]
@geckolinux which doesn't really matter in term since Deepin is based on KDE and deepin's pattern already installs Plasma dependencies. For example I just installed all deepin related patterns, then went and got sddm without sddm asking for extra dependencies

**Comment by geckolinux** [comment]
@Mar0xy Yep so that should work. I personally avoid patterns and just install the individual packages needed for a given desktop to function.

**Comment by Mar0xy** [comment]
Understandable, I personally had issues with just the desktop package so I tried the pattern which worked for me in the end.

Since deepin heavily relies on all it's apps
