### ISSUE TITLE
synaptics touchpad not working

### ISSUE THREAD

**Issue by Unixware** [geckolinux/geckolinux-project#365]
as on the title, def works with original leap 15.3 but now yours, check what you cooked there, it's not good idea to mess with the kernel sources.

**Comment by geckolinux** [comment]
Hi there, no idea what you're talking about. GeckoLinux does not compile any packages at all, it's an ISO assembled from completely unmodified openSUSE and Packman packages directly from those original repositories. Please install `xf86-input-synaptics` if you need it, GeckoLinux uses `xf86-input-libinput` by default.
