### ISSUE TITLE
How to configure beautiful fonts on linux?

### ISSUE THREAD

**Issue by ilyaigpetrov** [geckolinux/geckolinux-project#37]
Hi.
Could you, please, share some tips/links about how do you manage to
get so beautiful fonts in GeckoLinux (in browsers particularly), so we
could apply your experience to other Linux distributions, OpenSUSE or not.

Thanks,
Ilya.

**Comment by geckolinux** [comment]
Hi there, sorry for the slow reply.

Probably the most important trick is to use a good font that renders well,, such as the Ubuntu family. (DejaVu Sans is also good.) 

Then in the desktop font settings, use RGBA antialiasing with slight hinting. On a modern system, this will get you 90% there.

This can also help (remove the .TXT extension):
- `/etc/fonts/conf.d/`[10-rendering-options.conf.TXT](https://github.com/geckolinux/geckolinux-project/files/815568/10-rendering-options.conf.TXT)
- `/etc/fonts/conf.d/`[30-metric-aliases.conf.TXT](https://github.com/geckolinux/geckolinux-project/files/815570/30-metric-aliases.conf.TXT)
- `/etc/fonts/conf.d/`[58-family-prefer-local.conf.TXT](https://github.com/geckolinux/geckolinux-project/files/815572/58-family-prefer-local.conf.TXT)
- `/etc/sysconfig/`[fonts-config.TXT](https://github.com/geckolinux/geckolinux-project/files/815598/fonts-config.TXT)

This subheading is also possibly useful:
https://wiki.archlinux.org/index.php/font_configuration#Applications_without_fontconfig_support
