### ISSUE TITLE
Driver for TP Link tl-wn781nd (version 3) not preinstalled on All Static Releases

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#374]
The card (https://www.tp-link.com/pk/home-networking/pci-adapter/tl-wn781nd/)  works  on  the previous live environment of Pantheon rolling, however it won't work on any of the latest Static KDE and cinnamon releases before and after installation. The card itself is working fine. Which package should I install to get the driver for this model?

**Comment by geckolinux** [comment]
It's probably a driver that is included only in the much newer Tumbleweed kernel that the Rolling editions use. You can install a newer kernel for openSUSE Leap, but it's probably best to just use Tumbleweed if your hardware requires it.

**Comment by ghost** [comment]
The driver is included in OpenSuse Leap 15.4 but not in GeckoLinux Static. Please reopen this issue.

**Comment by geckolinux** [comment]
Is the driver included in openSUSE Leap 15.4 as a separate package or is it part of the updated Leap kernel?

**Comment by ghost** [comment]
> Is the driver included in openSUSE Leap 15.4 as a separate package or is it part of the updated Leap kernel?

[From the source code ](https://github.com/geckolinux/geckolinux-project/files/8934964/TL-WN781ND_V3_180409_linux.zip) I knew that I had to install every package with the word realtek & rtl in the name or description but it still would not work.

**Comment by geckolinux** [comment]
I believe it's a driver built into the kernel, so GeckoLinux Static will always be subject to the kernel and driver support that openSUSE Leap has.

**Comment by ghost** [comment]
> I believe it's a driver built into the kernel, so GeckoLinux Static will always be subject to the kernel and driver support that openSUSE Leap has.

Is Static release based on the live openSUSE ISO which lacks a lot of drivers and is only meant for trying the OS out?

**Comment by geckolinux** [comment]
> Is Static release based on the live openSUSE ISO which lacks a lot of drivers and is only meant for trying the OS out?

No, it's not based on the live openSUSE ISO.
The current GeckoLinux Static series was built from Leap 15.3 with its much older kernel at version 5.3 that does not support your WiFI. Once a set of new GeckoLinux Static ISOs are generated from Leap 15.4 with its newer kernel your WiFI should work. Or if you want it sooner, you can simply install GeckoLinux Static and then update the system to Leap 15.4 by following these instructions:
https://github.com/geckolinux/geckolinux-project/wiki#updating-geckolinux-static-to-a-major-new-opensuse-release

**Comment by ghost** [comment]
> > Is Static release based on the live openSUSE ISO which lacks a lot of drivers and is only meant for trying the OS out?
> 
> No, it's not based on the live openSUSE ISO. The current GeckoLinux Static series was built from Leap 15.3 with its much older kernel at version 5.3 that does not support your WiFI. Once a set of new GeckoLinux Static ISOs are generated from Leap 15.4 with its newer kernel your WiFi should work. Or if you want it sooner, you can simply install GeckoLinux Static and then update the system to Leap 15.4 by following these instructions: https://github.com/geckolinux/geckolinux-project/wiki#updating-geckolinux-static-to-a-major-new-opensuse-release

The reason I want to install the static version is to decrease the update size, have better tested packages & a more stable kernel. I'm having some problems with Cinnamon in Rolling. Is Cinnamon more bug-free in Static or Rolling. I would wager that the Tumbleweed version of Cinnamon is more stable because it is in the official repositories and therefore tested by the openQA team, whereas the Leap version of Cinnamon is community maintained and therefore not tested as thoroughly, meaning I will have way more bugs if I start using Static Cinnamon than what I am currently using.

**Comment by geckolinux** [comment]
> whereas the Leap version of Cinnamon is community maintained and therefore not tested as thoroughly

This is incorrect. Cinnamon is in the official Leap repositories and it goes through the same quality control processes as in Tumbleweed, although Cinnamon in not tested in openQA for Leap or for Tumbleweed.

**Comment by ghost** [comment]
> > whereas the Leap version of Cinnamon is community maintained and therefore not tested as thoroughly
> 
> This is incorrect. Cinnamon is in the official Leap repositories and it goes through the same quality control processes as in Tumbleweed, although Cinnamon in not tested in openQA for Leap or for Tumbleweed.

So the Cinnamon in static will have less bugs?

**Comment by geckolinux** [comment]
> So the Cinnamon in static will have less bugs?

I personally haven't experienced major bugs with Cinnamon in either of the two branches except for occasional random crashes of Cinnamon. There will always be edge cases, so generalizations don't really apply.

**Comment by ghost** [comment]
> > Is Static release based on the live openSUSE ISO which lacks a lot of drivers and is only meant for trying the OS out?
> 
> No, it's not based on the live openSUSE ISO. The current GeckoLinux Static series was built from Leap 15.3 with its much older kernel at version 5.3 that does not support your WiFI. Once a set of new GeckoLinux Static ISOs are generated from Leap 15.4 with its newer kernel your WiFI should work. Or if you want it sooner, you can simply install GeckoLinux Static and then update the system to Leap 15.4 by following these instructions: https://github.com/geckolinux/geckolinux-project/wiki#updating-geckolinux-static-to-a-major-new-opensuse-release

In how much time will the new version be released?

**Comment by geckolinux** [comment]
> In how much time will the new version be released?

No fixed timeframe, hopefully soon. The new update will have a very similar configuration to the current one, so you'll get basically the same thing by installing the 153.220104 release and then upgrading it.

**Comment by amethylghostling** [comment]
> > In how much time will the new version be released?
> 
> No fixed timeframe, hopefully soon. The new update will have a very similar configuration to the current one, so you'll get basically the same thing by installing the 153.220104 release and then upgrading it.

Within weeks or days?

**Comment by ghost** [comment]
>The current GeckoLinux Static series was built from Leap 15.3 with its much older kernel at version 5.3 that does not support your WiFI. Once a set of new GeckoLinux Static ISOs are generated from Leap 15.4 with its newer kernel your WiFI should work.

Since there is no official package of Cinnamon for Leap 15.4, only community package, When the official Cinnamon package from Leap 15.3 will be used in the next release which is based on Leap 15.4, won't there be issues with system dependencies.

**Comment by geckolinux** [comment]
@amethylghostling That's not correct. Cinnamon is in the main openSUSE Leap repositories for Leap 15.3 and 15.4.

**Comment by ghost** [comment]
> @amethylghostling That's not correct. Cinnamon is in the main openSUSE Leap repositories for Leap 15.3 and 15.4.

It says on http://software.opensuse.org that for Leap 15.4, only community packages are available.
![](https://user-images.githubusercontent.com/95931540/175353861-554e6d91-a3a2-4e22-8ec7-29af192573a8.png)

**Comment by geckolinux** [comment]
The software.opensuse.org results have been broken for Leap 15.3 and 15.4 for a long time, it's a known issue.

**Comment by ghost** [comment]
[I asked people that which DE had the least bugs on Leap.](https://www.reddit.com/r/openSUSE/comments/vgqtyr/which_desktop_breaks_the_least_and_is_the_most/?utm_medium=android_app&utm_source=share) Which one you reckon would be the most stable on Leap. Which one would you prefer?

**Comment by geckolinux** [comment]
I've had very good results with Cinnamon and XFCE on Leap.

**Comment by amethylghostling** [comment]
Will it take a week or two for the new release to be out or will it be out in some days?

**Comment by ghost** [comment]
> > In how much time will the new version be released?
> 
> No fixed timeframe, hopefully soon. The new update will have a very similar configuration to the current one, so you'll get basically the same thing by installing the 153.220104 release and then upgrading it.

Will it be out in a few weeks or days?

**Comment by ghost** [comment]
[People are saying that Cinnamon is not actively maintained for Leap.](https://www.reddit.com/r/openSUSE/comments/vk7mg1/leap_cinnamon_vs_kde/)
