### ISSUE TITLE
NO GTK4 app working on Rolling Cinnamon

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#378]
ie clapper
** (com.github.rafostar.Clapper:19207): WARNING **: 23:21:29.026: Failed to load shared library 'libgtk-4.so.1' referenced by the typelib: /lib64/libgtk-4.so.1: undefined symbol: hb_font_get_var_coords_design

(com.github.rafostar.Clapper:19207): Gjs-CRITICAL **: 23:21:29.026: JS ERROR: Error: Unsupported type void, deriving from fundamental void
_init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:20:5
@/usr/share/com.github.rafostar.Clapper/src/main.js:11:34
@/usr/bin/clapper:9:1

(com.github.rafostar.Clapper:19207): Gjs-CRITICAL **: 23:21:29.026: Script /usr/bin/clapper threw an exception
Same error for all apps.

**Comment by geckolinux** [comment]
Hi, do you have the `libgtk-4-1` package installed?

**Comment by ghost** [comment]
Yes

**Comment by geckolinux** [comment]
And is your system up to date?

**Comment by geckolinux** [comment]
This is from my personal system, also _ROLLING_ Cinnamon:
![Screenshot from 2022-04-04 21-36-17](https://user-images.githubusercontent.com/2692138/161668057-44797bea-59b4-4fa2-8f06-32890fcf99e4.png)
