### ISSUE TITLE
Gecko Plasma Rolling is not waking display from sleep; machine runs, screen is black, etc??

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#379]
@geckolinux 

So, as I posted in my other thread, in my Gecko Rolling Plasma edition I was having problems getting to the GUI, then I added "gdm" and was able to get into the GUI.  But, then the problem is on "waking" from sleep, the computer would spin up, but the display would not . . . .

This morning I added "lightdm" and reset the display manager, but the problem remains.  I believe that it was originally "sddm" but obviously at some point a "glitch" was introduced into the system rendering the GUI inoperable.

I'm in lightdm and Plasma right now, but I had to shut down using power button and cold boot to get the display functioning . . . .  I'm about out of ideas on it, maybe at some point I'll re-config back into sddm, but, basic function of "waking from sleep" is a needed component in any OS I use . . . ????

**Comment by geckolinux** [comment]
Thanks for the report. Yes, as far as I know SDDM is required for some functions in Plasma.

**Comment by esteelpaz** [comment]
@geckolinux 

Alrighty, appreciate the reply . . . I just had to again shut down after trying to revive using lightdm . . . .  So, when I get a chance I'll try to get sddm back online and see if I can get a GUI and then will it revive the display from sleep.  I'll post back when I get some data on it . . . maybe later today or tomorrow . . . .  Seems like gdm and lightdm aren't providing full service.  Question is, what happened previously when it would only boot to TTY?

**Comment by esteelpaz** [comment]
@geckolinux 

Alrighty, I switched back to sddm and on cold boot the GUI doesn't load again, so something seems "busted" in sddm??  There are "129" packages to upgrade right now, but I didn't see anything starting with "sddm" in the list.  I'm back in gdm right now, which gets me to a GUI log in, but then which doesn't revive the display from sleep.  Once the upgrade finishes I'm about done messing with it for the day.  I've added and changed to gdm to lightdm to sddm and then back to gdm . . . problems with any of those decisions, but the sddm stays in the TTY . . . .

**Comment by geckolinux** [comment]
There must be some local configuration that is breaking it. Tumbleweed is usually very stable in terms of booting and loading graphical components, and I haven't seen any openSUSE bug reports about it. Maybe try deleting or renaming anything in `/etc/sddm.conf.d` and/or `/etc/sddm.conf`. If there's still no luck please file an openSUSE bug report.
