### ISSUE TITLE
Strange RAM and swap size

### ISSUE THREAD

**Issue by theArianit** [geckolinux/geckolinux-project#381]
Checking the system monitor, it says that my machine has 16.7GB RAM and 17.2GB swap! My machine has actually 16GB RAM.
![Screenshot from 2022-04-16 13-23-21](https://user-images.githubusercontent.com/17601489/163686296-4680f2c6-f46b-4264-a3d8-063c359fecea.png)

Why is that so and how can I fix it to show the right numbers?

when I run free -m I get this resul:
                    total        used        free      shared  buff/cache   available
Mem:           15888        2172       11421         586        2294       12848
Swap:          16400           0       16400

and swapon -s:
Filename				      Type		Size		Used		Priority
/swap/swapfile                          file		524284		0		-2
/dev/zram0                              partition	4067412		0		100
/dev/zram1                              partition	4067412		0		100
/dev/zram2                              partition	4067412		0		100
/dev/zram3                              partition	4067412		0		100

**Comment by geckolinux** [comment]
Hi there, it looks like the 16.7GB of RAM is some sort of rounding error with the bytes --> GB conversion. As for the 17.2GB of swap, that's approximately correct, as the system uses zram swap by default and it creates about the same amount of maximum RAM swap space as your physical RAM. (It doesn't affect your actual available RAM, it just compresses items in the RAM if you start getting close to using all of your available physical RAM.)

**Comment by theArianit** [comment]
I thought it was something wrong with the numbers. In opensuse tw the swap size was 2 gigs, and somehow I thought I have seen the same number after installation of gecko. but if nothing is wrong then it's fine with me. thanks

**Comment by theArianit** [comment]
If I may add a question to this topic. I have read about this a bit and it seems like this is because of hibernation or for it. is that true? and how can I make use of hibernation, how can I enable it, or is it done automatically?

**Comment by geckolinux** [comment]
Hi, there's three kinds of swap:

- Physical swap partition on disk -- if hibernation is desired, the swap with hibernation option needs to be selected in Calamares during installation, and it will create a swap partition that is the same size as the amount of RAM.
- Swap file on disk -- This can also be selected during installation in Calamares, but it's not compatible with hibernation.
- Virtual compressed RAM swap (zRAM) -- This is dynamic and happens in RAM as needed, also not compatible with hibernation since the RAM gets wiped when powered off. GeckoLinux enables zRAM by default, vanilla openSUSE does not.

**Comment by theArianit** [comment]
so hibernation cannot be enabled in gecko?

**Comment by geckolinux** [comment]
> * Physical swap partition on disk -- if hibernation is desired, the swap with hibernation option needs to be selected in Calamares during installation, and it will create a swap partition that is the same size as the amount of RAM.

**Comment by theArianit** [comment]
I wish I knew this during installation. thank you for the clarification

**Comment by tuxayo** [comment]
> it just compresses items in the RAM if you start getting close to using all of your available physical RAM

Great, so it shouldn't be a perf issue for old CPUs? Unless most of the RAM is used which anyway would cause more perf issues than just compressing stuff.

**Comment by geckolinux** [comment]
Right, overall it's the best option, and definitely performs better than swapping to the disk. It's the same mechanism that Android devices have used for a long time now with their relatively limited RAM and CPU resources.
