### ISSUE TITLE
Trying to download Cinnamon Rolling but download speed very low for two days

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#387]
Tried multiple mirrors and download managers. Speed does not exceed 30 kb/s. On other websites I get upto 1.4 mb/s.
I think you should provide alternative download methods especially torrents since they have great download speeds and do not fail even if downloading stops.

**Comment by geckolinux** [comment]
Hi there, please try switching to a different Sourceforge mirror and/or use a multi-threaded download manager such as `aria2c`.

There also appear to be torrents here: https://linuxtracker.org/index.php?page=torrents&category=2214

**Comment by ghost** [comment]
Is this https://linuxtracker.org/index.php?page=torrent-details&id=6096318200bf404378939eaba91956f724f45230 the latest isos?

**Comment by geckolinux** [comment]
Hi there, the latest releases are always the ones in the links here:
http://geckolinux.github.io/#download

**Comment by ghost** [comment]
I tried using aria2c it failed
<pre>Download aborted. URI=https://sourceforge.net/projects/geckolinux/files/Rolling/999.220115/GeckoLinux_ROLLING_Cinnamon.x86_64-999.220115.0.iso/download
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://downloads.sourceforge.net/project/geckolinux/Rolling/999.220115/GeckoLinux_ROLLING_Cinnamon.x86_64-999.220115.0.iso?ts=gAAAAABif_iGzaXVVi4Ejqz47ljkiSL4oTklddikBGPKkCRJrua0I22q7BNbpRSvCwo7q6zet5WIkZ3mF3Ro0mOn76HyKfguCQ%3D%3D&amp;use_mirror=webwerks&amp;r=
  -&gt; [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure:  `not signed by known authorities or invalid&apos; `expired&apos;

05/14 23:44:28 [<font color="#4E9A06"><b>NOTICE</b></font>] Download GID#c469b8681ef2074d not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c469b8|<font color="#CC0000"><b>ERR</b></font> |       0B/s|https://sourceforge.net/projects/geckolinux/files/Rolling/999.220115/GeckoLinux_ROLLING_Cinnamon.x86_64-999.220115.0.iso/download

Status Legend:
(ERR):error occurred.
</pre>
Just how old is the torrent?

**Comment by geckolinux** [comment]
Hi again, you need to use the direct download link to your selected mirror, without hitting the bouncer. For example, copy the click the "Problems downloading?" button and then select a mirror:

![Screenshot from 2022-05-14 13-58-38](https://user-images.githubusercontent.com/2692138/168444956-fad95c78-da4f-44bf-a45c-5b021402724b.png)

Then let it start downloading with your web browser, but cancel the download and copy the direct link. Then it will work with `aria2c`, for example:

`aria2c -x10 https://razaoinfo.dl.sourceforge.net/project/geckolinux/Rolling/999.220115/GeckoLinux_ROLLING_Plasma.x86_64-999.220115.0.iso`

**Comment by ghost** [comment]
Still giving error:<pre>[<font color="#CC0000"><b>ERROR</b></font>] CUID#7 - Download aborted. URI=https://razaoinfo.dl.sourceforge.net/project/geckolinux/Rolling/999.220115/GeckoLinux_ROLLING_Plasma.x86_64-999.220115.0.iso
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://razaoinfo.dl.sourceforge.net/project/geckolinux/Rolling/999.220115/GeckoLinux_ROLLING_Plasma.x86_64-999.220115.0.iso
  -&gt; [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure:  `not signed by known authorities or invalid&apos; `expired&apos;

05/15 14:30:42 [<font color="#4E9A06"><b>NOTICE</b></font>] Download GID#47ca2f303ebcab5b not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
47ca2f|<font color="#CC0000"><b>ERR</b></font> |       0B/s|https://razaoinfo.dl.sourceforge.net/project/geckolinux/Rolling/999.220115/GeckoLinux_ROLLING_Plasma.x86_64-999.220115.0.iso

Status Legend:
(ERR):error occurred.
</pre>

**Comment by geckolinux** [comment]
It sounds like there are issues on the system you're using to download it, such as missing or outdated certificate packages. I just confirmed with the same `aria2c` command from the same Sourceforge mirror and I'm getting about 2MB/s with no errors.
