### ISSUE TITLE
Rolling Cinnamon: Unable to open GUI apps as root.

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#389]
I.e. sudo mousepad gives "(mousepad:6127): Gtk-WARNING **: 08:59:18.536: cannot open display:" pkexec mousepad works

**Comment by geckolinux** [comment]
Hello, this is by design in openSUSE:
https://www.suse.com/c/how-get-graphical-applications-working-sudo-sle-10/

Please use `gnomesu` to open GUI apps as root.

**Comment by ghost** [comment]
> Hello, this is by design in openSUSE: https://www.suse.com/c/how-get-graphical-applications-working-sudo-sle-10/

I wish to have my text editor always open files as root without asking a password (using sudo). Should I follow this guide so that I can run GUI apps using sudo. Will it have any negative repercussions?

**Comment by geckolinux** [comment]
Why not simply use "Open with..." and define a custom command of `gnomesu mousepad` ?
