### ISSUE TITLE
NetworkManager-wifi will be required on Tumbleweed to connect to wifi with NetworkManager

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#394]
Source: https://www.reddit.com/r/openSUSE/comments/ut2kh2/heads_up_tw_users_if_you_disabled_installing/

NetworkManager-wifi is (as of the time of opening this issue) only a recommended dependency of NetworkManager so it may cause issues on GeckoLinux, such as:
https://github.com/geckolinux/geckolinux-project/discussions/393

**Comment by geckolinux** [comment]
Thanks a lot for the heads-up, it will be added to the next set of ISOs.

**Comment by geckolinux** [comment]
The change was later reverted in Tumbleweed.
