### ISSUE TITLE
LiveDVD boot/run problems

### ISSUE THREAD

**Issue by fixer1234** [geckolinux/geckolinux-project#40]
I created a LiveDVD of the 42.2 Plasma stable version, downloaded 6/19/2017 (Hash verified).  I'm trying to install it on a plain vanilla, OTS Gateway desktop computer that's probably on the order of 5 years old.  The computer has no issues; currently multi-booting Win 7, Mint and Debian.  Debian is old-stable, long in the tooth, and I'm looking to replace it with Gecko.  The computer has plenty of hardware resources and nothing esoteric.

Booting normally from the LiveDVD is glitchy.  Several attempts worked for a few minutes, then ran into what appeared to be video issues--temporary screen blackouts coupled with freezing.  I tried running the Install to Disk several times.  One time it started to run, then simply disappeared as if I had never started it.  Another time, the system hung.

I tried the failsafe boot.  That has been hung in some kind of trial loop for several thousand iterations at this point.  The messages say:

[incrementing number]  Audit: type 1400 audit (incrementing number): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="usr/lib64/libsyslog-ng-3.8.so.0.0.0" pid=<incrementing number> comm="syslog-ng" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[incrementing number] vboxguest: PCI device not found, probably running on physical hardware.
(last line repeated with another incrementing number.)

I'm guessing it is trying to find a driver (maybe a video driver?), and the pid is product ID's it's testing.  At this point, though, the pid is past 24000, with no sign of giving up and using some default setting.  The video is run-of-the-mill ATI Radeon.

Is this a known bug or incompatibility (or the LiveDVD doesn't contain a needed proprietary driver)?  Is there a recommended solution?  I've been playing with 42.1 installed on a flash drive, booting that on a laptop.  At this point I'm just trying to install 42.2 on the desktop.

**Comment by geckolinux** [comment]
Hi there, it might be good to play around with some of the other F-key 
options listed at the bottom of the initial boot screen of the live DVD. 
Specifically the option to disable KMS sometimes is needed with Radeon 
hardware.

**Comment by fixer1234** [comment]
@geckolinux thanks for the response.  My brain isn't clicking on "KMS" (not enough coffee, yet).  I did try the function keys to change the video from auto to the specific resolution, and to change the default kernel setting to the safe setting.  Those didn't make a difference.  

Also, although the behavior suggests a driver problem, I did spot that apparmor appears to relate to security, in which case it isn't clear what's giving it indigestion.

Another thought: sometimes a LiveDVD runs into problems that a dedicated installation disk does not.  It doesn't look like Gecko has a non-live version.  Might there be a way to install openSUSE using their installation DVD, and then modify the installation with the Gecko DVD to turn it into Gecko?

**Comment by fixer1234** [comment]
@geckolinux Looks like it's some kind of driver or compatibility issue with either Gecko or openSUSE.  I've got Gecko 42.1 installed on a flash drive that I use with a laptop.  I tried booting from that on the desktop that's having problems.  It got as far as a stylized cursor on a black background and froze (never made it all the way into the session.
