### ISSUE TITLE
GeckoLinux Leap 15.4 Status Update

### ISSUE THREAD

**Issue by newinnov** [geckolinux/geckolinux-project#405]
Hi Gecko, 

Thanks again for your brilliantly tweaked Suse releases.
Any hope for next Leap Gnome 15.4 release? 
This release is quite exciting as Gnome 40+ is coming to stable release.

Regards,

**Comment by geckolinux** [comment]
Hi there, yes there definitely will be a GeckoLinux Static series generated for Leap 15.4. Meanwhile, I would recommend existing users to simply upgrade their systems to achieve the same result:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux
