### ISSUE TITLE
Provide More  Better download Alternatives like Torrents etc.

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#408]
I am trying downloading Gecko linux Rolling but Source forge doesnt start the download, i cleared cache, network reset etc. but no fix, source forge only allows download of Xfce Variant that to at a ugly speed of 20-50 KBPS, so you should provide more better ways to download isos.... 

![Screenshot_2022-07-04_16-01-52](https://user-images.githubusercontent.com/100503303/177137391-cf7edc31-6340-4252-a034-bb29723f544a.png)
![Screenshot_2022-07-04_16-03-28](https://user-images.githubusercontent.com/100503303/177137589-95eececc-f53d-45a6-bd4b-938055a7c01f.png)

**Comment by geckolinux** [comment]
Hi there, please switch to a different Sourceforge mirror and/or use a multi-threaded downloader such as `aria2`. By doing so I can saturate out my 50mbps connection.
