### ISSUE TITLE
New internet connection not accepted on ethernet but works on wifi??

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#409]
@geckolinux 

I just did an internet upgrade to FIOS at my place yesterday and on cold boot into Gecko rolling MATE install  FF fails to load any web sites??  I shut down and tried again and the internet applet shows "connected" but ethernet did not work??

I connected via wifi and ran something like "278" package upgrades, including the "broadcom -wl" . . . not sure what else.  After that I disconnected wifi and tried ethernet (no proxy) and still nothing?

I rebooted into OSX 10.13 and it connected w/o issue.  I booted into Linux Mint and also no problem???  Back into Gecko and again no "connection" even though applet says I am?  I checked Yast Network??? and it said, "Yast doesn't handle this, Network Manager is in charge."  I checked into FF "settings" and "network"  and it had "let system choose proxy"??  I changed it to "No proxy" but it didn't make a difference.

Any thoughts?  I'm running Deb Bookworm right now, no problems with the ethernet connection.  Seems like Gecko has not "adjusted" to the new ISP??? on ethernet, but does work on wifi??  This is for a desktop so I prefer to use ethernet, Gecko doesn't seem to want to do that for me???  : - 0

**Comment by geckolinux** [comment]
Hi there. Maybe try to delete the the ethernet connection in NetworkManager so that it reconfigures it from scratch.

If it still doesn't work, check the properties of the connection in NetworkManager to see if it's getting an IP address. Check if you can ping the router. Check if you can `ping google.com` , and if not, check if it works to `ping 8.8.8.8` (to check for DNS vs. connectivity issues).

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks for the reply and suggestions . . . I'll check on it in a bit.  Since I posted I booted up original SUSE TW and had no issues with ethernet, but again today in Gecko rolling MATE when I booted it on the gdm3 login window upper right there was the "internet" applet and it had a question mark over it.  Logging in the Network Manager applet spun for 30-40 seconds, then stopped, then spun again and connected to the wifi . . . .

I didn't know about deleting the ethernet option, usually it is the wifi that gets messed up with upgrades or changes.  It is showing an IP address and all of the other numbers, and it shows itself as "connected" . . . but it doesn't actually "connect."  Before I posted this thread I did check "ping google.com" and that did not "work."

Same thing when I ran "zypper ref" . . . it kept erroring out on it.  I'll post back when I've had a chance to figure out how to delete an ethernet connection . . . and I'll try the 8888 option as well.

I have a couple other Gecko installs in the machine that I'll try to boot and see if it is all of them or just the one that has this problem.  They are all "rolling" Geckos, but different DEs . . . .

**Comment by esteelpaz** [comment]
@geckolinux 

So, just for the info, rebooted into Gecko rolling Plasma in the same machine, also using I believe gdm3 and there no question mark over the applet and logging in and launching browser . . . operational.

So, I have one other Gecko install to check, but right now seems like it's the first Gecko install that isn't clicking on ethernet.

**Comment by esteelpaz** [comment]
@geckolinux 

OK, nope, Gecko Mate is not rallying on the ethernet connection front.  I deleted the old one, "created" a new one.  It shows IP address and what IPv4 number, but actually not working.  Had to flip to wifi to get to post this.  

With ethernet ping google.com brings error, but ping 8.8.8.8  shows data:

`ping google.com
ping: google.com: Temporary failure in name resolution
n1@n1:~> ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=5.13 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=117 time=5.46 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=117 time=4.93 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=117 time=5.33 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=117 time=5.36 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=117 time=5.21 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=117 time=5.03 ms
64 bytes from 8.8.8.8: icmp_seq=8 ttl=117 time=5.31 ms
64 bytes from 8.8.8.8: icmp_seq=9 ttl=117 time=5.23 ms
64 bytes from 8.8.8.8: icmp_seq=10 ttl=117 time=5.23 m`

**Comment by geckolinux** [comment]
Hi again, thanks for testing. Could you please post the results of these commands?

`ip a`

`cat /etc/resolv.conf`

**Comment by esteelpaz** [comment]
@geckolinux 

``````

`:~> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wls5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a8:96:8a:f1:df:17 brd ff:ff:ff:ff:ff:ff
    altname wlp13s0
    inet 192.168.4.25/22 brd 192.168.7.255 scope global dynamic noprefixroute wls5
       valid_lft 14338sec preferred_lft 14338sec
    inet6 fd92:b072:9d6d:1:620d:4ca2:2694:be9a/64 scope global temporary dynamic 
       valid_lft 604735sec preferred_lft 85938sec
    inet6 fd92:b072:9d6d:1:8002:8f81:d30e:fd27/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591935sec preferred_lft 604735sec
    inet6 fe80::b635:8568:4c78:271f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp9s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 00:3e:e1:b7:89:f2 brd ff:ff:ff:ff:ff:ff
4: enp10s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:3e:e1:b7:8a:de brd ff:ff:ff:ff:ff:ff
    inet 192.168.254.123/24 brd 192.168.254.255 scope global dynamic noprefixroute enp10s0
       valid_lft 14278sec preferred_lft 14278sec
    inet6 fe80::6ff:85d:d3a4:41f1/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
nonspace1@nonspace1:~> cat /etc/resolv.conf
### /etc/resolv.conf file autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
# Note: Manual change of this file disables netconfig too, but
# may get lost when this file contains comments or empty lines
# only, the netconfig settings are same with settings in this
# file and in case of a "netconfig update -f" call.
#
### Please remove (at least) this line when you modify the file!
search home
nameserver 192.168.1.1
`

**Comment by esteelpaz** [comment]
@geckolinux 

???  Don't know why those lines had strikethrough and the others had large bold text??

**Comment by geckolinux** [comment]
OK, let's try disabling IPv6 for the ethernet connection:
![Screenshot from 2022-07-17 13-13-59](https://user-images.githubusercontent.com/2692138/179419283-50757b27-e4c4-4cb8-90b4-9b98ecdfeef7.png)

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks for the suggestion, made that adjustment . . . logged out and back in, didn't get ethernet working.  Rebooted and back in, same problem.  I had no problem with ethernet in the Gecko Plasma install, and the IPv6 settings were the same, "automatic."

I'm now typing this in wifi connection.  It's kind of odd, no?  usually it's the wifi that gets wonky . . . .   Just about everybody else in the machine is finding ethernet.  Here, in Gecko MATE it shows it is "connected," . . . but, it isn't.

Might set IPv6 back to "auto" and see what happens the next time I boot it up??

**Comment by geckolinux** [comment]
It appears that your machine has two ethernet ports, are you sure you're plugged into the correct one?

**Comment by esteelpaz** [comment]
@geckolinux 

Yes, it does have two eth ports . . . but nothing changed on the machine side, other than switching to new router/modem.  Here, "we" deleted the ethernet connection and then "created" a new name for it . . . .

But, otherwise I didn't change anything on the machine, the ethernet was plugged into the same port as before, etc.  And, th eissue seems exclusive to the one Gecko system, but the other one w/ Plasma DE is not "confused" and gets it done.

I'm not sure, as I'm away from that machine, whether now the Network is showing just one ethernet option, since we deleted ethernet and then I only added one back in???

Perhaps I could try to plug into the other port and see if that "auto-fills"???  I don't recall in years of fiddling with linux there was ever a time where the system couldn't connect to direct wired connection . . . .

**Comment by geckolinux** [comment]
Well, it's not that it doesn't have a connection, but your testing shows that it doesn't have working DNS resolution. That's why you can ping Google's IP address but not its `google.com` domain. The problem appears to be that the ethernet is getting an IP address of ` inet 192.168.254.123` but your `/etc/resolv.conf` is showing that it expects `nameserver 192.168.1.1` which is in a different subnet. (I imagine that was the IP of your old router.) You might want to try deleting  `/etc/resolv.conf` so that it gets regenerated.

**Comment by esteelpaz** [comment]
@geckolinux 

OK, that sounds reasonable.  Is that something that I can run in console with "sudo zypper rm /etc/resolv.conf"  or will I have to be logged in as root with "# zypper rm /etc/resolv.conf"???

Or navi into /etc  and trash the file via GUI???

**Comment by geckolinux** [comment]
`sudo rm /etc/resolv.conf`

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks kindly, I'll post back when I've tried that out . . . finger's crossed, etc.

**Comment by geckolinux** [comment]
BTW you'll also need to reboot it after performing that step.

**Comment by esteelpaz** [comment]
@geckolinux 

Thanks . . . did more or less "figure" that would be needed to get it to re-shuffle . . . . .  : - ))))

**Comment by esteelpaz** [comment]
@geckolinux 

Looks like deleting that file did the trick, thanks very kindly for the help on it. Still a bit "odd" that this was the only system that didn't "auto-correct" on the change.  I often have "stuff" happen in my Debian Sid install, like yesterday I couldn't get it to boot, but today it booted cleanly and ethernet was fine.  

Data now shows matching IP numbers, but also has that suggested `Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
search home`  line toward the end??  Would that be the quick n dirty way to handle this, if there is a next time???

````
cat /etc/resolv.conf
### /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
### autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
### Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
search home
nameserver 192.168.254.254

**Comment by geckolinux** [comment]
Hi there, really glad to hear it's solved.

> suggested `Call "netconfig update -f" to force adjusting of /etc/resolv.conf`  search home line toward the end?? Would that be the quick n dirty way to handle this, if there is a next time

Good question. For the initial resolution I suggested deleting `/etc/resolv.conf` because it started off as a static file in older versions of Tumbleweed (which I believe you have installed). But then a few years ago they changed it to a symlink as mentioned in the comments now: `/etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf` . So I suspect this was a one-time glitch due to that transition. It shouldn't happen again, but if it does then you could follow the `netconfig update -f` suggestion.

**Comment by esteelpaz** [comment]
Cool.  I guess that might be the issue, the Gecko MATE install is the oldest, first Gecko install that I ran.

See you when I "see" you . . . next time.
