### ISSUE TITLE
Need Help, WiFi not working 

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#410]
Hey i am in gecko leap on my laptop, have realtek wifi, i first tried connecting but there was no wifi option available, so from yast software, i searched reltek and downloaded two files they are -
rtl8812au-kmp-default
rtl8812au
they both are drivers for wifi but installing them didint resolve my issues, Please help...

**Comment by geckolinux** [comment]
Hi there, a few things come to mind:
- Did you reboot after installing the driver packages?
- Did you make sure that you installed the right package for your specific WiFI model? Especially in the case of Realtek there are quite a few different models with different drivers.
- Did you [update](https://github.com/geckolinux/geckolinux-project/wiki#updates-to-geckolinux-static-within-the-same-major-opensuse-version) the entire installation? The driver is compiled for a specific kernel version, and if you're still on the original kernel version that came with the last GeckoLinux Static release it won't be compatible.

**Comment by ghost** [comment]
Yes I rebooted several times, I also updated to 15.4 but no results, and when I search realtek only this driver is available I mean no other package is shown, please help regarding finding relevant drivers, the device recommended downloading realtek-kernel-firm I did but no results.

**Comment by geckolinux** [comment]
Hi again. Please try the `lspci -vv` command and look through the output to determine the exact model of the WiFI device.

**Comment by CapeCrusader321** [comment]
The command isnt available

**Comment by ghost** [comment]
Done, the model is RTL8723BE PCIe Wireless Network Adapter, how to get all needed files and drivers...

**Comment by geckolinux** [comment]
Unfortunately you will generally be in for a world of hurt with Realtek WiFI, even under Windows, and it's worse still under Linux.

Let's see what drivers it's automatically trying load for that card, if any:
`sudo lsmod | grep rtl`

**Comment by ghost** [comment]
btrtl                  28672  1 btusb
bluetooth             700416  43 btrtl,btintel,btbcm,bnep,btusb,rfcomm
This is the output that the command gave...

**Comment by geckolinux** [comment]
OK, thanks, so from what I've read it looks like those drivers should already be included in more recent kernels, but apparently not in the version that Leap 15.4 has. You might want to try GeckoLinux Rolling to see if that makes any difference, and if not also try the latest openSUSE Tumbleweed live ISO. (If the Tumbleweed ISO works with your WiFI but the GeckoLinux Rolling doesn't, it would simply be a matter of installing GeckoLinux Rolling and then updating the installed system.)

**Comment by ghost** [comment]
Ok, Thanks for taking out your time to help me, i will try rolling edition, i had once tried it but the experience was a nightmare, retryying it.
