### ISSUE TITLE
preinstall flatpak & add flathub by default

### ISSUE THREAD

**Issue by soredake** [geckolinux/geckolinux-project#411]
spirallinux is doing this by default, so i though, maybe geckolinux can do this too?

**Comment by geckolinux** [comment]
Unfortunately no, I only find Flatpaks to be useful for normal users with a graphical manager like Gnome Software or KDE Discover, and both of those require PackageKit, which causes major conflicts with the underlying `zypper` package manager.

**Comment by soredake** [comment]
I don't use opensuse myself, but i think discover with packagekit can be used now:
https://www.reddit.com/r/openSUSE/comments/qc8bf6/tumbleweed_can_gnome_software_kde_discover_etc/
https://www.reddit.com/r/openSUSE/comments/qdy84z/tumbleweed_does_packagekit_become_unreliable_if/

![изображение](https://user-images.githubusercontent.com/5204968/179478314-7d1703af-f42e-401f-b417-22abf66ba510.png)

**Comment by geckolinux** [comment]
Be that as it may, it's still an unmaintained disaster, at least on openSUSE. Even if it doesn't break the system, it still frequently gets in the way of `zypper` by locking the package database and preventing it from running:
https://www.reddit.com/r/openSUSE/comments/n3v2ie/this_is_why_i_dont_use_packagekit_gnome_software/

**Comment by geckolinux** [comment]
I should also mention that I don't see any need to load GeckoLinux with poorly designed software given that better alternatives exist in openSUSE's OBS. It's almost always preferable to use native RPM packages on openSUSE, and a ton more can be found on the openSUSE OBS. There's really tons of good software in OBS. There are even semi-official openSUSE repos like Hardware and ProAudio and Graphics and Mozilla that allow for some applications to roll along on the newest version while still using a Leap/Static base. And lots of proprietary software producers for Linux offer RPMs. So it's simply not necessary to include bad software in GeckoLinux, as users can usually easily find what they need in the form of RPM and/or RPM repositories and graphically manage them with YaST.
