### ISSUE TITLE
Migrate to opensuse Tumbleweed after install?

### ISSUE THREAD

**Issue by danielyrovas** [geckolinux/geckolinux-project#412]
Hello,
I am having issues with the opensuse installer on my laptop (the menus aren't rendering correctly) so I was wondering if I could use the Gecko Linux installer and then migrate upstream to opensuse?
From the information I can see it doesn't look like there would actually be any difference to opensuse after install except the default configuration/installed packages? Would there be anything to do other than remove the google/skype repos?
My desktop uses an Nvidia GPU, would I be better off using the Gecko installer for that as well?
Thanks for your work on this!

**Comment by geckolinux** [comment]
Hi there, thanks for the question. GeckoLinux isn't a derivative of openSUSE, it _is_ openSUSE with a different default configuration and a different installer. It has no repositories specific to GeckoLinux, and it uses the exact same repositories and infrastructure for openSUSE. So basically if it works well for you then you would simply continue to use it. After installation you would update the Rolling version according to these instructions:
https://github.com/geckolinux/geckolinux-project/wiki#updating-geckolinux-rolling

BTW, the Google and Skype repos are enabled out-of-the-box, but nothing is pre-installed from them.

The Nvidia repository is also enabled out-of-the-box, but there are never any guarantees when it comes to Nvidia drivers and Tumbleweed. Here are the instructions, which you can start following after the step of adding the repository, which is already done for you by default in GeckoLinux:
https://en.opensuse.org/SDB:NVIDIA_drivers#YaST_2

Hope it works well for you!
