### ISSUE TITLE
Wayland is here bro.

### ISSUE THREAD

**Issue by concatime** [geckolinux/geckolinux-project#42]
Time for new stacks.
Hi. I love geckoLinux (using it right now), and think it's time for some changes.
Could-you add an i3 based on sway/wayland/weston without lightDM, XOrg and Xinit. I meen, first, is that at least possible? Fedora and [OpenSUSE](https://www.reddit.com/r/openSUSE/comments/5j44q5/gnome_on_wayland_in_tumbleweed_works/dbddn74) made the firsts step for Gnome.

**Comment by geckolinux** [comment]
Hi there, thanks for the suggestion. It would have to be a community edition, as I have zero experience with i3 and almost no practical experience with Wayland. However I do know that at the moment, none of the YaST modules and neither of the two installers for GeckoLinux will run under Wayland.
