### ISSUE TITLE
Bogus BOINC version

### ISSUE THREAD

**Issue by RolandHughes** [geckolinux/geckolinux-project#424]
After following the trail of tears in various OpenSuSE forum posts to get BOINC both installed and running on GeckoLinux, there were no projects listed to add. Spend several hours this morning tracking this down. It appears both Gecko and OpenSuSE don't actually test BOINC.

https://boinc.n-helix.com/forum_thread.php?id=14650

You can read the full thread if you want or just focus on this snippet.

=====
That will be a version chosen by the Ubuntu package maintainers - but they got it wrong.

BOINC certified a version called 7.18.1 for use on Android only around 3 August 2021, and that code hasn't been touched since. There is still no sign even of preparation work for any newer release that might become v7.20.x for the major desktop platforms, even though it was promised in 'around two months' - three months ago.

=====

You have 7.18.1 in your repos.

This machine only runs BOINC so it looks like I have to install Manjaro. Just wanted to give you a heads up on this major oopsie.

**Comment by geckolinux** [comment]
Thanks, GeckoLinux does not create or maintain any packages, so this is an upstream issue.
