### ISSUE TITLE
Gecko Linux not able to see virtual drive under Virt manager

### ISSUE THREAD

**Issue by Mirppc** [geckolinux/geckolinux-project#43]
I am testing out Gecko linux using Virtmanager under Leap 42.2 and for some reason the Calamares installer cannot see the virtual machine drive i set up.  Gparted within the iso can see it and was able to create a partition table and a partition but alas when i go to try an install it i get nothing in the option for drives and if i chose automatic, the installer crashes without any error.

I can see and manage the Virtual drive via YAST > Partition Manager just fine.

Here is a copy of the log.

http://paste.opensuse.org/34633383

Took me a few hours just to post that log as systemd decided to coredump on the live instance, firefox refused to do anything.  so i ended up having to kill the systemd coredum and firefox and do a zypper in susepaste, then manualy type the address into my browser on the workstation.  Then i had to reupload the past so it would not expire in an hour.  What a convoluted mess.

**Comment by geckolinux** [comment]
Hi, thanks for reporting this bug. I re-posted it over at the Calamares bug tracker:
https://github.com/calamares/calamares/issues/768

Meanwhile, you could try the yast2-live-installer, which is the alternate installer for GeckoLinux.
