### ISSUE TITLE
TW heads up - kernel firmware fails to install- hits Gecko Rolling as well

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#439]
@geckolinux 

I'm on the "factory" list-serve and saw some posts about this, in "LENOVO" so I didn't pay attention to it.  But, today I'm in Gecko Rolling MATE and hit the error.  Just giving you a heads up on it.  Haven't rebooted to see if there are any issues stemming from it.

Running zypper dup -l in a Gecko Rolling addition I hit this error in a list of "firmware" updates . . . .  I tried "retry" and that failed, then I tried "ignore" and it went through w/o error.  Haven't rebooted yet to see if any effects will hit.

[CODE]( 92/160) Installing: kernel-firmware-qlogic-20220930-1.1.noarch .........[done]
error: unpacking of archive failed on file /usr/lib/firmware/qcom/LENOVO/21BX;634045b4: cpio: File from package already exists as a directory in system
error: kernel-firmware-qcom-20220930-1.1.noarch: install failed
error: kernel-firmware-qcom-20220902-1.1.noarch: erase skipped
( 93/160) Installing: kernel-firmware-qcom-20220930-1.1.noarch ..........[error]
Installation of kernel-firmware-qcom-20220930-1.1.noarch failed:
Error: Subprocess failed. Error: RPM failed: Command exited with status 1.
Abort, retry, ignore? [a/r/i] (a): [/CODE]

**Comment by geckolinux** [comment]
Thanks for the heads-up. Sounds like a temporary upstream issue.
