### ISSUE TITLE
6.0 kernel seems to be "rough trade" upgrade in my MacPro??

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#442]
@geckolinux 

Just giving a head's up, over in Gecko Rolling Mate today and it showed "99" packages to upgrade, including the new 6.0 kernel . . . around "100" zypper flippedd into a huuuge number of depmod lines, many of them mentioning "nvidia," . . . I have an nvidia card, but not using proprietary driver . . . seemed to install it anyway . . . .  It's been like an hour in the process.

I had a problem with TW after upgrading to the 6.0 kernel as well, seemed to wipe grub menu out, having a hard time getting that back properly . . . .

I haven't seen the kind of depmod data that is showing up previously:

[CODE] Skipping BTF generation for /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-modeset.ko due to unavailability of vmlinux
  CC [M]  /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-peermem.mod.o
  LD [M]  /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-peermem.ko
  BTF [M] /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-peermem.ko
Skipping BTF generation for /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-peermem.ko due to unavailability of vmlinux
  CC [M]  /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-uvm.mod.o
  LD [M]  /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-uvm.ko
  BTF [M] /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-uvm.ko
Skipping BTF generation for /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia-uvm.ko due to unavailability of vmlinux
  CC [M]  /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia.mod.o
  LD [M]  /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia.ko
  BTF [M] /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia.ko
Skipping BTF generation for /usr/src/kernel-modules/nvidia-470.141.03-default/nvidia.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/linux-6.0.0-1-obj/x86_64/default'
make[1]: Leaving directory '/usr/src/linux-6.0.0-1'
ld  -T /usr/src/linux-obj/x86_64/default/scripts/module.lds -r -o nv-linux.o \
  nvidia.mod.o nvidia/nv-interface.o
/
/usr/src/kernel-modules/nvidia-470.141.03-default /
rm -f -r conftest
make[1]: Entering directory '/usr/src/linux-5.19.13-1'
make[2]: Entering directory '/usr/src/linux-5.19.13-1-obj/x86_64/default'
  CLEAN   /usr/src/kernel-modules/nvidia-470.141.03-default
  CLEAN   /usr/src/kernel-modules/nvidia-470.141.03-default/Module.symvers
make[2]: Leaving directory '/usr/src/linux-5.19.13-1-obj/x86_64/default'
make[1]: Leaving directory '/usr/src/linux-5.19.13-1'
/
Modprobe blacklist files have been created at /usr/lib/modprobe.d to prevent Nouveau from loading. This can be reverted by deleting /usr/lib/modprobe.d/nvidia-*.conf.
*** Reboot your computer and verify that the NVIDIA graphics driver can be loaded. ***
pbl: 2022-10-12 10:09:26 <3> pbl-4389 run_command.294: '/usr/lib/bootloader/grub2-efi/add-option nosimplefb=1' failed with exit code 2, output:
<<<<<<<<<<<<<<<<
/etc/default/grub: No such file or directory
>>>>>>>>>>>>>>>>
pbl: 2022-10-12 10:09:26 <3> pbl-4389 run_command.294: '/usr/lib/bootloader/grub2-efi/config' failed with exit code 1, output:
<<<<<<<<<<<<<<<<
grub2-mkconfig: command not found
>>>>>>>>>>>>>>>>
[/CODE]

Not sure if there is any more of a problem than I had with losing grub . . . just sayin' it seems like 6.0 is not "polished"???

**Comment by geckolinux** [comment]
Could be... That's an upstream issue unfortunately. Thanks for the heads-up.
