### ISSUE TITLE
[Kind Request] Make YaST in upcomming (?) KDE spin look consistent with the rest of the desktop

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#45]
@geckolinux Like Gecko a lot, especially the KDE spin. The only annoyance is YaST's look. Please make it consistent with the VDG guidelines (Breeze icons). If the equivalent Breeze icons don't exist, we should find a solution together. But I would like to know your opinion on the issue first.
***
I'm not gonna open a separate issue on this: please consider making StarkMenu default in your upcoming Cinnamon spin. Gecko is going to continue, I hope.

**Comment by geckolinux** [comment]
Hi there, I would love to theme YaST differently, but that would require upstream openSUSE changes, and is out of the scope of the GeckoLinux project.

**Comment by ghost** [comment]
Can you point me to the upstream developer(s), please?

**Comment by geckolinux** [comment]
Hi there, sure:
http://yast.opensuse.org/contributing
