### ISSUE TITLE
Installer won't load in rolling release Budgie live environment

### ISSUE THREAD

**Issue by techguy378** [geckolinux/geckolinux-project#46]
I downloaded the latest rolling release of Geckolinux as of November 12, 2017. After booting from my USB drive to the Budgie live environment I connected to my wifi network then double clicked on the Installer icon on the desktop. The mouse pointer changed from an arrow to a spinning wheel for about 30 seconds then changed back to an arrow and nothing happened. The installer did not load. Every time I clicked on the installer icon the same thing happened. I'm using a System76 laptop with a Skylake Intel Core i7-6700HQ processor (4 cores w/hyperthreading), 16GB RAM, Intel Wireless-AC 8260 wifi adapter and a 250GB Samsung EVO 850 SSD. My USB drive is a SanDisk Extreme 16GB USB 3.0 flash drive. I don't have any trouble installing other Linux distros such as OpenSUSE Tumbleweed with this laptop and flash drive.

**Comment by geckolinux** [comment]
Hi, thanks for reporting. I won't fix any bugs on the currently released versions of GeckoLinux, since newer releases are currently being worked on. Please stay tuned, as I hope to get to releasing them before too long.
