### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by Thaodan** [geckolinux/geckolinux-project#473]
Hey, I noticed a few packaging issues with this project. 

First of all package sources and binaries are dumped into archive files which are impossible to track.
Why don't you build them on the obs and track the sources here?

Same for the generated iso files why not attach them to an Github release?

**Comment by geckolinux** [comment]
Hi there,

> all package sources and binaries are dumped into archive files which are impossible to track

GeckoLinux does not create or modify any software packages with the exception of the Calamares installer that is only used in the installation ISO. So there is no "source code" to track. The ISO is built directly from unmodified openSUSE and Packman packages, and all security/feature updates for the installed system come directly from openSUSE and Packman.

The archives that I upload here to Github are simply a courtesy for users that want to inspect how the GeckoLinux ISOs are built and/or to use as base for their own custom spins. The "development" of GeckoLinux happens on my workstation where I tweak the Kiwi configuration, and then I build the ISOs in a cloud VPS and upload them from there to Sourceforge.

> Same for the generated iso files why not attach them to an Github release?

As far as I know Github would only allow those large ISOs to be attached if they were built on Github. As mentioned, Github is not used to develop or build GeckoLinux, it is simply a free and permanent zero-maintenance host for the website and issue tracker/forum.

**Comment by Thaodan** [comment]
GeckoLinux ***@***.***> writes:

> Hi there,
>
>> all package sources and binaries are dumped into archive files which are impossible to track
>
> GeckoLinux does not create or modify any software packages with the
> exception of the Calamares installer that is only used in the
> installation ISO. The ISO is built directly from unmodified openSUSE
> and Packman packages, and all security/feature updates for the
> installed system come directly from openSUSE and Packman.
>
> The archives that I upload here to Github are simply a courtesy for
> users that want to inspect how the GeckoLinux ISOs are built and/or to
> use as base for their own custom spins. The "development" of
> GeckoLinux happens on my workstation where I tweak the Kiwi
> configuration, and then I build the ISOs in a cloud VPS and upload
> them from there to Sourceforge.

Because you upload them in a zip archive it's hard to collaborate on
them anyone that want's to help would need to extract the archive, make
changes and upload a new archive.

I'm asking to upload the kiwi configuration and any files involved for
the image creation without them being in an archive file.

You should also be able to store the kiwi configuration on the obs and
generate the images through there.

>> Same for the generated iso files why not attach them to an Github release?
>
> As far as I know Github would only allow those large ISOs to be
> attached if they were built on Github.

That is not true. Yo can upload any file to a release, I build my
Sailfish OS Images in a very similar and upload them to a Github release.
