### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by andresimi** [geckolinux/geckolinux-project#48]
Hi, I installed Geckolinux NEXT and everything went fine, except for translations. Some KDE applications like doplhin, kate are in english, how do I get them to portuguese-br? On System configuration there is only english option. And on Yast, I could make terminal in portuguese.

thanks

**Comment by geckolinux** [comment]
Hello, did you run the GeckoLinux language installer script?

**Comment by andresimi** [comment]
No, I thought it should be runned after the installation. Is it possible to be run after the installation?

**Comment by geckolinux** [comment]
Hi, the language installer script needs to be run after the installation. Then use the YaST Language module to change the system language, and then reboot.

**Comment by andresimi** [comment]
I tried this but only the terminal things were translated. Not the graphical environment like Dolphin, Kwrite, tec

**Comment by andresimi** [comment]
Hey as I said, the graphical Yast didn't worked, but I accidently found this solution:

> cd /etc/skel/Desktop
> sudo language-installer.sh

Now everything in environment is translated too

**Comment by geckolinux** [comment]
Hi, thanks for confirming, glad it's working. That's the language installer script I was referring to. It's located in `/usr/bin/language-installer.sh` and there are Start menu and desktop shortcuts to it as well. It needs to be run first, and then the language needs to be set in YaST.

**Comment by candrapersada** [comment]
Translations cinnamon and yast indonesian not working?

**Comment by geckolinux** [comment]
https://github.com/geckolinux/geckolinux-project/wiki#how-to-install-non-english-languages
