### ISSUE TITLE
Gecko Rolling Updating

### ISSUE THREAD

**Issue by SUSEuser** [geckolinux/geckolinux-project#49]
I recently installed gecko linux rolling kde because I prefer the rolling release mentality, yet I can't seem to update it with the way you posted within your documentation of gecko linux.

**Comment by SUSEuser** [comment]
I'm having an issue with the repositories for OSS and non-OSS. Apparently I can't connect to the medium and I have no Idea why? Is there a fix for this?

**Comment by MrWrestling** [comment]
I had the same problem that i solved by editing the repos urls by adding an "s" after both "http".

**Comment by geckolinux** [comment]
Hi there, how did you try to update the system, and what exactly happens when it fails to work?

**Comment by geckolinux** [comment]
Hi there, this is probably a temporary openSUSE infrastructure issue.
