### ISSUE TITLE
Latest update to Rolling Plasma, / now using "41 GB"????

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#495]
@geckolinux 

Hope all is well . . . today I ran a firmware update in my Sys76 Gaz15 laptop, and that wiped grub.  I use the Gecko Plasma system to handle grub duties, so I had to use SG2 disk to boot to Gecko.  While there I ran a zypper dup and it showed roughly "411" packages to install, and a fair number to remove, it ran through fairly quickly, except for the "wl" package.  And I ran #update-bootloader while I was there to update grub.

I rebooted back into the OEM Pop!_OS system and for kicks decided to check GParted out, because Pop! loads their kernel into the efi/boot partition and sometimes it fills up.

Instead, I found that the Gecko / partition is showing as using "41 GB"???  compared to the two other OSs I have installed showing 11GB & 13GB . . . 41 is extraordinarily high?  I have a separate /home partition and I don't have a bunch of stuff added to the Gecko system, it is more or less box stock, as installed and zypper'd.

It doesn't seem like openSUSE has the same "autoremove" command that ubuntu flavors do, so I'm stuck for moves to make to try to get / down to normalcy?

I compared the contents of the three / partitions and Gecko is showing a "lib64" directory that has "2541" items in it, the other two systems, Pop! and Debian Bookworm are showing 1 item in that same directory the other items having large number of files are the sbin and bin . . . Gecko's seem to be close to those, but the lib64 seems "loaded."

Any way to do a system cleaning so that only the good packages are taking up space?  I checked the YaSt settings and the "keep downloaded packages" box is not checked on . . . i.e., it's off.

**Comment by geckolinux** [comment]
Hi there, hope you're doing well too.

Here are two of my favorite programs for inspecting disk usage:
- For the terminal install `ncdu` and run it with: `ncdu /`
- For a regular GUI app try installing `baobob` .

**Comment by esteelpaz** [comment]
@geckolinux 

OK, thanks for the suggestions, I'll check into either of them later, today, or tomorrow.  I already seem to have the possible "hint" with the many items in lib64 . . . but, will either of those apps tell me what packages aren't useful, or are overlaps??

In other words, what will "the next step" be after running either of those apps??  I vaguely recall something similar being discussed, possibly on the same machine with the Pop! techs, some app that showed "usage" . . . when the /efi/boot partition was over-filling--but, then what we did after that is even more vague.

I'll post back when I've run either or both of your suggested apps.

**Comment by esteelpaz** [comment]
@geckolinux 

OK, I installed ncdu and ran the ncdu / command, and it seems like a bunch of stuff is still in /var/cache/zypp/packages/Tumbleweed_OSS/x86_64 ????  I copy/pasted a few lines from in various drop down or drill down in the line item, in there I counted what is something like 25 kernels listed at 175MB a piece.

Thinking that it might be packages were still waiitng to be installed I ran a zypper and it found 27 new packages, nothing showing as "in cache" etc.  Also it shows the lib64 as being 2.7GB in content.

I wasn't sure if you would want to see the entire output of ncdu /??  Wasn't sure how to provide that so I just selected a few, and then at the bottom the initial data from the command.

`--- /var/cache/zypp/packages/Tumbleweed_OSS --------------------------------------------------------------------------------------------------------------------------- 
                                     /.. 
  15.8 GiB [#######################] /x86_64 
   8.2 GiB [###########            ] /noarch       



--- /usr -------------------------------------------------------------------------------------------------------------------------------------------------------------- 
                                     /..                                                                                                                               
   8.9 GiB [#######################] /lib 
   2.7 GiB [#######                ] /lib64

 24.1 GiB [#######################] /var                                                                                                                              
.  12.9 GiB [############           ] /usr 
.   2.7 GiB [##                     ] /home 
.   1.1 GiB [#                      ] /boot 
.  35.9 MiB [                       ] /etc 
.   1.6 MiB [                       ] /run 
  16.0 KiB [                       ] /srv 
!  16.0 KiB [                       ] /lost+found 
   4.0 KiB [                       ] /dev 
!   4.0 KiB [                       ] /root 
e   4.0 KiB [                       ] /opt 
e   4.0 KiB [                       ] /mnt 
!   4.0 KiB [                       ] /.Trash-999 
.   4.0 KiB [                       ] /tmp 
.   0.0   B [                       ] /proc 
.   0.0   B [                       ] /sys 
@   0.0   B [                       ]  lib64 
@   0.0   B [                       ]  sbin 
@   0.0   B [                       ]  lib 
@   0.0   B [                       ]  bin 
   0.0   B [                       ]  .autorelabel 







`

**Comment by mclose90-cmd** [comment]
@esteelpaz 
Hi. When you remove a package, such as Chromium for example, you can append `--clean-deps` to remove any unneeded packages along with it. Ex. `sudo zypper rm --clean-deps chromium`
Also, you can run `zypper packages --orphaned` to check for orphaned (unneeded packages) and remove those manually as well. In the future you could try running `rm` commands always appended with `--clean-deps`.
Please double-check things when you remove unneeded dependencies. I've noticed that once in awhile that packages that are useful and sometimes even still necessary can show up as an unneeded dependency. Zypper should inform you if there is an issue, but if not you should be or should become familiar with what packages might be useful or needed and which ones are not. 

To delete all cache files created by zypper, that is, downloaded packages and partial incomplete downloads of packages you can run `sudo zypper clean`. 
Zypper always keeps copies of downloaded and installed packages.  

You can check the `zypp.conf` file and configure it to your liking. `zypp.conf` configures how zypper should run. It's located at `/etc/zypp/zypp.conf`. The maintainer of GeckoLinux has already done a great job tweaking that file for us though. You can edit it by running `sudo nano /etc/zypp/zypp.conf`. After you make your edits do `Ctrl-O` to write the file, hit `Return/Enter` to save your changes, and then `Ctrl-X` to exit the `nano` terminal text editor. 
I hope you find this helpful. 
Regards.

**Comment by geckolinux** [comment]
@esteelpaz Thanks, so that confirms that `/var/cache/` has most of the the bloat. In addition to the suggestions that @Bum-Cement gave you might want to try the first three suggestions here:
https://en.opensuse.org/SDB:Cleanup_system

`/usr/` also looks a bit bloated to me, after trying the above steps you can dig in to that with `ncdu /usr`

**Comment by esteelpaz** [comment]
@Bum-Cement 

Thanks for the thoughts . . . having spent a lot of time in debian/ubuntu based liinux, I still look for commands like ¨autoremove" and äutoclean"to follow an upgrading, but largely, in running a TW and Leap 15.5, and some Gecko installs, just running ¨zypper dup -l" maintains the system in good order.

Today Iḿ booted in Gecko MATE, maintained via zypper on my older  Mac desktop and GParted shows / using 8.27 GB . . . without me having to run any extra commands.

@geckolinux 

Thanks also to you for the link to system clean up . . . I did just dig through my linux notes and did find an option for using ¨zypper clean --all" to apparently ¨clear cache". . . .  So, when I get back to the errant machine Iĺl try to run that command to see if it brings the / closer to being in shape.

Thanks also for the /usr  suggestion, yes, I did post the first step into it in the data . . . .

The question is, ḧow or why did all this bloat get there?" when, for the most part, on my desktop my openSUSE systems do not??  For some reason my newer ´20 laptop does seem to collect junque data???

**Comment by esteelpaz** [comment]
et al:

So I ran the "clean -all" and that did clear the cache and shrink the content substantially, but it was the "purge-kernels" command that showed "80" packages of kernel and broadcom-wl that took an hour to remove and did bring the / down to a very slim and trim 6.75 GB of usage.

Thanks for the assist on it.

**Comment by geckolinux** [comment]
Nice! Thanks for confirming.
