### ISSUE TITLE
Please release some new ISOs

### ISSUE THREAD

**Issue by SquarePeg79** [geckolinux/geckolinux-project#498]
I know it's a bit of a chore to produce new ISOs all the time but since the last ones were produced, there has been an update of several GBs. This isn't that much of a problem for me at the moment as my ISP is pretty good but for people with slower connections, it could take a long time.
Could you please produce some new ISOs?

Thanks

**Comment by geckolinux** [comment]
Hi, they will be updated as needed. The entire repository of Tumbleweed packages is usually updated several times a year, so it's normal to have to have updates of several GBs.
