### ISSUE TITLE
apparmor="DENIED" spam in plasma 5 failsafe mode

### ISSUE THREAD

**Issue by tkelman** [geckolinux/geckolinux-project#5]
I spent way too long getting something to at least boot on my actual hardware. I'm on a Lenovo Ideapad Y700 laptop with an Nvidia GTX 960M. Nouveau is causing problems, but that's a separate issue. From Windows I used [ImageUSB](http://www.osforensics.com/tools/write-usb-images.html) to copy over the Plasma 5 151220.0 iso to a USB stick, but then needed to mess around in the BIOS to turn off secure boot and fast boot to get it to actually be recognized. Useful things that I wish were written down somewhere centralized: F2 while booting for BIOS configuration, F12 while booting to open boot device selector, hold shift while clicking restart from Windows to get extra options for starting from a device.

Once I got booting off the USB, I tried the failsafe first, which did actually get to a prompt, but it's being spammed with the following messages:

```
[ TIME.STAMP] audit: type=1400 audit(TIMESTAMP:COUNTER): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/avahi-daemon" name="rw/etc/ld.so.cache" pid=PID# comm="avahi-daemon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ TIME.STAMP] audit: type=1400 audit(TIMESTAMP:COUNTER): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="rw/etc/ld.so.cache" pid=PID# comm="syslog-ng" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ TIME.STAMP] audit: type=1400 audit(TIMESTAMP:COUNTER): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="lib64" pid=PID# comm="syslog-ng" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ TIME.STAMP] audit: type=1400 audit(TIMESTAMP:COUNTER): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="syslog-ng" name="usr/lib64/libsyslog-ng-3.7.so.0.0.0" pid=PID# comm="syslog-ng" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ TIME.STAMP] audit: type=1400 audit(TIMESTAMP:COUNTER): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/avahi-daemon" name="lib64" pid=PID# comm="avahi-daemon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ TIME.STAMP] audit: type=1400 audit(TIMESTAMP:COUNTER): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/sbin/avahi-daemon" name="usr/lib64/libavahi-common.so.3.5.3" pid=PID# comm="avahi-daemon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

I'm not sure what to make of this, but it's spamming the console repeatedly every ~5 seconds.

**Comment by geckolinux** [comment]
Hi Tony,

Thanks for testing GeckoLinux and providing feedback.

> Useful things that I wish were written
> down somewhere centralized: F2 while booting for BIOS configuration, F12
> while booting to open boot device selector, hold shift while clicking
> restart from Windows to get extra options for starting from a device.

I agree that this is a royal pain, and Microsoft's Secure Boot invention 
has made things dreadfully more complicated than it used to be. But the 
worst part is that I can't even provide general information about how to 
work around it, because each and every computer has a different UEFI 
implementation and different F-keys to access different BIOS settings. 
:( Glad you figured it out in your case anyway.

> Once I got booting off the USB, I tried the fallback first, which did
> actually get to a prompt, but it's being spammed with the following
> messages:

Could you please try the normal boot method to see if it boots to a 
graphical login screen? Please allow it a bit of time for that to work 
correctly. Please let me know.

Thanks.

**Comment by tkelman** [comment]
It actually did finally boot into the plasma graphical environment. I'm not sure whether I fixed it by doing

```
zypper ar -f ftp://download.nvidia.com/opensuse/leap/42.1/ nvidia
zypper ref
zypper in nvidia-settings
```

(ref https://forums.opensuse.org/showthread.php/510615-Leap-42-desktop-freeze), or by some combination of bios changes, or just luck. One unrelated thing to note is my partitioning setup hit a snag due to missing `mkdosfs` / `dosfstools` and I had to re-do it. The YaST installer got to the end where it said the system needs restarting, though I think something may be wrong with restarting from inside the graphical environment since it appears frozen after I clicked "Reboot Now."

**Comment by geckolinux** [comment]
Hi @tkelman  thanks for the additional details.

About the `mkdosfs` / `dosfstools` packages, did it throw an error complaining that it needed those? And do you know what it was needed for? Do you have FAT32 partitions on your disk?

**Comment by tkelman** [comment]
The installer complained that it would be unable to finish my partitioning setup (which was very custom, I have an SSD and an HDD, I wanted to partition each in half, plus boot and swap on the ssd, plus several extra existing windows partitions on the ssd). I think one of my existing partitions may have been fat32.

So I got to a point where plasma would boot off the disk install somewhat repeatably, but freeze after a few minutes of use - some actions like configuring wifi were especially prone to freezing. Installing the nvidia drivers on the disk install actually seems to have made things worse, it now freezes during boot. There's an open issue about plasma freezing with either nouveau or nvidia drivers and I didn't see any clear fixes there (can drag up a link when not on a phone).

I think I'm going to try something gnome based and see if I have any better luck there. Do you know if anyone on obs has tried building Unity for Leap? It seems Ubuntu has these driver issues figured out better than anyone else does, but as a dev environment I'm trying to avoid launchpad and deb packaging, obs and spec files are much nicer.

**Comment by geckolinux** [comment]
Thanks for the additional information!

To solve the Windows / FAT32 installation error, all future editions of GeckoLinux will include `dosfstools`. Thanks for the tip.

Re: Plasma freezes, even I experienced some Plasma freezes in the live session, and I have Intel graphics. They appeared to be related to Dolphin, and I suspect they only happen on the live session. In your case, it definitely sounds like graphics driver issues. On all GeckoLinux images I included `xf86-video-nouveau` and `xf86-video-nv`. I really don't know much about Nvidia cards, so I'm not sure which of those is preferable, or which might be in use on your system?

At any rate, it definitely sounds like a good idea to try a lighter system that is not Plasma-based, just to see if the problem goes away. I would recommend GeckoLinux XFCE, since it doesn't use accelerated graphics to render the interface.

Please let me know how it turns out. Thanks!

**Comment by tkelman** [comment]
We've gotten a ways from the initial report (which from systemctl logs looked to be due to a permissions error when trying to load libavahi or libsyslog-ng, iirc). That may have been particular to running from the live usb.

I think the moral of the story right now is avoid KDE for a while, maybe once Wayland is everywhere it'll be better off? I went with Gnome and it seems to be working so far, though nouveau is still complaining and there's an annoying "something has gone wrong" screen that pops up briefly in the background as I log in. Installing `x11-video-nvidiaG04` from the nvidia repo made that screen more prominent and prevent logging in, so I may have to stick with nouveau.

**Comment by tkelman** [comment]
Much better news to report today. The single most helpful thing in making the install and boot process more stable and usable was disabling KMS by hitting `e` every time I saw a grub boot menu and adding `nomodeset` to the end of any "linux" line (even for the installer, helped avoid the freezing issues). I think that basically makes Nouveau go away - the GTX 900 series GPU's apparently require signed firmware which the Nouveau driver doesn't support yet.

And because of the Optimus dual GPU setup of this laptop, I apparently should have been getting my Nvidia drivers via Bumblebee, not directly from Nvidia? There may have also been some missing kernel headers causing issues when building the Nvidia kernel module (I'll see if I can find and submit a change request to fix Bumblebee's spec file for this). The following set of steps worked for Gnome:

```
zypper ar -f http://download.opensuse.org/repositories/X11:/Bumblebee/openSUSE_Leap_42.1/ Bumblebee
zypper install kernel-default-devel binutils dd_rescue man less
zypper install bumblebee nvidia-bumblebee nvidia-bumblebee-32bit
gpasswd -a $USER bumblebee
gpasswd -a $USER video
systemctl enable bumblebeed
systemctl enable dkms
mkinitrd
```

Kind of an ordeal, but after rebooting `optirun glxspheres` is nearly 10x faster than `glxspheres`, so I think it's working correctly. I'm going to close this since the original log spam may have been harmless, just a consequence of avahi having trouble starting on the live USB due to some shared library permissions. Avahi seems to start okay from disk.

**Comment by geckolinux** [comment]
Hi @tkelman  , great to hear you got it worked out. Congratulations for sticking with it, I hope it will be nice and stable now that you got the kinks worked out.

**Comment by tkelman** [comment]
I hope so too - next I have to figure out Cuda and Virtualbox (edit: nuisance startup error about "Not running on a virtualbox guest" was fixed via `sudo insserv -r vboxadd vboxadd-service`). Thanks for your help and bearing with my venting/progress updates as I worked through this. I totally agree with your goals for the GeckoLinux project and hope it takes off, despite a few hardware configuration problems. I imagine I would have hit all of these with stock opensuse leap, so I don't think any of your customizations were at fault in any way.

Aside from installing `dosfstools`, I wonder if a few more configuration changes might help ease these issues for future users?
- have zypper keys for additional repos already accepted?
- always disable KMS? does it provide enough benefits on non-nvidia hardware to be worth it?
- maybe attempt to detect nvidia and/or optimus configurations and suggest adding some repositories or running extra steps? worth looking into how ubuntu is implementing things like this: https://help.ubuntu.com/community/BinaryDriverHowto/Nvidia#Installation

Do you have a set of scripts that you use to drive SUSE Studio, or is all of the configuration done by hand? I tried it out and seem to remember an option for a general provisioning script where you could run almost anything?

**Comment by geckolinux** [comment]
Sorry for the delay in replying.

> - have zypper keys for additional repos already accepted?

I definitely want to figure out how to do this.

> - always disable KMS? does it provide enough benefits on non-nvidia hardware to be worth it?

I think that other drivers like Intel practically expect KMS. I would suspect that your troubles were due to it using the wrong open source driver. I've read the open source drivers for Nvidia cards are normally stable and fairly bug free, just not as fast as the proprietary drivers. Do you know if `xf86-video-nouveau` or `xf86-video-nv` is preferable?

> - maybe attempt to detect nvidia and/or optimus configurations and suggest adding some repositories or running extra steps? worth looking into how ubuntu is implementing things like this: 
>   Adding a proprietary driver configuration tool would indeed be nice, but I'm afraid it's a bit beyond my technical abilities. But I would however like to consider adding Nvidia and Radeon repositories available but disabled by default. Thanks for the idea.
> 
> Do you have a set of scripts that you use to drive SUSE Studio, or is all of the configuration done by hand? 

By hand. :) It's easy enough, all point-n-click thanks to SuseStudio.

**Comment by tkelman** [comment]
No worries, it is the new year after all. I'm not sure what effect the xf86-video packages have, but I suspect nouveau was causing most of my problems due to not supporting recent cards.

Waking from suspend is the next thing giving me trouble, it just gives a black screen. Manually doing `systemctl hibernate` works properly and wakes up fine, but getting the lid switch associated with either suspend or hibernate has remained beyond my reach so far. Again probably not specific to geckolinux customizations in any way.

I guess if SuseStudio has your existing config all saved so you're only ever making incremental changes then it's not so bad, but it would be cool to export the entire configuration to some repeatable source format aside from the image itself.

edit: as far as driver detection tools go, I agree it could be tricky to put something like that together from scratch. Maybe leveraging what ubuntu has done and seeing if any of their tools could be repackaged and used on opensuse would be worth experimenting with.

**Comment by geckolinux** [comment]
> I suspect nouveau was causing most of my problems due to not supporting recent cards.

So your card is pretty new? (Sorry I really am quite ignorant about Nvidia hardware.)

Re: suspend-- You get a black screen with the lid switch, or it just doesn't try to suspend? And what about the keyboard shortcut with an F-key to suspend? And what about the menu option to suspend the system? (Unfortunately this requires an extension to enable that option in Gnome shell.)

> it would be cool to export the entire configuration to some repeatable source format aside from the image itself.

I think the Kiwi configuration can actually be exported from SuseStudio, although I don't have any experience with that.

**Comment by tkelman** [comment]
Yeah, GTX 900 series, it's a brand new laptop that I got specifically to do cuda dev work. I don't know if anything has changed since http://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-Unfriendly-OSS-Hardware, but it's the newest NV110 column at http://nouveau.freedesktop.org/wiki/FeatureMatrix/ which still has a lot of "WIP."

The lid switch currently shuts the display off, but doesn't suspend or hibernate. I haven't tried the keyboard suspend yet, or found the right gnome extension for it. I've been manually triggering from the command line with `systemctl suspend` or `systemctl hibernate` to test, but would prefer lid switch for day to day use if I can get it working.

Anyway, thanks for all your help. I'll probably move to opensuse forums for future things now that at least the basics are running.

**Comment by geckolinux** [comment]
For the Gnome Shell suspend button, try this extension:
https://extensions.gnome.org/extension/826/suspend-button/

And for the lid suspend, could you please verify this option is enabled?

![3ui558l](https://cloud.githubusercontent.com/assets/2692138/12072930/a2ea022e-b0cd-11e5-9fad-8451165cec34.jpg)

**Comment by tkelman** [comment]
That suspend button looks nice and works to trigger suspend, as does the keyboard option (Fn-F1 here, but I imagine that varies a lot). Once suspended if I close then reopen the lid it does try to wake up, but gives a nonresponsive black screen when it does.

That's in `gnome-tweak-tool`, right? My "Power button action" was set to "Interactive" but changing it to Suspend does not improve anything. I see a toggle for "Don't suspend on lid close" that is set to Off.

**Comment by geckolinux** [comment]
Thanks for confirming. And does `systemctl suspend` also fail to resume?

**Comment by tkelman** [comment]
Right, black screen. It's trying to wake up but not getting very far.

**Comment by geckolinux** [comment]
OK, got it. Well, the only other thing I can think to try is suspending and resuming from a fresh live session of GeckoLinux with no modifications to anything. Then I would recommend posting to the openSUSE forums for help with the kernel and/or video driver problems that are causing the suspend issue. Thanks!
