### ISSUE TITLE
unable to do zypper dup on fresh install

### ISSUE THREAD

**Issue by dtk1985** [geckolinux/geckolinux-project#508]
hello, i did a fresh install of the rolling plasma version (https://sourceforge.net/projects/geckolinux/files/Rolling/999.220820/GeckoLinux_ROLLING_Plasma.x86_64-999.220820.0.iso/download), tried to upgrade after i booted into the system with "zypper dup" but got an error that the nvidia repo cannot be reached. i changed the repository url for nvidia from httpS to http in yast repository config, seems like that fixed the nvidia repo issue. but now I am getting dependency problems when zypper dup runs:

```
ryzen-tw:~ # zypper dup
Loading repository data...
Reading installed packages...
Warning: You are about to do a distribution upgrade with all enabled repositories. Make sure these repositories are compatible before you continue. See 'man zypper' for more information about this command.
Computing distribution upgrade...
3 Problems:
Problem: problem with the installed gstreamer-plugins-libav-1.20.3-72.4.x86_64
Problem: nothing provides 'kernel-uname-r = 6.3.6-1-default' needed by the to be installed broadcom-wl-kmp-default-6.30.223.271_k6.3.6_1-1699.18.pm.156.x86_64
Problem: nothing provides 'kernel-uname-r = 6.3.6-1-default' needed by the to be installed r8168-kmp-default-8.051.02_k6.3.6_1-1699.2.pm.39.x86_64

Problem: problem with the installed gstreamer-plugins-libav-1.20.3-72.4.x86_64
 Solution 1: install gstreamer-plugins-libav-1.22.3-1.1.x86_64 from vendor openSUSE
  replacing gstreamer-plugins-libav-1.20.3-72.4.x86_64 from vendor http://packman.links2linux.de
 Solution 2: keep obsolete gstreamer-plugins-libav-1.20.3-72.4.x86_64

Choose from above solutions by number or skip, retry or cancel [1/2/s/r/c/d/?] (c):

```
the package name "kernel-uname-r = 6.3.6-1-default" does not look right to me, what is "uname-r = " doing in the package name?

**Comment by geckolinux** [comment]
Hi there, that always happens from time to time when Tumbleweed updates the kernel and Packman takes a bit longer to update the KMP packages. Just wait a day or so and it should be resolved.

As for `gstreamer-plugins-libav` you can choose Solution # 1.

**Comment by dtk1985** [comment]
> Hi there, that always happens from time to time when Tumbleweed updates the kernel and Packman takes a bit longer to update the KMP packages. Just wait a day or so and it should be resolved.
> 
> As for `gstreamer-plugins-libav` you can choose Solution # 1.

thanks for the quick reply, and your work on this spin. 
meanwhile what i did was I installed nvidia drivers from Yast Software manager which also updated the kernel. after the reboot I ran zypper dup again and all the dependency problems disappeared. my system is up to date now, nvidia driver works and also secure boot is enabled on top of that :)
