### ISSUE TITLE
geckolinux update leap 15.0

### ISSUE THREAD

**Issue by candrapersada** [geckolinux/geckolinux-project#51]
how to leap update 15.0?

**Comment by geckolinux** [comment]
https://github.com/geckolinux/geckolinux-project/wiki#updating-to-a-major-new-opensuse-release

**Comment by candrapersada** [comment]
change the main openSUSE Leap OSS repository or all repository 42.3 to 15.0?

**Comment by geckolinux** [comment]
Any repository that has `42.3` please change it to `15.0`

**Comment by candrapersada** [comment]
can or not use # sed -i 's/42.3/15.0/g' /etc/zypp/repos.d/* for replace the version numbers as necessary?

**Comment by geckolinux** [comment]
Sure, but I prefer the visual method.
