### ISSUE TITLE
System restore tool for Linux.

### ISSUE THREAD

**Issue by candrapersada** [geckolinux/geckolinux-project#52]
how to use snapshot or other for backup?

**Comment by geckolinux** [comment]
Hi there, what are you trying to backup?

**Comment by candrapersada** [comment]
Backup system linux

**Comment by geckolinux** [comment]
- https://wiki.archlinux.org/index.php/System_backup
- https://wiki.archlinux.org/index.php/Synchronization_and_backup_programs

**Comment by candrapersada** [comment]
Backup and restore use gui
