### ISSUE TITLE
Cracking Audio on Barebones

### ISSUE THREAD

**Issue by h8uthemost** [geckolinux/geckolinux-project#520]
Hey GeckoLinux'ers

I'm having a problem with my audio. I'm using Bare bones. And have been using it happily for months. All for one annoying issue, that I have cracking audio. I've had it since I installed bare bones.

I'm using headphones not speakers. It doesn't matter if I listen from an installed app or from a browser. It sounds like baking recorded vinyl with all the pops and clicks. When I use whatever headphones in using on my phone I don't get the crackling. So it's not the headphones. And I don't get this issue with other distros that I've tried. So I'm guessing because it's barebones, I might need to install something or tweak something? I don't know. 

I don't have any error files for you. I'm running tumbleweed which is up to date.  Newest kernel and newest everything. So if there's any other info you need from me then just ask. 

It's just weird I only get this from barebones and not other distros. I'm thinking of downloading the xfce version and see if I still get this problem. But of course I'd rather fix this issue in bare bones then wiping and installing a new system. Although I guess I could try dual booting the xfce edition just to try it. 

Like I said, whatever other info you need just ask. 

Oh, and great distro, even with the crackling audio. openSuSe won't even install on my computer but Gecko does. 

Thanks for reading

**Comment by geckolinux** [comment]
Hi there, let's try the default openSUSE Pipewire configuration (GeckoLinux modifies it for low latency audio tasks). Please try this:
`sudo mv /etc/pipewire /etc/pipewire-BAK`
and then reboot.

**Comment by h8uthemost** [comment]
No way! How did you know that would fix the problem?! So it was just the default openSUSE file that needed some love. Very awesome.

I  just sat and listened to a 14 min Jerry Garcia song, and the crackling is absolutely gone.

I can't thank you enough. Thank you for the fix(I'll have to keep that command around if I have to reinstall), and thank you for GeckoLinux. I absolutely love it. 

Thank you Thank you Thank you

I'll report back if it starts happening again. But I think it's safe to say that you fixed this.

**Comment by geckolinux** [comment]
Awesome, glad it was a simple fix.
