### ISSUE TITLE
font settings

### ISSUE THREAD

**Issue by wrosenauer** [geckolinux/geckolinux-project#53]
Hi,
your "Forum" link points me to this issue tracker so I'm using it as a forum in this case.

Is there documentation what you change on GeckoLinux 150 compared to openSUSE upstream in the font settings? I'm interested in that since I'm not satisfied by the openSUSE defaults and I'm looking for better recommendations. On the other side I do not really want to replace my installation with GeckoLinux just because of that.

**Comment by geckolinux** [comment]
Hi there, yes, this is the forum. :-)

The most important element to the font tweaks is using a default system font that renders well, Ubuntu in this case. Another good option would be DejaVu Sans. Then make sure to use RGB subpixel rendering with "slight" hinting in the desktop environment's font settings. I also make some tweaks to `/etc/fonts/conf.d` which you can find [here](https://github.com/geckolinux/geckolinux-project/blob/geckolinux-release/Kiwi-20171231_000_GeckoLinux_Kiwi_skeleton.tar.gz). Depending on the desktop environment being used you might need to tweak a couple of other local user config files, but the above is usually enough for the full-featured desktops.
