### ISSUE TITLE
Plasma 5.13

### ISSUE THREAD

**Issue by danielwei15** [geckolinux/geckolinux-project#54]
Is Geckolinux NEXT have the update for KDE Plasma 5.13?
Perhaps Geckolinux Rolling?

I wish to know which edition I need to run this latest version.

Thanks!

**Comment by geckolinux** [comment]
Hi there,

Yes, one way would be to install GeckoLinux *Rolling* and update the system. It will be available any day now if it isn't already. I will also update the GeckoLinux *Rolling* Plasma ISO as soon as I have time.

Also around the same time as the updated GeckoLinux *Rolling* Plasma ISO, I'll also try to release an update to GeckoLinux *NEXT* Plasma (based on Leap 15.0), provided that all of the additional repositories are in a good state at that time.

**Comment by danielwei15** [comment]
Alright. Thank you!

**Comment by geckolinux** [comment]
Hi there, here you go:
https://sourceforge.net/projects/geckolinux/files/NEXT/GeckoLinux_NEXT_Plasma.x86_64-150.180616.0.iso/download
