### ISSUE TITLE
Rolling too old to install on newer hardware

### ISSUE THREAD

**Issue by FitzM** [geckolinux/geckolinux-project#543]
Could you please update ( or tell me how to update) the snapshot the  rolling versions are based on? Currently it's 202208... something and I can't get it to boot on my laptop at all ( newer gen Ryzen cpu).  Could we please update this?

**Comment by geckolinux** [comment]
Hi there, I'm working on the next set of updates, you can try the Cinnamon beta if you want: https://github.com/geckolinux/geckolinux-project/discussions/503#discussioncomment-10552766
Please leave feedback in the above thread if you give it a try.
