### ISSUE TITLE
GeckoLinux_ROLLING_XFCE.x86_64-999.180607.0.iso: os-prober is missing

### ISSUE THREAD

**Issue by robertwolter** [geckolinux/geckolinux-project#56]
I used GeckoLinux_ROLLING_XFCE.x86_64-999.180607.0.iso for installation and at the end there was only one entry for GeckoLinux generated during grub2-mkconfig because os-prober wasn't installed in the live system.

**Comment by geckolinux** [comment]
Thanks very much. I'll add it for the next release.

**Comment by robertwolter** [comment]
Ok, I close this as well.

**Comment by geckolinux** [comment]
And I'm reopening it so I don't forget to fix it in the next release. :-) Thanks!

**Comment by robertwolter** [comment]
Ok ;) You're welcome!

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
