### ISSUE TITLE
Yast installer

### ISSUE THREAD

**Issue by konig1** [geckolinux/geckolinux-project#58]
Hi,
How do I go about getting the yast installer working? I want to use btrfs as a filesystem, something calamares do not support

**Comment by geckolinux** [comment]
Hi there, Calamares _does_ support BtrFS and a whole ton of other common and esoteric filesystems.

What it _doesn't_ support (yet) is automatically setting up Snapper + GRUB integration for booting BtrFS snapshots.

The old YaST live installer was jettisoned by openSUSE a long time ago, and is now completely incompatible with the current state of openSUSE Leap and Tumbleweed.
