### ISSUE TITLE
Change Kernel

### ISSUE THREAD

**Issue by Chente-Su** [geckolinux/geckolinux-project#59]
Currently I have 3 kernels in my system, I would like to change the default kernel.  In Grub only 1 kernel is displayed 4.16.12-1.4  How can I change the kernel to 4.17.2-1.4 to load by default?  And how can I have the other kernel in Advanced section as fallback?  

-FYI - In the Boot Loader setting the tab Boot Loader option the drop down menu Default Boot Section only shows 1 kernel which the 4.16

Please help.  Thank you

**Comment by geckolinux** [comment]
Hi there,

Could you please open the YaST Software tool and search for `kernel-default` and give me a screenshot of the **Versions** tab?

Thanks.

**Comment by Chente-Su** [comment]
Hi, I figured it out.  Thank you for your response, appreciate it.

**Comment by geckolinux** [comment]
Thanks for confirming. Glad you figured it out.
