### ISSUE TITLE
Failed to find MBR.

### ISSUE THREAD

**Issue by darkphoenixff4** [geckolinux/geckolinux-project#6]
Every time I try to boot off my USB key, the loader stops at "Trying to find boot device for Application ID", displays a bunch of bash, and then states that it can't find an MBR on my device.

**Comment by geckolinux** [comment]
Hi there, could you please try to create your bootable USB key with [openSUSE ImageWriter](https://www.github.com/openSUSE/imagewriter)?

**Comment by lokopepe** [comment]
I had tried with usbwriter, opensuse imagewriter and rufus 11. The same result. Thank

**Comment by geckolinux** [comment]
OK, could you please try one of the newer releases? Thanks!

**Comment by geckolinux** [comment]
Hello, please try the newest GeckoLinux release with the Calamares installer.
