### ISSUE TITLE
OpenSuse-2018-515-Security update for the Linux Kernel

### ISSUE THREAD

**Issue by amg81649** [geckolinux/geckolinux-project#60]
OpenSuse-2018-515-Security update for the Linux Kernel after i install this update it breaks my system.
 Re installed and skipped the update all goes well. How important is this update? by the way I'm using plasma next 15.0 thanks in advance..

**Comment by geckolinux** [comment]
Hi there, could you please describe what exactly happens after you install the update, and how you installed the update?

**Comment by amg81649** [comment]
Hi thanks for the fast reply, after the installation I did the usual update using the terminal "sudo zypper dup" 
then I got this Open Suse-2018-515 Security update for the Linux kernel

**Comment by geckolinux** [comment]
Hi, but what exactly is broken?

**Comment by amg81649** [comment]
Sorry I just can't type properly in a smartphone. Now the Suse update is warning me about a kernel conflict and there's an option that it's going to do a reinstallation I don't remember the second one and the third is to not install the update I did the first option
after that I got a frozen system no cursor no keyboard a frozen display.
I have to reinstall and this time I did the update through yast online update
I still get the Security update warning but I just ignore it and skip installing it
Then I manage to complete the installation.

**Comment by geckolinux** [comment]
Hi there, I'm still a bit confused about what steps were actually performed the first time, and what the end result was.

But in any case, openSUSE updates are usually very reliable and trouble-free. For starters, `sudo zypper dup` should only be used on Tumbleweed based systems and to update between major Leap releases.

Please follow these instructions for updating GeckoLinux:
https://github.com/geckolinux/geckolinux-project/wiki#how-to-update-geckolinux

**Comment by amg81649** [comment]
Hi there again, i did some googling about the openSUSE security update it's the fix for Meltdown and Spectre vulnerabilities, Now here's what i got when i did the updates:

patch:openSUSE-2018-515-1.noarch conflicts with kernel-default-base.x86_64 <4.12.14-lp150.12.4.1 provided by kernel-default-base-4.12.14-lp150.11.4.x86_64

Conflict Resolution:
1: Following action will be done:
deinstallation of  kernel-default-base.x86_64 <4.12.14-lp150.12.4.1
deinstallation of virtualbox-guest-kmp-default-5.2.12_k4.12.14_lp150.4.3.1x86_64
deinstallation of virtualbox-guest-x11-5.2.12-lp150.4.3.1.x86_64
deinstallation of virtualbox-guest-tools-5.2.12-lp150.4.3.1.x86_64
2: deinstallation of kernel-default-base-4.12.14-lp150.11.4.x86_64
3: do not install patch:openSUSE-2018-515-1.noarch
What's your advice? i already did the first option and it breaks the system 
I'm thinking of doing the second option, what do you think?

**Comment by amg81649** [comment]
Sorry I want to clarify that this is a fresh installation using a usb stick. not an updates from a previous version.Actually right now i have a working Gecko Plasma Static15.0 I have already downloaded some of my basic apps. As you can see the screenshot below that's what i've got when i try to install updates.

patch:openSUSE-2018-515-1.noarch conflicts with kernel-default-base.x86_64 <4.12.14-lp150.12.4.1 provided by kernel-default-base-4.12.14-lp150.11.4.x86_64

I just have to skip the update to continue. How can I resolve this issue? Your help is greatly appreciated
thank you very much..

**Comment by amg81649** [comment]
![screenshot_20180702_152941](https://user-images.githubusercontent.com/40729519/42174312-11800406-7e4c-11e8-880c-7fd068625a6a.png)

**Comment by geckolinux** [comment]
Hi there, yes, option 2 is fine.

**Comment by amg81649** [comment]
Thank you very much the second option did it. thanks again cheers!

**Comment by geckolinux** [comment]
Glad it worked, thanks for confirming. Since that package is now removed, it shouldn't give you any more trouble on future updates.
