### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by tosim91** [geckolinux/geckolinux-project#61]
Running Mint18.3-MATE,64b. Have downloaded (at 2 different times), Gecko-MATE static 64-150.180607, and Gecko-MATE rolling 64-999.180607, but neither will install. Messages I  am getting, after original screen boots are:
Load Static Mate 7068088 dfacat: Refusing to continue, and 7.105425 reboot:System Halted

Any help will be greatly appreciated. Thank you.

**Comment by geckolinux** [comment]
Please check your ISO md5sum to make sure it's not corrupted.

Also, you can try booting with some of the other options displayed along the bottom of the initial boot screen.

**Comment by tosim91** [comment]
Thanks for the reply. Will try bottom options, and if still no boot, will
re dl, and try again.

**Comment by tosim91** [comment]
I dl'ed both editions, static and rolling, tried virtually every combo of bottom options, and NADA! Been using Linux since 1998, and never had a  problem like this. Although I am a dedicated Mint-MATE user, for at least past 10 years, I still dl other Linux versions as they appear, just to "play around" a bit.
Anyhow, I've devoted way too much time to Gecko, so I'll say goodbye, and thank you once again for your kind help.
