### ISSUE TITLE
xhost message on "sudo su"

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#62]
This message is displayed

`xhost:  unable to open display ""`

I've added 

`export DISPLAY=:0` to `/etc/environment`
 The another message

```
No protocol specified
No protocol specified
xhost:  unable to open display ":0"
```

When type `xhost +`

`non-network local connections being added to access control list`

On OpenSUSE 15.0 KDE live image and install this not occurs.

**Comment by geckolinux** [comment]
Hi there, please try deleting the `.bashrc` file from your `~/` and `/root/` directories.

**Comment by ghost** [comment]
Works great!
