### ISSUE TITLE
Problem when import openvpn file

### ISSUE THREAD

**Issue by ghost** [geckolinux/geckolinux-project#63]
Gecko 15 Plasma NEXT

When import .ovpn file the networkmanager does nothing, I've install

`NetworkManager-openvpn plasma-nm5-openvpn`

And import fine

**Comment by geckolinux** [comment]
Thanks, I'll add VPN packages to future releases of GeckoLinux.

**Comment by ghost** [comment]
Thanks

**Comment by geckolinux** [comment]
Implemented in the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
