### ISSUE TITLE
Persistence with YUMI

### ISSUE THREAD

**Issue by H0w4rd** [geckolinux/geckolinux-project#64]
Is there any way how can I run Gecko from a flash drive created with YUMI? The special partition 'cow' is not automatically created. If I copy this partition from another flash drive (created with imagewriter with using Gecko ISO where it works), it won't use it anyway. Is there any way?

**Comment by geckolinux** [comment]
Hi there,

Sorry, but I'm really not familiar with how YUMI works. You could try asking the YUMI devs if they have any suggestions, explaining how the flash drive is partitioned after creating it using the normal `dd` method with GeckoLinux.

Cheers.
