### ISSUE TITLE
accessibility for the mate version of gecko linux

### ISSUE THREAD

**Issue by mhussaincov** [geckolinux/geckolinux-project#65]
hi there,
I am blind and require speech to interact with my machine
would it be possable to have gnome-orca installed on your mate live image?
gnome-orca is the screen reader that runns on linux.
with out orca, I will not be able to use gecko linux.
I am thinking of trying it out opensuse does not have orca on there images but would you be able to help?
my thanks,
Majid Hussain

**Comment by geckolinux** [comment]
Hi @mhussaincov , thanks for the request. I generated a special Mate image for you with Orca installed:

https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_STATIC_Mate-Orca.x86_64-150.180726.iso/download

Please let me know how it works for you.

**Comment by mhussaincov** [comment]
hi there,
just saw your message,
i'll respond as soon as i've tested your iso.
thanks, you are the only person that goes so far in helping, have some
good luck from me, you are ausom!
Majid

On 26/07/2018, GeckoLinux <notifications@github.com> wrote:
> Hi @mhussaincov , thanks for the request. I generated a special Mate image
> for you with Orca installed:
>
> https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_STATIC_Mate-Orca.x86_64-150.180726.iso/download
>
> Please let me know how it works for you.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/geckolinux/geckolinux-project/issues/65#issuecomment-408208021


-- 
kind regards,
Majid Hussain

**Comment by mhussaincov** [comment]
hi there,
i tryed the iso,
there is an issue.
launching orca I get the speech dispatcher dummy output module no
sound from orca just a repete message.
would it be possable for you to change the voice in orca's voice
settings dyalog box to espeak or espeak-ng?
not sure if that will fix the issue but worth a try,
Majid Hussain

On 26/07/2018, Majid Hussain <mhussaincov93@gmail.com> wrote:
> hi there,
> just saw your message,
> i'll respond as soon as i've tested your iso.
> thanks, you are the only person that goes so far in helping, have some
> good luck from me, you are ausom!
> Majid
>
> On 26/07/2018, GeckoLinux <notifications@github.com> wrote:
>> Hi @mhussaincov , thanks for the request. I generated a special Mate
>> image
>> for you with Orca installed:
>>
>> https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_STATIC_Mate-Orca.x86_64-150.180726.iso/download
>>
>> Please let me know how it works for you.
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/geckolinux/geckolinux-project/issues/65#issuecomment-408208021
>
>
> --
> kind regards,
> Majid Hussain
>


-- 
kind regards,
Majid Hussain

**Comment by geckolinux** [comment]
Hi there, sorry about that, it looks like it was missing the `speech-dispatcher-module-espeak` package. Now it appears to work for me. 

Here's the new ISO:
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_STATIC_Mate-Orca.x86_64-150.180727.0.iso/download

Hope it works for you! Best regards.

**Comment by mhussaincov** [comment]
hi there,
went to the link to get the iso,
it says no mirror for file and does not download,
Majid Hussain

On 26/07/2018, Majid Hussain <mhussaincov93@gmail.com> wrote:
> hi there,
> just saw your message,
> i'll respond as soon as i've tested your iso.
> thanks, you are the only person that goes so far in helping, have some
> good luck from me, you are ausom!
> Majid
>
> On 26/07/2018, GeckoLinux <notifications@github.com> wrote:
>> Hi @mhussaincov , thanks for the request. I generated a special Mate
>> image
>> for you with Orca installed:
>>
>> https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_STATIC_Mate-Orca.x86_64-150.180726.iso/download
>>
>> Please let me know how it works for you.
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/geckolinux/geckolinux-project/issues/65#issuecomment-408208021
>
>
> --
> kind regards,
> Majid Hussain
>


-- 
kind regards,
Majid Hussain

**Comment by geckolinux** [comment]
Hi there, sorry about that. That's just a temporary Sourceforge problem. It should work if you try it again.

**Comment by mhussaincov** [comment]
hey there,
yes, orca and all work!
there's a downside however,
you are using calamares which does not seembe to be accessible,
is there a text based installer or a way of installing with out calamares?
my thanks,
Majid Hussain

On 28/07/2018, GeckoLinux <notifications@github.com> wrote:
> Hi there, sorry about that. That's just a temporary Sourceforge problem. It
> should work if you try it again.
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/geckolinux/geckolinux-project/issues/65#issuecomment-408607525


-- 
kind regards,
Majid Hussain
