### ISSUE TITLE
GeckoLinux Rolling Openbox edition/version???

### ISSUE THREAD

**Issue by Suo-Eno-1357** [geckolinux/geckolinux-project#67]
This is probably asking for too much but if anyone else here shares the same past/current xp of #! or Bunsenlabs, you know what I'm talking about. Especially when it seems like an opportune moment to replace the Budgie variant (I like Budgie fwiw but I plan to run this on my spare creaky old Thinkpad T60 with 2GB RAM that's probably gonna crawl with Budgie) and also a chance finally for a ground up OpenSUSE based Openbox remix as Gecko's?

Or will YaST become the hurdle or something??? Anyways feel free to quickly delete this post if it's a waste of space, tyvm for your patience!

**Comment by geckolinux** [comment]
Hi there, if somebody can contribute a configuration for Openbox I'd be glad to consider merging it with the "BareBones" edition.

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
