### ISSUE TITLE
Is there a way to do toram?

### ISSUE THREAD

**Issue by nxdiamond** [geckolinux/geckolinux-project#68]
Some live distros accept a parameter like toram or toram=filesystem.squashfs in the line that loads the kernel. This can either be included in grub.conf in the ISO image or can be added when editing the grub commands before booting. After the boot media is copied to RAM, the boot media can be ejected and booting continues.

Does geckolinux accept some kind of parameter like this?

I'm not sure if it was officially added to OpenSuse or if one person made this for a customized image:
https://lizards.opensuse.org/2016/01/29/running-live-image-from-ram/

**Comment by geckolinux** [comment]
Hi there, I just tried it and it doesn't appear to be possible.
