### ISSUE TITLE
Unable to Change GTK+ Theme

### ISSUE THREAD

**Issue by Tvrdoglavi** [geckolinux/geckolinux-project#7]
GNOME Tweak Took shows only two GTK+ themes. High Contrast and Numix. No matter how many themes I installed those remain the only two options.
You can change them using the command line but that is not an efficient way of doing it.

**Comment by geckolinux** [comment]
Hi there,

How and where are you attempting to install the additional themes?

Best regards,
Sam

**Comment by Tvrdoglavi** [comment]
I downloaded a few from gnome-look.org. I installed a few and none were added to GTK+ list. I checked the themes folder and it was full of themes. I was able to change them with command line commands I found on the web, but not through the GUI.
While I'm already writing this, I know it's a separate bug but ....
Installing GeckoLinux messed up my boot records. it was showing geckolinux and linux mint but I was not able to start my Windows 8 Install. They are all on separate hard drives. I installed Ubuntu over gecko linux after I wrecked it while trying to install nvidia drivers and that fixed the issue.

**Comment by geckolinux** [comment]
On 05/03/2016 12:30 PM, Tvrdoglavi wrote:

> I downloaded a few from gnome-look.org. I installed a few and none were
> added to GTK+ list. I checked the themes folder and it was full of
> themes. I was able to change them with command line commands I found on
> the web, but not through the GUI.

Hello, could you please confirm the complete path of the folder where 
you installed the themes to?

> While I'm already writing this, I know it's a separate bug but ....
> Installing GeckoLinux messed up my boot records. it was showing
> geckolinux and linux mint but I was not able to start my Windows 8
> Install. They are all on separate hard drives. I installed Ubuntu over
> gecko linux after I wrecked it while trying to install nvidia drivers
> and that fixed the issue.

Sorry to hear that. Unfortunately I can't do anything to fix the 
openSUSE live installer.

**Comment by Tvrdoglavi** [comment]
I don't have Gecko installed at the time. It was the default folder. I did not change anything as far as those paths are concerned. Sorry I don't have more information for you.

**Comment by Tvrdoglavi** [comment]
A silly question for you if you don't mind. I clicked the fork button to see what it does and now I'm suddenly a proud owner of a Gecko Linux fork and it looks like I can't remove it from my account. Any idea on how to do that?

**Comment by geckolinux** [comment]
On 05/03/2016 03:55 PM, Tvrdoglavi wrote:

> A silly question for you if you don't mind. I clicked the fork button to
> see what it does and now I'm suddenly a proud owner of a Gecko Linux
> fork and it looks like I can't remove it from my account. Any idea on
> how to do that?

Yep, in the https://susestudio.com/home overview there is an X button to 
delete it in the top right corner.

**Comment by Tvrdoglavi** [comment]
It was on github. I found a way to delete it minutes after posting, but you replied before I managed to delete the post.
Thank you for the response.

**Comment by geckolinux** [comment]
Hello, please re-open this issue if the problem still persists. Thanks.
