### ISSUE TITLE
BTRFS not offered on Rolling iso

### ISSUE THREAD

**Issue by horizonbrave** [geckolinux/geckolinux-project#70]
Hi, I was trying to install Gecko Linux and opted for the rolling version.
At installation (Calamares) with "Erase and Install" I'm offered a Ext4 installation(?!): my plan was to install Gecko for having a more polished version of OpenSuse and the reason to try OpenSuse was for BTRFS! :)
Did I miss something? Cheers

**Comment by geckolinux** [comment]
Hi there, BtrFS is available under the manual partitioning options. Please note that the Calamares installer will not provide an automatic configuration of BtrFS with Snapper and GRUB integration.
