### ISSUE TITLE
IRC support group?

### ISSUE THREAD

**Issue by baimafeima** [geckolinux/geckolinux-project#71]
Is there currently any IRC support group and if no, would you consider starting one?

**Comment by geckolinux** [comment]
Hi there, no, there is currently no IRC channel. I don't really know much about IRC, so I'm adding the "Help Wanted" tag to this report.

**Comment by minikN** [comment]
I'd recommend an IRC channel too. Preferebly on freenode, all other major distros or even topics in general like PHP have an "official" IRC channel there. It's as simply as joining the network and then joining an empty channel (#geckolinux). Whoever joins the channel first is it's admin, or at least that's how I remember it. There are also certain ways to reserve a channel in case it's empty, but I'd have to look into that.

**Comment by ajhcasual** [comment]
The way IRC servers work, the first person to enter a new room creates the chat.  freenode.net, the most popular IRC host for open source software projects, has a procedure for doing the paperwork to be formally recognized with them, but the truth is, you can just type "/join #geckolinux" and _voila!_  The room exists.

I would be happy to learn the proper procedure, as Gecko Linux deserves formal recognition if it is going to have an official support channel.  Just now, I have joined #geckolinux as it didn't exist.  I have used the Chanserv bot to hold ownership of the channel, ownership which I can subsequently share or transfer to whomever the creator (@geckolinux) wishes.

`(02:04:56 PM) ChanServ: (notice) #geckolinux is now registered to ca-on-adam.`
`(02:04:56 PM) ChanServ: (notice)  `
`(02:04:56 PM) ChanServ: (notice) Channel guidelines can be found on the freenode website:`
`(02:04:56 PM) ChanServ: (notice) http://freenode.net/changuide`
`(02:04:56 PM) ChanServ: (notice) This is a primary namespace channel as per`
`(02:04:56 PM) ChanServ: (notice) http://freenode.net/policies#channel-ownership`
`(02:04:56 PM) ChanServ: (notice) If you do not own this name, please consider`
`(02:04:56 PM) ChanServ: (notice) dropping #geckolinux and using ##geckolinux instead.`

If for some reason, he/she objects to me doing the paperwork for the Gecko Linux channel to be recognized, I can move to the double-pound version (_##channel_name_) to remain as an unrecognized project.  People will still be able to get help so it isn't a big deal as long as they know where we are.

**Comment by slaffcheff** [comment]
Guys, I am using gecko for a while and from time to time checking the IRC but it's always empty. How about a Telegram group. The official openSUSE group is there as well so we can probably call more people from there. I know most of them. If you are OK with this I can easily create a group?

**Comment by geckolinux** [comment]
Feel free, thanks @slaffcheff !

**Comment by ajhcasual** [comment]
Apologies, I haven't been present in that IRC channel due to difficulties with my client, Pidgin, which was unstable.  I should be back there regularly once I get another backtrace sent to the Pidgin devs then I'll be regularly using Hexchat instead.

I'm looking forward to joining the Telegram group!

**Comment by slaffcheff** [comment]
Guys, sorry for the delay.

It's public. Feel free to join and ask friends to come :) 
https://t.me/geckolinux

**Comment by Afsalmc** [comment]
@slaffcheff username geckolinux not found .
