### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by fuji-itsu** [geckolinux/geckolinux-project#73]
After I have added an additional language (Russian) to Geckolinux LXQT, my @ and " keys are reversed, with the @ moving to numeric key number 2 and my " symbol moving to the @ key. When I remove addional language, the keys return to normal, matching the symbols on the actual keyboard

**Comment by geckolinux** [comment]
Hello, please use the LXQt settings to set your desired keyboard layout. If you want to change the keyboard layout across the entire system, please use the YaST Languages module.
