### ISSUE TITLE
Intel Centrino wireless n1030

### ISSUE THREAD

**Issue by fuji-itsu** [geckolinux/geckolinux-project#74]
I have moved from Linix Mint to Geckolinux LXQT. I am suffering the same problem as I had with Mint, if I am listening through bluetooth speakers, my internet is unusable. This is a common fault and there are plenty of posts detailing how to fix the issue by creating a file in modprobe.d and disabling the "n" speed. I havent been able to find any solution for Geckolinux. I am unable to create a .conf file in modprobe.d, as I could in Mint, in which I used 

sudo gedit /etc/modprobe.d/iwlwifi.conf

options iwlwifi 11n_disable=1

echo "options iwlwifi bt_coex_active=N" | sudo tee -a /etc/modprobe.d/iwlwifi.conf

which gave me both working bluetooth and internet

**Comment by geckolinux** [comment]
Hello,

Thanks for the bug report. 

Are you unable to create the `/etc/modprobe.d/iwlwifi.conf` file, or did you create it and it doesn't work?

Cheers.

**Comment by fuji-itsu** [comment]
I am unable to create the iwlwifi.config file, it syas permision denied

**Comment by geckolinux** [comment]
Hello, you need to create it with the root user:

`su root`
`touch /etc/modprobe.d/iwlwifi.conf`
`pluma /etc/modprobe.d/iwlwifi.conf`

**Comment by fuji-itsu** [comment]
Hello, thank you so much for your help, this has worked, many thanks. Do I
have to mark the topic solved?

**Comment by geckolinux** [comment]
Hi there, glad it worked. The issue is now closed.
