### ISSUE TITLE
Enable ISO image to be in any partition of USB stick

### ISSUE THREAD

**Issue by nxdiamond** [geckolinux/geckolinux-project#75]
Etcher puts Gecko's ISO image in partition 1 of a USB stick, but it doesn't have to be that way.  If Gecko's ISO image is in a later partition of a USB stick, Gecko boots but the cow partition is not found.  Here is a fix.

In /usr/lib/dracut/modules.d/90kiwi-live/kiwi-live-lib.sh
line 13 (in function lookupIsoDiskDevice)
```
    iso_volid=$(blkid -s LABEL -o value "${disk}")
```
change to
```
    iso_volid=$(lsblk -p -n -r -o LABEL "${disk}" | grep "${iso_label}")
```

It's also possible to let the cow filesystem be on a different USB stick.  Function preparePersistentOverlay will only create a new cow filesystem on the same USB stick that has the ISO image, but the function can be modified to find an existing cow filesystem no matter where it is.
These lines:
```
    if [ -z "${isodiskdev}" ]; then
        return 1
    fi
```
can be moved down into the then-block of the if statement:
```
    if ! mount -L cow "${overlay_mount_point}"; then
```

But this has to be changed in the squashed filesystem in the ISO image.  I'm not sure if the pathname is the same in the squashed filesystem.  I'm not sure yet if I can modify it myself.

**Comment by geckolinux** [comment]
Thanks a lot for looking into this and providing some solutions, I really appreciate it. I think this could be considered an upstream improvement that should be handled with the Kiwi developers, who are usually very responsive to bug reports:

https://groups.google.com/forum/#!forum/kiwi-images
