### ISSUE TITLE
Default partition layouts

### ISSUE THREAD

**Issue by cuvtixo** [geckolinux/geckolinux-project#77]
In my latest attempt at Gecko install from calamares, I was presented with a straightforward traditional partition layout. EFI boot partition, ext4 for root, and a swap. 
The following is a bit of a rant, and may not apply to Gecko, and hopefully never will:
It bugs the heck outta me that official OpenSUSE documentation doesn't explain their default partition layout. I had been getting used to having a UEFI boot partition installed, and the swap partition, and ext4 for root (/).  But OpenSuse now makes btrfs the default for root, and  /home partition is XFS, and I'm still unclear what gets put on the ext4 partition. Btrfs has its own specialized set of tools, and XFS cannot be shrunk. I had no idea of any of this before installing, when it was presented as the default partition layout for a blank hard drive. 
I also tried installing Suse on a single ext4 partition (and with an EFI boot partition), and found I could not upgrade from an installation DVD. The installer updater refused to recognize the installation on a single ext4 partition. This was on Tumbleweed.
I'm a little worried about Gecko following suit. If it does, a full description of how it is done should be included.
I understand extra documentation would be needed for those with a legacy/CSM boot install, and that the exact sizes calculated for each partition will depend on the space available (actually I'm still confused about how partitions other than /home partitions are spaced). But partitioning has become critical. Once users need to maintain these various partitions, it can be a nasty surprise, and this info should be available BEFORE the actual installation procedure. It's also key for differentiating OpenSUSE and/or in the future Gecko, from other popular distros.
 I'm a little put off by their apparent assumption that knowledgeable SysAdmins (or Forum lurkers?) will understand all of this and take care of it after installation. That's the impression I get from current documentation
Is an install procedure that is not only complicated, but opaque, putting off newbie adopters for OpenSUSE? It's what turned me onto Gecko.
I'd be interested in documenting this partition procedure myself, but I actually don't know what is going on, under the hood. I have a very limited number of hard drives to make new installations and figure it out through experience.

**Comment by cuvtixo** [comment]
Sorry for this rant. If Gecko maintainers want to stay away from OpenSUSE partition layout installation, well, then there's nothing to do, and I'm just babbling.

**Comment by geckolinux** [comment]
Thanks for the comments, it's good to know what users find annoying in openSUSE and how GeckoLinux can possibly avoid those annoyances; that's basically the whole point of the project. 

There are no plans to switch the default GeckoLinux partition layout, because that's a function of the Calamares installer that we use. By default, it uses EXT4 for the automated or "replace a partition" quick install options, or you have a *massive* selection of root partition filesystem options available in the manual partitioner.
