### ISSUE TITLE
Reprise: Is there a way to do toram?

### ISSUE THREAD

**Issue by nxdiamond** [geckolinux/geckolinux-project#78]
Issue 68 was closed with a negative answer, but after more studying, I wonder if there is a way.

Kiwi-live has some options for overlay and some options for dmsquash-live.  Gecko uses overlay but I wonder if a kernel boot line could set options to use dmsquash-live instead of overlay.  dmsquash-live has an option rd.live.ram=1 which copies the ISO image to /run/initramfs/squashed.img, changes a dracut variable to "/run/initramfs/squashed.img", and can allow ejecting the DVD (or in my case USB).  My experiments failed but it seems to me there is some way to set a kernel command line to do it.

(After that, I think it will be comparatively easier to put cow in a tmpfs instead of persisting it on the USB, and copy in customizations from a tar file on the USB before ejecting.)

**Comment by geckolinux** [comment]
Hi there, thanks for your sharing your experiments and ideas. I don't doubt that there is a way to make this work, but the low-level boot process isn't really my area of expertise. So if you can come up with a solution on the [Kiwi dev forum](https://groups.google.com/forum/#!forum/kiwi-images) I'd be glad to see if it can be implemented in GeckoLinux.

**Comment by nxdiamond** [comment]
Booting with rd.break=pre-mount, I could type commands to copy the ISO image to a file under /run/initramfs, unmount the stuff that and been mounted and mount them again, and continue booting.  So if we can't find the "correct" way to do it using existing tools, there is probably a way to hack it in.

**Comment by nxdiamond** [comment]
Success.  I can't make a diff file display correctly in this github discussion and I can't attach a diff file as an attachment so I made a txt copy of the diff file and attached that.  The only file in Gecko (in Kiwi-Live) that needs editing is kiwi-live-lib.sh

[kiwi-live-lib.sh.diff.txt](https://github.com/geckolinux/geckolinux-project/files/2556929/kiwi-live-lib.sh.diff.txt)
