### ISSUE TITLE
having kiwiInstallPhaseFailed error 

### ISSUE THREAD

**Issue by jaypatelani** [geckolinux/geckolinux-project#84]
Hi,
I am getting this error. Any idea what could be causing it ?
[ ERROR ]: 21:03:19 | KiwiInstallPhaseFailed: System package installation failed: [ INFO ]: 21:03:19 | Cleaning up SystemPrepare instance [ WARNING ]: 21:03:19 | remove_hierarchy: path /tmp is protected

Regards, 
Jay

**Comment by geckolinux** [comment]
Hi there,

Are you trying to install the operating system or are you trying to build something with Kiwi? What version of GeckoLinux did you download? Did you verify the checksum?

Thanks.

**Comment by jaypatelani** [comment]
Hi There,  

It was an error while building using kiwi-ng.

Thanks,
Jay

Edit : I am using OpenSuse Tumbleweed

**Comment by geckolinux** [comment]
Hi there, please post your question to the Kiwi forum:
https://groups.google.com/forum/#!forum/kiwi-images

**Comment by vinyanalista** [comment]
Discussion is now here:

[kiwi-ng error KiwiInstallPhaseFailed - Google Groups](https://groups.google.com/d/msg/kiwi-images/vJ5pvX1oHpk/bTMuSfBYDAAJ)
