### ISSUE TITLE
Can't change login screen resolution

### ISSUE THREAD

**Issue by dradtke** [geckolinux/geckolinux-project#86]
I just installed GeckoLinux ROLLING with Cinnamon on my new Dell XPS13, and overall everything seems to be working great. The one problem I can't figure out is how to fix the LightDM login screen's resolution. Since this is a laptop with a 4K monitor, everything on the login screen is super tiny. I've tried creating a script that runs via `display-setup-script` and runs `xrandr` to set the resolution, but that always fails even though the script works fine when run manually after logging in. Any tips on how to do this? Thanks!

**Comment by geckolinux** [comment]
Hmm, interesting problem. Could you please try some of these suggestions?

- https://askubuntu.com/questions/72486/can-i-pass-a-dpi-flag-to-lightdm-to-set-the-proper-dpi-for-x
- https://bit.ly/2tKlwOx

Specifically, the `xft-dpi=192` option looks promising. Just remember that GeckoLinux uses the LightDM GTK Greeter, not Unity Greeter.

**Comment by dradtke** [comment]
That may have worked, but the DPI value might need some tweaking. With 192 I didn't really notice a difference, so I bumped it up to 300 just to see, and that might have had an effect. I'm going to play around with it a little more to see if I can find a good number.

**Comment by dradtke** [comment]
So I believe that the suggestion to update `xserver-command` was most successful, but it seems to only make the static text bigger, and not the user selection dropdown. But hey, that's something.

**Comment by geckolinux** [comment]
Please try the latest GeckoLinux *Static* release:
https://github.com/geckolinux/geckolinux-project/releases/tag/152.200719
