### ISSUE TITLE
Packages file

### ISSUE THREAD

**Issue by ideeman** [geckolinux/geckolinux-project#87]
Sorry for the simple question, but how do you use the packages file?  The install is very simple and elegant, but I did not see a way to link to the packages file as there is in the OpenSuse installation process.

GeckoLinux_ROLLING_Cinnamon.x86_64-999.180607.0.iso
GeckoLinux_ROLLING_Cinnamon.x86_64-999.180607.0.packages

**Comment by geckolinux** [comment]
Hi there, the packages file isn't used for anything. It's just information for those who want to know what the ISO contains, principally for the listing on Distrowatch.

**Comment by thohnhaus** [comment]
Hi
I just installed Gecko on my machine.
I cannot install updates or any new packages.
here is my report: - page one of multiple pages please help

cannot install both broadcom-wl-kmp-default-6.30.223.271_k5.1.15_1-11.35.x86_64 and broadcom-wl-kmp-default-6.30.223.271_k4.16.12_1-10.68.x86_64

    [ ] Following actions will be done:
replacement of broadcom-wl-kmp-default-6.30.223.271_k4.16.12_1-10.68.x86_64 with broadcom-wl-kmp-default-6.30.223.271_k5.1.15_1-11.35.x86_64
deinstallation of broadcom-wl-kmp-default-6.30.223.271_k4.16.12_1-10.68.x86_64
    [ ] do not install broadcom-wl-kmp-default-6.30.223.271_k5.1.15_1-11.35.x86_64



libyui-ncurses-pkg8-2.48.5-1.6.x86_64 requires libzypp.so.1702()(64bit), but this requirement cannot be provided
deleted providers: libzypp-17.3.1-1.1.x86_64
    [ ] Following actions will be done:
do not install libzypp-17.12.0-1.2.x86_64
do not install zypper-1.14.28-1.1.x86_64
do not install libsolv-tools-0.7.5-1.1.x86_64
    [ ] deinstallation of libyui-ncurses-pkg8-2.48.5-1.6.x86_64

    [ ] break libyui-ncurses-pkg8-2.48.5-1.6.x86_64 by ignoring some of its dependencies



ruby-2.6-1.3.x86_64 requires ruby2.6 >= 2.6.3, but this requirement cannot be provided
not installable providers: ruby2.6-2.6.3-2.3.i586[Tumbleweed_OSS]
                   ruby2.6-2.6.3-2.3.x86_64[Tumbleweed_OSS]
    [ ] Following actions will be done:
do not install ruby-2.6-1.3.x86_64
do not install yast2-ntp-client-4.1.8-1.3.noarch
do not install yast2-network-4.2.2-1.3.noarch
    [ ] deinstallation of ruby2.5-2.5.0-4.2.x86_64

    [ ] break ruby-2.6-1.3.x86_64 by ignoring some of its dependencies



yast2-pkg-bindings-4.1.2-1.4.x86_64 requires libzypp.so.1712()(64bit), but this requirement cannot be provided
not installable providers: libzypp-17.12.0-1.2.x86_64[Tumbleweed_OSS]
    [ ] deinstallation of libyui-qt-pkg8-2.45.16-1.1.x86_64

    [ ] break yast2-pkg-bindings-4.1.2-1.4.x86_64 by ignoring some of its dependencies

    [ ] Following actions will be done:
do not install yast2-pkg-bindings-4.1.2-1.4.x86_64
do not install zypper-1.14.28-1.1.x86_64
do not install libsolv-tools-0.7.5-1.1.x86_64


yast2-ruby-bindings-4.2.1-1.3.x86_64 requires /usr/bin/ruby.ruby2.6, but this requirement cannot be provided
not installable providers: ruby2.6-2.6.3-2.3.i586[Tumbleweed_OSS]
                   ruby2.6-2.6.3-2.3.x86_64[Tumbleweed_OSS]

**Comment by geckolinux** [comment]
Hi @thohnhaus please use the following solutions:

Replacement of broadcom-wl-kmp-default-6.30.223.271_k4.16.12_1-10.68.x86_64 with broadcom-wl-kmp-default-6.30.223.271_k5.1.15_1-11.35.x86_64
deinstallation of broadcom-wl-kmp-default-6.30.223.271_k4.16.12_1-10.68.x86_64

deinstallation of libyui-ncurses-pkg8-2.48.5-1.6.x86_64

deinstallation of ruby2.5-2.5.0-4.2.x86_64

deinstallation of libyui-qt-pkg8-2.45.16-1.1.x86_64
