### ISSUE TITLE
Popups for settings are too large to click on OKAY/CLOSE

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#88]
I just built a GeckoLinux Cinnamon system. As I always do, I set fonts to large, which probably has something to do with the bug I will describe. When a settings popup is launched, for example, the settings for Pale Moon, the popup is slightly too large for me to click on OKAY/CLOSE. in other words, it fills the screen from top to bottom  with OKAY/CLOSE just below the screen. Is there a setting I can change?

**Comment by geckolinux** [comment]
Hi there, that sounds like a Palemoon and/or Cinnamon bug, unfortunately not something I can fix. It would be good for you to report the bug to their bug tracker.
