### ISSUE TITLE
MEGAsync does not launch

### ISSUE THREAD

**Issue by c8h10n4o2montreal** [geckolinux/geckolinux-project#90]
Installed the openSUSE Leap 42.3 version (from here https://mega.nz/sync) via Install/Remove Software because Leap 15 is not available. 

I can see the icon after clicking on the Menu, but the application does not launch.

Forgive me if what I did was stupid. The skills I master are a lot less than those I don't.

SOLVED: Removed openSUSE Leap 42.3 version and installed openSUSE Leap Tumbleweed version. It is syncing now.

**Comment by geckolinux** [comment]
Hi, could you please try to launch it from a terminal to see if it throws any errors?

**Comment by c8h10n4o2montreal** [comment]
SOLVED: Removed openSUSE Leap 42.3 version and installed openSUSE Leap Tumbleweed version. It is syncing now.
