### ISSUE TITLE
Cannot install Mate panel or libgtop

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#91]
Three times I have tried the following on GeckoLinux Leap Cinnamon:

- started YaST2 (install software) and entered the root password
- searched on "mate panel" which brought up libmate-panel-applet
- when I click on Accept, YaST2 disappears instead of displaying the screen where I am informed of dependencies

UPDATE: I'm trying to get a solution for displaying processor temperatures. I tried to install Psensor via the rpm from malcomlewis, but was informed that libgtop was a problem. So I tried to install libgtop, but the same YaST2 crash occurred. I think YaST2 or something it depends upon is broken.

**Comment by geckolinux** [comment]
That's strange. Please try to install it from the command line:
sudo zypper in libmate-panel-applet

**Comment by pccobbler** [comment]
I now have trouble doing much of anything on this system. I believe the HDD has problems. Sorry to waste your time. Go ahead and close the ticket.

**Comment by geckolinux** [comment]
No problem, hope you get your system fixed.
