### ISSUE TITLE
Kudos and Otter browser question

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#92]
First, I want to compliment GeckoLinux Cinnamon. I use the one for Leap.

Many distributions have eliminated TraditionalOk in Windows borders (they must have eliminated it from mate-themes), but GeckoLinux has it installed by default. Wonderful!

Also, the colors for the terminal are black on white, as they should be, as that combination was proven by NASA to be the easiest on the eyes.

I use both GeckoLinux Cinnamon and Linux Mint Cinnamon on a regular basis. I really appreciate the work done by the developers.

Second, I have a question regarding Otter browser. If I install it, which one do I get, the one from Malcolm (the moderator of openSUSE forum) or another one?

**Comment by geckolinux** [comment]
Hi there, thanks a lot for the praise, I'm really glad that GeckoLinux is working well for your needs.
> Second, I have a question regarding Otter browser. If I install it, which one do I get, the one from Malcolm (the moderator of openSUSE forum) or another one?

I'm sorry that I really don't know anything about Otter (although I must admit it piqued my interest, especially if they ever implement an integrated mail client). But if somebody reputable like Malcom creates an RPM package of it, that would probably be the best choice.
