### ISSUE TITLE
Help with printer install

### ISSUE THREAD

**Issue by tlcmd** [geckolinux/geckolinux-project#93]
I am new to Geckolinux having previously used other distros. I am having trouble installing the rpm format drivers for my older Brother MFC 490cw printer. Can someone walk me through this install. I got lost at step one.
Thanks,
tlcmd
Greensboro, N.C.

**Comment by geckolinux** [comment]
Hi, please right-click on the RPM and open it with "Install/Remove Software".

**Comment by tlcmd** [comment]
Thanks, but I've tried it and it did not work. I did find out that the rpm driver file for the Brother MFC 4900cw is unsigned, but I "installed" it anyway. I guess I'll contact Brother for help.
Thanks again,
tlcmd


.

"We can evade reality, but we cannot evade the consequences of evading reality"<http://www.great-quotes.com/quote/13754>  Ayn Rand<http://www.great-quotes.com/quotes/author/Ayn/Rand>

________________________________
