### ISSUE TITLE
ETA for Cinnamon version 3.8.x or above

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#94]
With Cinnamon version 3.8.x or above, mate-themes using metacity-theme-1.xml format are no longer supported. This has already been seen in Mint, Fedora, and Manjaro. My question is, what is the ETA for Gecko Leap incorporating Cinnamon version 3.8.x or above?

**Comment by geckolinux** [comment]
GeckoLinux Static does not create its own packages, and it essentially uses the exact same packages and repositories as openSUSE Leap. So judging from the current state of Cinnamon packages for Leap 15.1, the 3.8 update won't be coming at least until the next major 15.x release:
https://build.opensuse.org/package/binaries/openSUSE:Leap:15.1/cinnamon/standard

**Comment by pccobbler** [comment]
Thanks for the information. I hope openSUSE is late with that release.
