### ISSUE TITLE
Problem accesing Package Manager

### ISSUE THREAD

**Issue by tlcmd** [geckolinux/geckolinux-project#95]
Since a vary recent upgrade of Firefox to 66.0.2 and a failed attempt to upgrade Bleachbit, I have been unable to open my GeckoLinux package manager. Suggestions as to how to overcome this problem would be appreciated by this newbie to GeckoLinux. Every other program works. I get this window when I try to access the package manager:

Internal error. Please report a bug report with logs.
Run save_y2logs to get complete logs.

Caller: /usr/lib64/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

Details: Failed to load Module 'Packages' due to: Failed to load Module 'SpaceCalculation' due to: cannot load such file -- storage

Thanks for any help,
tlcmd

**Comment by geckolinux** [comment]
Could you please try updating the system from the command line?
`sudo zypper up`

**Comment by tlcmd** [comment]
Thanks, but the zipper command was not found. Further suggestions, please.
tlcmd

**Comment by geckolinux** [comment]
It's not "zipper", but rather "zypper". Please copy and paste into the terminal:
`sudo zypper up`

**Comment by tlcmd** [comment]
Mea Culpa! Thanks, In progress now.
As a newbie to Gekko and rpm files, I really appreciate the kind assistance. Really like the distro. 
Will let you know what happens.
tlcmd

**Comment by geckolinux** [comment]
OK, let's hope that fixes it.

**Comment by tlcmd** [comment]
Hate to be a pest, but did run zypper and got a long download and update, but now canot open Package Manager; my fault or the systems? I did reboot without any results. Next step??
Thanks,
tlcmd

**Comment by tlcmd** [comment]
I mean I clicked on the Package manager in the menu,added my root password and nothing.
 tlcmd

**Comment by geckolinux** [comment]
What do you see when you run this?
`sudo yast2 sw_single`

**Comment by tlcmd** [comment]
After everything was configured, I then got this as a part of the screen:  

 UI Syntax Error         │ 
                      │Couldn't load plug-in ncurses-pkg│ 
                      │       Check the log file!       │ 
                      │                                 │ 
                      │             [Close]

**Comment by tlcmd** [comment]
GekkoLinux, at this point should I consider a re-install of GekkoLinux? I really do like the distro! But it seems to know I'm a 78 year old newbie even though I was brought up on Dos, Windows, Ubuntu, Linux Mint, Linus Mint Debian Editions, etc. I tried several Linux rolling distros and Gekko is my preference even though I have to deal with rpm files.
Thanks for all the help and advice and now i'm asking for more including whether to back up and start with a re-install or keep going.
Thanks for your help and patience. 
tlcmd

**Comment by tlcmd** [comment]
Off-line until tomorrow, probably pm EDT.
tlcmd

**Comment by geckolinux** [comment]
Hi there, sorry for the difficulties. It looks like you somehow deleted some rather important files related to YaST. It would probably be easiest at this point to just backup your files and then re-install. Sorry for your difficulties, please let us know what you choose to do.

**Comment by tlcmd** [comment]
Am on-line briefly this AM, but plan to save files to external HDD and re-install GekkoLinux late this evening.Will update you with results.

Dick

**Comment by perjonasbengtsson** [comment]
Hi,
Could some Recovery Tool, like "Timeshift", be good for this kind of happenings?

Jonas

**Comment by tlcmd** [comment]
GekkoLinux,
As long as I have the guru on-line and plan to re-install this distro, how would you partition. Probably will do tomorrow (Good Friday) I have a 3 year old HP with quad-core Athlon chip, 12Gigs of RAM, and a 2 TB HDD. Of the 2 TB, I have 500 Gigs for the Windows 10 which I rarely use leaving around 1.3 TB free. Currently it is about equally partitioned into 650 Gig for GekkoLinux and 650 blank where I could add another distro in the future or expand my home files. 
Current partitions: 12 GB swap; 30 Gigs for / (root) and the rest of the GekkoLinux partition as home. I have a lot of Music files (11k+), picture files (2.6k plus) and Office Libre files as I dabble in writing. 
Thanks for any advice or suggestions.
tlcmd

**Comment by geckolinux** [comment]
> Could some Recovery Tool, like "Timeshift", be good for this kind of happenings?
Probably not, I think that's more meant to back up personal files in your `/home/*` directory.

For @tlcmd , I'd probably recommend a separate `/` root partition and a separate `/home` partition.

**Comment by tlcmd** [comment]
Not sure whether or not this should be a separate thread, but I am having a bear of a time trying to re-install GekkoLinux Mate or the GekkoLinux Bare Bones distro. I've tried using a USB thumb drive as well as dvd disks. I have a working GekkoLinux Mate except for no package manager. I also have Windows 10 and have tried several methods. 
Two Questions:
1) Is there a relatively easy way to get my package manager back (the rest of the Mate distro works perfectly)?
2) Is the login on the new distro still "linux" and is the password "none" of leave it blank? I'm getting the message that I'm using the wrong login and password on the new install of both Mate and Bare Bones. Help, please.
Thanks,
tlcmd

**Comment by tlcmd** [comment]
BTW, I do have separate / root and home partitions. I was just curious as to the recommended size since I'd like to get it right if I can get the distro reinstalled. I really like it and wish to either fix the Package Manager or do a correct install.
Thanks again,
tlcmd

**Comment by geckolinux** [comment]
Sorry for the slow reply.

Let's try fixing your existing installation like this:

`sudo zypper in yast2-country-data yast2-online-update yast2-theme yast2-samba-client yast2-perl-bindings yast2-fonts patterns-yast-yast2_install_wf yast2-python3-bindings yast2-security yast2-printer patterns-yast-x11_yast yast2-mail yast2-control-center-qt yast2-snapper yast2-services-manager yast2-hardware-detection yast2-users yast2-core yast2-trans-stats yast2 yast2-qt-branding-openSUSE yast2-proxy yast2-tune yast2-control-center yast2-update yast2-alternatives yast2-transfer yast2-x11 yast2-samba-server yast2-storage-ng yast2-bootloader yast2-xml yast2-ycp-ui-bindings yast2-metapackage-handler yast2-online-update-frontend yast2-country yast2-sudo yast2-installation yast2-pam patterns-yast-yast2_basis yast2-trans-en yast2-packager yast2-scanner yast2-ldap yast2-firewall yast2-sysconfig yast2-pkg-bindings yast2-ntp-client yast2-ruby-bindings yast2-logs patterns-gnome-gnome_yast yast2-network`

**Comment by tlcmd** [comment]
GeckoLinux, Thank you for following up, but I literally just re-installed GeckoLinux Mate to my computer.Now to finish fine tuning it for my use. Package manager works now!
I'm sure I'll be contacting you again with more questions; probably about how to convert deb to rpm files and installing Brother 490 MFC driver files. 
Thanks again,
tlcmd

**Comment by geckolinux** [comment]
Great, glad you got it fixed! I would suggest not using Bleachbit in the future, as that was probably what broke your YaST.

**Comment by tlcmd** [comment]
Actually what broke it was upgrading Firefox directly from Mozilla. Did not do that with the package manager.

tlcmd


.

"We can evade reality, but we cannot evade the consequences of evading reality"<http://www.great-quotes.com/quote/13754>  Ayn Rand<http://www.great-quotes.com/quotes/author/Ayn/Rand>

________________________________
