### ISSUE TITLE
GeckoLinux Rolling XFCE fresh install & update

### ISSUE THREAD

**Issue by AnotherGecko** [geckolinux/geckolinux-project#96]
Gents, I have installed Gecko XFCE rolling & did the update. After the update broadcom wifi is missing? So i tried lspci - not found? Strange? then tried hwinfo - not found? man nmcli bash: man: not found?  I then found a network cable and tried zypper install hwinfo - but it is already the latest version? I tried networkctl and got systemdnetworkd is not running. The update gave no error messages? 

OR was it user error and I should not have used zypper dup???

The wireless was working on a fresh install.
I can reinstall, but my metered connection internet is almost finished, an I do not have another 900+MB  for updating. 

oh and the os-prober the Guy mentioned in 2018 is still a problem, but I managed to add my windows partition manually.

**Comment by geckolinux** [comment]
Hi, is the broadcom-wl package still installed?

As for the os-prober thing, that's an upstream openSUSE issue. Hopefully it's fixed by now so that the fixed version can be included in the next set of GeckoLinux updated ISOs.
