### ISSUE TITLE
GeckoLinux Mate is very slow

### ISSUE THREAD

**Issue by tlcmd** [geckolinux/geckolinux-project#98]
Finally got GeckoLinux Mate installed, but it is running very slowly compared to the Windows 10 and Linux Mint 19 Mate. Suggestions to try to speed it up?
Thanks,
tlcmd

**Comment by geckolinux** [comment]
Hi there, in what sense is it slow? Also it would be good to know what kind of graphics card you have.

**Comment by tlcmd** [comment]
GeckoLinux, I finally realized that the problems were due to the idiot who was installing the distro. Wiped my linuc petition and re-installed GeckoLinux Mate and Linux Mint 19 mate and all work great now including Windows 10 which I rarely use. Now to reload my documents. 

BTW, is there a free program to easily convert deb files to rpm files?

Thanks for your help and in putting up with this old guy who has a bad learning curve.
tlcmd

**Comment by tlcmd** [comment]
GeckoLinux, when GeckoLinux installs itself nest to existing operating systems (Windows 10 and Linux Mint 19) does it partition itself into /boot and /home partitions? I currently have my Windows 10 partitions, a Linux Swap partition as well as Linux Mint /boot and /home partitions and 2 more partitions being 395.84 Gigs each which I assume are GeckoLinux ones. One has 7.33 Gigs used; the other 11.19 gigs used. Neither is assigned a label. Obviously I do not need these latter 2 partitions as large as they are and would like to shrink the /boot one down to 30 gigs at most. The GeckoLinux distro works great as it is, so I am very hesitant to "diddle" with it. Answers and comments, please.
Thanks,
tlcmd

**Comment by geckolinux** [comment]
> BTW, is there a free program to easily convert deb files to rpm files?

Yes, it's called [alien](https://www.tecmint.com/convert-from-rpm-to-deb-and-deb-to-rpm-package-using-alien/), but it's usually not a good solution.

Regarding the partition layout, unless you use a custom manual partitioning scheme, it will only use one partition.
