### ISSUE TITLE
Gecko LXQt icon theme refuses to be set

### ISSUE THREAD

**Issue by pccobbler** [geckolinux/geckolinux-project#99]
I'm running LXQt via a LiveUSB, seeing if I like it enough to install it. I tried to change the icon theme to GNOME, my usual choice. However, the icons never changed, even when I changed to the dramatic high contrast ones. Is this a bug or do they not change when running a LiveUSB?

**Comment by geckolinux** [comment]
It sounds like a bug. Maybe try changing them and logging out and logging again.

**Comment by pccobbler** [comment]
I figured it out. If the icon theme is changed via Preferences -> Customize Look & Feel, nothing will change (all other settings change properly, however). If the icon theme is changed via Preferences -> LXQt Settings -> LXQt Configuration Center, the icon theme will change. It's a bug.

**Comment by geckolinux** [comment]
Hi, that's just the way it is in LXQt, leftovers from the transition between LXDE -> LXQt.

**Comment by pccobbler** [comment]
Ah, so LXQt is very much a work in progress. I learn something new every day, thanks.
